### ISSUE TITLE
ads not ceasing.

### ISSUE THREAD

**Issue by chblaine** [AdguardTeam/AdGuardForSafari#1003]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS:
- Safari
sonoma 14.5 version:
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard URL Tracking filter, AdGuard Social Media filter

### Issue Details

Steps to reproduce:
1.?
2.
3.

### Expected Behavior

You tube ads too cease.

### Actual Behavior

Ads not ceasing.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@chblaine Hello! Please update the filters in AdGuard for Safari and [clean cookies](https://www.macworld.com/article/670948/how-to-clear-safaris-cache-and-cookies-on-mac.html) in Safari browser. 

If it didn't help please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
