### ISSUE TITLE
adguard no longer working?

### ISSUE THREAD

**Issue by chblaine** [AdguardTeam/AdGuardForSafari#1005]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS:
- Safari version:
```

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

ads would cease

### Actual Behavior

an adguard app popped up and told me trial had ended

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

adguard safari continues to run?
did i purchase the wrong app?
i use chrome

**Comment by alexx7311** [comment]
@chblaine Hello! AdGuard for Safari is a free extension that is working in Safary only. If you bought a subscription, you need to install AdGuard for Mac at https://adguard.com/download.html?auto=1 which will work in all browsers including Chrome.

If you having trouble activating your license you can email us at [support@adguard.com](mailto:support@adguard.com)
