### ISSUE TITLE
Trial Has Expired

### ISSUE THREAD

**Issue by sasea1** [AdguardTeam/AdGuardForSafari#1006]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS:
- Safari version:
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

I receive a pop-up everyday telling me that my trial has expired.  I have a paid subscription that is working and I need the pop-up to go away.  It is aggravating.

### Screenshots

<details><summary>Screenshot 1:</summary>

![ADGUARD - TRIAL HAS EXPIRED](https://github.com/user-attachments/assets/497b2ca0-9647-4d58-b98a-849d5a81e60c)

</details>

**Comment by Eugene-Savenko** [comment]
You need to activate your copy of AdGuard with a license key: https://adguard.com/kb/general/license/activation/#activating-adguard-for-mac
