### ISSUE TITLE
Now defeats AdGuard macOS and iOS...

### ISSUE THREAD

**Issue by IanMetz** [AdguardTeam/AdGuardForSafari#1008]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.8

### Environment

```markdown
- OS:Sonoma 14.5
- Safari version:18.0 (19619.1.24.111.3, 19619)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1. go to https://macdailynews.com
2.
3.

### Expected Behavior

No splash screen

### Actual Behavior

Splash screen on macOS as well as iOS.  This is a new phenomenon as of perhaps three days ago.
AdGuard used to block it, it seems the website has found a way around it!

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1083" alt="Screenshot 2024-08-08 at 16 29 14" src="https://github.com/user-attachments/assets/4c5bebf5-f645-444c-a689-f570c5c6a89f">
![IMG_1966](https://github.com/user-attachments/assets/f5820fb5-387f-4f8c-a78d-6622c8fd0510)

</details>

### Additional Information

I am not technical, but have all filters operating, including all Annoyances.

Hope I've provided enough details!

**Comment by Alex-302** [comment]
@IanMetz Fixed in AdGuard Popups filter.


You may report filtering problems by the Assistant:

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/5f2d5682-9564-4785-88b5-11b9bc2a5f8d)


</details>

**Comment by IanMetz** [comment]
Okay.
<img width="386" alt="Screenshot 2024-08-08 at 17 23 27" src="https://github.com/user-attachments/assets/6f6450b1-013b-41d2-aa5b-e19bf589be5b">
