### ISSUE TITLE
DPI guard function for MacOS 

### ISSUE THREAD

**Issue by zaebaloblyatebannayarossia** [AdguardTeam/AdGuardForSafari#1009]
### Issue Details

Nowadays in my country it became impossible to use YouTube without vpn (which is hard to find for free for mac). May be you don't care and I fully understand you in this matter, but it would be nice to have on os app same function as windows users have on their version. So, if you can, please add DPI guard function for MacOS app.

**Comment by alexx7311** [comment]
@zaebaloblyatebannayarossia, hello! This cannot be implemented as part of an extension, it requires full-fledged network filtering. The "Protect from DPI" feature is already implemented in [AdGuard for Mac](https://adguard.info/en/adguard-mac/overview.html) app.
