### ISSUE TITLE
ios block element tool: show rule preview

### ISSUE THREAD

**Issue by riklee124** [AdguardTeam/AdGuardForSafari#101]
When using block tool, the only information shown is element tag name under border highlighter.

Can you add text box on fixed toolbar with preview of actual rule and allow user edit it?

Some sites add extra class names to element that aren't needed to block element or random characters to class name to counter adblockers. In current version user has to let app upload rule list to safari before seeing new rule which is slow. Then editing rule and uploading again is slow.

It would be easier if user can edit rule and use preview button to test before uploading new rule

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardForiOS #1772](https://github.com/AdguardTeam/AdguardForiOS/issues/1772) via [**ZenHub**](https://www.zenhub.com/)
