### ISSUE TITLE
All Adverts are showing up on Times of India on Safari Browser

### ISSUE THREAD

**Issue by manishik** [AdguardTeam/AdGuardForSafari#1010]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS:
- Safari version:
Allowing all adverts on Times of India especially on Safari browser
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Just Open times of India on Safari browser
2.
3.

### Expected Behavior

All adverts should be blocked 

### Actual Behavior

All adverts are being displayed 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@manishik Hello! Please update the filters and check if the problem persists.
If it does you can report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
