### ISSUE TITLE
YouTube keeps detecting AdGuard

### ISSUE THREAD

**Issue by kbwizzard** [AdguardTeam/AdGuardForSafari#1013]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

 AdGuard for Safari Version 1.11.14

### Environment

```markdown
- OS:
- Safari version:
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

YouTube error appears frequently

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="831" alt="Screenshot 2024-08-23 at 11 02 54 PM" src="https://github.com/user-attachments/assets/e4d497a4-276f-40a8-9e34-60aa0cde5ebe">

**Comment by alexx7311** [comment]
@kbwizzard Hello! Please update AdGuard for Safari to the latest 1.11.19 version and check for the filter updates.
If the problem persists you can report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
