### ISSUE TITLE
Broken web site

### ISSUE THREAD

**Issue by noahkim123** [AdguardTeam/AdGuardForSafari#1020]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

ADGUARD 4.5.5

### Environment

```markdown
- OS: IOS 17
- Safari version: IDK
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

Steps to reproduce:
1. Turn on the Adguard.
2. Enter the https://www.ygosu.com

### Expected Behavior

![image](https://github.com/user-attachments/assets/99f3a756-b87a-4336-bc19-445e02a2fb17)

### Actual Behavior

![image](https://github.com/user-attachments/assets/5b083af5-ce1c-450b-a5e0-3fc92b3bf751)

**Comment by alexx7311** [comment]
@noahkim123, hello! Looks like filters problem, not the app problem. Please report the problem with website according to these instructions https://adguard.app/kb/guides/report-website/#ios
