### ISSUE TITLE
wfmz.com

### ISSUE THREAD

**Issue by Rivaraav** [AdguardTeam/AdGuardForSafari#1021]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.2

### Environment

```markdown
- OS:ios 17.6.1
- Safari: 17.6
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

Steps to reproduce:
If you enable Mobile Adgard for Safari and access ```wfmz.com``` , the page will break out of service.

### Actual Behavior

A warning window appears and the web page is broken to be disabled.

![image](https://github.com/user-attachments/assets/fd8b0601-3036-44ce-978e-1e68d3a70394)

### Screenshots

![image](https://github.com/user-attachments/assets/b0faf9bb-54fd-4a6c-8bbb-67f481ba7a18)

**Comment by alexx7311** [comment]
@Rivaraav, hello! This is AdGuard for Safari repo, not AdGuard for iOS. But anyways this looks like filters problem, not the app problem. Please report the problem with website according to these instructions https://adguard.app/kb/guides/report-website/#ios
