### ISSUE TITLE
AdGuard for Safari doesn't block pop-ups as effectively as it does on Chrome or Microsoft Edge

### ISSUE THREAD

**Issue by JohniHashim** [AdguardTeam/AdGuardForSafari#1028]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.19

### Environment

```markdown
- OS: Sequoia 15.0
- Safari version: 18.0
When using AdGuard for Safari on a website called "Braflix," every second mouse click triggers a pop-up window, which redirects to another site with a URL like: https://elfishtutman.click[bunch of numbers]. The message shown is: "URL was blocked by content blocking: (WebKitErrorDomain:104)" (translated from Danish).
On Chrome and Microsoft Edge, AdGuard successfully detects the pop-up the first time and blocks it, preventing it from appearing again.

Is this an issue on my end, or is it a problem with AdGuard for Safari? Could it also be related to Safari's handling of content blockers?
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. open Braflix.gd on safari
2. click ramdom placses
3. every other "detected" click should redirect you to a blocked filter
4. Just annyong that it is blocked but still opens the website

### Expected Behavior

I expected that Adguard could detect this and stop opening the other website when it knows that its just a popup

### Actual Behavior

The pop-up is still opened and will redirect me away from the "current" website 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by windwak3r** [comment]
@JohniHashim, hello! 
This is a limitation of the Safari browser and $popup modifier can only work that way in Safari https://adguard.com/kb/general/ad-filtering/create-own-filters/#popup-modifier-limitations
