### ISSUE TITLE
Add support for if-top-url to Safari rules converter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#103]
@ameshkov commented on [Thu Jun 08 2017](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/729)

> New in Safari 11.0 – content blocker rules.
> Added if-top-url and unless-top-url, new triggers that execute when a regular expression is matched against the entirety of the main document URL.

With it we'll be able to fully support all kinds of document-level exceptions (elemhide, generic block, etc).
However, we should do it for new Safari or iOS only.

**Comment by Mizzick** [comment]
https://issues.adblockplus.org/ticket/5571
Considering the above, we cannot use both `if-domain` and `if-top-url` triggers in whole one content blocker list, so for now, we decided to postpone this changes.
