### ISSUE TITLE
Not working properly on youtube

### ISSUE THREAD

**Issue by Rehan74849** [AdguardTeam/AdGuardForSafari#1030]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.19

### Environment

```markdown
- OS:
- Safari version:
```

### What filters do you have enabled?

IndianList

### Issue Details

Steps to reproduce:
1.
2.
3.
Not working properly

### Actual Behavior

Whenever I am playing video on youtube it takes about 40-50 seconds to play the video and I have to refresh about 2-3 times for playing the video.
Please fix this issue

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by windwak3r** [comment]
@Rehan74849, hello! Please clear your browser cookies, update filters in AdGuard for Safari and check if the problem persists. If it does please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
