### ISSUE TITLE
New Blank Tabs repeatedly Pop Up regularly when clicking a link anywhere on the site in question.

### ISSUE THREAD

**Issue by chrisrothe1** [AdguardTeam/AdGuardForSafari#1035]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.19 (build 335, CT 2.0.44)

### Environment

```markdown
- OS: macOS Sequoia Version 15.1
- Safari version: Version 18.1 (20619.2.8.11.10)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Popups filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1. Navigate to https://moviesjoy.is/
2. Click on the enter website button - this should illustrate the issue right away.
3. However, if it somehow does not then when accessing the site, click on a more or TV show - any link that is clickable, and a new, blank tab will automatically pop up within the same window.

Photos:
<img width="1440" alt="Screenshot 2024-11-09 at 11 30 03 PM" src="https://github.com/user-attachments/assets/4f061fcb-a074-434e-aa21-995e37b187ef">
<img width="1232" alt="Screenshot 2024-11-09 at 11 29 52 PM" src="https://github.com/user-attachments/assets/b3e4dc9b-39b1-49a9-95cd-8b0ece198517">

### Expected Behavior

I would like these pop-ups to discontinue when attempting to click on any links within this website; it opens up a brand new tab in the current window with the tab, displaying a bunch of gibberish without a legitimate page present. If there is anyway that we can prevent this new tab from popping up whenever I click a link within this website, that would be wonderful.

<img width="1232" alt="Screenshot 2024-11-09 at 11 29 52 PM" src="https://github.com/user-attachments/assets/d7bce86e-7abe-4f8c-bcbe-74d3f37ebb65">
<img width="1440" alt="Screenshot 2024-11-09 at 11 30 03 PM" src="https://github.com/user-attachments/assets/a5d5cc12-5e4c-4dd9-8927-a31a5c8b8b0c">

### Actual Behavior

When attempting to click on any link within this website, a new tab populate within the same window. This tab does not load any information and simply displays a list of words, but this occurrence happens far too frequently and usually takes me 3 to 4 times to exit out of the ad before it will let me proceed with clicking on the desired link within this website if there is any way that we can resolve this so that these pop-ups within the current window do not continue to plague my experience with this website, that would be wonderful. Thank you so much.

### Screenshots

Screenshots 
<img width="1232" alt="Screenshot 2024-11-09 at 11 29 52 PM copy pdf" src="https://github.com/user-attachments/assets/dcbf0c7d-9295-4742-b617-766ec4961ced">
<img width="1440" alt="Screenshot 2024-11-09 at 11 30 03 PM" src="https://github.com/user-attachments/assets/7859852e-b6f7-408e-a9b9-7c24b11de64b">

### Additional Information

I have maybe 10 ad-blocker extensions implemented into my Safari browser in an attempt to limit popups and advertsements, but for some reason, whoever I click on any link within the website Moviesjoy.is, I am bombarded with repeated new blank tabs that I must exit out of repeatedly. This helps resolve the issue for a small amount of time before populating these popup windows/tabs within the same window each time.

**Comment by chrisrothe1** [comment]
Please reach out to me at **chrisserothe@gmail.com** if you are able.

I am unfamiliar with GitHub's customer support process and am afraid I will miss a response. Thank you so very kindly!

**Comment by windwak3r** [comment]
@chrisrothe1, hello! Please disable all other extensions in Safari except for AdGuard ones as they may conflict with each other. Then clear your browser cookies, update filters in AdGuard for Safari and check if the problem persists. If it does please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
