### ISSUE TITLE
Ads on YouTube are not blocked

### ISSUE THREAD

**Issue by kcsembos** [AdguardTeam/AdGuardForSafari#1038]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.19

### Environment

```markdown
- OS:11.7.10
- Safari version:16.6.1
```

### Issue Details

Steps to reproduce:
1. Open YouTube
2. Play any video
3.

### Expected Behavior

I expected not to see those unskippable ads at the start of a video.

### Actual Behavior

Unskippable ads play at the start of every video, without a way to skip

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by windwak3r** [comment]
@kcsembos, hello! Please clear your browser cookies, update filters in AdGuard for Safari and check if the problem persists. If it does please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
