### ISSUE TITLE
Unable to update filters

### ISSUE THREAD

**Issue by outwornb** [AdguardTeam/AdGuardForSafari#1042]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.20

### Environment

```markdown
- OS: Sequoia 15.1.1
- Safari version: 18.1.1 (20619.2.8.11.12)
```

### Issue Details

Steps to reproduce:
1. Click "Check for updates" in the "Filters" tab
2. Wait
3. Notification appears saying "Filters' update error"
<img width="380" alt="Screenshot 2024-12-02 at 14 09 38" src="https://github.com/user-attachments/assets/4d724ed8-9812-4ea4-8b14-a151b7b720f6">

### Expected Behavior

I should have received a notification where it would say the filters were successfully updated.

### Actual Behavior

The filters are not updated correctly and are stuck on an older version.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="380" alt="Screenshot 2024-12-02 at 14 09 38" src="https://github.com/user-attachments/assets/01326698-1c04-41b7-91bd-b125a0c36fdc">

</details>

**Comment by windwak3r** [comment]
@outwornb, hello! Does the problem reproduce if you switch to a different network?

**Comment by outwornb** [comment]
Hi!

It does, unfortunately. My main network is configured with NextDNS. Although if I turn it off and switch to another one, AdGuard for Safari still fails to update.

**Comment by windwak3r** [comment]
@outwornb In order to troubleshoot this issue, we need to get your application logs.

Here's what we need you to do:

1. Make sure all Safari content blockers are enabled.
2. Reproduce the problem, then remember the exact time it happened.
3. Open the extension *Settings -> Export logs and system info*.
4. Send the file to [qa@adguard.com](mailto:qa@adguard.com):
	- include `[safari]` keyword and `1042` in the subject of your email
	- specify the exact time when the issue occurred

**Comment by outwornb** [comment]
Hi,

I’ve sent the exported application logs as well the exact time the issue occurred to the mentioned address just now.

Thank you!

**Comment by windwak3r** [comment]
@outwornb I can't find your mail. Can you send it again please?

**Comment by outwornb** [comment]
Hi,

I resolved the problem by installing and using the AdGuard app instead. I have uninstalled the AdGuard for Safari extension already.

Thank you!
