### ISSUE TITLE
still google sign in request; ads on weather.com;besthomepageever clicks as directed, then quickly. disappears

### ISSUE THREAD

**Issue by kokyharvey** [AdguardTeam/AdGuardForSafari#1043]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.110

### Environment

```markdown
- OS:12.7.6-monterey
 Safari version:Version 17.6 (17618.3.11.11.7, 17618)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, Filter unblocking search ads and self-promotion

### Issue Details

Steps to reproduce:above
1.
2.
3.

### Expected Behavior

above

### Actual Behavior

above

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by windwak3r** [comment]
@kokyharvey, hello! Please clear your browser cookies, update filters in AdGuard for Safari and check if the problem persists. If it does please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/

**Comment by kokyharvey** [comment]
all done - problem persists
