### ISSUE TITLE
Wordpress plugins can anti-bypass all adblocker

### ISSUE THREAD

**Issue by Batman8088** [AdguardTeam/AdGuardForSafari#1044]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.7(1025)

### Environment

```markdown
- OS: 18.2
- Safari version: Safari 18.0 (20619.1.26)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1. Go to Chikianimation.com while AdGuard is active
2. And you try even use AdGuard element blocker
3. And element blocker doesn’t even touch the cosmetic ads that originating from Wordpress plugins

### Expected Behavior

Well I really thought that AdGuard element blocker would work on these sort of annoyance.

### Actual Behavior

I can see in the future that Wordpress anti-Adblock plugins will gain a lot of attraction because ads revenue 
Making hard for adblockers to even keep up.

### Screenshots

![IMG_1253](https://github.com/user-attachments/assets/e1d4cc11-b5a0-40d7-aa6c-7941b17d31f2)

**Comment by alexx7311** [comment]
@Batman8088, hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
