### ISSUE TITLE
[question] Differences from old extension

### ISSUE THREAD

**Issue by andrews05** [AdguardTeam/AdGuardForSafari#106]
Before the new extension app was released, an earlier blog post mentioned that the upcoming app would "definitely be worse" than the old extension due to SDK differences. Now that the new app is out, what are the differences? In what ways is it worse?
(sorry if this is the wrong place to ask)

**Comment by ameshkov** [comment]
It is worse indeed as we have to rely on the Safari content blocking API only. For instance, it means that some powerful types of rules (extended CSS for instance) cannot be used, and it makes the overall quality lower. I'd say on 90% of websites we don't need those though.

**Comment by superlex** [comment]
Yes, and it doesn't support script (e.g. in order to abort inline-script) and style rules :/
https://github.com/AdguardTeam/AdGuardForSafari/issues/80

**Comment by andrews05** [comment]
Thanks guys, good to know. I'm sure the new one will be fine but I'll keep running the old one for as long as it works :)
