### ISSUE TITLE
Please update translations of the extension and app store's description.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardForSafari#113]
@aalpatkina
I found that v1.2.0 was released one week ago.
Today, I just finished all Traditional Chinese (**zh-TW**) translations in the projects of **AdGuard for Safari** and **AG for Safari (AppStore Desc)**.

Please also update to Traditional Chinese description on Mac App Store (Taiwan).
https://itunes.apple.com/tw/app/adguard-for-safari/id1440147259

May you update translations of the extension and app store's description in the next version?
Thanks.

**Comment by ameshkov** [comment]
@zebrum @Mizzick let's do it before publishing the hotfix

**Comment by lancelot-moon** [comment]
@ameshkov

Taiwanese users reported that you didn't correctly apply my Traditional Chinese for AG for Safari.
It wrongly shows English interface in most places.
May you fix it in the next version?
Thanks.

**Comment by Mizzick** [comment]
Hello!
What's the correct locale for Traditional Chinese?
We'd updated `zh-Hant` in v1.2.1, but was it `zh-TW` you had done?

**Comment by lancelot-moon** [comment]
If you take Traditional Chinese translations from onesky, it's zh-TW.

Have you know the cause?

(The formal locale is zh-hant-TW.
But you open zh-TW for Traditional Chinese on onesky.)

**Comment by Mizzick** [comment]
Ok, it's clear now.
Will be done in next version.

**Comment by lancelot-moon** [comment]
In language tags,
zh-Hant: Chinese, in traditional script
zh-Hant-TW: Taiwan Chinese in traditional script
zh-Hant-HK: Hong Kong Chinese in traditional script

On onesky, AG team only opened zh-TW locale.

Some app designer will only open zh-TW because it's convenient to use it for Taiwan, Hong Kong and Macow.

**Comment by lancelot-moon** [comment]
For your reference:
https://github.com/getnikola/nikola/issues/1637

**Comment by lancelot-moon** [comment]
@Mizzick
@aalpatkina

English
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Gp9Auyk.png)
</details><br/>

I have line breaks for those keywords in my translations on onesky.
Why is there no line break in Traditional Chinese description on Mac App Store (Taiwan)?
Traditional Chinese:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/EyO3sJI.png)
</details><br/>

May you fix it?
Thanks.

**Comment by lancelot-moon** [comment]
@Mizzick
@aalpatkina

I don't have macOS but I guess your date format in Chinese is as wrong as the situation in browser extension.

A strange date format in Chinese.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/yAT1Led.png)
</details><br/>

ex: 29 Dec. 2018
The correct date format in Chinese should be 2018年12月29日 or 2018年十二月29日.

The date format in #47616884 of Adguard Android / Android App is what you should give.
#47616884
Updated %s
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7M2KlsN.png)
</details><br/>

For your reference about date format in Chinese:
https://www.ibm.com/support/knowledgecenter/en/SSS28S_3.0.0/com.ibm.help.forms.doc/locale_spec/i_xfdl_r_formats_zh_Hant_TW.html

**Comment by lancelot-moon** [comment]
Have you solved the locale issue?
Traditional Chinese can't be shown in v1.2.1 Hotfix.

I read your locals files.
You use zh-Hans for Simplified Chinese and zh-Hant for Traditional Chinese.
Why do you not use zh-CN for Simplified Chinese and zh-TW for Traditional Chinese?
(The same locale names from onesky.)

I don't have Mac.
I can't check language interface of v1.3.0 beta.
May you give the screenshots of settings about v1.3.0 beta when you set system language to Traditional Chinese?

**Comment by Mizzick** [comment]
@lancelot-moon 
<img width="713" alt="Screenshot 2019-04-24 22 38 23" src="https://user-images.githubusercontent.com/13855288/56689056-da24d600-66e2-11e9-907e-3783d6ff2cd9.png">
We are limited with xcode built-in locales here.
And an other problem is that this list should be conformed with browser locales.

**Comment by lancelot-moon** [comment]
In your screenshot, there are Chinese (Traditional).
Maybe zh-TW is there.

I see zh-HK, which means Traditional Chinese in Hong Kong.
So I think zh-TW should exist.

BTW, there is also zh-Hant-TW in your screenshot, which is for Taiwan.

But you know my Traditional Chinese translations are in zh-TW locale on onesky.

v1.3.0 beta was released.
I don't have Mac.
May you give me its screenshots while macOS system language is 繁體中文 (zh-TW or zh-Hant-TW)?

Thanks.

**Comment by Mizzick** [comment]
Chinese(China) - I guess it's traditional
<img width="1021" alt="Screenshot 2019-04-24 23 06 09" src="https://user-images.githubusercontent.com/13855288/56690216-997a8c00-66e5-11e9-9238-14897463f9b9.png">

**Comment by lancelot-moon** [comment]
@aalpatkina

Will you need to move my Traditional Chinese translations from zh-TW locale to zh-Hant-TW locale? (AG for Safari)

I'm from Taiwan, Not China.
Do you use zh-TW or zh-Hant-TW for AG for Mac?

**Comment by Mizzick** [comment]
Why don't you use `zh-Hant` for your translations on onesky?

**Comment by lancelot-moon** [comment]
Nooo, I don't need Simplified Chinese.
I need Traditional Chinese (Taiwan).

Do you not understand Traditional Chinese didn't correctly show on v1.2.1?

**Comment by Mizzick** [comment]
I'm sorry, I'm lost in all Chinese Taiwan locales.
There is no correlation with AG for Mac.

I guess we could try to add `zh-Hant-TW` locale, is this what you want, @lancelot-moon ?

**Comment by lancelot-moon** [comment]
> Why don't you use zh-Hant for your translations on onesky?

@aalpatkina only opened zh-TW locale for Traditional Chinese.

Could you not ask your devs of AG for Mac?
We don't meet locale issue in AG for Mac.

@ameshkov
Excuse me, may you help?

**Comment by lancelot-moon** [comment]
You can directly tell @aalpatkina to move my Traditional Chinese translations from zh-TW locale to zh-Hant-TW locale. (AG for Safari)

**Comment by Mizzick** [comment]
I guess we figured out, I will show you Traditional Chinese interface screenshots a bit later.

**Comment by lancelot-moon** [comment]
@Mizzick 

Did you remember that you ever let me see the screenshot when setting Traditional Chinese in macOS?
https://github.com/AdguardTeam/AdGuardForSafari/issues/139#issuecomment-471958228

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/13855288/54195938-a9893400-44c8-11e9-9d59-d6b018b0178c.png)
</details><br/>

I told that there were 3 issues from your screenshot.
Do you remember?
https://github.com/AdguardTeam/AdGuardForSafari/issues/139#issuecomment-471964441

1. Before, we had known that AG team didn't correctly use zh-TW locale for Traditional Chinese interface in AG for Safari v1.2.1, so the interface is still **English**.

2. You use outmoded translations of filters' name and descriptions.
Ex: In that screenshot, 英文過濾器 means English filter.
But it's renamed as Base filter (基本過濾器).
Do you remember that this similar issue ever occurred in AG Browser Extension v3?

3. In the filter's update time, the date format is 2019/3/12 下午12:30:47. (下午=PM)
But I wish it could be 2019年3月12日 12:30:47. (24-hour clock)

**Comment by Mizzick** [comment]
<img width="1004" alt="Screenshot 2019-04-25 19 59 48" src="https://user-images.githubusercontent.com/13855288/56754057-b7eb9080-6794-11e9-977b-4df83b6f1a1b.png">
@lancelot-moon

**Comment by lancelot-moon** [comment]
Oh yeah, it's Traditional Chinese.
Finally, you got it.))

1. BTW, I don't know how long you updated translations last time.
It's better to update translations for v1.3 release.

2. May you show the screenshot of AG Spanish/Portuguese filter?
I will know if you use the latest Traditional Chinese translations for filters.
Thanks.

**Comment by Mizzick** [comment]
<img width="995" alt="Screenshot 2019-04-25 21 17 29" src="https://user-images.githubusercontent.com/13855288/56758566-a1970200-679f-11e9-9297-327d0d789b46.png">
We gonna updated all translations before release anyways

**Comment by lancelot-moon** [comment]
It's not just if you update translations on onesky.

You knew we updated filters' locales several days ago.

**From your filter's screenshot, you're using outmoded filters' locales in v1.3.0 beta.**

**Comment by lancelot-moon** [comment]
@zzebrum

This isn't fixed.

https://github.com/AdguardTeam/AdGuardForSafari/issues/113#issuecomment-453130861
