### ISSUE TITLE
YouTube "iCards" don't display properly on Safari when using AdGuard

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdGuardForSafari#122]
@AppleAuthority commented on [Tue Jan 08 2019](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1244)

### Steps to reproduce

1.Open a YouTube video with an iCard in it ([example](https://youtu.be/-Sex3r_CNWU?t=74))
2. Fullscreen the video
3.
4.

### Expected behavior

Entire iCard displays properly
### Actual behavior

Only the ⓘ displays and the rest of the card is blocked by AdGuard

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: AdGuard for Safari 1.2.1
* Environment name and version: Safari 12.0.2 (14606.3.4)
* Filters you use in AdGuard: None
* Any other browser extensions you have installed: Ghostery Lite for Safari 1.0.0

**Comment by karina-archazh** [comment]
https://monosnap.com/file/tjv8x6SwCTXseSyWiWdYBvFEKxj5OC

I cant reproduce on a last update 1.2.1

**Comment by AppleAuthority** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44805409/50895854-33504e80-13ff-11e9-80db-4b312de7fdc0.gif)
I disabled all my other extensions.

**Comment by karina-archazh** [comment]
@AppleAuthority Send me your filters list, please!

**Comment by AppleAuthority** [comment]
![screenshot 2019-01-09 at 5 30 32 pm](https://user-images.githubusercontent.com/44805409/50917040-7e388900-1434-11e9-956a-55c5ee9ad857.png)

**Comment by karina-archazh** [comment]
I still can't reproduce this case.
What is your Flash player plugin version?

**Comment by AppleAuthority** [comment]
I don't have flash installed

**Comment by zzebrum** [comment]
guys, this is blocked by annoyances filter. 
@AppleAuthority if you want to unblock it, add this to the user filter:

`youtube.com#@#.ytp-cards-teaser`

**Comment by AppleAuthority** [comment]
@zzebrum I've noticed the same thing happens to video links. Is there a fix for that too?

**Comment by zzebrum** [comment]
@ sorry, I think I gave you the wrong rule. This is the right one `youtube.com#@#.video-annotations`
Please, confirm it helped you.

What exact video links are you talking about?
