### ISSUE TITLE
Unclear wording: « Use Optimized Filters »

### ISSUE THREAD

**Issue by FJdeKermadec** [AdguardTeam/AdGuardForSafari#123]
The current window in Preferences → General states that “Optimized filters” provide “light-weight filter lists optimized for Safari Content Blocking API.”

Unfortunately, the wording gives rise to more questions than it answers. Toggling this setting on or off has no visible effect on the list of filters available in Preferences → Filters. This begs the question:

1. Does toggling the setting _optimise_ all the lists chosen by the user before they are loaded into Safari?

2. Does the setting _restrict_ the lists being loaded to those that are optimised, regardless of the user’s chosen filters?

3. Does this setting _add to the list_ of filters enabled by the user?

This, coupled with the outdated "AdGuard Safari filter” in Filters → Other (which I believe is due for removal in an upcoming update) makes it very difficult to know what, ultimately, is loaded by AdGuard.

Would the developers care to offer some insights and maybe update the wording of the setting to better define its scope?

**Comment by ameshkov** [comment]
Basically, it means that AG downloads optimized versions of filter lists, i.e. `https://filters.adtidy.org/extension/safari/filters/2_optimized.txt` instead of `https://filters.adtidy.org/extension/safari/filters/2.txt` (compare the size to get the idea).

> 1. Does toggling the setting optimise all the lists chosen by the user before they are loaded into Safari?

Not all lists are optimized. We do this for huge lists only. For instance, AdGuard Base filter is optimized, and AdGuard Mobile Ads filter is not.

> Does the setting restrict the lists being loaded to those that are optimised, regardless of the user’s chosen filters?

No, it does not.

> Does this setting add to the list of filters enabled by the user?

No.

**Comment by FJdeKermadec** [comment]
Thank you for your kind and pellucid answer, @ameshkov! 😊

May I suggest a tweak to the wording, then? Something like:

> **Use optimized filters**
> Prefer versions of the filtering lists that have been optimised for Safari’s Content Blocking API, when these are available. This will not affect the nature of the blocked content, but may make blocking faster when using popular lists.

Ideally, lists that have been optimised should be tagged with a grey `#optimized` tag in the interface when this setting is on.
