### ISSUE TITLE
Video load slow on pornhub

### ISSUE THREAD

**Issue by Tsahao** [AdguardTeam/AdGuardForSafari#128]
### Steps to reproduce

1.any video on pornhub
2.
3.
4.

### Expected behavior

Loading speed shouldn't be much slower than it without Adguard
### Actual behavior

load slower than turning off Adguard

<details><summary>Screenshots:</summary>

</details>

### Your environment

* AdGuard for Safari version: 1.2.1
* Environment name and version: Safari 12.0.2(e.g. Safari 11.1.2 (13605.3.8))
* Operating System:Mohave 10.14.2 (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard: Adguard Base Filter, Adguard Anooyances filter, Easylist China, Filter unblocking search ads and self-promotion

* Any other browser extensions you have installed:

**Comment by Alex-302** [comment]
@Tsahao could you, please, check without filters? I see no difference.

**Comment by zzebrum** [comment]
reopen if needed.

**Comment by sorypsi** [comment]
yeah, this is it. i've been wondering why Pornhub is slow this whole year. just turned off adguard. now it loads videos at 1080p without stopping to buffer. adguard was the cause. so weird?

**Comment by ameshkov** [comment]
I wonder could pornhub penalize ad blocking users this way?

**Comment by TheHasagi** [comment]
@sorypsi 

Can you check with only AdGuard filters? I see no difference.
