### ISSUE TITLE
Cannot submit feedback to Google due to "a problem"

### ISSUE THREAD

**Issue by pentool** [AdguardTeam/AdGuardForSafari#129]
When you try to send feedback to Google (YouTube, Google Voice, Maps, etc) Safari will report a problem first. The second time you try it, Safari will display a blank page and reports that there were multiple problems with the website XYZ.

Initially I thought this might be an issue with Safari so I reported this to Apple. I realized a few days later that this might be an issue with the AdGuard. Sure enough, when you disable AdGuard this issue will not surface.

### Steps to reproduce

This screen recording demonstrates the issue with YouTube. The same problem happens when you try to provide similar feedback for Google Maps, Google Voice, etc.
[https://www.youtube.com/watch?v=MtK51R-umcc](https://www.youtube.com/watch?v=MtK51R-umcc)

1. Make sure you use the standard installation of AdGuard and after install, do not make any changes to the various options/preferences.
2. Go to a Google product in Safari, such as YouTube, Google Voice, Maps, etc.
3. You can log in to your Google account but it is not required (as you can see in the video)
4. Find the menu item/link to provide a feedback (usually under your account menu, and select "Send feedback".
5. The first time you do this, Safari will display a message bar across the top of the window that a problem occurred and the page was reloaded.
6. When you repeat the action again (eg you select the "Send feedback" menu item), Safari will display a blank page and reports that multiple problems occurred with the website XYZ and you need to reload the page.

### Expected behavior

Ideally, AdGuard should not block the user from sending feedback. Maybe there's a way to tweak the settings in AdGuard, but this happens just with the basic installation without any tweaks or changes in the default settings.

### Actual behavior

<details><summary>Screenshots:</summary>

![user-filter](https://user-images.githubusercontent.com/1972916/51586568-9d063900-1e92-11e9-9006-ef9f5a9f05d5.png)
![general](https://user-images.githubusercontent.com/1972916/51586569-9d063900-1e92-11e9-8516-41e96df36877.png)
![filters](https://user-images.githubusercontent.com/1972916/51586570-9d063900-1e92-11e9-8d69-2d03e9ec7679.png)
</details>

### Your environment

* AdGuard for Safari version: 1.2.1
* Environment name and version: Safari 12.0.2
* Operating System: macOS Mojave 10.14.2
* Filters you use in AdGuard: whatever comes with the basic installation, without modifying anything
* Any other browser extensions you have installed: none

**Comment by zzebrum** [comment]
@pentool  Sorry, I missed the issue. 
yeap, it's reproducible, disabling filters doesn't help

**Comment by Mizzick** [comment]
Disabling filters helps on my side, problematic rule is in Base Filter.
Most probably the issues caused by removing some library. But this way Safari handles it is a shame.
@Alex-302 please have a look.
<img width="1229" alt="Screenshot 2019-03-19 15 45 16" src="https://user-images.githubusercontent.com/13855288/54610946-b70d6380-4a5e-11e9-9b25-185d0669ff31.png">

**Comment by Alex-302** [comment]
It works with `@@|http`, but I can't find a working specific exclusion.
