### ISSUE TITLE
Toolbar extension is not changed if Adguard stoped via Menu Bar icon menu

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdGuardForSafari#131]
[▶️ <b>Actual behaviour</b>](https://uploads.adguard.com/slbdzd8lmodqb.mp4)

* AdGuard for Safari — 1.2.1
* Safari 12.0.2 
* MacOS 10.14.2

**Comment by slavaleleka** [comment]
Close the app.

Blocking **continues to work**, but Toolbar Button looks like paused:

![image](https://user-images.githubusercontent.com/45171506/54698264-1000f880-4b40-11e9-9b6b-d344b16bba2a.png)

**Comment by Mizzick** [comment]
I request some design changes then, in case the app is closed toolbar extension is not fully functional.

**Comment by ameshkov** [comment]
This is actually by design
