### ISSUE TITLE
YouTube flicker at start

### ISSUE THREAD

**Issue by Tsahao** [AdguardTeam/AdGuardForSafari#132]
### Steps to reproduce

1.https://www.youtube.com/watch?v=0tLE8hLD9TQ
2.

### Expected behavior

go full screen and play as normal
### Actual behavior

there is screen flicker at the start for several seconds.
if turn on screen recording, it turns to normal.
Turn off Adguard extension, it turns to normal, behave very consistent.
<details><summary>Screenshots:</summary>

</details>

### Your environment

* AdGuard for Safari version: 1.2.1
* Environment name and version: 12.0.2(e.g. Safari 11.1.2 (13605.3.8))
* Operating System:10.14.3 (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:* Adguard Base Filter, Adguard Anooyances filter, Easylist China, Filter unblocking search ads and self-promotion
* Any other browser extensions you have installed:LastPass

**Comment by Tsahao** [comment]
only happen on 16:9 ratio videos, not happen on wider ratio video.

**Comment by zzebrum** [comment]
@Tsahao try to disable all filters and check if the issue will persist, please.

**Comment by Tsahao** [comment]
Wont persist.
And after testing, I think it is the AdGuard Annoyances filter doing this. Disabling it would be okay, reenabling it would bring the problem back.

**Comment by TheHasagi** [comment]
@Tsahao 

Can you check now and confirm that problem is gone?

**Comment by Tsahao** [comment]
@TheHasagi Yes it is gone. Seems like a macOS bug.
