### ISSUE TITLE
False positive result on app.bugsnag.com

### ISSUE THREAD

**Issue by chimit** [AdguardTeam/AdGuardForSafari#135]
### Steps to reproduce
1. Open app.bugsnag.com
2. See the endless loading of content

### Expected behavior
Normal loading.

### Actual behavior
Endless loading indicator in the main content section.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/839349/53313177-24f8bc00-38f3-11e9-82f1-9ec964a91e85.png)

</details>

### Your environment

* AdGuard for Safari version: 1.2.1
* Environment name and version: Safari 12.0.3 (14606.4.5)
* Operating System: macOS Mojave 10.14.3
* Filters you use in AdGuard: all without Custom
* Any other browser extensions you have installed: LastPass, Font Ninja, Pocket, Grammarly, FreeStyler.

**Comment by ameshkov** [comment]
@Alex-302 plz take a look, I guess this is a filters issue

**Comment by Alex-302** [comment]
It works on my end.
`Filters you use in AdGuard: all`
maybe this is a reason - too much filters(with ABP Japanese)

**Comment by chimit** [comment]
It's because "Anti-tracking" option is enabled. If I switch if off the problem is gone.

**Comment by zzebrum** [comment]
@chimit are you talking about Spyware filter? or something else?

**Comment by chimit** [comment]
I don't know how is it called in the English version:

![image](https://user-images.githubusercontent.com/839349/53401097-1d680e80-39ea-11e9-9ac6-43c988adec22.png)

**Comment by zzebrum** [comment]
Oh, sorry I missed your reply. The problem is indeed with Spyware filter enabled
console: 
https://uploads.adguard.com/Welcome_to_Bugsnag_2019-03-14_12-27-52.png

**Comment by Alex-302** [comment]
@chimit проверьте такое правило, добавив в пользовательский фильтр:
`@@||app.bugsnag.com^$domain=app.bugsnag.com`

**Comment by SoLenny** [comment]
For a long time we did not receive a response from the user, therefore we close this task at the moment.
But you can open it again at any time :)
