### ISSUE TITLE
Stop enabling Safari filter by default

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#137]
The filter is now marked "obsolete", all the necessary rules are included into the base filter.

**Comment by iDjay** [comment]
just to make sure, I don't need the Safari anymore? Running the latest system/ Safari versions.

**Comment by ameshkov** [comment]
Yep, you don't

**Comment by BranchS** [comment]
Forget not enabling it, if it's not needed at all anymore, why not just remove it? #134

**Comment by zzebrum** [comment]
@Mizzick Other filters group should be disabled by default in this case I think

**Comment by slavaleleka** [comment]
@zzebrum but search ads and the self-promotion of websites should be enabled by default, shouldn't they? if so, Filter unblocking search ads and self-promotion should be enabled (and Other filters group too)

**Comment by zzebrum** [comment]
@slavaleleka oops, how did I miss that?

**Comment by superlex** [comment]
Hi :)
Thank you for new 1.3.0 beta :)
Safari filter is now disabled by default, however "Other" is still enabled, even if without filters. Maybe it should be disabled as well.

**Comment by BranchS** [comment]
I asked before but I’ll ask again. If it’s obsolete and not needed anymore, why not just remove it? #134

**Comment by ameshkov** [comment]
> I asked before but I’ll ask again. If it’s obsolete and not needed anymore, why not just remove it? #134

We will get rid of it when all AG products that work with Safari are updated.

**Comment by BranchS** [comment]
@ameshkov So when the Mac Version of 1.3 is released, it'll be removed?

**Comment by ameshkov** [comment]
@BranchS no, there's also AdGuard for iOS that needs to be updated as well.

**Comment by iDjay** [comment]
@ameshkov any news on the iOS beta version? Would love to test it :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
Huh, I'm reopening the issue because I was right and search ads filter is disabled by default, so Other filter group also should be disabled now. 

@iDjay there will be an announcement about it in our blog very soon.
