### ISSUE TITLE
Use localized date format

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardForSafari#139]
Suggest to use Chinese date format for filters' update time in Chinese interface.
Use 24-hour clock.
Don't need AM or PM.
ex: March 08, 2019 19:23:56
Chinese date format: 2019年3月8日 19:23:56

Because I don't have Mac, I can't check its Chinese date format.
Please note it.
If you already did it, please ignore this request.
Thanks.

**Comment by floam** [comment]
FYI you can just use `toLocaleString()` and get a date formatted for the user's locale. 

Before and after configuring my Mac with simplified Chinese in a Safari javascript console:
```
> new Date().toLocaleString()
< "3/8/2019, 6:31:55 PM"
> new Date().toLocaleString() 
< "2019/3/8 下午6:32:26"
```

However it seems not to respect the 24-hour preference in WebKit.

**Comment by lancelot-moon** [comment]
Can this help?
let date = Date()
let dateFormatter = DateFormatter()
dateFormatter.dateFormat = "YYYY年MM月dd日 HH:mm:ss"
dateFormatter.string(from: date)

https://www.ibm.com/support/knowledgecenter/en/SSS28S_3.0.0/com.ibm.help.forms.doc/locale_spec/i_xfdl_r_formats_zh_Hant_TW.html

HH: 24-hour clock
hh: 12-hour clock

**Comment by Mizzick** [comment]
As I see it's implemented already.

**Comment by lancelot-moon** [comment]
In v1.2.1, you used wrong locale, so my Traditional Chinese translations aren't applied.
It shows English interface while the system language is Traditional Chinese (zh-TW).

May you give the screenshot?
Ex: Go to the filters of ad blocking.
Thanks.

**Comment by Mizzick** [comment]
@lancelot-moon, It is not possible to provide the screenshot, cause we use system locale, which could not be changed so easy in mac os.

**Comment by Mizzick** [comment]
<img width="994" alt="Screenshot 2019-03-12 13 12 59" src="https://user-images.githubusercontent.com/13855288/54195938-a9893400-44c8-11e9-9d59-d6b018b0178c.png">
<img width="1015" alt="Screenshot 2019-03-12 13 12 45" src="https://user-images.githubusercontent.com/13855288/54195939-aa21ca80-44c8-11e9-834a-018cf9bf2941.png">

**Comment by lancelot-moon** [comment]
@ameshkov 

Please reopen the issue.

In Mizzick's screenshots, there are 3 problems.
1. Before, we have known that AG team didn't correctly use zh-TW locale for Traditional Chinese interface in AG for Safari v1.2.1.

2. You use **outmoded translations of filters' name and descriptions**.
Ex: In that screenshot, 英文過濾器 means English filter.
But it's renamed as Base filter (基本過濾器).
Do you remember that this issue ever occurred in AG Browser Extension v3?

3. In the filter's update time, the date format is 2019/3/12 下午12:30:47. (下午=PM)
But I wish it could be 2019年3月12日 12:30:47. (24-hour clock)

**Comment by Mizzick** [comment]
1-2. These are the screenshots from my developer's build, the phrases may not be up to date.
3. I'm not familiar with Chinese date formatting, but this is the format given by `toLocaleString()`.

**Comment by lancelot-moon** [comment]
In AG Browser Extension v3, @maximtop had fixed it.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Q52yPMI.png)
</details><br/>

It should be able to be fixed in the filter's update time.
"YYYY年MM月dd日 HH:mm:ss"

**Comment by ameshkov** [comment]
Hour format depends on your settings. On @Mizzick computer it is set to be 12-hour, on yours you can set whatever you want.

**Comment by lancelot-moon** [comment]
> 1-2. These are the screenshots from my developer's build, the phrases may not be up to date.

In v1.2.1 **release**, it might be already so.
It doesn't just occur from your developer's build.

I don't know how it will be on macOS.
On my Windows 10, my system time setting is 12-hour clock.
But as what I said, @maximtop can let it correctly show Chinese date and 24-hour clock in the configuration of AG Browser Extension v3.

BTW, your date formats in all platforms are **a little disordered**...
While the system's and AG's language are Traditional Chinese, it shows some different date formats somewhere in AG apps.

12/03/2019 <- The filter's update time in AG Browser Extension v3.
2019/3/12 <- The filter's update time in AG for iOS, AG Content Blocker for Android, AG for Windows and AG for Safari.
2019年3月12日 <- The filter's update time in AG for Android.
