### ISSUE TITLE
You can’t see how many filter rules are enabled

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardForSafari#142]
Maybe I‘m blind, but I can‘t find a way to see how many filter rules are activated. On iOS f.e. I can see that 47.416 are enabled.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
It's here:
https://uploads.adguard.com/up04_3kslm_AdGuard_for_Safari_-_Settings.png

**Comment by iDjay** [comment]
@ameshkov not in my case, running v. 1.2.1 ![GitHawk Upload by iDjay](https://i.imgur.com/aw0Ggn5.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
Huh, and that's weird. @Mizzick could it be a localization issue?

**Comment by Mizzick** [comment]
Yes, it is. Gonna be fixed with updated locales

**Comment by iDjay** [comment]
@ameshkov maybe add a „,“ between filters and the number, so it‘s „6 Filters, 46811 rules“ easier to read in my opinion :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
