### ISSUE TITLE
Blocking should be paused if Adguard is closed

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdGuardForSafari#145]
### Steps to reproduce:
1. Close Adguard for Safari.

### Expected behavior
If Adguard is closed blocking should be paused.

### Actual behavior
After Adguard's closing Toolbar Button shows it as paused, but it's not actually and ads still blocking as nothing happened.

![image](https://user-images.githubusercontent.com/45171506/54694866-01174780-4b3a-11e9-8d0f-85cfaa47a90b.png)

### Your environment
* AdGuard for Safari new build

**Comment by ameshkov** [comment]
This is actually by design
