### ISSUE TITLE
Notification about continuous blocking after AG closing 

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdGuardForSafari#146]
There is no sign of continuous blocking if Adguard for Safari is closed. 

Before closing the app (or/and somewhere else) should be notification, something like this: 
**After you close the app, blocking will continue to work. 
To stop it properly you should use *Toolbar AG Button > Stop Adguard.***

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/f63a5bca-2cd0-4b45-b3ae-5c6a1ff0f75f

**Comment by Mizzick** [comment]
Do we really want to prevent user from closing the app?
In my own experience it could be very annoying.

**Comment by ameshkov** [comment]
In fact, we should instead change how the toolbar icon's menu looks like when AdGuard is disabled.

We should indicate that content blocking is enabled even though AdGuard's main process is not running.

**Comment by ameshkov** [comment]
Main text:
```
AdGuard is disabled. It needs to be running if you want to change content blocking settings.
```

Small gray text under the "Run AdGuard" button:
```
Please note that content blocking in  Safari is operational even when the app is not running.
```
