### ISSUE TITLE
AdGuard on meun bar

### ISSUE THREAD

**Issue by chrxszy** [AdguardTeam/AdGuardForSafari#147]
Really don't want to have AdGuard logo on my menu bar, can we at least have an option to not showing it if we don't want it to show? please? thanks

**Comment by iDjay** [comment]
There is an option to disable it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by superlex** [comment]
Fixed in https://github.com/AdguardTeam/AdGuardForSafari/issues/84
