### ISSUE TITLE
How to remove AdGuard notifications from safari console?

### ISSUE THREAD

**Issue by yarovikov** [AdguardTeam/AdGuardForSafari#148]
hi all. how can i hide it?

<img width="404" alt="Screenshot 2019-03-24 at 12 17 04" src="https://user-images.githubusercontent.com/30932012/54877378-c14caa80-4e2e-11e9-915d-ec9bf14b3233.png">

**Comment by ameshkov** [comment]
Hm, what version you are using?

**Comment by yarovikov** [comment]
> Hm, what version you are using?

adguard 1.2.1
safari 12.0.3
mac os 10.14.3

**Comment by ameshkov** [comment]
Once #174 is done, we should print these records only when verbose logging is enabled.
