### ISSUE TITLE
Smaller app icon

### ISSUE THREAD

**Issue by chinnnki** [AdguardTeam/AdGuardForSafari#149]
### Expected behavior
Appropriate app icon size

### Actual behavior
Current app icon appears a lot larger than others

<details><summary>Screenshots:</summary>
</details>
<img width="319" alt="Screen Shot 2019-03-27 at 14 10 38" src="https://user-images.githubusercontent.com/12984268/55052176-50f69100-509b-11e9-9fdf-c7ffa3a01460.png">

Scaling it down to 85–90% of the current size should suffice.

### Your environment

* AdGuard for Safari version: 1.2.1
* Environment name and version: Safari 12.1 (14607.1.40.1.4)
* Operating System: macOS Mojave 10.14.4

**Comment by chernikova-yana** [comment]
Smaller app icon:
https://share.goabstract.com/064ac422-b6c0-4342-9069-b25226ac4fcc?sha=167660ada0a6c907e225af32f2ece511036b2eb4
