### ISSUE TITLE
Block an element is not working in some websites

### ISSUE THREAD

**Issue by duplex143** [AdguardTeam/AdGuardForSafari#150]
### Steps to reproduce

1.Open https://www.cricbuzz.com/live-cricket-scorecard/22403/srh-vs-rr-8th-match-indian-premier-league-2019
2.On the top, advt is displayed. I blocked it manually. Filter for the top advt is `cricbuzz.com###google_ads_iframe_\/1024780\/FullScorecardPage_728x90_0`
3.Similarly I'm blocking other advts in the page. After refreshing, the same advts are displayed again.
4.Similar case with YouTube as well.

### Screenshots

<img width="1280" alt="Screenshot 2019-03-29 at 9 18 50 PM" src="https://user-images.githubusercontent.com/24863030/55245147-974d1b00-5268-11e9-985a-c88be8465677.png">

Advts are marked in purple rectangle. I couldn't block them no matter what. Those advts are automatically blocked by AdBlockPlus by default. I don't know why Adguard isn't blocking them  automatically in the first place.

### Your environment

* AdGuard for Safari version: 1.2.1
* Environment name and version: 12.1 (14607.1.40.1.4)
* Operating System: 10.14.4 (18E226)
* Filters you use in AdGuard: All filters
* Any other browser extensions you have installed: None

**Comment by slavaleleka** [comment]
@duplex143 The issue may be caused by too many enabled filters. First of all disable all filters please and turn on only recommended ones

**Comment by superlex** [comment]
I think Safari has some limitations.
Check raiplay.it : 
`raiplay.it##.paddingSociale`
works with AG Ext + Firefox but it doesn't with AG For Safari, I have to use 
`raiplay.it##[class*="paddingSociale"]`

**Comment by duplex143** [comment]
> @duplex143 The issue may be caused by too many enabled filters. First of all disable all filters please and turn on only recommended ones

Even after enabling only the recommended ones, I'm facing the issue. It's like Adguard is not at all working. I'm seeing advts before every YouTube video.

**Comment by superlex** [comment]
> I'm seeing advts before every YouTube video.

Cannot reproduce. How many rules do you have enabled?

**Comment by duplex143** [comment]
> > I'm seeing advts before every YouTube video.
> 
> Cannot reproduce. How many rules do you have?

2 filters and 0 rules. 
AdGuard Base filter and AdGuard Mobile Ads filter

**Comment by superlex** [comment]
0 rules?
It looks like you're experiencing bug #90 .
Try to update filters and remove AdGuard Mobile Ads filter, it isn't needed for desktop.

**Comment by zzebrum** [comment]
@duplex143 what filters are enabled in AdGuard?

**Comment by duplex143** [comment]
https://github.com/AdguardTeam/AdGuardForSafari/issues/150#issuecomment-478352141

**Comment by duplex143** [comment]
> @duplex143 what filters are enabled in AdGuard?

https://github.com/AdguardTeam/AdGuardForSafari/issues/150#issuecomment-478352141

**Comment by zzebrum** [comment]
🙈 I don't know what's wrong with me.
@duplex143 I'd recommend to clear browser cache and cookies and to enable spyware, base, and language-specific filters.

**Comment by duplex143** [comment]
> 🙈 I don't know what's wrong with me.
> @duplex143 I'd recommend to clear browser cache and cookies and to enable spyware, base, and language-specific filters.

I've cleared browser cache and cookies. Still the same. My query is not why Adguard is not blocking the advts in the first place. But why is **Block an element** not working?

**Comment by duplex143** [comment]
> > I'm seeing advts before every YouTube video.
> 
> Cannot reproduce. How many rules do you have?

Can you check for [this](https://www.cricbuzz.com/live-cricket-scorecard/22403/srh-vs-rr-8th-match-indian-premier-league-2019) website? Check if you are seeing the 3 advts like I said [here](https://github.com/AdguardTeam/AdGuardForSafari/issues/150#issue-427058224). If yes, try blocking them with **Block an element** and refresh. Tell me if you are seeing the 3 advts again.

**Comment by zzebrum** [comment]
@duplex143 I understand your question. But the thing is that it should be blocked by filters rules and it's not. Anything in User filter?

**Comment by duplex143** [comment]
```
9gag.com###google_ads_iframe_\/16921351\/9GAG\/Unit8_0
youtube.com###invideo-overlay\:7 > div.ytp-ad-overlay-container > div.ytp-ad-image-overlay:last-child > div.ytp-ad-overlay-image:last-child > img
cricbuzz.com###google_ads_iframe_\/1024780\/FullScorecardPage_300x250_2_0
cricbuzz.com###google_ads_iframe_\/1024780\/FullScorecardPage_300x250_2_0
```

**Comment by slavaleleka** [comment]
@duplex143 are you sure Adguard isn't paused and that website isn't whitelisted?

**Comment by duplex143** [comment]
> @duplex143 are you sure Adguard isn't paused and that website isn't whitelisted?
@slavaleleka Yes

**Comment by duplex143** [comment]
Can you post the ss of this page?
https://www.cricbuzz.com/live-cricket-scorecard/22403/srh-vs-rr-8th-match-indian-premier-league-2019
Reinstalling didn't help either.

**Comment by duplex143** [comment]
@slavaleleka @zzebrum I just noticed that no ad block extensions are working in my Safari. I've tried Adguard, Adblock, Adblock plus. Any advice?

**Comment by zzebrum** [comment]
> no ad block extensions are working in my Safari.
🙃 

I would've tried to reset Safari settings.

**Comment by superlex** [comment]
@duplex143 
Try
`defaults delete com.apple.Safari`
(you could lose your bookmarks and other things)

@zebrum @slavaleleka 
Could you try https://github.com/AdguardTeam/AdGuardForSafari/issues/150#issuecomment-478089866, please?

**Comment by duplex143** [comment]
I can't reset Safari for this. I've switched to chrome for now. I think the latest Safari update messed up something. Apparently another user is also facing the same issue.
https://www.reddit.com/r/Adguard/comments/b8ih41/adguardforsafari_not_working/

**Comment by duplex143** [comment]
Resetting Safari didn't help. Apparently there's no problem with Adguard. Some issue with my native Safari. There's this beta Safari called [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/). Adguard is working perfectly fine there. I'll use this beta in the meanwhile. Thanks for the help.

**Comment by slavaleleka** [comment]
> Could you try #150 (comment), please?

@superlex AG for Safari has limitations, but they are not linked with class names, and `raiplay.it##.paddingSociale` works quite fine in Safari on my end.

**Comment by superlex** [comment]
Thanks @slavaleleka 
On my end it doesn't. However, `raiplay.it##.prefooter-fixed` works and `raiplay.it##[class*="paddingSociale"]` works as well; also, `raiplay.it##.paddingSociale` works with AG Ext for Firefox.

**Comment by duplex143** [comment]
There was some issue with my Safari. Reinstalling macOS from recovery fixed the problem.
