### ISSUE TITLE
Add scriptlet rules support to the advanced blocking extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#151]
See the details here: `/browser-extension/pull-requests/328/overview`

In case of Safari, I guess it'd be easier to use the corelibs build of scriptlets library:
https://github.com/AdguardTeam/Scriptlets#corelibs-library

Please note, that it's not final, and AG for Safari will be the first to use it. Feel free to change the format if you feel that there's a better solution

1. [x] Add integration with AdGuard scriptlets: https://github.com/AdguardTeam/Scriptlets
2. [x] Automatically convert `##+js` scriptlets and `#$#` snippets to AG rules
4. [x] Add "debug" mode to scriptlets. It needs to be enabled only when the filtering log is open, call to `hit()` should be printed to the console. Here's what is important: stack trace and rule text.
5. [x] Make sure that we're compatible with `##+js` (check that popular rules work similarly)
6. [x] Make sure that we're compatible with `#$#` (check that popular rules work similarly)
7. [x] Syntax highlighting for `##+js` and `#$#`
8. [x] Make sure that `#@#+js` works as intended
9. [x] Check if it's possible to disable ABP snippets (maybe `#@$#`?)
10. [x] Limit scriptlet rules to trusted filters only

**Comment by superlex** [comment]
Wonderful, I cannot wait :D

**Comment by Mizzick** [comment]
Testcases:
http://testcases.adguard.com/Filters/scriptlet-rules/test-scriptlet-rules.html

**Comment by ameshkov** [comment]
@Mizzick we should allow enabling "Verbose" mode of the advanced blocking extension: https://uploads.adguard.com/up04_4y5fx_up04_mk6nm_Extensions.png_17721320.png

If "verbose" mode is enabled:
1. Extension prints debug-level logs
2. Scriptlets `source` object has `verbose` flag set to true (this enables logging scriptlet hits)

**Comment by superlex** [comment]
Thank you! :)
