### ISSUE TITLE
Standalone builds of AdGuard for Safari

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#153]
We need to have two channels: beta and release

* [ ] Beta channel
* [ ] Release channel
* [ ] Add "How to release" section to the readme
* [ ] Update the readme and add links to standalone builds

Also, there's one more important thing about standalone builds, they must be notarized. See the details here:
https://github.com/AdguardTeam/AdguardForMac/issues/350

**Comment by iDjay** [comment]
How can we Beta Test version 1.3? Only got the key for the Mac version (2.0) but I prefer the safari extension 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
@iDjay currently - there's no beta channel, but that's what we're trying to achieve in this issue -- establish standalone beta/release channels

**Comment by ameshkov** [comment]
@Mizzick auto-update seems to be working okay in the dev build.

There's one slight change that needs to be done: click on the notification should open `https://github.com/AdguardTeam/AdGuardForSafari/releases`
