### ISSUE TITLE
Incorrectly detected number of rules for Custom filter

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdGuardForSafari#157]
Disable all filters group except Custom and add a custom filter, e.g. [this one](https://raw.githubusercontent.com/AdguardTeam/TestCases/master/Filters/extended-css-rules/test-extended-css-rules.txt). There are 18 rules

<details><summary>Screenshots:</summary>

![image.png](https://images.zenhubusercontent.com/5be2d97b7c17fe10e1b42e01/b45d8e3c-3d78-48cc-9f79-0b806abc8682)

</details>

* AdGuard for Safari version: 1.3.0

**Comment by Mizzick** [comment]
In most cases this could happen during updating content-blocker in Safari, it usually could take some time. So I propose we might have some "loading" state for this information label.

**Comment by zzebrum** [comment]
Nah, the number didn't change since yesterday )
