### ISSUE TITLE
Block an Element not working in Safari Technology Preview 80

### ISSUE THREAD

**Issue by villaineyed** [AdguardTeam/AdGuardForSafari#159]
Block an Element not working in Safari Technology Preview 80

**Comment by Mizzick** [comment]
@zebrum please check.
All good on my side.

**Comment by villaineyed** [comment]
Definitely still not working for me. Should I post video to confirm?

**Comment by ameshkov** [comment]
@villaineyed sorry for the delay. Could you please try the beta version of AdGuard for Safari?

**Comment by zzebrum** [comment]
Safari Technology Preview 81 and AG beta - cannot confirm the problem
@villaineyed yes, please, explain in more details or record a video how exactly is not working.
