### ISSUE TITLE
AG for Safari integration mode with the desktop app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#162]
Just like other AG extensions, we should provide integration mode in AG for Safari:
https://kb.adguard.com/ru/browser-extensions/integration-mode

**Comment by superlex** [comment]
Uhm..
So will it be better to have both AG for Mac and AG for Safari instead of just AG for Mac?

**Comment by lancelot-moon** [comment]
AG Browser Extension/AG for Safari is for free users...
After all, AG company hope that those free users will be interested in paid AG products.
How do you think it's better to have them both if you're ever using paid AG desktop app?

https://www.reddit.com/r/Adguard/comments/bh3xdv/adguard_please_consider_removing_clutter/elzahu2/

Andrey:

> Also, you were right to remove the Safari extension. AG for Mac is more powerful, and there's little sense in keeping them both.

**Comment by superlex** [comment]
@lancelot-moon 

> AG Browser Extension/AG for Safari is for free users...
> After all, AG company hope that those free users will be interested in paid AG products.
 
Make sense, but it's another matter :)

> How do you think it's better to have them both if you're ever using paid AG desktop app?

In fact my question was about that: what's the purpose of integration mode?
If 

> AG for Mac is more powerful, and there's little sense in keeping them both

then it should be better suggest to remove AG for Safari when you install AG for Mac (also because otherwise there would be 2 AG apps). On the contrary, if AG for Mac + AG for Safari is better than only AG for Mac, then integration mode has a purpose.

**Comment by lancelot-moon** [comment]
> missing features could be added to AG for Mac

For example??

Go to read about integration mode on AG KB.
They're not necessary points if you can judge.
For now, the integration mode only makes sense for AG Assistant.

But finally I believe that users will be able to hide the icon of AG Assistant.

**Comment by superlex** [comment]
@lancelot-moon 
According to https://kb.adguard.com/en/browser-extensions/integration-mode

> If you already use an AdGuard app, our browser extension may become a very useful additional tool

it looks like yes, having both AG for Mac and AG for Safari instead of just AG for Mac it's better than just AG for Mac.

**Comment by lancelot-moon** [comment]
@superlex

How is it useful if you really read the KB?
Anything which only Browser Extension can do?
I supposed that you have yourself thought.
Disappointed.
Andrey had said Browser Extension has little sense if having AG for PC.
Well, just waste our time.

**Comment by superlex** [comment]
Sorry if you lost your time reading my questions and doubts.

**Comment by lancelot-moon** [comment]
I think, therefore I am.
Sorry if you can't tell any useful points about Browser Extension/integration mode when having AG for PC.

It's a good thing if somebody needs integration mode.
Then AG provides it even if this makes little sense.
See you...

**Comment by Mizzick** [comment]
There is no way we can achieve this without WebRequest API in Safari

**Comment by ameshkov** [comment]
Well, it's possible, but makes no sense since AG for Mac now provides its own assistant extension.

**Comment by superlex** [comment]
So I'm not was so wrong

> if AG for Mac + AG for Safari is better than only AG for Mac, then integration mode has a purpose, but in this case missing features could be added to AG for Mac.

:)
