### ISSUE TITLE
AdGuard Safari takes longer than AdGuard Mac to launch

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardForSafari#167]
I realized that AdGuard for Safari takes longer to start at launch than AdGuard for Mac.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
Yeah, that's because Electron is quite slow, and AdGuard for Mac is a native app.
This can't be changed unless we ditch Electron :(
