### ISSUE TITLE
Safari freezes for a few seconds when AdGuard updates the filters

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardForSafari#168]
When AdGuard performs an auto update, Safari freezes for a few seconds

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
Marked as a bug for now, but it might be a Safari issue and not ours. We should look into it.

**Comment by FatKiwi** [comment]
@ameshkov is this the first time something like this is reported? I have this issue for over 2 years and keep hoping it gets fixed but it never does.

Happens on PC, Android. Everywhere. Normally at least once a day all connections would freeze while it calls to local.adguard

Updating the filters always solves it immediately.

**Comment by zzebrum** [comment]
@FatKiwi please create issues in suitable repositories and explain with more details what is happening. 
I'll assign this issue to 1.5 milestone.

**Comment by FatKiwi** [comment]
@zebrum Found it posted on Windows issues - [#2057](https://github.com/AdguardTeam/AdguardForWindows/issues/2057)
