### ISSUE TITLE
The number of rules is zero right after the installation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#173]
### Steps to reproduce

1. Download the latest AdGuard for Safari Beta
2. Unzip, move to Applications, run it
3. Enable Safari extensions
4. Go to the "Filters" tab

You will see that the rules count is 0.
Also, even if you check filters updates, it won't change unless you restart the UI.

**Comment by superlex** [comment]
Hi,
maybe they can be related:
https://github.com/AdguardTeam/AdGuardForSafari/issues/90
