### ISSUE TITLE
Use multiple extensions to bypass 50,000 rule limit

### ISSUE THREAD

**Issue by lawrence-m** [AdguardTeam/AdGuardForSafari#176]
Safari content blockers have a limit of 50,000 rules, however this could be increased by using multiple extensions for each category — for example, "AdGuard  – Ad Blocking", "AdGuard – Privacy", "AdGuard – User Filter".

This method is used on [1Blocker X](https://itunes.apple.com/us/app/1blocker-x-faster-safer-web/id1365531024?mt=8) for iOS.

**Comment by superlex** [comment]
Please wait for version 1.4 :
https://github.com/AdguardTeam/AdGuardForSafari/issues/93#issuecomment-444911540

**Comment by ameshkov** [comment]
Marked as duplicate
