### ISSUE TITLE
Please update translations.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardForSafari#179]
1. I found that they're outmoded translations in v1.3.2.
Please update translations before release version.

2. Please update the translations of overview on Mac App Store (Taiwan) because the English overview was changed.

Thanks.

**Comment by lancelot-moon** [comment]
Updated in v1.3.3.
Can be closed.
Thanks.

**Comment by lancelot-moon** [comment]
@Mizzick 
May you update the translations of overview on Mac App Store because the English overview was changed?

Well, new Traditional Chinese (zh-TW) translations for overview on Mac App Store were ready, but other languages' translations aren't ready.
Maybe wait for some time.

Thanks.

**Comment by zzebrum** [comment]
@lancelot-moon I'll update translations in the next release

**Comment by lancelot-moon** [comment]
Hi, it's already done.
You don't need to do.
Thanks.
