### ISSUE TITLE
Crash on the MAS build startup

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#185]
> If you are unable to reproduce this issue, ensure you are testing the exact version of the app that you submitted for review, and that you're doing so in a minimally privileged environment. See [Technical Q&A QA1778: How to reproduce bugs reported against Mac App Store submissions](https://developer.apple.com/library/mac/#qa/qa1778/_index.html).

<img width="532" alt="attachment-9024152549369065574Screenshot-0613-125144" src="https://user-images.githubusercontent.com/5947035/59463999-f960f980-8e2f-11e9-982f-bef01b6b5ad4.png">

**Comment by Yoshi2889** [comment]
Possibly related to #172 ? Almost exactly the same filename occurs in that issue as well.

**Comment by Mizzick** [comment]
@Yoshi2889 thanks, the issue is resolved in 1.3.4 version, which is currently in MAS.
