### ISSUE TITLE
With release 1.3.3 the autostart feature is not working anymore

### ISSUE THREAD

**Issue by interpretor** [AdguardTeam/AdGuardForSafari#190]
### Steps to reproduce

1. (Re-)install Adguard for Safari
2. Enable automatic Startup
3. Reboot

### Expected behavior

The Adguard for Safari application should start automatically on login

### Actual behavior

Nothing happens

### Your environment

* AdGuard for Safari version: 1.3.3
* Environment name and version: Safari 12.1.1
* Operating System: macOS Mojave 10.14.5
* Filters you use in AdGuard: Basic, Spyware and Language
* Any other browser extensions you have installed: -

**Comment by interpretor** [comment]
How is the autostart feature implemented? Does it use the ~/Library/LaunchAgents?

**Comment by Mizzick** [comment]
We simply used electron built-in functionality `app.setLoginItemSettings(settings)`
https://electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows.
Seems like it doesn't work well in 10.14.5

**Comment by ameshkov** [comment]
@interpretor version 1.3.4 should be available on the App Store in a couple of hours. Could you please check if the issue is gone in this new update?

**Comment by interpretor** [comment]
The autostart is now working again.

OT: Do you have an idea, why updates for the Adguard for Safari Extension are not showing up in the App Store updates section? I had to reinstall 1.3.3 and now 1.3.4.
Issue might not be on the OS side, as it is a fresh install with 1.2.1 extension, and other apps are updated normally.

**Comment by ameshkov** [comment]
@interpretor this is due to phased release:
https://uploads.adguard.com/up04_y3c4b_App_Store_Connect.png
