### ISSUE TITLE
Extension blocks non-advertising pages completely if they have "ad" in the URL 

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardForSafari#192]
### Steps to reproduce
1. Access **any** page containing "ad" in URL, e.g. https://www.theregister.co.uk/2019/06/19/brave_browser_gdpr_adtech_complaint/
2. Get a "page blocked by content blocker" message.
3. Behavior can only be mitigated by disabling the extension entirely.
4. Even the reports web app is blocked!

### Expected behavior
Page should open

### Actual behavior
All pages containing "ad" in its URL are blocked

<details><summary>Screenshots:</summary>
n/a
</details>

### Your environment
* AdGuard for Safari version: 1.2.1
* Environment name and version: Safari 11.1.1
* Operating System: macOS 10.14.5
* Any other browser extensions you have installed: Ghostery, Camelizer, uBlock Origin, 1Password

**Comment by Alex-302** [comment]
Caused by `_adtech_`
Fixed
