### ISSUE TITLE
Typed text appears with a delay in filter editor

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#193]
### Steps to reproduce

1. Type any text and wait for `Saved` message;
2. Start typing again

### Actual behavior
Text appears with a random delay.
* AdGuard for Safari version: 1.2.1
* Environment name and version: Safari 12.1.1
* Operating System: macOS 10.14.5
* Filters you use in AdGuard: Base, Rus

**Comment by superlex** [comment]
AdGuard For Safari 1.3.4 is affected too.

**Comment by zzebrum** [comment]
obsolete
