### ISSUE TITLE
Disable notifications for background filters updates

### ISSUE THREAD

**Issue by devburke** [AdguardTeam/AdGuardForSafari#195]
It would be great to have an option to disable notifications for filter updates. Right now, users can disable notifications for the whole app, but they may still want to be able to get notifications about extension updates. There's an option within the app to disable notifications about extension updates specifically. The option to disable just the filter update notifications would be nice. I think many users want something like an adblocker to essentially work silently in the background, and only call our attention if it's needed for something (I'd put extension updates in this category, since they can include feature/functionality changes).

Thanks!

**Comment by ameshkov** [comment]
Hm, well, in theory, the notification should be only shown when you trigger filters update from the UI.

If they are shown for background filters update, this is a bug.

**Comment by devburke** [comment]
Beginning with recent versions of the app, I am indeed getting notifications for background updates.

**Comment by Mizzick** [comment]
Don't you guys think it would be ok to update filters completely silent without any notifications?
I'm not so sure about it, this is kind of external network activity, most probably user should know about it?

**Comment by ameshkov** [comment]
Well, I wouldn't say it's that heavy, it's less than 1MB.

**Comment by devburke** [comment]
I think honestly users expect the background updates. If there's a concern about doing so without users' knowledge, then perhaps there could be a setting to notify about background updates. It could even be on by default (although I'd argue this wouldn't be what most users would want).
