### ISSUE TITLE
AdGuard for Safari uses between 2 and 10% CPU at every time even if Safari doesn't run

### ISSUE THREAD

**Issue by egla89** [AdguardTeam/AdGuardForSafari#200]
As the title suggest, AdGuard uses quite a lot of CPU in the background if Safari doesn't run. It results in AdGuard being the application with the third highest average energy impact on my computer.

### Your environment
* AdGuard for Safari version: 1.3.4
* Environment name and version: Version 12.1.1 (14607.2.6.1.1)
* Operating System: macOS Mojave 10.4.5
* Filters you use in AdGuard: Base Filter, AG Tracking Protection, AG Annoyances, AG Safari, AG German
* Any other browser extensions you have installed: 1password

**Comment by ameshkov** [comment]
I guess you mean the main app process?

**Comment by egla89** [comment]
Yes. The process usually hovers around 2.4% when the computer is idle, thus being by far the most demanding non-system process on idle

**Comment by ameshkov** [comment]
Do you have AdGuard Preferences window open at that moment or is it just the icon? I am trying to reproduce this issue.

**Comment by egla89** [comment]
I don't have the window open and "Show AdGuard for Safari in the menu bar" disabled.

**Comment by ameshkov** [comment]
@Mizzick any idea how we can figure out what's wrong?

**Comment by Mizzick** [comment]
I suppose this could be something like new version downloading or very slow filters update.
Somehow we should get the logs out.

**Comment by ameshkov** [comment]
@Mizzick what about simply invoking dev tools and checking what's going on on the performance tab?

**Comment by Mizzick** [comment]
As I know it's not possible to do it externally for electron main process. I'm preparing the new beta with changed logger, so we will be able to see it.

**Comment by Mizzick** [comment]
@egla89 
Please try the [latest beta](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.4.1-beta).

**Comment by egla89** [comment]
this seems to be better. I'm seeing 0.1-0.3% CPU usage

**Comment by zzebrum** [comment]
ok then, reopen if needed.
