### ISSUE TITLE
AdGuard for Safari 1.3.4 Opening Settings Panel on Every Login

### ISSUE THREAD

**Issue by PBearSF** [AdguardTeam/AdGuardForSafari#202]
Ever since AdGuard for Safari upgraded itself, a week or two ago, to version 1.3.4, it now displays its Settings panel on the screen every time the computer is (re)started.

### Steps to reproduce

1.
2.
3.
4.

### Expected behavior

AdGuard for Safari should start automatically every time the Mac is started (as the setting for automatic start is selected) but should only place its icon in the menu bar, as previous versions of AdGuard for Safari did.
### Actual behavior

AdGuard for Safari starts automatically every time the Mac is started or restarted and pops up its Settings panel on the screen with every start.

<details><summary>Screenshots:</summary>

</details>

### Your environment

* AdGuard for Safari version: 1.3.4
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) Safari 12.1.1 (14607.2.6.1.1)
* Operating System: (e.g macOS High Sierra 10.13.6) macOS Mojave 10.14.5
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

**Comment by superlex** [comment]
Hi,
try the latest beta:
https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.4.1-beta
See https://github.com/AdguardTeam/AdGuardForSafari/issues/201 and https://github.com/AdguardTeam/AdGuardForSafari/issues/141

**Comment by PBearSF** [comment]
Will do. Thanks.

**Comment by zzebrum** [comment]
closed as dup #141
