### ISSUE TITLE
Remove "AdGuard Safari filter" toggle.

### ISSUE THREAD

**Issue by devburke** [AdguardTeam/AdGuardForSafari#205]
If my understanding of reading the "AdGuard Safari filter" description is correct, then it is required to be turned on all the time if the app is to work at all. In that case, why even have a toggle? Why have a listing? If this is required for AG to work, why not just have it built in as something that's always enabled, and remove it from the filter list altogether? As it is, it just seems confusing and potential for users to cause problems.

This would go for AdGuard iOS as well.

**Comment by devburke** [comment]
I see that this is also discussed in #137, although there it refers to the filter as obsolete. It does not show as obsolete on my computer, so I'm not sure if it's still considered obsolete?

Either way, still seems like it should be removed from the settings, whether it needs to be turned on or not.

**Comment by ameshkov** [comment]
It is obsolete indeed, and eventually, it will be replaced with a different filter list.

**Comment by devburke** [comment]
Gotcha, I see. Well thanks for all you do!
