### ISSUE TITLE
MAS updates do not install unless user quits Safari manually first

### ISSUE THREAD

**Issue by unikitty37** [AdguardTeam/AdGuardForSafari#206]
### Steps to reproduce

1. Launch Safari.
2. Wait for an AdGuardForSafari update to be published to the App Store.
3. Attempt to update AdGuardForSafari through the App Store.
4. Click 'Continue' on the prompt that says the update cannot be installed without first quitting AdGuardForSafari.

### Expected behavior
The update installs, and AdGuardForSafari restarts.

### Actual behavior
The prompt appears again. Quitting Safari before clicking 'Continue' does not fix the problem. `ps auxww | grep -i adguard` shows no processes running.

The only way to install the update is to click 'Cancel' in the prompt, quit Safari, and *then* try and run the update.

(Sorry, I don't have any screenshots — I found the fix before opening the bug report, and I'd have to wait for you to release another update in order to get them :)

### Your environment

* AdGuard for Safari version: 1.4.1
* Environment name and version: Safari 12.1.1 (14607.2.6.1.1)
* Operating System: Mac OS X 10.14.5 (18F132)
* Filters you use in AdGuard: **Ad Blocking**: AdGuard Base / AdGuard Mobile Ads, **Privacy**: AdGuard Tracking Protection / EasyPrivacy, **Annoyances**: Annoyances / Adblock Warning Removal List, **Other**: AdGuard Safari filter
* Any other browser extensions you have installed: 1Password, StopTheMadness, Ghostery, JS Blocker 5, Camelizer, uBlock Origin.

**Comment by ameshkov** [comment]
Tbh, I don't think we can do anything with this. This is all controlled by macOS, not by us

**Comment by unikitty37** [comment]
I feared that might be the case, but it might be worth raising a radar with Apple as this isn't particularly helpful behaviour from Safari when a browser extension that has a helper app is being updated — either Safari should handle it without needing to quit, or Safari should quit (and the prompt should warn the user this will happen :)

Could you raise it? I only have the free developer account, and I get the distinct feeling any radars I open are treated as *very* low priority in Cupertino…

**Comment by BranchS** [comment]
This is now fixed in the latest version of Catalina. A notification appears from MAS asking you to quit Safari to continue the update. This can be closed :)

**Comment by ameshkov** [comment]
Thanks for the good news!:)
