### ISSUE TITLE
A wrong link to Tracking Protection filter on KB.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardForSafari#207]
AG Browser Extension has the wrong link to Tracking Protection filter on KB.
I guess AG for Safari is so.
Please check.

Outmoded:
https://kb.adguard.com/en/general/adguard-ad-filters#spyware-filter

Current:
https://kb.adguard.com/en/general/adguard-ad-filters#privacy

**Comment by superlex** [comment]
Yep, I can confirm.
