### ISSUE TITLE
See how many ads are being blocked?

### ISSUE THREAD

**Issue by BranchS** [AdguardTeam/AdGuardForSafari#208]
Not sure if this is possible with Content Blockers on Safari, but seeing in the AdGuard extension menu how many ads are being blocked at any given time would be nice-- that way you can tell right away if AG is affecting the display of a webpage.

Something like this ("9 blocked on this page"):
<img width="308" alt="Screen Shot 2019-07-19 at 8 34 10 PM" src="https://user-images.githubusercontent.com/38893932/61571826-954fd780-aa64-11e9-8d3e-fb7b0d2ae011.png">

**Comment by zzebrum** [comment]
@BranchS content blocking API doesn't provide such features, unfortunately.
