### ISSUE TITLE
Safari Launch Delay with AdGuard for Safari Installed

### ISSUE THREAD

**Issue by ifarlow** [AdguardTeam/AdGuardForSafari#209]
### Steps to reproduce
There are no specific steps to take except simply launching Safari.

### Expected behavior
I expect Safari to launch with AdGuard for Safari installed on my system as quickly as it does when AdGuard for Safari is not installed.

### Actual behavior
I have noticed that when AdGuard for Safari is installed, Safari has a noticeable delay when launched. I have also noticed that this delay is not eliminated simply by disabling AdGuard for Safari. The only way to remove this delay when launching Safari is to completely uninstall AdGuard for Safari.

### Your environment
* AdGuard for Safari version: 1.4.1
* Environment name and version: Safari 12.1.1 (14607.2.6.1.1)
* Operating System: macOS Mojave 10.14.5 (18F132)
* Filters you use in AdGuard: AdGuard Base Filter and AdGuard Tracking Filter
* Any other browser extensions you have installed: 1Password

**Comment by bro-ep** [comment]
+1

Your environment

- AdGuard for Safari version: 1.4.1
- Environment name and version: Safari 12.1.2 (14607.3.9)
- Operating System: macOS Mojave 10.14.6 (18G84)
- Filters you use in AdGuard: standard configuration
- Any other browser extensions you have installed: none

**Comment by Mizzick** [comment]
Most probably this delay caused by loading content blocker file into Safari.
Do you have less delay with less amount of enabled filters?

**Comment by ifarlow** [comment]
I only have the default filters enabled (which is either two or three, I can't recall and I'm in front of a Windows box at the moment). I can try disabling them this evening to see what happens, but I hope this is a bug that can be addressed versus expected behavior due to the filters, if what I'm saying makes sense. I don't see this behavior when I install and use other ad blocking apps that follow the new Apple extension rules.

**Comment by bro-ep** [comment]
Thanks for your reply. I have this delay even with no filters enabled.

**Comment by ifarlow** [comment]
> I disabled all filters and the delay remains.

Well, dang.

**Comment by ameshkov** [comment]
@Mizzick since we now have more content blockers, this is really important to fix this issue. Let's add some native logging to the content blocking extensions and see what they do on init.

**Comment by interpretor** [comment]
I also noticed that the upstart of Safari causes even more CPU time with the additional filters.

**Comment by ifarlow** [comment]
So the milestone has moved from 1.5 to 1.6 and the impact on start time is going to get worse before it gets better? I guess I'm out, then.

**Comment by ameshkov** [comment]
The milestone has been set to 1.6 because 1.5 is already released. v1.6 will be out rather soon, though. It will be all about bug fixes and performance optimizations.

**Comment by ifarlow** [comment]
Thanks for the update, but now the settings panel opens at launch, something it didn't do before. We seem to be going backwards.

**Comment by interpretor** [comment]
I don't have this issue here @ifarlow. The settings panel opens only when the app is startet manually, at automatic startup it will hide the panel. I'm really happy this works now.

**Comment by ameshkov** [comment]
@ifarlow could you please attach the logs from `~/Library/Logs/AdGuardSafariApp`
