### ISSUE TITLE
Initial app translations

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#21]
@timirila1 please work with @aalpatkina and prepare a shortlist of languages we will have on the initial release (I suggest English, German, and Russian at least).

Also, we need to update the oneskyapp project and upload the app screenshots there.

**Comment by ameshkov** [comment]
Here's what needs to be done (with the help of @aalpatkina):

1. Proofread the English strings
2. Upload the app screenshots to oneskyapp: https://adguard.oneskyapp.com/admin/project/dashboard/project/151092
3. Review & update the existing translations (we will start with EN, DE, RU)

**Comment by Mizzick** [comment]
we still have a lot of hardcoded string in UI

**Comment by Mizzick** [comment]
Screenshots ready.
