### ISSUE TITLE
Infinite loading during shutdown of extension 

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdGuardForSafari#213]
### Steps to reproduce

1. Install AdGuard for Safari from App Store (it reproducible only if you install from there) 
2. Open Safari 
3. Click on extension's icon ( in settings enable "show AdGuard for Safari in the menu bar").
4. Click "Stop AdGuard".

### Expected behavior
The extension's menu has changed, information that the extension is suspended is displayed. Extension's icon changed to "pause".

### Actual behavior
Infinite download icon, the extension icon does not change.
It will change only if you close extension's menu and open it again.

### Your environment

* AdGuard for Safari version: 1.4.1
* Environment name and version: Safari 12.1.2 (14607.3.9)
* Operating System: macOS Mojave 10.14.6

**Comment by Mizzick** [comment]
@SoLenny 
Please provide a screenshot, we don't really have "Stop Adguard" button.

**Comment by SoLenny** [comment]
@Mizzick I mean "Pause" button.
But now it's fixed.
