### ISSUE TITLE
Unable to whitelist a website in Safari Tech Preview

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdGuardForSafari#215]
@akmLaVx commented on [Tue Aug 13 2019](https://github.com/AdguardTeam/AdguardForMac/issues/581)

### Steps to reproduce
1. Install & start using Safari Tech Preview
2. Attempt to whitelist a website

### Expected behavior
AdGuard should whitelist a website immediately

### Actual behavior
First whitelist attempt ends in nothing. Refreshing the page and attempting to whitelist the page for the second time successfully whitelists a webbsite.

<details><summary>Screenshot:</summary>
Screen recording available in ticket 2284014
</details>

### Customer ID 
2284014

### Your environment
* Environment name and version: Safari Tech Preview 13.1r89

---

@kxlt commented on [Tue Aug 13 2019](https://github.com/AdguardTeam/AdguardForMac/issues/581#issuecomment-520976213)

Hi, I contacted support in the first place. This seems to be happening to other adblockers such as Adblock Plus as well, but again, only on Safari Technology Preview. Might be helpful knowing for you.

**Comment by Mizzick** [comment]
> AdGuard should whitelist a website immediately
This is not possible to do it immediately. And there will always be some cache delay.
