### ISSUE TITLE
Pausing Adguard for Safari has no effect

### ISSUE THREAD

**Issue by interpretor** [AdguardTeam/AdGuardForSafari#216]
### Steps to reproduce

1. Untick activate Adguard in the Toolbar
2. Browse to any site with ads

### Expected behavior

Ads should not be blocked.

### Actual behavior

Ads are still blocked.
When the filters are manually disabled in the filter tab, ads are visible again.

### Your environment

* AdGuard for Safari version: 1.4.1 (Github release)
* Environment name and version: Safari 12.1.2 (14607.3.9)
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: Default
* Any other browser extensions you have installed: -

**Comment by Mizzick** [comment]
Not reproducible on my side.
Checked both safari toolbar and macos toolbar buttons.
