### ISSUE TITLE
Question about $redirect

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#217]
Hello,
does AG for Safari support $redirect modifier or is there any plan to support it in the future?
Thanks.

### Your environment

* AdGuard for Safari version: 1.4.1
* Environment name and version: Safari 12.1.2
* Operating System: macOS Mojave 10.14.6

**Comment by ameshkov** [comment]
Nope, and unfortunately, this is not possible to implement:(

**Comment by superlex** [comment]
Oh ok, thanks anyway :/

**Comment by rodeodomino** [comment]
Since this ticket, there's been work at adding scriptlets and I see that the redirect resources are being injected in Safari. Is it now working or do only scriptlets work?

Thanks!

**Comment by ameshkov** [comment]
Unfortunately, only scriptlets can work in Safari, there's no API to intercept a web request in Safari extensions.
