### ISSUE TITLE
AdGuard doesn't notify if some of content blockers are disabled in safari preferences

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdGuardForSafari#220]
**Steps to reproduce:**

1. Install a previous beta build (1.3.1 Beta).
2. Enable all (3) content blockers in safari preference.
3. Update to last Beta (1.5.1).
4. Open AdGuard for Safari.

**Expected behavior:**

AdGuard notifies that some of content blockers are disabled.

**Actual behavior:**

AdGuard doesn't notify if some of content blockers are disabled in safari preferences.
In addition, if you enable a filter group that is turned off in the safari settings, the toggle switch will be green and there will be no warnings

**Comment by Mizzick** [comment]
@SoLenny please check it again, seems like outdated completely.
