### ISSUE TITLE
Add "content blockers" state screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#223]
Just like what we have on iOS, there should be a screen that shows the current state of the content blockers.

@AlikhanAliev plz assist

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/620207fc-90c3-4593-bc61-1f8397c254ef?sha=ad02ee8401c834269d51f9ac553c9cb81e02a061 - screens
https://share.goabstract.com/c5ac3eb2-05c2-4931-b922-8c306aa75c2e?sha=ad02ee8401c834269d51f9ac553c9cb81e02a061 - preview

**Comment by Mizzick** [comment]
https://share.goabstract.com/90eadf35-0cf5-4385-aeaa-58fddf24fa19?sha=978d5c8ed104e5cf9f0fea3baea0c82530b091f6

https://share.goabstract.com/ccebb551-7106-46e5-a27c-9233756d32d2?sha=f37833b4577f5011a99fceae2b640c8aeadae07d
