### ISSUE TITLE
An error after adding custom filter

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdGuardForSafari#225]
**Steps to reproduce:**

1. Install AdGuard for Safari Build 1.5.1
2. Add custom filter https://raw.githubusercontent.com/slavaleleka/webweb/master/customlist.txt

**Expected behavior:**

Custom filter successfully added, filtering on web-sites is working.

**Actual behavior:**

There is an error:  https://uploads.adguard.com/solenny9uyqr.png
Filtering doesn't work.

**Comment by Mizzick** [comment]
Test filter
https://mizzick.github.io/custom_filter.txt
