### ISSUE TITLE
Extension icon too dark when using a dark theme of Mac

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdGuardForSafari#230]
https://uploads.adguard.com/solennywxf8i.png

**Comment by SoLenny** [comment]
Need to fix it on Catalina OS @Mizzick 
Please take a look.

**Comment by vozersky** [comment]
![image](https://user-images.githubusercontent.com/17472907/75469935-e92e8180-59a0-11ea-9d60-b26eb0a58e13.png)

it's back in 10.15.3

**Comment by Oleg-Chashko** [comment]
**Issue Details**
• AdGuard for Safari version: 1.7.4
• Environment name and version: Safari 13.1 (15609.1.20.111.8)
• Operating System: macOS 10.15.4 (19E266)
• Filters you use in AdGuard: AdGuard Base Filter, Annoyances filter, AdGuard Deutscher Filter, AdGuard Russischer Filter.
• Any other browser extensions you have installed: Polyglot, Open in IINA, RSS Button for Safari.

**Bug**
The “AdGuard for Safari” icon on a dark theme is poorly visible, and it is unclear whether the application is running or not.

**Screenshots**
<img width="598" alt="77804063-f6fa2400-707e-11ea-8b12-8ca8738f101e" src="https://user-images.githubusercontent.com/62497891/77823464-a5dc4580-70fb-11ea-9627-f97ad14f8825.png">
