### ISSUE TITLE
Filters conversion

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#236]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1452

**Comment by Mizzick** [comment]
- [x] Scriptlets/snippets conversion (don't forget about converting #@#+js).

- [x] Convert :style uBO rules to #$#.

- [ ]  Convert ##^script:has-text to $$script[tag-containts]

- [ ] Also, assume text content for $empty: gorhill/uBlock@3e5c9e0

- [ ] Add media for mp4: gorhill/uBlock@68ae847

- [ ] all -> multiple rules ($document,popup and $csp)
