### ISSUE TITLE
Why are some phrases and translations different in English locale on Crowdin?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardForSafari#247]
1. On 13 Sep, 2019, AdGuard team approved 20 suggestions in Russian and English.
Those phrases and translations are different in English locale on Crowdin.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/LCCNu3K.png)
</details><br/>

ex:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/L7qqwkG.png)
</details><br/>

2. 250k rules -> 300k rules since you added the amounts of extensions (content blockers) from 5 to 6.
https://crowdin.com/translate/adguard-applications/17920/en-zhtw#3905700
`More than 50 popular filters and up to 250k rules`
-> `More than 50 popular filters and up to 300k rules`

**Comment by aalpatkina** [comment]
fixed on Crowdin
