### ISSUE TITLE
Add support for domain.* TLD matching

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#248]
See the details here:
https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/421

**Comment by ameshkov** [comment]
I suggest using a limited solution in this case.

When you encounter a `*.tld`, use a pre-defined array of the most popular country TLDs.

**Comment by Alex-302** [comment]
Please add `.vip` to TLD
https://github.com/AdguardTeam/AdguardFilters/issues/67699

**Comment by ameshkov** [comment]
@Alex-302 it'd be better to open a new issue for that.

I guess it makes sense to list all TLDs you might need, we can add up to 100 TLDs, easy.

**Comment by Mizzick** [comment]
Not a hundred I guess, cause it gonna affect performance. But 20-50 gonna be ok.
This is the current list:
```
        "com", "org", "ru", "net", "de", "com.br", "ir","co.uk", "pl", "it", "com.au", "fr", "info", "in", "cz", "es",
        "io", "jp", "ro", "nl", "gr", "co", "ca", "eu", "ch", "com.tw", "se", "sk", "hu", "me", "co.za", "no", "tv",
        "dk", "at", "co.jp", "edu", "be", "cn", "co.kr", "com.ar", "com.ua", "cl", "biz", "xyz", "com.mx", "fi", "us",
        "vn", "pt", "com.tr", "club", "ie", "pro", "online", "co.in", "ua", "org.uk", "cc", "az", "by", "mx", "tw",
        "co.il", "gov.in", "com.cn", "kz", "bg", "lt", "site", "su", "hr", "org.br", "gov", "com.pl", "co.nz", "si",
        "top", "ac.in", "com.hk", "com.sg", "rs", "com.co", "kr", "co.id", "pw", "uz", "com.my", "ae", "nic.in",
        "com.vn", "hk", "org.au", "tk", "lv", "live", "to", "mobi", "gov.cn", "sh"
```

**Comment by ameshkov** [comment]
I really doubt it would affect performance. Note that there are just a few dozens of rules using the TLD syntax.
