### ISSUE TITLE
Allow hiding the "Some AdGuard extensions are disabled notice"

### ISSUE THREAD

**Issue by technocoreai** [AdguardTeam/AdGuardForSafari#253]
I've enabled all AdGuard extensions except Advanced Blocking and Safari Icon, since I don't want to give the extension access to the pages I visit. However, I still see a prominent warning in the application every time I open it, with no way to hide it while keeping the privacy settings I prefer. This feels a bit pushy, and I'd like the app to recognize that I've enabled all "normal" extensions and at least downgrade the warning to a hint.

### Your environment

* AdGuard for Safari version: 1.5.4
* Environment name and version: Version 12.1.2 (14607.3.9)
* Operating System: macOS 10.14.6 (18G95)

**Comment by ameshkov** [comment]
@AlikhanAliev plz think this through.

**Comment by chapito** [comment]
Where can we get a _beginner-friendly_ explanation of allowing AdG to be "able to read pages" (as in Safari icon and advanced ext). Many thanks!

**Comment by ameshkov** [comment]
@chapito good point, we need to write one. Filed an issue about that: https://github.com/AdguardTeam/AdGuardForSafari/issues/276

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/bb32bf75-c25d-4508-b002-effc47032c5e
