### ISSUE TITLE
The Chinese language is unavailable on version 1.5.4

### ISSUE THREAD

**Issue by HolyyyCrap** [AdguardTeam/AdGuardForSafari#256]
Yeah, the Chinese language is unavailable on version 1.5.4. Could you please check and repair it?

**Comment by ameshkov** [comment]
你好, we are on it, thanks for letting us know!

**Comment by lancelot-moon** [comment]
Chinese Traditional (zh-TW) isn't correctly show in v1.5.4, too.
Only English interface.
