### ISSUE TITLE
Can I stop the settings screen to be always open?

### ISSUE THREAD

**Issue by Black-Simorgh** [AdguardTeam/AdGuardForSafari#258]
hi,
I choose the option to start the App at login and it starts how it should, but the settings window opens every time, and I have to close it first in order to browse properly. Is there any option, I didn't saw? If not can you please add this option to the App?

Besides that, I like it very much.
Thanks

<details><summary>Screenshots:</summary>

<img width="1136" alt="Screenshot 2019-09-24 13 59 24" src="https://user-images.githubusercontent.com/55745340/65509796-98879980-ded3-11e9-96ab-fb03d49a7723.png">

</details>

### Your environment

* AdGuard for Safari version: Version 1.5.4
* Environment name and version: Safari 13
* Operating System: macOS Mojave 10.14.6

**Comment by zzebrum** [comment]
@Black-Simorgh what if you enable all content-blockers in Safari settings?

**Comment by Mizzick** [comment]
Most likely enabling all extensions in Safari will help, but anyway we are going to change this a bit in the next version.

**Comment by BranchS** [comment]
This issue occurs even when all extensions are enabled in Safari. I thought it was supposed to be fixed in 1.5. It's been going on for a while and super annoying.
