### ISSUE TITLE
UI hangs after every filter change

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#259]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** AdGuard v1.5.4
- **Browser and version:** Safari
- **Operating system and version:** MacOS
- **Filters you use in AdGuard:** Base filter, Social filter, Russian

### Actual Behavior

UI hangs for a few seconds after every filter change(enable/disable), even while typing a rule in user filter.

**Comment by Mizzick** [comment]
Duplicates #233
