### ISSUE TITLE
User Filter rules applying take some time

### ISSUE THREAD

**Issue by timirila1** [AdguardTeam/AdGuardForSafari#26]
Steps

1. Open any site (e.g. example.org)
2. Open Safari Extension in toolbar
3. Select area to block on site
4. Refresh page

Expected: 
Selected area not visible

Actual:
Selected area on it's place

**Comment by timirila1** [comment]
UPD: User rules was applied, but it takes about several minutes to see changes

**Comment by zebrum** [comment]
I would say it still takes some time. (e.g. yandex.ru, meduza.io)
@Mizzick can you check it again?
