### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by TomW28** [AdguardTeam/AdGuardForSafari#262]
As I have my Mac running with dark mode on all the time, the AdGuard app is one of the few apps I use that doesn't support it, which makes it very stark when opened. Would it be possible to add support for this?

**Comment by superlex** [comment]
See https://github.com/AdguardTeam/AdGuardForSafari/issues/120

**Comment by Mizzick** [comment]
@superlex thanks!
Closing as duplicate now.
