### ISSUE TITLE
AdGuard is unresponsive when launched automatically at login

### ISSUE THREAD

**Issue by djdiaz** [AdguardTeam/AdGuardForSafari#265]
### Issue Details

* AdGuard for Safari version: 1.5.4
* Environment name and version: N/A
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: N/A
* Any other browser extensions you have installed: N/A

### Expected Behavior

On login, AdGuard should start normally.

### Actual Behavior

On logging in, AdGuard starts, but hangs and is unresponsive. It must be force quit and restarted before it will run normally.

**Comment by kimonostereo** [comment]
Having the same issue. Beachballs at launch. Force quit, the relaunch.

**Comment by Mizzick** [comment]
@SoLenny are you able to reproduce this?

**Comment by SoLenny** [comment]
@Mizzick It isn't reproducible now
@kimonostereo @djdiaz Can you guys describe the problem in more details?
or try to reproduce it again?

**Comment by akmLaVx** [comment]
Helpdesk user 2308753 is facing the same issue.

**Comment by kimonostereo** [comment]
@SoLenny Here's a better description:

Model: MacBookPro13,2 
macOS Mojave 10.14.6
AdGuard 1.5.4
Filters ON: AdBlocking, Privacy, Annoyances, Security, Language-specific

Each time I reboot, AdGuard for Safari will launch but just hang with a blank screen. I need to force quit the app and relaunch it in order for it to actually launch correctly. Once I do this, the app functions normally.

**Comment by continuity0** [comment]
I'm seeing the same thing in the recent Catalina betas, specifically 8,9, and 10. Recently, I've started getting the following error at startup, and have to force quit AdGuard and relaunch it for it to work. 

Uncaught Exception:
RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870174
    at Object.getSystemErrorName (util.js:213:11)
    at exceptionWithHostPort (internal/errors.js:458:21)
    at internalConnect (net.js:840:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:288:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:983:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:63:10)

**Comment by SoLenny** [comment]
@djdiaz @kimonostereo @continuity0 Hello, guys.

To troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Send it to apple@adguard.com 
Mention this issue number in the email text.
Specify the approximate time when this happens and  witch version do you use? From Mac AppStore or GitHub?

Also please write what extensions for safari do you use besides AdGuard?

**Comment by ameshkov** [comment]
Thanks Ben!

@Mizzick please find the logs in our ncloud

**Comment by ameshkov** [comment]
If you can find the log where it should be, please check `~/Library/Application Support` directory, it seems that in come cases it may be there.

**Comment by continuity0** [comment]
Here are the log files from AdGuard’s Application Support folder. Did you want the files that are in the Local Storage folder as well?

On Oct 11, 2019, at 5:05 AM, Andrey Meshkov <notifications@github.com<mailto:notifications@github.com>> wrote:


If you can find the log where it should be, please check ~/Library/Application Support directory, it seems that in come cases it may be there.

**Comment by bunnyhero** [comment]
i installed AdGuard for Safari from the mac app store, so i had to use spotlight to find the log files (i searched "AdGuardForSafari"). in my case it was at `/Users/bunnyhero/Library/Group Containers/{bunch of letters and numbers}.com.adguard.safari.AdGuard/Logs`

**Comment by SoLenny** [comment]
@djdiaz @kimonostereo @continuity0 @bunnyhero Hello, guys. We recently published a new beta version in which we tried to fix this bug.
Could you try it and say whether your problem has been resolved?

**Comment by kimonostereo** [comment]
Tried it this morning. Q: Is AdGuard not supposed to show that it's launched in the beta? I see it in the dock and in the menu bar after reboot, but the preference screen no longer appears. If this is intended then it seems to be working.

**Comment by continuity0** [comment]
Unfortunately, I’m still seeing the same Javascript error window at login followed by AdGuard becoming unresponsive with the new 1.6.1 beta. I haven’t tried a complete uninstall and reinstall of AdGuard yet.



On October 31, 2019 at 1:14:16 PM, kimonostereo (notifications@github.com<mailto:notifications@github.com>) wrote:

Tried it this morning. Q: Is AdGuard not supposed to show that it's launched in the beta? I see it in the dock and in the menu bar after reboot, but the preference screen no longer appears. If this is intended then it seems to be working.

**Comment by Mizzick** [comment]
@continuity0 do you use app store version?

**Comment by SoLenny** [comment]
@continuity0 Hello, can you please try clean install? It should help.

**Comment by continuity0** [comment]
I had used the app store version previously, but I’m now using the download from GitHub.

I tried a clean install last night, removed all of Adguard’s data that I could find from ~/Library and /var/folders, but I’m still seeing the javascript error at login followed by Adguard becoming unresponsive. This only seems to happen when Adguard is set to open at login, if I launch it manually later, there are no problems with it. If you need information from my Adguard installation or about the configuration of my computer, please let me know.

On Nov 1, 2019, at 5:36 AM, Lenny <notifications@github.com<mailto:notifications@github.com>> wrote:


@continuity0<https://github.com/continuity0> Hello, can you please try clean install? It should help.

**Comment by zzebrum** [comment]
@continuity0 first of all , please try the latest beta build: https://agrd.io/safari_beta

**Comment by continuity0** [comment]
Thanks for this, while I’m still seeing the error, this new version gave me more information that allowed me to track down a conflict. It looks like these newer versions of Adguard aren’t playing well with LuLu, a firewall from Objective-See that’s similar to Little Snitch. https://objective-see.com/products/lulu.html. With this information and what I’ve found previously, I wrote a quick AppleScript to launch Adguard’s login helper 8 seconds after login, which seems to be working to avoid the conflict.
