### ISSUE TITLE
Ability to block those pesky Adblocker Pop Ups on news sites, etc….. 

### ISSUE THREAD

**Issue by Freida-Moo-Goo-Gai-Pan** [AdguardTeam/AdGuardForSafari#271]
So, I came back to AdGuard since UBO no longer works on Safari.  The one thing I cannot figure out is to how to block those “we notice you are using an ad blocker….” pop ups. I know it is possible, but AdGuard doesn’t do it by default.  

UBO could do it without issue. Can this be added?   Can I just add it myself via a list?

**Comment by ameshkov** [comment]
Try adding "uBlock filters" as a custom filter list and see if it helps:
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt

**Comment by Freida-Moo-Goo-Gai-Pan** [comment]
Thank you, thank you, thank you. It was driving me crazy and this fixed it. I was looking everywhere for that.
