### ISSUE TITLE
An issue with affinity directive

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#274]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.5.4/1.6.0
* Environment name and version: Safari 13.0.1
* Operating System: macOS 10.14.6 mojave
* Filters you use in AdGuard: Base, Russian

### Actual Behavior

`Privacy` content blocker size is 3.3 MB when filters are enabled of disabled(or goroup).

Probably, it leads to problems with another content blockers.
For example:
https://github.com/AdguardTeam/AdguardFilters/issues/42000
this issue was fixed in Base filter(caused by `##.content_ads` and fixed by `disk.yandex.by,disk.yandex.com,disk.yandex.com.tr,disk.yandex.fr,disk.yandex.kz,disk.yandex.ru,disk.yandex.ua,yadi.sk#@#.content_ads`) But after filters update #42000 was not fixed on my end - element iss still hidden(no one can reproduce this issue, but me). When `Privacy` is disabled, the problem goes away.

### Additional Information

Content blocker's JSON files:
[JSON_files.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/3718811/JSON_files.zip)
Electron log:
https://gist.githubusercontent.com/Alex-302/35b34b3165ea900e0fdd6a8263e8d567/raw/f0c52474101179709ed2aea7efb95a015a184484/gistfile1.txt

* Base filter only:

<details>

```
{
        "trigger": {
            "url-filter": ".*",
            "unless-domain": [
                "*yadi.sk",
                "*disk.yandex.ua",
                "*disk.yandex.ru",
                "*disk.yandex.kz",
                "*disk.yandex.fr",
                "*disk.yandex.com.tr",
                "*disk.yandex.com",
                "*disk.yandex.by",
                "*yadi.sk",
                "*voipstunt.com",
                "*freevoipdeal.com"
            ]
        },
        "action": {
            "type": "css-display-none",
            "selector": ".content_ads"
        }
    },
```

</details>
* Base + Privacy content blocker

<details>

```
{
        "trigger": {
            "url-filter": ".*",
            "unless-domain": [
                "*yadi.sk",
                "*voipstunt.com",
                "*freevoipdeal.com"
            ]
        },
        "action": {
            "type": "css-display-none",
            "selector": ".content_ads"
        }
    },
```

</details>

More discussion in `***.com/archives/C0C3D45S7/p1570794255034300`

**Comment by Alex-302** [comment]
Another one
https://github.com/AdguardTeam/AdguardFilters/issues/42221

**Comment by superlex** [comment]
@Alex-302 @ameshkov @Mizzick 
Maybe there are issues with affinity directive again.
The rule
`@@||telefonino.net/app/plugins/blazemedia_adv/data/js/ads.js`
in AG Annoyances for Safari
`https://filters.adtidy.org/extension/safari/filters/14_optimized.txt`
doesn't work, but if you add it to your user filter list then it works.
I suppose an issue with affinity directive because the problmatic rule is 
`/js/ads. `
in AG Base while the exception is in AG Annoyances.

**Comment by Alex-302** [comment]
This directive is not used in filters at the moment. Please wait for 1.6.0

**Comment by superlex** [comment]
I'm using v 1.6.3 beta, if you prefer I can file a bug report in AdguardFilters repo.

**Comment by ameshkov** [comment]
We're waiting for Apple to finally review the v1.6 in Mac App Store.
