### ISSUE TITLE
Unable to launch Safari app due to failed malware check by Apple

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardForSafari#275]
### Issue Details

* AdGuard for Safari version: 1.5.4
* Environment name and version: Safari
* Operating System: macOS Catalina
* Filters you use in AdGuard: N/A
* Any other browser extensions you have installed: None detected

### Expected Behavior
AdGuard should be able to get launched

### Actual Behavior
AdGuard doesn't launch citing a failed antimalware scan

### Screenshots
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33634917/66720088-ede30680-ee00-11e9-9d6a-fae7a15c5563.png)

</details>

### Additional Information
Helpdesk ID: 2347168

**Comment by zzebrum** [comment]
Since AG for Safari is notarized, the user asked to check if apps from identified developers are allowed, reinstall the standalone app and run the app from Applications.

**Comment by akmLaVx** [comment]
We've received no response from the user, and there have been no similar reports over these past weeks.
