### ISSUE TITLE
Add an explanation of how and what permissions AG for Safari uses

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#276]
Safari uses some scary wording on the extensions page:
https://uploads.adguard.com/up04_xcb4r_Extensions.png

We should add a detailed and user-friendly explanation of what exactly AG Advanced Blocking and AG Safari Icon extensions do.

Brief description for now:

* `AG Safari Icon`:
    1. It needs to know what website is currently open in order to check if filtering is enabled for this website, and be able to disable or enable filtering for this website.
    2. When you choose to block an element on a webpage, it needs to be able to inject the "selector" widget into the page.
* `AG Advanced Blocking`:
    1. This extension provides advanced content blocking rules: extended CSS rules and scriptlets. In order to apply this type of rules, AdGuard injects javascript code into the page.

**Comment by BigTimeStats** [comment]
Can someone confirm that this is not able to read passwords and credit cards or do man in the middle attacks for other data?

https://www.reddit.com/r/MacOS/comments/d6isg2/updated_to_safari_13_compatible_adblocker/f1lhir2/

**Comment by SoLenny** [comment]
@BigTimeStats Your reddit link refers to the version for macOS, and this is the repository for the AgGuard for safari. MacOS repository is [here](https://github.com/AdguardTeam/AdguardForMac). 
[Here](https://adguard.com/en/privacy/mac.html) you can read about our privacy policy.
And the answer for your question, talking about the extension for safari: Our project is opensource, so you can check what we are doing. Moreover, our safari extensions do not install any certificates.
