### ISSUE TITLE
Scriptlets are not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#279]
Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/41407 (first message)

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Ad script is not blocked by AdGuard for Safari

- **AdGuard version:** 1.5.4/1.6.0
- **Browser and version:** Safari 13.0.1
- **Operating system and version:** Mojave
- **Filters you use in AdGuard:** Base filter
- **Stealth Mode settings:** no
- **Other browser extensions:** no

### Expected Behavior

Popular popup script is blocked by `#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "zfgloaded")`

### Actual Behavior

Script is not blocked. The rule above works with AdGuard extension for Chrome/FF.

Even `#%#//scriptlet("set-constant", "test", "true")` is not working - `Can't find variable: test` in console output.

**Comment by ameshkov** [comment]
@superlex we're going to get rid of the old-style JS rules in favor of scriptlets so it's important so that they were working.

**Comment by Alex-302** [comment]
@superlex no. 
`#%#alert();` works.

**Comment by superlex** [comment]
@ameshkov 
> we're going to get rid of the old-style JS rules in favor of scriptlets so it's important so that they were working.
I agree :) Btw, I was try to understand if it was only a scriplet issue or a js one too. 

Thanks @Alex-302 , I confirm.

**Comment by Mizzick** [comment]
@SoLenny pls have a look
`#%#//scriptlet("set-constant", "test", "true")`
works fine at my side

**Comment by Alex-302** [comment]
It seems it is not working not with all sites. On my devise that rule works on i.ua, but not on https://ww1.solarmovie.cr/movie/my-first-client-35976/watching

**Comment by Mizzick** [comment]
@Alex-302, then probably we shoudl move this issue to Scriptlets repo?

**Comment by Alex-302** [comment]
Not sure. This rule works in Chrome.

**Comment by Mizzick** [comment]
This is site specific. Even if the examples above work fine in Chrome extension or other products, it could not work with Safari due to different implementation under Safari restrictions.

Most probably this issue caused by scripts execution timings, which we cannot change in Safari.
