### ISSUE TITLE
Something wrong with user rules count indication

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#280]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
Hello,
there is something wrong with rules count, or I don't understand how it works.

### Steps
- disable all filters
- got to https://filters.adtidy.org/extension/safari/filters/2_optimized.txt
- copy all text and paste in user filter (about 30.000 rules + 6000 advanced rules)

### Expected Behavior
User filter rules are applied to all content blockers, but they don't exceed 50.000 rules limit

### Actual Behavior
they exceed 50.000 rules limit

**Results:**

**AdGuard General**
Il limite di 50.000 regole è stato superato. Si prega di disabilitare le regole non necessarie per il funzionamento corretto dell'applicazione.
Regole abilitate al momento: 135524 (regole disabilitate: 85524)
Abilitato: User filter

**AdGuard Privacy**
Il limite di 50.000 regole è stato superato. Si prega di disabilitare le regole non necessarie per il funzionamento corretto dell'applicazione.
Regole abilitate al momento: 135530 (regole disabilitate: 85530)
Abilitato: User filter

**AdGuard Social**
10052 regole utilizzate
Abilitato: User filter

**AdGuard Security**
10052 regole utilizzate
Abilitato: User filter

**AdGuard Altri**
10052 regole utilizzate
Abilitato: User filter

**AdGuard Custom**
10052 regole utilizzate
Abilitato: User filter

### Additional Information
* AdGuard for Safari version: 1.6 beta
* Environment name and version: Safari 13.0.2
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: none

**Comment by ameshkov** [comment]
What exactly is wrong?

**Comment by ameshkov** [comment]
Yeah, this is 100% a bug

**Comment by superlex** [comment]
Thanks @ameshkov.

In addition, if you remove all filters and you clean user filter, if you add 
https://filters.adtidy.org/extension/safari/filters/2_optimized.txt
to custom filter this is the result

**AdGuard General**
20913 regole utilizzate
Nessun filtro abilitato

**AdGuard Privacy**
20914 regole utilizzate
Nessun filtro abilitato

**AdGuard Social**
1 regola utilizzata
Nessun filtro abilitato

**AdGuard Security**
1 regola utilizzata
Nessun filtro abilitato

**AdGuard Altri**
1 regola utilizzata
Nessun filtro abilitato

**AdGuard Custom**
10053 regole utilizzate
Abilitato: AdGuard Base filter

**Comment by superlex** [comment]
@ameshkov 
Cannot reproduce anymore, maybe there was a problem with AdGuard Base list.

**Comment by Mizzick** [comment]
@superlex 
Now it's temporary fixed in Base list.
There is a bug actually, thanks a lot for this clear issue - it helped a lot.
Will be fixed with the next beta.

**Comment by superlex** [comment]
Ah ok.
You're welcome, thanks to you :)
