### ISSUE TITLE
Cosmetic css rules exceptions break other rules

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#282]
### Prerequisites

Read
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#cosmetic-css-rules-exceptions-1

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Steps to reproduce:
- Add these rules to your user filter:
```
hdmotori.it###main_container > header
hdmotori.it#@#.ads_block
hdmotori.it#$#.ads_block { width: 15px!important; height: 15px!important; }
hdmotori.it#@$#.ads_block { width: 15px!important; height: 15px!important; }

```
(the first one is only for this example)
- go to `hdmotori.it`

### Expected Behavior
- header is hidden

### Actual Behavior
- header is not hidden, all rules seem don't working

### Environment

* AdGuard for Safari version: 1.6.0 beta
* Environment name and version: Safari 13.0.2
* Operating System: Mojave 10.14.6
* Filters you use in AdGuard: Peter Lowe, EasyList, Spyware, EasyPrivacy
* Any other browser extensions you have installed: none

**Comment by Mizzick** [comment]
```
www.hdmotori.it###main_container > header
www.hdmotori.it#@#.ads_block
www.hdmotori.it#$#.ads_block { width: 15px!important; height: 15px!important; }
www.hdmotori.it#@$#.ads_block { width: 15px!important; height: 15px!important; }

example.com#$#h1 { color:red; }
example.com#@$#h1 { color:red; }
```

All good, tried example.com also.

**Comment by superlex** [comment]
@Mizzick 
I am still able to reproduce it
```
example.com##h1
example.com#$#div { max-height: 2px !important; }
example.com#@$#div { max-height: 2px !important; }
```

**Comment by Mizzick** [comment]
ahh, ok, got it
