### ISSUE TITLE
When Ad guard is running in the background it will become unresponsive indefently 

### ISSUE THREAD

**Issue by Baccount** [AdguardTeam/AdGuardForSafari#284]
### Issue Details
The app will become unresponsive while in the background and when I try to open it nothing happens, activity monitor says its unresponsive.
* AdGuard for Safari version: 1.5.4
* Environment name and version: Safari Version 13.0.3 (15608.3.10.1.3)
* Operating System: macOS 10.15.1 Beta (19B77a)
* Filters you use in AdGuard: All standard filters
* Any other browser extensions you have installed: N/A

### Expected Behavior
The app should never become unresponsive1
### Actual Behavior
While the app is running in the background it will always become responsive after a while and require a force restart of the app to get it to work

### Additional Information
I captured a spindump and a sample of the app while it was unresponsive.
[Spindump.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/3748146/Spindump.txt)
[Sample of AdGuard for Safari.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/3748147/Sample.of.AdGuard.for.Safari.txt)

**Comment by Mizzick** [comment]
Duplicate #265
