### ISSUE TITLE
$elemhide exclusion issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#285]
@Alex-302 commented on [Wed Sep 18 2019](https://github.com/AdguardTeam/AdguardForiOS/issues/1253)

### Steps to reproduce:
0. Disable all filters;
1. Go to https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/quotidien-premiere-partie-3-mai-2019.html
2. Add these rules:
```
@@||tf1.fr^$generichide
##body
```
3. Refresh page.

### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** AdGuard for iOS v3.1
- **Device model and storage size:** iPad mini
- **Operating system and version:** 12.4.1
- **Browser or App:** browser

### Expected Behavior

BODY is not hidden(page is blank);

### Actual Behavior

BODY is hidden.
The same with `$generichide`.

**Comment by ameshkov** [comment]
The easiest way to reproduce would be to disable ALL filters and just add these two rules to the user filter:
```
@@||tf1.fr^$generichide
##body
```

**Comment by Mizzick** [comment]
```
@@||example.org$generichide
##h1
```

There is something interesting with that site tf1.fr, the example above works fine, our testcases test works as well.
