### ISSUE TITLE
Upgrade Electron to v8.0

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#286]
Check out the release notes first:
https://github.com/electron/electron/releases/tag/v7.0.0

**Comment by specter78** [comment]
Considering that the latest version is 8.3, the app should skip v7 and go directly to v8.

**Comment by zecanard** [comment]
That’s if they even stick with Electron: https://github.com/AdguardTeam/AdGuardForSafari/issues/344#issuecomment-628618468.

**Comment by Sam5883** [comment]
they didnt. they updated electron to 8.3.3

**Comment by ameshkov** [comment]
> That’s if they even stick with Electron: #344 (comment).

We shouldn't ignore Electron updates even though we'd like to drop it:)
