### ISSUE TITLE
[Error] Failed to load resource -- scriptlets.js.map

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#287]
### Issue Details

On console, I read for any site
`[Error] Failed to load resource:    ---   safari-extension://**/scriptlets.js.map`
Btw, scriptlets work fine.

### Steps to reproduce
1) go to example.com
2) open console
3) read the error

### Environment
* AdGuard for Safari version: 1.6.0 beta
* Environment name and version: Safari 13.0.2
* Operating System: macOS Mojave
* Filters you use in AdGuard: AG Base, AG Spyware, EasyList Italy, all Security default filters
* Any other browser extensions you have installed: none

**Comment by sAws** [comment]
Hello! I'm getting this error in my console again.

Safari 14.0
Adguard 1.8.2

**Comment by tvinzz** [comment]
@sAws, it's fixed in [v1.8.3-beta](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.8.3-beta)
