### ISSUE TITLE
Download from Apple App Store impossible

### ISSUE THREAD

**Issue by seriousrec** [AdguardTeam/AdGuardForSafari#294]
### Issue Details

* AdGuard for Safari version: N/A
* Environment name and version: Version 13.0.3 (14608.3.10.10.1)
* Operating System: macOS Mojave 10.14.6 (18G103)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior
Download it from App Store

### Actual Behavior
Download launch but nothing append

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by superlex** [comment]
@ameshkov 
Could it be related to this
https://9to5mac.com/2019/11/04/electron-app-rejections/
?

**Comment by seriousrec** [comment]
I don’t know why.
I finale find the standalone version and it works. the version on the App Store still not downloadable .

Best regard

**Comment by ameshkov** [comment]
@SoLenny can you reproduce this on a clean MacOS machine?

Tbh, I think this is a MAS issue, not ours.

**Comment by F3000** [comment]
I have seen this last week on iOS too . After deactivating DNS I could download apps .

**Comment by zzebrum** [comment]
I faced this issue. Removing AdGuard completely didn't help last week.
I've tried to hide this purchase in account settings in AppStore and I don't know if it helps or the issue just gone by itself :)

Although it's not reproducible on clean MacOS @ameshkov

**Comment by floam** [comment]
Please just quit using Electron here - make a native controller.

**Comment by zzebrum** [comment]
@seriousrec @superlex is the problem gone?

**Comment by seriousrec** [comment]
It’s ok for now

Thanks

**Comment by superlex** [comment]
> @seriousrec @superlex is the problem gone?

Yes, it is, thank you!
