### ISSUE TITLE
Custom filters works randomly and causes problems with scrolling

### ISSUE THREAD

**Issue by PLSomebody** [AdguardTeam/AdGuardForSafari#295]
<details>
### Issue Details

* AdGuard for Safari version: 1.5.4
* Environment name and version: Safari 13.0.3 (15608.3.10.1.4)
* Operating System: macOS Catalina 10.15.1 (19B88)
* Filters you use in AdGuard:
Basic AdGuard Filter
Malware Domains
Spam404
NoCoinFilterList
Safari AdGuard
Official Polish filters for AdBlock, uBlock Origin & AdGuard

* Any other browser extensions you have installed:
1Password
DuckDuckGo Privacy
StopTheMaddness

### Expected Behavior
AdBlock should block content in repeatable way

### Actual Behavior
Content is sometimes blocked and sometimes not.
Page scrolling sometimes works and sometimes not.
Pages to show behaviour:
www.auto-swiat.pl
www.swiatksiazki.pl

### Screenshots
Not applicable
</details>

### Additional Information
Here are set of cutom rules used:

##.rodo-popup
###rodo-layer
forbes.pl##.contentInfo
##.cmp-popup_popup
targeo.pl##.banner_banner--3pjXd
##.modals-overlay
##.modal-popup, .modal-agreement, .popup-agreement, .modal-slide, ._inner-scroll, ._show

**Comment by Mizzick** [comment]
I guess this is filter rules issue @Alex-302

**Comment by Alex-302** [comment]
@PLSomebody it seems some sites blocks scrolling until popup is opened.

**Comment by zzebrum** [comment]
the issue should have been moved to another repo. Closed as obsolete, please reopen if needed.
