### ISSUE TITLE
AdGuard slows down Safari cold start

### ISSUE THREAD

**Issue by mario-grgic** [AdguardTeam/AdGuardForSafari#298]
First of all, thank you for the extension, it is wonderful and offers great level of control that is now sorely missing. 

However, I notice that AdGuard slows down Safari cold starts. Each time Safari is cold started the following 3 processes are also launched:

1. AdGuard Advanced Blocking (Safari)
2. AdGuard Safari Icon (Safari)
3. AdGuardForSafariBlockerExtension

These processes run for about 17 seconds on my 27'' iMac and if you type a site to navigate to, nothing is rendered for a long while. The above processes eventually quit and from then on browsing is faster.

Is launching these processes on Safari cold start really necessary? Is the only purpose to check for filter updates? If so, I would much rather trade this auto update functionality for manual filter update and faster Safari startup.

* AdGuard for Safari version: Version 1.5.4
* Environment name and version: 13.0.3 (15608.3.10.1.4)
* Operating System: macOS Catalina 10.15.1
* Filters you use in AdGuard: AdBlocking, Privacy, Social Widgets, Annoyances, Custom (empty).
* Any other browser extensions you have installed: none

**Comment by ameshkov** [comment]
Actually, they are launched by Safari, these are all extension processes.

* AdGuard Advanced Blocking (Safari) -- advanced blocking extension
* AdGuard Safari Icon (Safari) -- toolbar icon
* AdGuardForSafariBlockerExtension -- content blocker

> The above processes eventually quit and from then on browsing is faster.

They all three quit? Which extensions do you have enabled in Safari preferences?

**Comment by mario-grgic** [comment]
I have AdGuard Custom, AdGuard General, AdGuard Privacy and AdGuard Social enabled in the preferences.

And yes, all of the above processes do exit in about 16 seconds. Before they do pages (e.g. hotmail.com) usually don't render at all.

**Comment by ameshkov** [comment]
Hmm, so it seems the problem is with **disabled** extensions, I don't really understand why Safari launches them.

@Mizzick did we add enough logging in v1.6 to figure what's wrong?

@mario-grgic do you mind trying the v1.6 beta version?

**Comment by mario-grgic** [comment]
I don't mind trying it out. Where do I get the beta version?

**Comment by ameshkov** [comment]
Here: https://agrd.io/safari_beta

**Comment by mario-grgic** [comment]
I get exact same behavior with 1.6.2 as well.

**Comment by ameshkov** [comment]
@Mizzick do we log the process startup and arguments passed by Safari? Why does it take so long?

**Comment by mario-grgic** [comment]
Not sure what is going on, but AdGuard main UI also takes about the same time to launch. Sometimes AdGuard UI comes up as ghost outline of the window first and then much later the UI is painted fully. 

No other electron apps behave the same (I have VS Code, Slack, Skype) and they all launch relatively fast and without issues.

**Comment by ameshkov** [comment]
@mario-grgic is that easy to reproduce?

If it is, it'd help if we take a look at the logs: `~/Library/Logs/AdGuardSafariApp`

**Comment by mario-grgic** [comment]
Interestingly enough `~/Library/Logs/AdGuardSafariApp` does not exist. No AdGuard directory exists in `~/Library/Logs`

**Comment by mario-grgic** [comment]
Sorry, version 1.6.2 does create the log (I looked on machine with previous release version). Here it is: 

[log.log](https://github.com/AdguardTeam/AdGuardForSafari/files/3870130/log.log)

**Comment by mario-grgic** [comment]
This video shows the typical launch sequence: 

https://youtu.be/eeCAMsQzvys

Note that I don't always get ghosted window on launch, but the launch is pretty slow in any case.

**Comment by Mizzick** [comment]
As about this video, I want to say we have improved UI performance slightly in 1.6.x, the release version is coming very soon. I hope you have seen it already with 1.6.2 version.

With the slowdown for now we are not able to reproduce the issue, might we ask you to for some more details, such a screencast for example?

**Comment by mario-grgic** [comment]
Yes, 1.6.2 main GUI does launch a lot faster than previous version. But the behavior of extensions is the same as described in this ticket (as in they do start and exit in about 15 seconds). I'm not sure if this is related to start speed or not at all.

**Comment by ameshkov** [comment]
Unfortunately, it is not related.

Since we cannot reproduce this, we have to ask for your help in troubleshooting this. Here's what can be done:
1. Close Safari
2. Open console.app
3. Search for "Safari" there
4. Click the "Clear" button
5. Run Safari and try opening google.com
6. Ctrl+A, copy/paste the log somewhere

Try comparing it with my log when I was doing the same: https://gist.github.com/ameshkov/8c9880c00fd695b15af2ef92d349cf5b

Do you see anything suspicious in yours?

**Comment by mario-grgic** [comment]
Here is my log:

https://gist.github.com/mario-grgic/1c88cfab8286caec86b2724be90ec6a5

The only difference I see is the launching of processes and subsequent killing of them. Specifically:

default	15:28:09.901669-0500	runningboardd	Removing process: [xpcservice<com.adguard.safari.AdGuard.Extension(501)>:2725]
default	15:28:09.903081-0500	runningboardd	Removing assertions for terminated process: [xpcservice<com.adguard.safari.AdGuard.Extension(501)>:2725]
error	15:28:09.981838-0500	runningboardd	RBSStateCapture remove item called for untracked item 305-174-790 (target:xpcservice<com.adguard.safari.AdGuard.Extension(501)>)
default	15:28:13.216141-0500	runningboardd	[xpcservice<com.adguard.safari.AdGuard.AdvancedBlocking(501)>:2727] Death sentinel fired!
default	15:28:13.250550-0500	runningboardd	Invalidating assertion 305-174-791 (target:xpcservice<com.adguard.safari.AdGuard.AdvancedBlocking(501)>) from originator 174
default	15:28:13.319670-0500	runningboardd	Removing process: [xpcservice<com.adguard.safari.AdGuard.AdvancedBlocking(501)>:2727]
default	15:28:13.320533-0500	runningboardd	Removing assertions for terminated process: [xpcservice<com.adguard.safari.AdGuard.AdvancedBlocking(501)>:2727]
default	15:28:13.338165-0500	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:AdGuard Advanced Blocking (Safari), _appTrackingState = 2
error	15:28:13.362166-0500	runningboardd	RBSStateCapture remove item called for untracked item 305-174-791 (target:xpcservice<com.adguard.safari.AdGuard.AdvancedBlocking(501)>)

**Comment by ameshkov** [comment]
@Mizzick we need a log from Catalina to compare to. I don't see this `runningboardd` at all on my Mac, I guess it appeared in Cataline.

@mario-grgic just in case, is there any change if you enable all extensions?

**Comment by mario-grgic** [comment]
No change if I enable all extensions.

**Comment by Mizzick** [comment]
https://gist.github.com/Mizzick/6bb501514a1dbd580f992d6de8077beb
Ok, now we have the logs from our QA running Catalina 10.15.1 without issue being reproduced.

**Comment by ameshkov** [comment]
@Mizzick I don't see `AdvancedBlocking` extension there at all

**Comment by ameshkov** [comment]
Okay, here is some good news, I've managed to reproduce this.

The thing is that it must be really **cold** start. For instance, after rebooting the computer, or waiting for an hour after closing Safari.

Here's what's common with Mario's log on my side:
```
error	14:06:56.861736 +0300	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: com.adguard.safari.AdGuard.AdvancedBlocking, PID[2758], auid: 501, euid: 501, binary path: '/Applications/Adguard for Safari.app/Contents/PlugIns/AdvancedBlocking.appex/Contents/MacOS/AdvancedBlocking'}, REQ:{ID: com.apple.appleeventsd, PID[57], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
```

Maybe it tries to prompt something and starts waiting?

I see the same message for 1Password extension btw:
```
error	14:06:59.961928 +0300	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: com.agilebits.onepassword7.1PasswordSafariAppExtension, PID[2757], auid: 501, euid: 501, binary path: '/Applications/1Password 7.app/Contents/PlugIns/1PasswordSafariAppExtension.appex/Contents/MacOS/1PasswordSafariAppExtension'}, REQ:{ID: com.apple.appleeventsd, PID[57], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
```

**Comment by ameshkov** [comment]
This thread looks relevant:
https://forum.xojo.com/55310-how-to-add-entitlements-to-a-xojo-app-using-codesign

**Comment by ameshkov** [comment]
@mario-grgic could you please try this build and see if it helps?
https://uploads.adguard.com/up04_i04i0_AdGuard_Safari.app_4.zip

**Comment by mario-grgic** [comment]
I tried the above linked 1.6.3 and it still launches extensions as described in the issue (they all exit after about 15 seconds). See the screen recording here: 

https://youtu.be/jOL7i0ZGso0

**Comment by ameshkov** [comment]
@mario-grgic in my case I also see these processes, I guess this is just how Safari behaves. The difference is that I have no issues with loading websites after cold start.

**Comment by mario-grgic** [comment]
Interesting. In my case the site navigation is delayed by about 3 to 5 seconds (not entire duration these 3 processes run).

**Comment by ameshkov** [comment]
@mario-grgic could you please collect another log with v1.6.3 and tell me the timing? When exactly have you tried to load a website and for how long was it stuck

**Comment by mario-grgic** [comment]
It looks like not all websites are equally affected. For example with 

https://www.bbc.com/news

there is no noticeable difference with Adguard and no Adguard installed at all. With say 

https://hotmail.com/ 

which in my case redirects to my inbox, there is a noticeable delay. Not sure why any more (the site could have ad blocker detection script or something running different code path with Adguard installed).

**Comment by ameshkov** [comment]
This is weird indeed, maybe the reason is the website's scripts after all.

**Comment by mario-grgic** [comment]
I did some more testing, and indeed it is very web site specific. That coupled with the fact that the extension has no control over Safari launching it, basically means this issue can be closed.

**Comment by ameshkov** [comment]
@mario-grgic well, anyways, this bug report helped us improve a few things, thank you!
