### ISSUE TITLE
Whitelist, Pause does not work

### ISSUE THREAD

**Issue by sassomedia** [AdguardTeam/AdGuardForSafari#305]
As mentioned in https://github.com/AdguardTeam/AdGuardForSafari/issues/216, pausing AdGuard has no effect. Neither does the whitelist.

### Steps to reproduce
- Example: whitelist https://login.smbctb.co.jp/ or pause AdGuard
- Go to https://login.smbctb.co.jp/ib/portal/POSNIN1prestiatop.prst?LOCALE=en_JP

### Expected behavior
No calls originating from that top-level domain/site should be blocked, whether first nor third-party

### Actual behavior
Various calls are blocked, see devtools console:
"Content blocker prevented frame displaying https://login.smbctb.co.jp/ib/portal/POSNIN1prestiatop.prst from loading a resource from https://www.googletagmanager.com/gtm.js?id=GTM-TH7M7PH"

Only on long press on the reload button to "Reload without Content Blocker" does AdGuard actually get ignored and the page works as expected.

### Your environment
- AdGuard for Safari version: 1.5.4
- Environment name and version: Safari 13.0.4 (14608.4.9.1.4)
- Operating System: macOS Mojave 10.14.6 (18G2022)
- Filters you use in AdGuard: All except Custom
- Any other browser extensions you have installed: Dark Reader, 1Password

**Comment by SoLenny** [comment]
@sassomedia Hello, it isn't reproducible on last beta version. You can try it, by downloading [there](https://github.com/AdguardTeam/AdGuardForSafari/releases) or wait until release :)

**Comment by sassomedia** [comment]
Ok thanks, I can confirm that this is working now with the version 1.6.4. 👍
