### ISSUE TITLE
AdGuard for Safari asks to enable all extensions even though they are all enabled already

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardForSafari#307]
### Issue Details

* AdGuard for Safari version: 1.5.4
* Environment name and version: Safari 13.0.4
* Operating System: macOS Catalina 10.15.2
* Filters you use in AdGuard: N/A
* Any other browser extensions you have installed: N/A

### Expected Behavior
If AdGuard extensions are enabled, it shouldn't ask the user to enable them

### Actual Behavior
See screenshot

### Screenshots
<details><summary>Screenshot:</summary>

<img width="640" alt="Screenshot 2019-12-30 at 15 54 23" src="https://user-images.githubusercontent.com/33634917/71790608-fc287380-3039-11ea-8e7f-4df9dbbf2d4c.png">
<img width="632" alt="Screenshot 2019-12-29 at 22 15 00" src="https://user-images.githubusercontent.com/33634917/71790609-fc287380-3039-11ea-84e4-181c23604629.png">

</details>

### Additional Information
Submitted by helpdesk user 1129580.

**Comment by SoLenny** [comment]
@akmLaVx Can't reproduce it on my side. Any additional information?

**Comment by kakolisgay** [comment]
@akmLaVx Having the same issue on Catalina 10.15.1 Beta (Safari 13.0.3, Adguard 1.6.3 Beta Standalone Build) on a fresh os install. The "Adguard" extension does not appear in Extensions
![Screenshot from 2020-01-13 16-12-01](https://user-images.githubusercontent.com/16590431/72271807-7ac77700-361f-11ea-9d30-5f9051e462fb.png)

**Comment by SoLenny** [comment]
@Mizzick  Any ideas why this is happening?

**Comment by Mizzick** [comment]
@kakolisgay @akmLaVx 
`Adguard` is renamed to `Adguard General`
This could happen in some rare cases, quitting and relaunching should help.
