### ISSUE TITLE
Provide rule counts in order to better solve error: "Too many filters enabled. Safari cannot use more than 50,000 rules in one group."

### ISSUE THREAD

**Issue by nitramwin** [AdguardTeam/AdGuardForSafari#311]
### Problem Description
If the error message "Too many filters enabled. Safari cannot use more than 50,000 rules in one group" comes up, it is impossible to know in which filter 'category' to go in order to fix the issue. The only way to solve this is to do a trial and error method: 1) Turn off one rule, 2) update rules, 3) see if message comes up. If yes, 4) turn off another rule and return to step 2....

### Proposed Solution
- I propose implementing a count field next to each filter 'category' in the Filter tab. This could be marked in green text or as a progress bar that turns red if the maximum is exceeded. 
- A further step could be to implement a counter field next to each filter title in each filter 'category's' own page.  

![Screenshot 2020-01-23 at 11 15 01](https://user-images.githubusercontent.com/20186215/72976494-fe792480-3dd2-11ea-80ba-d41873926d03.png)

**Comment by SoLenny** [comment]
@nitramwin Hello. You can check the number of rules used in the content blockers tab. To open it go to "General" -> "Content blockers".
https://uploads.adguard.com/solennyc0s7t.png

**Comment by nitramwin** [comment]
@SoLenny I see this now. As such, I'd like to propose moving the information from "General" -> "Content blockers" to the "Filters" tab for increased ease of use.

**Comment by SoLenny** [comment]
@nitramwin This information is specially displayed in a separate tab so as not to clutter the tab with filters.
