### ISSUE TITLE
AdGuard blocks embedded twitter tweets

### ISSUE THREAD

**Issue by tiiiecherle** [AdguardTeam/AdGuardForSafari#312]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.6.4
* Environment name and version: 13.0.4 (15608.4.9.1.3)
* Operating System: macOS Catalina 10.1.5.2
* Filters you use in AdGuard: all that are marked as # recommended

### Expected Behavior
I don't know if this is expected behavior, but I would like to see embedded twitter tweets on the websites I visit.

### Actual Behavior
Embedded twitter tweets are not shown or shown shortened or as text only.

### Additional Information
The problem is not occurring when deactivating Safari - Preferences - Extensions - AdGuard Social.

It can easily be tested on multiple websites, e.g.
- containing multiple embedded tweets
[https://www.sport1.de/fussball/bundesliga/2020/01/bundesliga-mit-leipzig-gladbach-frankfurt-live-im-tv-stream-und-ticker](https://www.sport1.de/fussball/bundesliga/2020/01/bundesliga-mit-leipzig-gladbach-frankfurt-live-im-tv-stream-und-ticker)
- containing one embedded tweet in the middle
[https://www.nba.com/article/2020/01/24/when-nba-players-get-mentioned-rap-songs](https://www.nba.com/article/2020/01/24/when-nba-players-get-mentioned-rap-songs)

I don't know if this is intentional when the specified extension is enabled or if it is a rule issue.

If or if not a rule issue I'd like to know if the following user rules are the correct way and correct syntax to allow embedded twitter tweets specifically.

```
### unblock embedded twitter
# per domain
@@/tweets.json$domain=nba.com
@@/tweets.json$domain=sport1.de

# for all websites
@@||platform.twitter.com/widgets.js (not actually needed right now)
@@||syndication.twimg.com/tweets.json?*

# or for all websites
@@/tweets.json
```

Websites have to be reloaded or cache cleaned after applying the rules, but they are all working.

So there are three questions:

1. Is the syntax of the above rules correct (they are working) or do they have to be optimized to have the latest supported syntax and to avoid side effects (unblocking stuff that should not be unblocked)?

2. Is this a rule issue or intended behavior? 

3. Is there already a place (wiki, documentation) where these kind of working examples can be found by other users? It took me quite some time to figure them out with the help of the documentation and some google searching. But I did not find a place containing these kind of working rules with up-to-date syntax.

As it seems to concern rules feel free to move the issue to the correct place inside the Adguard GitHub development.

Thanks for looking into it. 

Kind regards.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #48693](https://github.com/AdguardTeam/AdguardFilters/issues/48693) via [**ZenHub**](https://www.zenhub.com/)
