### ISSUE TITLE
Question about $$script support

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#313]
### Issue Details

Hello,
does AG for Safari support $$script rule?
Here
https://github.com/AdguardTeam/AdGuardForSafari/commit/04350908f276d83da0d2e4de10f82fd7bb4ff8da#diff-6fe05c2822bf53d5bcdbaba6cea1cb2c
##^script:has-text is converted to $$script[tag-content
so it looks like yes..

* AdGuard for Safari version: 1.6.4
* Environment name and version: Safari 13.0.5
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: default
* Any other browser extensions you have installed: none

**Comment by ameshkov** [comment]
Hm, looks like an unnecessary copy/paste from a different place.

Unfortunately, HTML filtering is technically not possible in Safari.

**Comment by superlex** [comment]
Uhm ok, thanks.
Infact it doesn't even support $csp modifier :(

**Comment by ameshkov** [comment]
Yeah, this one cannot be implemented either at least at this point.

Meanwhile, I've just filed a feature request:
https://bugs.webkit.org/show_bug.cgi?id=207039

**Comment by superlex** [comment]
Thank you! :)
