### ISSUE TITLE
Rename 'Fanboy's Cookiemonster List' to 'EasyList Cookie List'

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#314]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Details here:
https://github.com/AdguardTeam/FiltersRegistry/pull/270

In AG for Safari v.1.6.4 it still has the old name, while in AG ext, AG for Android, etc, it has the new one.

Thanks :)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #301](https://github.com/AdguardTeam/FiltersRegistry/issues/301) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
@superlex uh, sorry.

The issue will be fixed automatically when we update the app. We sync filter lists metadata every time when we build a new release.

**Comment by superlex** [comment]
Ok, thanks!

**Comment by zecanard** [comment]
I’m still seeing the old name in AdGuard for iOS (3.1.4b254).

**Comment by ameshkov** [comment]
Uh, sorry. I'll keep this open so that we don't forget to update metadata next time

**Comment by superlex** [comment]
Btw, it's ok in AG for Safari v.1.7.4 ..

**Comment by ameshkov** [comment]
Ah, so we didn't forget after all?:)

**Comment by superlex** [comment]
@ameshkov 
This is what I see :)

<img width="554" alt="Schermata 2020-03-30 alle 14 32 13" src="https://user-images.githubusercontent.com/1375223/77912786-7a8c5e80-7293-11ea-8abc-abdbcc6cc2f7.png">

However, I don't know about AG for iOS, maybe the issue should be moved there (according to zecanard comment).

**Comment by zecanard** [comment]
Yes, my apologies. This is for AdGuard on iOS.

**Comment by ameshkov** [comment]
Filters' metadata will be updated there when the new major update is ready. Currently, we're in the process of the app review and it can take quite some time
