### ISSUE TITLE
show total blocked ad count in the AdGuard Safari Icon

### ISSUE THREAD

**Issue by kuige** [AdguardTeam/AdGuardForSafari#316]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

There is no total number of blocked ads of current page displayed on the AdGuard Safari Icon, I don't whether AdGuard is working or not.

### Proposed Solution

Show the total number of blocked ads of current page on the AdGuard Safari Icon.

**Comment by superlex** [comment]
I suppose it can't because of Safari content blocking API limitations.

**Comment by zzebrum** [comment]
yep, this can not be done.

**Comment by kuige** [comment]
pity
