### ISSUE TITLE
Adguard Reloads When Updating Filters

### ISSUE THREAD

**Issue by zecanard** [AdguardTeam/AdGuardForSafari#317]
### Issue Details

* **Version of AdGuard for Safari:**
  * 1.6.4
* **Environment name and version:**
  * 13.0.5 (15608.5.11)
* **Operating system and version:**
  * macOS 10.15.3 (19D76)
* **Filters you use in AdGuard:**
  * Adguard Base, Adguard Mobile Ads, Peter Lowe, Adguard Annoyances, Web Annoyances Ultralist, Adblock Warning Removal List, I don’t care about cookies, Fanboy’s Cookiemonster List, Malware Domains, Spam404, NoCoin, Adguard for Safari, BarbBlock, Adguard French
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior
Adguard should stay hidden in the background when closed/minimized.

### Actual Behavior
Ever since 1.6.4 landed, Adguard will randomly reopen and steal focus, even though I had previously closed it with ⌘W. The app window actually remains hidden, but the Adguard icon reappears in the Recent Apps section of my dock, with the little dot indicating that the app is now running. Even though the Adguard window remains hidden, this behavior actually causes the app to steal focus, and becomes particularly disruptive if I’m in the middle of typing something.

### Screenshots
The Adguard app reappears in the Recent Applications section of the dock with the Running indicator dot.

<details><summary>Screenshot:</summary>

</details>

### Additional Information
I believe this happens whenever Adguard updates its filters, because clicking “Check for filter updates” from the menu bar icon causes the same reload + focus-stealing behavior if updated filters were discovered and downloaded. I have my filter-update frequency set to Every hour.

**Comment by superlex** [comment]
I'm able to reproduce it.

**Comment by ameshkov** [comment]
Thank you for reporting it!

**Comment by zecanard** [comment]
This also appears to happen when Pausing/Starting ad blocking using the AdGuard icon inside Safari, or when checking/unchecking “Enabled on this website.”

Also, up until this point, whenever the app reloaded I would click the icon and close the window manually. However, I’ve just noticed that if you just leave AdGuard alone, the app will close on its own after 5–10 seconds. This would explain why I never found AdGuard open when unlocking my Mac, only while actively using it.
