### ISSUE TITLE
YouTube Advanced filter render error

### ISSUE THREAD

**Issue by sweetppro** [AdguardTeam/AdGuardForSafari#318]
AdGuard for Safari: Version 1.6.4: 
Safari Version 13.0.5 (15608.5.11)
macOS Catalina 10.15.3
Other Extensions Installed : (Cascadea)

I have a render issue, when, and only when the Advanced filter is enabled. When viewing user videos, the header renders above the first row of videos. you can see in the screen grab below:

![Screen Shot 2020-02-10 at 11 32 31 am](https://user-images.githubusercontent.com/7323792/74142627-93648600-4bf9-11ea-940e-27926cddb097.jpg)

**Comment by ameshkov** [comment]
@sweetppro what filter lists do you have enabled in AdGuard?

**Comment by sweetppro** [comment]
All of them.
Although the advanced filter is the one which cars the issue

**Comment by ameshkov** [comment]
What i mean is what filter lists do you have enabled here:
https://uploads.adguard.com/up04_yvek4_AdGuard_for_Safari_-_Settings.png

**Comment by sweetppro** [comment]
ah, here you go:
![Screen Shot 2020-02-10 at 7 38 14 pm](https://user-images.githubusercontent.com/7323792/74179169-38548280-4c3d-11ea-9e40-18fd7185db26.jpg)

**Comment by Alex-302** [comment]
@sweetppro please check without Web Annoyances Ultralist(or disable filters one by one with checking)

**Comment by sweetppro** [comment]
that was it, thanks!
