### ISSUE TITLE
Cannot login to Bing.com Account

### ISSUE THREAD

**Issue by hjstephens09** [AdguardTeam/AdGuardForSafari#319]
### Issue Details

* AdGuard for Safari version: Version 1.6.4
* Environment name and version: Safari 13.0.5 (15608.5.11)
* Operating System: macOS High Catalina 10.15.3
* Filters you use in AdGuard:
> - AdGuard Base
> 
> - AdGuard Tracking Protection
> - EasyPrivacy
> - Fanboy's Enhanced Tracking List
> 
> - AdGuard Annoyances
> - Fanboy's Annoyances
> - Web Annoyances Ultralist
> - Adblock Warning Removal
> - I don't care about cookies
> 
> - Spam404
> - NoCoin Filter
> 
> - AdGuard Safari Filter
> 
> - CrapBlock General  https://crapblock.theel0ja.info/crapblock-annoyances.txt

* Any other browser extensions you have installed:
Bitwarden

### Expected Behavior
Show login page for Bing / Microsoft account.

### Actual Behavior
Error page.

### Screenshots
https://postimg.cc/xkpkBNXn

<details><summary>Screenshot:</summary> >/details>

**Comment by hjstephens09** [comment]
I may have found the issue. Even after whitelisting `login.live.com` and `www.bing.com`, Safari was still showing an error page. I had to flush my DNS cache (macOS terminal: `sudo killall -HUP mDNSResponder`) to allow me to login to Bing with Safari.

I was able to reproduce the problem immediately after by:

1. Clearing all history (and thus website data) from Safari.
2. Removing `login.live.com` and `www.bing.com` from whitelist.
3. Quit Safari
4. Flush DNS cache.
5. Start Safari
6. Attempt to login to Bing. Can't.
7. Whitelist `login.live.com` and `www.bing.com`
8. Clear all history (and thus website data)
9. Still can't login to Bing

Therefore, a user doesn't know he needs to whitelist these two sites in order to login to Bing. After whitelisting, he will always have to clear his DNS cache.

How can we avoid this?

**Comment by zzebrum** [comment]
@hjstephens09 sorry for the late reply! Does it help if you disable all filters?

**Comment by hjstephens09** [comment]
I got it to work. Don't ask me how, though lol.

Whatever the kink was is now gone. I removed _AdGuard Safari Filter_ as I just started using AdGuard and didn't realize that filter was obsolete.
