### ISSUE TITLE
Cannot enable extension

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardForSafari#321]
* **Version of AdGuard for Safari:**
  *  1.6.4
* **Environment name and version:**
  *  13.0.5 (15608.5.11) 
* **Operating system and version:**
  *  Catalina 10.15.3 (19D76)
* **Any other browser extensions you have installed:**
  *  No

### Actual Behavior

The app freezes and the extension cannot be enabled in Safari.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/74835531-9c0e3800-532e-11ea-8140-befac8fc4033.png)

</details>

<details><summary>Logs:</summary>

>Jan 30 17:26:22 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100010.Aqua): Could not import service from caller: caller = otherbsd.457, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Jan 30 17:26:22 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100010.Aqua): Could not import service from caller: caller = otherbsd.457, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Jan 31 05:11:39 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Jan 31 05:11:39 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Jan 31 18:00:16 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Jan 31 18:00:16 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 1 08:08:46 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 1 08:08:46 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 1 13:07:44 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.324, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 1 13:07:44 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.324, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 1 13:10:01 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.adguard.safari.AdGuard.Extension[442]): Service exited due to SIGKILL | sent by launchd[1]
Feb 1 13:15:19 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 1 13:15:19 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 2 07:28:02 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.328, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 2 07:28:02 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.328, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 5 19:23:58 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.adguard.safari.AdGuard.Extension[907]): Service exited due to SIGKILL | sent by launchd[1]
Feb 5 19:23:58 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.adguard.safari.AdGuard.AdvancedBlocking[908]): Service exited due to SIGKILL | sent by launchd[1]
Feb 5 19:24:00 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.adguard.safari.AdGuard.AdvancedBlocking[909]): Service exited due to SIGKILL | sent by launchd[1]
Feb 5 19:24:00 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.adguard.safari.AdGuard.Extension[910]): Service exited due to SIGKILL | sent by launchd[1]
Feb 5 20:22:19 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.324, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 5 20:22:19 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.324, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 6 05:29:54 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 6 05:29:54 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 6 08:06:57 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.adguard.safari.AdGuard.Extension[641]): Service exited due to SIGKILL | sent by launchd[1]
Feb 6 08:06:58 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.adguard.safari.AdGuard.Extension[643]): Service exited due to SIGKILL | sent by launchd[1]
Feb 8 08:38:32 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 8 08:38:32 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 8 19:00:10 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 8 19:00:10 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 9 07:50:08 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 9 07:50:08 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 9 11:57:41 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 9 11:57:41 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.325, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 9 13:16:20 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.324, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 9 13:16:20 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.324, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 9 16:52:28 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 9 16:52:28 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 9 17:51:36 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 9 17:51:36 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.326, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled
Feb 10 05:05:54 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.329, service = com.adguard.safari.AdGuard.loginhelper, error = 119: Service is disabled
Feb 10 05:05:54 Bretts-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.329, service = com.adguard.safari.AdGuard.login-helper, error = 119: Service is disabled

</details>

### Additional Information

Users from our [forum](https://forum.adguard.com/index.php?threads/adguard-for-safari-cannot-enable-extension.37307/#post-195239) report that issue.

**Comment by choco** [comment]
I think this is an issue with the latest version of Safari. As a workaround you can start up in safe mode and you should be able to enable the extension.

**Comment by ameshkov** [comment]
@choco can you reproduce this? We weren't able to

**Comment by choco** [comment]
Yes, unfortunately I'm affected by this. It is not limited to Adguard, every extension in Safari has the same issue. There's also a post on the Apple developers forum https://forums.developer.apple.com/message/403929#403929

**Comment by zzebrum** [comment]
I've faced the issue with AdGuard assistant couple of times too

**Comment by ameshkov** [comment]
Relevant thread:
https://developer.apple.com/forums/thread/128456
