### ISSUE TITLE
Add new localizations

### ISSUE THREAD

**Issue by aalpatkina** [AdguardTeam/AdGuardForSafari#322]
Please add Croatian [hr], Thai [th], Slovak [sk], Romanian [ro], Serbian [sr-Latn] and Persian [fa] localization

**Comment by lancelot-moon** [comment]
@aalpatkina 
@ameshkov 

On 10th October, 2019, you changed these English phrases but didn't disapprove their outmoded translations.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Wn64OKf.png)
</details><br/>

Today, I just found the changes and then fixed their translations. (Delay for 5 months)
Well, update translations in v1.8.
I still wish you can disapprove outmoded translations once you change English phrases even if it's only minor changes...

**Comment by ameshkov** [comment]
@lancelot-moon we do disapprove them on really serious changes, but when the changes are cosmetic (like this case), disapproving will make us delay the release in order to wait until the translators catch up
