### ISSUE TITLE
cmd+w causes exiting instead of closing window

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#328]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
When you press cmd+w or you go to AG For Safari menu -> "close the window", AG should stay opened in background, that is, only the main window should be closed. On the contrary, it completely closes the application: the only way to close the window without exiting is to press the red circle.

### My environment

* AdGuard for Safari version: 1.6.2
* Environment name and version: Safari 13.0.5
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: default
* Any other browser extensions you have installed: none

**Comment by zzebrum** [comment]
@superlex please, update the program. In the new version the is a new confirmation dialog when closing the settings window.

**Comment by superlex** [comment]
@zebrum 
Sorry, I'm was wrong, I'm using v1.7.2.
Are you able to reproduce the issue?

**Comment by ameshkov** [comment]
Nope. Quick question -- when you were closing AdGuard window the first time, did you answer that you want to keep it in the background or exit completely?

Because the behavior depends on what you answered there

**Comment by superlex** [comment]
Mmh maybe, with a clean version I can no longer reproduce it.
Thank you!
