### ISSUE TITLE
AdGuard for Safari (Not Responding) 

### ISSUE THREAD

**Issue by jwchong** [AdguardTeam/AdGuardForSafari#331]
### Issue Details

* AdGuard for Safari version: 1.7.1
* Environment name and version: Safari 13.0.5 (15608.5.11)
* Operating System: macOS 10.15.3 (19D76)
* Filters you use in AdGuard: AdGuard Base Filter, NoCoin Filter List
* Any other browser extensions you have installed: 1Password

### Expected Behavior
AdGuard for Safari should automatically loaded properly in every reboot, without "Not Responding" status in Activity Monitor.

### Actual Behavior
Happens many times (although not every time) when reboot, AdGuard for Safari loaded automatically but it is shown as "Not Responding" in Activity Monitor.

### Screenshots
<details><summary>Screenshot:</summary>

<img width="815" alt="Screen Shot 2020-03-21 at 11 09 32 PM" src="https://user-images.githubusercontent.com/24342851/77229859-2e725780-6bcb-11ea-9ee3-4489c133a8f1.png">

</details>

**Comment by ameshkov** [comment]
@jwchong 

Could you please export logs (if that's possible) when this happens again?
AG menu icon -> "export logs and system info".

**Comment by Oleg-Chashko** [comment]
**Issue Details**
•	AdGuard for Safari version: 1.7.2
•	Environment name and version: Safari 13.0.5 (15608.5.11)
•	Operating System: macOS 10.15.3 (19D76)
•	Filters you use in AdGuard: AdGuard Base Filter, Annoyances filter, AdGuard Deutscher Filter, AdGuard Russischer Filter
•	Any other browser extensions you have installed: Polyglot, Open in iina
•	Startup Programs: OneDrive, Mail, Leaf

**Expected Behavior**
AdGuard for Safari should automatically loaded properly in every reboot, without "Not Responding" status in Activity Monitor.

**Actual Behavior**
This problem arose about four months ago.
With a manual start, about 2 out of 10 freezes.
When the system starts automatically, about 7-8 out of 10 freezes.

**Screenshots**
<img width="1037" alt="Bildschirmfoto 2020-03-22 um 09 35 41" src="https://user-images.githubusercontent.com/62497891/77246123-5d68e780-6c24-11ea-94e6-35a6bf185a20.png">

**Logs**
[adg_safari_logs_1584867211772.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/4364919/adg_safari_logs_1584867211772.zip)

**Comment by ameshkov** [comment]
@Oleg-Chashko quick question -- do you have this issue on the standalone build of AG?

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko quick question -- do you have this issue on the standalone build of AG?

Yes, the problem exists.

**Comment by ameshkov** [comment]
Hmm, got it.

The problem here is that we cannot reproduce it at all so we need your help with figuring out what's wrong.

First of all, we need a crash dump:

1. Next time the issue occurs, open the activity monitor
2. Find and select AdGuard for Safari process
3. Click "View", then select "Send Signal to Process..."
https://uploads.adguard.com/up04_f8wb7_Activity_Monitor_All_Processes_Hierarchically.png
4. Choose "Abort (SIGABRT)" from the list and send it
5. Go to `~/Library/Logs/DiagnosticReports`, you'll find the crash dump there, the file name would be something like this: `AdGuard for Safari_2020-03-22-144450_Andreys-MacBook-Pro.crash`

**Comment by Oleg-Chashko** [comment]
The problem here is that we cannot reproduce it at all so we need your help with figuring out what's wrong.
[Crash dump.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/4365175/Crash.dump.zip)

**Comment by ameshkov** [comment]
@Oleg-Chashko awesome, thank you!

Is this the standalone build or the MAS build?

**Comment by Oleg-Chashko** [comment]
> Is this the standalone build or the MAS build?

Yes. This is a standalone assembly.

AdGuard starts in the pause mode, in the process it still does not freeze. After that, I move the cursor to the AdGuard icon (but I don’t click it) and freezes in AdGuard processes. Watch the video file.
I am attaching a video file, it may help.
I am glad to help.
If you want, send or give a test AdGuard for Safari. I can test and blow you a report.
[Bildschirmvideo aufnehmen 2020-03-22 um 12.56.03.mkv.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/4365319/Bildschirmvideo.aufnehmen.2020-03-22.um.12.56.03.mkv.zip)

**Comment by vozersky** [comment]
@jwchong 
the new [beta](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.7.3-beta ) addresses the issue

**Comment by Oleg-Chashko** [comment]
I’ve been testing it for about an hour now, it does not freeze, everything is OK!

**Comment by vozersky** [comment]
@Oleg-Chashko thanks a lot for testing it, glad to hear that :)

**Comment by jwchong** [comment]
Hope you release new update soon, I do not want to test the Beta. Thanks.

**Comment by zzebrum** [comment]
@jwchong you can always switch to standalone release channel - it gets updates sooner than Appstore channel

**Comment by jwchong** [comment]
May I know what is standalone release channel? Have link?

**Comment by zzebrum** [comment]
sure, here it is: https://agrd.io/safari_release

**Comment by Oleg-Chashko** [comment]
I managed to cause it to fail (Not Responding). But crash dump, failed to do.
<img width="1316" alt="Bildschirmfoto 2020-03-27 um 11 55 22" src="https://user-images.githubusercontent.com/62497891/77750070-735f1980-7023-11ea-9995-ef8bb899ea5f.png">

**Comment by ameshkov** [comment]
@Oleg-Chashko how did you do that? It was on the latest beta, right?

**Comment by Oleg-Chashko** [comment]
Yes, this is the last beta v.1.7.3. It took about three hours to reboot. But for some reason it did not work to make a dump.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko how did you do that?

[Crash dump.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/4393390/Crash.dump.zip)

**Comment by ameshkov** [comment]
@Oleg-Chashko you've been simply restarting the app until it occurred, right?

**Comment by Oleg-Chashko** [comment]
As I tested:
1. About three hours I restarted the Mac, once AdGuard (Not Responding). I sent a screenshot, but failed to remove the dump.
2. Then, in order to facilitate the test, I restarted the application, and you see it in the dump.
After your [Fixed] result is very good, but not 100%.

**Comment by SoLenny** [comment]
@Oleg-Chashko Please, try this one https://uploads.adguard.com/AdGuard_Safari.app.zip and let us know if this helps.

**Comment by ameshkov** [comment]
@Oleg-Chashko I am pretty sure the latest beta (v1.7.4) will help with this issue, please try updating to it.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko I am pretty sure the latest beta (v1.7.4) will help with this issue, please try updating to it.

I test about 2 hours, it works stably. Tomorrow I will say the result.

**Comment by Oleg-Chashko** [comment]
On the dark theme of AdGuard, the icon is almost invisible!
<img width="598" alt="Bildschirmfoto 2020-03-27 um 21 23 41" src="https://user-images.githubusercontent.com/62497891/77797792-fc9d3d00-7071-11ea-80f1-07933ce7f491.png">

**Comment by Oleg-Chashko** [comment]
A JavaScript error occurred in the main process!
<img width="445" alt="Bildschirmfoto 2020-03-27 um 21 31 22" src="https://user-images.githubusercontent.com/62497891/77798045-72090d80-7072-11ea-91a7-af3261d15010.png">

**Comment by ameshkov** [comment]
@Oleg-Chashko how can we reproduce it?

**Comment by Oleg-Chashko** [comment]
Clicked "Beenden" to exit the application.
<img width="469" alt="Bildschirmfoto 2020-03-27 um 21 41 52" src="https://user-images.githubusercontent.com/62497891/77799129-69193b80-7074-11ea-942b-1ab4552233c7.png">

**Comment by Oleg-Chashko** [comment]
Clicked “AdGuard anhalten” to stop the AdGuard application.
<img width="298" alt="Bildschirmfoto 2020-03-27 um 22 11 11" src="https://user-images.githubusercontent.com/62497891/77801091-71737580-7078-11ea-8318-03ca70b2ec77.png">
<img width="436" alt="Bildschirmfoto 2020-03-27 um 22 09 33" src="https://user-images.githubusercontent.com/62497891/77801136-86500900-7078-11ea-90b9-8e817723972a.png">

**Comment by ameshkov** [comment]
Several times? I've tried doing that a dozen times and cannot achieve this.

**Comment by Oleg-Chashko** [comment]
> Several times? I've tried doing that a dozen times and cannot achieve this.

As I understand it, it is written on the Electron engine. It is slow and not always stable.
<img width="440" alt="Bildschirmfoto 2020-03-27 um 22 34 37" src="https://user-images.githubusercontent.com/62497891/77802725-c8c71500-707b-11ea-9cc8-345723854cfa.png">

**Comment by ameshkov** [comment]
Yeah, Electron is not ideal. Unfortunately, we used it and replacing it right now would be rather problematic.

Anyways, could you please tell me how often you are able to reproduce this? Do you repeatedly exit / stop / pause AG in order to reproduce that crash?

**Comment by Oleg-Chashko** [comment]
Anyways, could you please tell me how often you are able to reproduce this? Do you repeatedly exit / stop / pause AG in order to reproduce that crash?
Yes! I scoff at full!
But there has never been an AdGuard (Not Responding). I am pleased with this, but I will test tomorrow.

**Comment by ameshkov** [comment]
Got it, thank you! In this case, we'll push this update to MAS asap to resolve the most pressing issues. What for the crash, we'll try reproducing it on our side and file a new bug report.

**Comment by Oleg-Chashko** [comment]
On the dark theme of AdGuard, the icon is almost invisible!
<img width="598" alt="77797792-fc9d3d00-7071-11ea-80f1-07933ce7f491" src="https://user-images.githubusercontent.com/62497891/77804063-f6fa2400-707e-11ea-8b12-8ca8738f101e.png">
And thank you!
I would like to fix the icon. Sometimes it is not visible at all and it is not clear whether the application works or not.

**Comment by Oleg-Chashko** [comment]
Problems with the bug (Not Responding), no Bug!
Test:
1. Wrote a script in "Automator"
2. All night he started and turned off AdGuard for Safari.
3. 360 times per hour, for 10 hours.
4. Bug (Not Responding), no Bug!
Result: I think the topic can be closed, Thank you.

**Comment by ameshkov** [comment]
@Oleg-Chashko cool, thank you! Let me please ask, are you a professional QA engineer? :)

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko cool, thank you! Let me please ask, are you a professional QA engineer? :)

In my heart I'm a perfectionist - Professional QA Engineer :)

**Comment by jwchong** [comment]
Great to have a professional to test and speed up the process. Thanks a lot
for your time.

**Comment by ameshkov** [comment]
Thank you so much! We've published updates to the standalone channels, and the updated MAS version is on the review now.

**Comment by vulieumang** [comment]
Try to unistall by this way
https://kb.adguard.com/en/macos/installation#uninstall
it work for me
Run ’Activity Monitor’ app.
Using search tool, find the process cfprefsd.
