### ISSUE TITLE
No auto launch after reboot

### ISSUE THREAD

**Issue by kevinchan0903** [AdguardTeam/AdGuardForSafari#333]
Device:
macOS 10.15.4
AdGuard for Safari 1.7.2

I have checked "Launch AdGuard for Safari at Login". After rebooting my Macbook Air, it doesn't auto-launch. In Safari, the icon of AdGuard is a Pause sign that it indeed is not running.

**Comment by zecanard** [comment]
Same here.

**Comment by Mizzick** [comment]
Looks like a duplicate of #331
