### ISSUE TITLE
The “AdGuard for Safari” icon on a dark theme is poorly visible.

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#335]
**Issue Details**
• AdGuard for Safari version: 1.7.4
• Environment name and version: Safari 13.1 (15609.1.20.111.8)
• Operating System: macOS 10.15.4 (19E266)
• Filters you use in AdGuard: AdGuard Base Filter, Annoyances filter, AdGuard Deutscher Filter, AdGuard Russischer Filter.
• Any other browser extensions you have installed: Polyglot, Open in IINA, RSS Button for Safari.

**Bug**
The “AdGuard for Safari” icon on a dark theme is poorly visible, and it is unclear whether the application is running or not.

**Screenshots**
<img width="598" alt="77804063-f6fa2400-707e-11ea-8b12-8ca8738f101e" src="https://user-images.githubusercontent.com/62497891/77823263-0a96a080-70fa-11ea-86b7-384342684575.png">

**Comment by SoLenny** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardForSafari/issues/230
