### ISSUE TITLE
Is the "Adblock Warning Removal List" still effective?

### ISSUE THREAD

**Issue by strafe** [AdguardTeam/AdGuardForSafari#342]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.7.4
* Environment name and version: Safari 13.1 (15609.1.20.111.8)
* Operating System: macOS Catalina 10.15.4
* Filters you use in AdGuard: Defaults +  the aforementioned filter.
* Any other browser extensions you have installed: 1Password
### Expected Behavior

When visiting http://canyoublockit.com the Ad Block detected message should not appear.
### Actual Behavior

The message does appear.
### Screenshots

<details><summary>Screenshot:</summary>

<img width="640" alt="image" src="https://user-images.githubusercontent.com/15663890/79288936-f3a8ca00-7ebf-11ea-90f6-99d6c5efbc1e.png">

</details>

**Comment by ameshkov** [comment]
Well, we are not the ones who maintain that list. I can see that it's being maintained. Apparently, not too well.

**Comment by buawf** [comment]
> Well, we are not the ones who maintain that list. I can see that it's being maintained. Apparently, not too well.

 Andrey,  what is the (best) alternative of it in AdGuard or outside of AdGuard ?

**Comment by ameshkov** [comment]
`AdGuard Popups filter` for instance
