### ISSUE TITLE
Local file as blocklist

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdGuardForSafari#345]
### Problem Description
I am using iCloud to share custom block rules between iOS and Mac.
- iOS -> Export Rules and Import Rules
- Mac -> Copy and paste custom rules between the app and file

### Proposed Solution
Allow export - import option like iOS, or allow using local file as custom blocklist (and editing it directly when any rule is changed, if possible).

**Comment by ameshkov** [comment]
> or allow using local file as custom blocklist (and editing it directly when any rule is changed, if possible).

We should at least start with this

**Comment by superlex** [comment]
Hello,
see https://github.com/AdguardTeam/AdGuardForSafari/issues/16 too.
