### ISSUE TITLE
Advanced ad blocking scripts are executed even when the page is whitelisted

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#346]
_Originally posted by @einfallstoll in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/111#issuecomment-633030862_

I use Safari and have whitelisted "localhost". However, the extension still injects the script, which throws an CSP exception causing the debugger to run:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/619048/82729509-5fb8f200-9cf8-11ea-9450-231a581aa936.png">

I would expect AdGuard to *not* inject any scripts into whitelisted pages.

**Comment by einfallstoll** [comment]
The extension pop-up recognises localhost being whitelisted:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/619048/82754276-2ce02e00-9dcc-11ea-9ede-cad4f26b152d.png">

Error message from the console:
> Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

The configured website uses nonces for the `script-src` directive, therefore all unsafe inline scripts are automatically blocked. To me there are two fixes needed:

- Never inject any scripts into whitelisted pages.
- Take the Content-Security-Policy into consideration. If inline scripts are blocked, don't try to inject scripts.

**Comment by mrlife** [comment]
> Never inject any scripts into whitelisted pages.

Is there a technical/architectural limitation that allows this now?

**Comment by ameshkov** [comment]
Nope, I don't see any limitation that would stop us from implementing this properly.

**Comment by tvinzz** [comment]
as a temporary solution please try add `@@localhost$document` rule.
we'll fix it on next release.

**Comment by einfallstoll** [comment]
@tvinzz Thanks for the response, I added this to the whitelist and then tried it in my custom user rules. However, this does not work. Where am I supposed to add this?

**Comment by tvinzz** [comment]
@einfallstoll, to user rules

![image](https://user-images.githubusercontent.com/15062885/87723749-8a846b80-c7ba-11ea-9de2-aecab9c87793.png)
