### ISSUE TITLE
Issues with "prevent-setTimeout" scriptlet

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#347]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.7.4
* Environment name and version: Safari 13.1.1
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: default
* Any other browser extensions you have installed: none

Scriptlet tested:
`gorhill.github.io#%#//scriptlet("prevent-setTimeout", "removeClass")`

Test page:
`https://gorhill.github.io/uBlock/tests/scriptlet-injection-filters-1.html `

### Expected Behavior
All setTimeout should be defused, that is Results: all "not executed"

### Actual Behavior
All Results are "executed"

No problems with Firefox 77.0.1 and AG ext 3.4.31, Results: all "not executed"

Could you take a look, please?
Or let me know if I'm doing something wrong.
Thanks.

**Comment by ameshkov** [comment]
Most likely the issue is with timing

**Comment by superlex** [comment]
Thanks :)
