### ISSUE TITLE
YouTube ad before video

### ISSUE THREAD

**Issue by justinlovesmen** [AdguardTeam/AdGuardForSafari#349]
Although the ad itself doesn't play, a skippable ad that's just a white screen appears before a video if an ad was suppose to be there.

**Comment by Oleg-Chashko** [comment]
Please AdGuard Team! Remove ads from "Youtube". 
Topic discussion: https://github.com/AdguardTeam/AdguardFilters/issues/57483

**Comment by ameshkov** [comment]
@Oleg-Chashko this is quite complicated because the issue is not reproducible on our side.

It seems that Youtube has enabled some new ad format for some users. Signing out of YT helps.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko this is quite complicated because the issue is not reproducible on our side.
> 
> It seems that Youtube has enabled some new ad format for some users. Signing out of YT helps.

@ameshkov Hi,
1. **Signing out of YT helps.**  
I don’t have a Google account, I don’t enter my YouTube account. Accordingly, I can not get out of it.

2. It only helps to turn on the filter: AdGuard Annoyances filter, version 2.0.50.88, updated: 19/06/2020, 13:30:33

3. If you can transfer filter strings from the (AdGuard Annoyances filter) to the (AdGuard Base filter).

**Comment by ameshkov** [comment]
> It only helps to turn on the filter: AdGuard Annoyances filter, version 2.0.50.88, updated: 19/06/2020, 13:30:33

Ah, you're right, @Alex-302 moved the test rules to Annoyances filter yesterday to check if it helps.

We are not sure about adding them to the Base filter because there were a couple of reports that these rules can break YouTube. That's why we're collecting as much feedback as possible.
