### ISSUE TITLE
Leaving Facebook Warning When Clicking an URL

### ISSUE THREAD

**Issue by einsteinbqat** [AdguardTeam/AdGuardForSafari#350]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.7.4
* Environment name and version: Version 13.1.1 (13609.2.9.1.3)
* Operating System: macOS High Sierra 10.13.6
* Filters you use in AdGuard: 
* Any other browser extensions you have installed:
	- 1Password
	- Adguard Advanced Blocking 1.7.4
	- Adguard Custom
		- None
	- Adguard General
		- AdGuard Base filter
	- Adguard Other
		- AdGuard Annoyances filter
		- Web Annoyances Ultralist
		- Adblock Warning Removal List
		- I don't care about cookies
	- Adguard Privacy
		- AdGuard Tracking Protection filter
	- Adguard Safari Icon
	- Adguard Security
		- Malware Domains Blocklist
		- Spam404
		- NoCoin Filter List
	- Adguard Social
		- None
	- Clean Links for Google 2.0
	- Google Analytics Opt-out Browser Add-on 1.0

### Expected Behavior

Clicking on a link from your Facebook feed sends you to the page without any other user input.

### Actual Behavior

Facebook displays a warning :
"We're just checking that you want to follow a link to this website: URL"

And the user is required to click:
"Follow link" or "Go back"

### Screenshots

 Included screenshot:
<details><summary>Screenshot:</summary>

![Screen Shot 1](https://user-images.githubusercontent.com/48373997/85189078-79a70f80-b279-11ea-8137-49af4e953042.png)

</details>

### Additional Information

The culprit "Adguard Advanced Blocking 1.7.4"

If I disable/uncheck "Adguard Advanced Blocking 1.7.4" from the extension list, quit Safari, and restart Safari, clicking on any links from the Facebook timeline will direct to the proper page without having to go through the Facebook warning page.

**Comment by zzebrum** [comment]
can not reproduce on my side.

**Comment by einsteinbqat** [comment]
I can't say why, but from what I read online, this seems to be a Safari thing, and it's an extension that is the problem. In my case, it's the "Adguard Advanced Blocking 1.7.4" that I must uncheck. It's "Adguard Advanced Blocking 1.7.4" in some cases, in some other it is Avira Browser Extension.

This is where I figured out that it was an extension issue : https://www.reddit.com/r/facebook/comments/gql1dx/how_to_turn_off_leaving_facebook_message_on/

**Comment by cpgn** [comment]
Hey, I'm having the same issue! Thought it was normal Facebook behaviour. Very sad to see this as unfixed and resolved now...

**Comment by einsteinbqat** [comment]
> Hey, I'm having the same issue! Thought it was normal Facebook behaviour. Very sad to see this as unfixed and resolved now...

They say that they cannot reproduce, and this is resolved… Go figure.

I disabled "Adguard Advanced Blocking 1.7.4" from the extension list. The additional page is getting on my nerves.

**Comment by tvinzz** [comment]
@einsteinbqat, do you use new FB design or old?

**Comment by einsteinbqat** [comment]
@tvinzz The new dark theme.

**Comment by tvinzz** [comment]
[Screen Recording 2020-08-25 at 00.25.16.mov.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5120328/Screen.Recording.2020-08-25.at.00.25.16.mov.zip)
still can't reproduce.
please update AdGuard for Safari and try again.

**Comment by einsteinbqat** [comment]
> [Screen Recording 2020-08-25 at 00.25.16.mov.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5120328/Screen.Recording.2020-08-25.at.00.25.16.mov.zip)
> still can't reproduce, all extensions are enabled.
> please update AdGuard for Safari and try again.

Indeed 1.8 seems to have fixed the issue!
