### ISSUE TITLE
Adguard Safari "ghost window" (i.e. blank window with only name) in Mission Control

### ISSUE THREAD

**Issue by oakif** [AdguardTeam/AdGuardForSafari#352]
### Issue Details

* AdGuard for Safari version: 1.7.4
* Environment name and version: Version 13.1.1 (15609.2.9.1.2)
* Operating System: macOS Catalina 10.15.5
* Filters you use in AdGuard: All
* Any other browser extensions you have installed: Not relevant 

### Expected Behavior

The described window in Mission Control shouldn't be there.

### Actual Behavior

There is a ghost window in Mission Control (only appears in one space). It only has a title but doesn't contain a window. A screenshot is attached below.

### Screenshots

![image](https://user-images.githubusercontent.com/48932412/85706639-68fafd00-b6b0-11ea-946d-5db79e5ce638.png)

### Other info

AdGuard is supposed to be closed (selected "Yes" when asked whether to close Adguard).

**Comment by zzebrum** [comment]
@oakif hello! Can you describe with more detail how I can reproduce this problem?

**Comment by oakif** [comment]
Hey, thanks for the reply! Sure, I think I know how to reproduce it:

1. Open the Adguard window
2. Close it and don't allow it to run in the background
3. Open a Safari tab
4. Click on the Adguard icon and click "Run Adguard" from the icon
5. Go into Mission Control, and you should see this "ghost window"

I hope that enabled you to reproduce it!

**Comment by oakif** [comment]
Seems like this happens to Dark Reader as well, so I'm assuming it's not an Adguard-related issue.
