### ISSUE TITLE
UI performance

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdGuardForSafari#353]
UI is terribly slow when you try to interact with the switch buttons in Filters section.

### Expected Behavior

All works smoothly without any delays and jumps

### Actual Behavior

UI is slow, "laggy" and jumping to the top of the section every time you switch on any filter

**Comment by tvinzz** [comment]
it should be more responsive after electron update https://github.com/AdguardTeam/AdGuardForSafari/issues/286

**Comment by zzebrum** [comment]
Fixed
