### ISSUE TITLE
Doesn't work with Safari Technology Preview

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdGuardForSafari#354]
Making STP as default browser, AdGuard gets stuck in "Check the boxes next to AdGuard extensions in Safari preferences" window. The app doesn't open until Safari is made default browser.

(AdGuard extensions have been enabled in both Safari and STP.)

STP version: 14 (Release 109)

**Comment by OutRunner** [comment]
I have this issue as well. I've got all the extensions ticked/enabled in both regular Safari and Technology Preview but opening the AdGuard app always goes to the "Check the boxes next to AdGuard extensions in Safari preferences" screen. I'll try making regular Safari the default like specter78 mentioned.

**Comment by chimit** [comment]
Have the same problem.

**Comment by apricot23** [comment]
Same issue. Wipr extension is also broken, seems to be an issue with Technology Preview.

As mentioned Adguard works fine if I set regular Safari as the default browser

**Comment by exabrial** [comment]
Having this issue as well. The safari technology preview supports U2F keys, which is why I run it instead of normal safari. Would love to see this fixed. Thanks!

**Comment by Sam5883** [comment]
well... adg for safari is working here, macos 11.0.1 with safari tech preview 115

**Comment by elvey** [comment]
WFM. Does work with STP for me too.    WFM:  AdGuard 1.8.6 and STP 116.
    Note: I enable the 6 parts of AdGuard (out of 8) that don't require I trust the developers.  (All but "...Advanced Blocking" and "...Safari Icon" (which are 1st and 6th).  It works well without 'em.

**Comment by OutRunner** [comment]
Seems to be working for me too now. I suspect it was something that got broken in Technology Preview rather than AdGuard.

**Comment by TheHasagi** [comment]
@specter78 

Cannot reproduce with the latest STP & AdGuard for Safari (1.8.10 release). Closed for now, should be reopened if needed.
