### ISSUE TITLE
Adguard thinks some extensions are disabled

### ISSUE THREAD

**Issue by unbeatable-101** [AdguardTeam/AdGuardForSafari#356]
### Issue Details

* AdGuard for Safari version: Latest from website
* Environment name and version: Version 13.1.1 (15609.2.9.1.2)
* Operating System: 10.15.5 (19F101)
* Filters you use in AdGuard: Can’t get to setting
* Any other browser extensions you have installed: none

### Expected Behavior
It lets me open the setting because they are all on.

### Actual Behavior
It still thinks they are off.

### Screenshots
![Screen Shot 2020-07-06 at 1 19 01 PM](https://user-images.githubusercontent.com/58151048/86621418-2e387500-bf8c-11ea-9975-13b2d7efc0a1.png)
![Screen Shot 2020-07-06 at 1 19 13 PM](https://user-images.githubusercontent.com/58151048/86621425-2f69a200-bf8c-11ea-9fef-7db4bc97110a.png)

**Comment by ameshkov** [comment]
Quick question: do you have Safari Technology Preview installed?

**Comment by unbeatable-101** [comment]
No

**Comment by unbeatable-101** [comment]
Turns out I needed to move it to my applications folder, maybe perform a check at the first run of the one downloaded from the website?
