### ISSUE TITLE
Suggestion to use "Trusted sites" instead of "Whitelist"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#357]
Suggestion to use "Trusted sites" instead of "Whitelist"
On the example of Microsoft:
![Addsite-03-TrustSites_58334111bec78](https://user-images.githubusercontent.com/62497891/87944667-fc510380-ca9f-11ea-9405-27d83684c561.png)

**Comment by ameshkov** [comment]
As I recall, we've already renamed it to Allowlist.

@tvinzz ?

**Comment by tvinzz** [comment]
yes, it was renamed into Allowlist and will be available with next release.
