### ISSUE TITLE
Buttons from popup menu in Safari are not clickable and have wrong color

### ISSUE THREAD

**Issue by Sam5883** [AdguardTeam/AdGuardForSafari#358]
i'm testing new version, beta v1.8.0, everything is ok except of this little bug, hope is fixed before public release (see photo attached); select button is unrecognizable basically. and nothing happens when i click them?
![Captura de Tela 2020-08-03 às 11 35 11](https://user-images.githubusercontent.com/65408779/89194668-08e45a00-d57e-11ea-9210-54d585caa81d.png)

**Comment by tvinzz** [comment]
@Sam5883, what is your OS?
I can't reproduce it on Mojave and Catalina.
@adgkart, @zebrum do you have this issue?

the buttons have proper color and become active when you visit any website:
 
![image](https://user-images.githubusercontent.com/15062885/89231020-c013bc00-d5e4-11ea-84f0-0a6abb839ca7.png)

**Comment by Sam5883** [comment]
@tvinzz lastest catalina, 10.15.6

i also have an other mac with mojave and everything is ok, but on catalina the issue persists even after reinstalling adguard and rebooting

**Comment by zzebrum** [comment]
since we can't repro the issue, can you test this build on your side, please? 
and tell if it fixed? 

https://uploads.adguard.com/AdGuard_Safari.app_2020-08-06_19-39-22.zip

**Comment by Sam5883** [comment]
yes, that build fixed this issue, now buttons are working again and with normal color. should i close this isseu?
