### ISSUE TITLE
All menu items are not available in tray menu

### ISSUE THREAD

**Issue by Sam5883** [AdguardTeam/AdGuardForSafari#362]
after switching between dark mode and light mode, these options turns blur and i cannot select them, or close adguard, which forces me to force quit adguard and reopen. version 1.8.0
![Captura de Tela 2020-08-03 às 16 17 20](https://user-images.githubusercontent.com/65408779/89218853-24af2680-d5a5-11ea-8c19-fe62d29eadcf.png)

what it should look like:
![Captura de Tela 2020-08-03 às 16 21 14](https://user-images.githubusercontent.com/65408779/89218999-63dd7780-d5a5-11ea-8768-d7d58dd8d0df.png)

**Comment by tvinzz** [comment]
@adgkart, @zebrum can you reproduce?

**Comment by Sam5883** [comment]
@zzebrum sent one build and this issue was fixed too fwiw
