### ISSUE TITLE
Previously removed custom filters being return after update

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#363]
Version of AdGuard for Safari: 1.8 Beta
Miracles happen with Custom filter. 
Custom filter are not my filters!
Once removed, they reappear. Miracles and magic.
<img width="1221" alt="Screenshot 2020-08-03 at 21 59 27" src="https://user-images.githubusercontent.com/62497891/89222660-b8005000-d5d5-11ea-81a6-c92395674a8f.png">

**Comment by Sam5883** [comment]
yeah same here, and sometimes it disables automatically without touching them. version 1.8.0 right?

**Comment by Oleg-Chashko** [comment]
> yeah same here, and sometimes it disables automatically without touching them. version 1.8.0 right?

Yes, v.1.8.0

**Comment by Sam5883** [comment]
since they're fixing issues, i think it would be helpful putting the steps to reproduce:

1) one or more custom filters
2) add one new filter
3) previous removed filters return
