### ISSUE TITLE
AdGuard Social Media filter disables Twitter account management

### ISSUE THREAD

**Issue by LDMartin1959** [AdguardTeam/AdGuardForSafari#364]
The "AdGuard Social Media filter” in the Mac/Safari extension instead of simply "Filter[ing] for social media widgets ("Like" buttons and such)” actually disables much of Twitters functionality. It actually blocks the entire left column of Twitter which is where all the account management functions reside.

**Comment by adgkart** [comment]
Could you please make some additional steps for us?

1. Check if the issue exists in Incognito mode
2. Check if there are no rules in the Custom filter or User Rules
3. Send us detailed information about your setup:
- macOS version
- Safari version
- AdGuard for Safari version
- What AdGuard settings are enabled/disabled

**Comment by slavaleleka** [comment]
we also need two screenshots with AdGuard on and off

**Comment by LDMartin1959** [comment]
• Check if the issue exists in Incognito mode
		Yes, it is an issue in a private window
	• Check if there are no rules in the Custom filter or User Rules
		There are none
	• Send us detailed information about your setup: macOS version, Safari version, AdGuard for Safari version, What AdGuard settings are enabled/disabled
		MacOS version 10.13.6
		Safari version 13.1.2 (13609.3.5.1.5)
		AdGuard for Safari version 1.7.4
		AdGuard Settings:	Allow search ads and the self-promotion of websites (off)
						Notify about extension updates (on)
						Show AdGuard for Safari in the menu bar (on)
						Launch AdGuard for Safari at Login (on)

AdGuard Disabled:


AdGuard Enabled:
Thank you.

Leslie D. Martin

**Comment by adgkart** [comment]
It seems that screenshots were not attached. Could you please upload them here?

**Comment by LDMartin1959** [comment]
Curious. I see them as attachments to the email I sent previously. Not sure if this will make a difference, but I’ll try it again.

Thank you.

Leslie D. Martin
[ Acts 2:38 <https://www.bible.com/bible/116/act.2.38.nlt> ]

Knowledge is not Wisdom.

"A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms shall not be infringed." What part of 'shall not be infringed' do you not understand?
A gun free zone is a crime spree zone!

Vote Constitution Party <http://www.constitutionparty.com/>

**Comment by adgkart** [comment]
Unfortunately screenshots are not visible here if you send them via email. May I ask you to download them directly to the GitHub page or upload them to any external web service and provide us a link?
