### ISSUE TITLE
When you click the "About" item, "General" opens first, then only "About"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#367]
AdGuard Safari v.1.8.1 Beta

1. When you click the "About" item, "General" opens first, then only "About"
**Screen Recording:**
[Screen Recording 2020-08-10 at 20.29.22.mov.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5052732/Screen.Recording.2020-08-10.at.20.29.22.mov.zip)

2. And also when you click the "Filters", opens first "General", then only "Filters”.
**Screen Recording:**
[Screen Recording 2020-08-10 at 20.55.56.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5052847/Screen.Recording.2020-08-10.at.20.55.56.zip)

**Comment by tvinzz** [comment]
Thanks for the report, we'll take note, but this can't be fixed for the moment.
