### ISSUE TITLE
Allow compiling for local usage without the need to create accounts

### ISSUE THREAD

**Issue by zearp** [AdguardTeam/AdGuardForSafari#368]
I been trying to compile this from source to hide the dock icon on start but the requirements are kind of weird.

```
Environment requirements
- Dev account on developer.apple.com and Adguard Software Limited membership, enabled App Store Connect
- Certificates Developer ID Application: Adguard Software Limited (TC3Q7MAJXF) and Developer ID Installer: Adguard Software Limited (TC3Q7MAJXF) in keychain
```

I can't find anything on what this ```Adguard Software Limited membership``` entails or where to sign up. It seems weird to me I need some kind of account (is it free?) in order to build something from source to run on my computer locally (for my own use only).

The same applies for the other requirements. 

Maybe I missed it but is there a way to build this add-on locally without those requirements?

**Comment by ameshkov** [comment]
These are requirements for production builds.

I suppose it's possible to build a version for local use without Apple dev program membership, but it requires changing the XCode project and removing development team from there.

@tvinzz we'll need to make some changes to the build script if we change XCode projects this way:  https://github.com/AdguardTeam/AdGuardForSafari/blob/master/build.sh

@zearp this is a time-consuming task. If you have some Apple development experience, you can try doing it yourself. Open https://github.com/AdguardTeam/AdGuardForSafari/tree/master/AdGuard in XCode and change the signing settings there.

**Comment by zearp** [comment]
Thanks for the response!

Didn't realise I could just compile from Xcode, was filling the build.sh instructions. 

I've changed those team and it builds almost completely now. Except for the Electron app. I've tried to [bypass](https://www.electron.build/code-signing#how-to-disable-code-signing-during-the-build-process-on-macos) it by adding the ```-c.mac.identity=null``` to the build-electron shell script but it still didn't want to complete. Everything does compile fine, only that last shell script it fails. I've tried removing all the code signing but that didn't finish without errors. It did create the apps in the build folder but no extension showed up in Safari itself when I ran it.

It's not a big deal, was just wondering if it would be possible (for me) to compile locally after making some small modifications. I'll stick with the pre-compiled version for now. Hopefully someone else can manage to fully hide the dock icon on start up. It should be [possible](https://www.electronjs.org/docs/api/dock#dockhide-macos).

**Comment by ameshkov** [comment]
> Hopefully someone else can manage to fully hide the dock icon on start up. It should be possible.

As I recall, we actually do call this method, but it's not as reliable as it's described in the documentation.

Btw, have you tried the beta version?

**Comment by zearp** [comment]
I wasn't aware of any beta version, but I just tried 1.8.2, same issue unfortunately. The dark mode support looks sweet though!

Funnily, I have another Electron [app](https://www.elektron.se/support/?connection=overbridge#resources) made by a company called Elektron that auto starts and doesn't show a dock icon. Too bad it isn't open source so I have no idea how they did it. Too bad the docks functions aren't reliable under all circumstances.

Either way its a minor niggle, the stealing of focus is most noticeable on systems that have NVMe. Those systems start up very quickly, you're able to open the Launchpad and start other apps before macOS finishes its auto starting, that's when focus stealing is most apparent.

Thanks for your tips so far. Later today I will try to build the Electron app again, there must be a way to build that too. It pretty much compiles everything fine and then fails at the very last step when it tries to sign the Electron app.
