### ISSUE TITLE
No Longer Blocking Any Ads on YouTube

### ISSUE THREAD

**Issue by Haravikk** [AdguardTeam/AdGuardForSafari#369]
### Prerequisites

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.7.4
* Environment name and version: Safari 13.1.2
* Operating System: macOS 10.15.6
* Filters you use in AdGuard: Basic
* Any other browser extensions you have installed: 1Password

### Expected Behavior
As many YouTube ads as possible should be blocked.

### Actual Behavior
Zero YouTube ads blocked.

### Additional Information
This issue surfaced in the latest version, presumably in response to AdGuard breaking YouTube videos when YouTube tries to play a pre-video ad, however now it's not blocking anything at all.

I know the Safari Content Blocker API is restrictive, but is it not possible to at least block *some* of the ads on YouTube? I've been using ad-blocking now for so long I didn't realise just how bad it has become with constant banner ads during videos, banners at the sides etc.

Of course if the full-video ads can't be blocked without breaking the video itself, then they'll need to allowed through, but the others are super annoying as well.

Alternatively, I'd like to have an option to bring the previous behaviour back (blocking everything even if it breaks the video), as it's easy to just do View -> Reload Without Content Blockers, skip the ad, then reload with blocking enabled. Annoying to have to do it, but only a short delay for full ad-blocking.

**Comment by zzebrum** [comment]
@Haravikk it should be fixed soon from the filters side. You can also send a report using `Report this website` tool from the AdGuard icon menu in the Safari browser.
