### ISSUE TITLE
AG displays incorrect filters number enabled

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdGuardForSafari#37]
<details>

<img width="1136" alt="adguard settings 2018-10-03 14-08-31" src="https://user-images.githubusercontent.com/23637588/46406990-13c9cb80-c716-11e8-980b-15f94a1761a7.png">

</details>

<details>

<img width="983" alt="adguard settings 2018-10-03 14-09-48" src="https://user-images.githubusercontent.com/23637588/46407043-36f47b00-c716-11e8-9305-960b59ebdb84.png">

</details>

**Comment by Mizzick** [comment]
Cannot reproduce

**Comment by zebrum** [comment]
reproducible on high Sierra
