### ISSUE TITLE
Advanced Blocking 1.7.4 breaks google.com layout

### ISSUE THREAD

**Issue by r-c-k** [AdguardTeam/AdGuardForSafari#373]
[x] I am running the latest version
[ ] I checked the documentation and found no answer
[x] I checked to make sure that this issue has not already been filed

### Issue Details

AdGuard for Safari version: 1.7.4
Environment name and version: Safari 14.0 (16610.1.25.1.3)
Operating System: macOS Big Sur Dev Beta 5

### Screenshots
![Bildschirmfoto 2020-08-22 um 15 24 15](https://user-images.githubusercontent.com/17240275/90957081-f5952200-e48b-11ea-9b5d-a85f3c374572.png)

**Comment by vozersky** [comment]
This has to be a filters issue, not the app's. We will look into it, thanks!
