### ISSUE TITLE
Replace Malware Domains Blocklist with Online Malicious URL Blocklist

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#374]
See
https://github.com/AdguardTeam/FiltersRegistry/issues/364

Just updated to AGforSafari v. 1.8.2 from Mac App Store, in Security section there is still Malware Domains Blocklist. 

Thanks :)

**Comment by Alex-302** [comment]
@superlex the filter is replaced. See content https://filters.adtidy.org/extension/safari/filters/208.txt Just metadata is not updated.

**Comment by superlex** [comment]
@Alex-302 
Thanks for your answer.
I mean in AGforSafari app, in fact
https://github.com/AdguardTeam/AdGuardForSafari/blob/master/ElectronMainApp/filters/filters.json
looks like not updated (see "filterId": 208).

**Comment by vozersky** [comment]
fixed in 1.8.3 beta
