### ISSUE TITLE
Twitch pre-roll ads not being blocked

### ISSUE THREAD

**Issue by fzefasef** [AdguardTeam/AdGuardForSafari#375]
### Issue Details

* AdGuard for Safari version: 1.8.2
* Environment name and version: Safari 14.0 (16610.1.25.1.3)
* Operating System: macOS Big Sur 11.0
* Filters you use in AdGuard: Adguard Base filter
* Any other browser extensions you have installed: None

### Actual Behavior
When switching to a new streamer after watching for a while, Twitch usually plays a pre-roll ad on the new streamer's channel. These ads are not being blocked.

**Comment by zzebrum** [comment]
@fzefasef it seems that the problem can't be fixed for Safari: https://github.com/AdguardTeam/AdguardFilters/issues/61617
