### ISSUE TITLE
Crash and Bugs in macOS Big Sur 11 beta *

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#379]
AdGuard for Safari version: 1.8.2
Environment name and version: Safari 14.0 (16610.1.25.1.3)
Operating System: macOS Big Sur 11 beta 5 (20A5354i)

[AdGuardForSafariExtension_2020-08-25-193939_MacBook-Pro.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5136507/AdGuardForSafariExtension_2020-08-25-193939_MacBook-Pro.zip)

**Comment by tvinzz** [comment]
is it version 1.8.2 from Apple Store?
does it crash every time you launch AdGuard or just a single crash?

**Comment by Oleg-Chashko** [comment]
> is it version 1.8.2 from Apple Store?
> does it crash every time you launch AdGuard or just a single crash?

1. is it version 1.8.2 from Apple Store?
Not.
2. does it crash every time you launch AdGuard or just a single crash?
So far, only once.

**Comment by tvinzz** [comment]
please check 1.8.2 from Apple Store, it should work stable on macOS Big Sur

**Comment by Oleg-Chashko** [comment]
> please check 1.8.2 from Apple Store, it should work stable on macOS Big Sur

Sorry, I have no particular desire to install from the Apple Store. No offense.

**Comment by Oleg-Chashko** [comment]
[AdvancedBlocking_2020-09-01-173850_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5170698/AdvancedBlocking_2020-09-01-173850_MacBook-Pro.crash.zip)
[log.log.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5170699/log.log.zip)

**Comment by Oleg-Chashko** [comment]
macOS Big Sur 11 beta **6**
Safari v.14.0 (16610.2.2.4)

"AdGuard for Safari" started crashing after updating to "macOS Big Sur 11 beta 6".
1. After crashes, the "AdGuard for Safari" settings are lost.
[adg_safari_logs_1599222525410.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5174892/adg_safari_logs_1599222525410.zip)

2. The function "Lock element on the page" stopped working. Verified only on (https://twitter.com/rgadguard).
It seems to work and creates rules only after refreshing the page, there is no result.
<img width="1293" alt="Bildschirmfoto 2020-09-04 um 14 56 12" src="https://user-images.githubusercontent.com/62497891/92241680-ea47ea80-eebe-11ea-862b-e49ce57389d8.png">
<img width="1019" alt="Bildschirmfoto 2020-09-04 um 15 00 57" src="https://user-images.githubusercontent.com/62497891/92242020-79ed9900-eebf-11ea-93b1-5dcc6b0c800d.png">

**Comment by Oleg-Chashko** [comment]
When the "Lock element on the page" function is called, the "AdGuard for Safari" extension window does not disappear and prevents me from seeing the "Lock element on the page" windows.
<img width="1320" alt="Bildschirmfoto 2020-09-04 um 23 02 57" src="https://user-images.githubusercontent.com/62497891/92285695-3cabfa00-ef05-11ea-9769-668a953634b9.png">

**Comment by Oleg-Chashko** [comment]
When calling the settings, it froze.
**Log:**
[adg_safari_logs_1599255227075.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5177037/adg_safari_logs_1599255227075.zip)
**Screen recording:**
[Bildschirmaufnahme 2020-09-04 um 23.30.40.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5177041/Bildschirmaufnahme.2020-09-04.um.23.30.40.zip)

**Comment by Oleg-Chashko** [comment]
AdGuard for Safari "Inhaltsblocker", it froze.
Restarting the MacBook did not help.
**Log:**
[adg_safari_logs_1599256949836.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5177120/adg_safari_logs_1599256949836.zip)
**Screen recording:**
[Bildschirmaufnahme 2020-09-04 um 23.47.18.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5177123/Bildschirmaufnahme.2020-09-04.um.23.47.18.zip)

**Comment by Oleg-Chashko** [comment]
> macOS Big Sur 11 beta **6**
> Safari v.14.0 (16610.2.2.4)
> 
> "AdGuard for Safari" started crashing after updating to "macOS Big Sur 11 beta 6".
> 
> 1. After crashes, the "AdGuard for Safari" settings are lost.
>    [adg_safari_logs_1599222525410.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5174892/adg_safari_logs_1599222525410.zip)
> 2. The function "Lock element on the page" stopped working.
>    It seems to work and creates rules only after refreshing the page, there is no result.
> 
> **https://twitter.com/rgadguard**
> <img alt="Bildschirmfoto 2020-09-04 um 14 56 12" width="1293" src="https://user-images.githubusercontent.com/62497891/92241680-ea47ea80-eebe-11ea-862b-e49ce57389d8.png">
> <img alt="Bildschirmfoto 2020-09-04 um 15 00 57" width="1019" src="https://user-images.githubusercontent.com/62497891/92242020-79ed9900-eebf-11ea-93b1-5dcc6b0c800d.png">
> 
> **https://de-de.facebook.com/vodafoneDEservice/**
> <img alt="Bildschirmfoto 2020-09-04 um 15 31 29" width="1052" src="https://user-images.githubusercontent.com/62497891/92245085-1c0f8000-eec4-11ea-845b-c434e0524e3e.png">
> <img alt="Bildschirmfoto 2020-09-04 um 15 35 57" width="1021" src="https://user-images.githubusercontent.com/62497891/92245253-5f69ee80-eec4-11ea-836e-438f3615072c.png">

In the morning I turn on the MacBook, the program automatically restored the settings that it had lost after its crashes.
One gets the feeling that she remembers a lot of settings profiles. And switches between them as she wants and when she wants. The good news is that "Lock element on the page" started to work and restored the Whitelist and User Filter by itself. (You are on the verge of creating a female Artificial Intelligence :)

**Log:**
[adg_safari_logs_1599305722376.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5178003/adg_safari_logs_1599305722376.zip)

**Comment by Oleg-Chashko** [comment]
You forgot to change "Whitelist" in all languages except English!

<img width="1021" alt="Bildschirmfoto 2020-09-05 um 13 54 34" src="https://user-images.githubusercontent.com/62497891/92304659-3a3ab600-ef80-11ea-9a10-367522a3e0a0.png">

**Comment by Oleg-Chashko** [comment]
**Crash:**
[AdGuard for Safari_2020-09-05-135232_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5179670/AdGuard.for.Safari_2020-09-05-135232_MacBook-Pro.crash.zip)

**Comment by Oleg-Chashko** [comment]
**Grammar errors in the source code:**
".twosky.json"
<img width="435" alt="twosky json" src="https://user-images.githubusercontent.com/62497891/92380683-e360e800-f109-11ea-80c9-ff9a042393b2.png">

"AESharedResources.h"
<img width="546" alt="AESharedResources h" src="https://user-images.githubusercontent.com/62497891/92380765-fd9ac600-f109-11ea-876a-d05f56e7f9b9.png">

"NSException+Utils.h"
<img width="546" alt="NSException+Utils h" src="https://user-images.githubusercontent.com/62497891/92380793-08555b00-f10a-11ea-85ec-daabf029ce5a.png">

"package.json"
<img width="449" alt="package json" src="https://user-images.githubusercontent.com/62497891/92380866-228f3900-f10a-11ea-8b34-9aa5d263fe9f.png">

"README.md"
<img width="546" alt="README md" src="https://user-images.githubusercontent.com/62497891/92380895-2de26480-f10a-11ea-803f-1ca26f8ab84d.png">

"localization.py"
<img width="449" alt="localization py" src="https://user-images.githubusercontent.com/62497891/92380945-418dcb00-f10a-11ea-8fac-d380df8d1e3b.png">

"ui-event-handler.js"
<img width="546" alt="ui-event-handler js" src="https://user-images.githubusercontent.com/62497891/92380986-5702f500-f10a-11ea-8e32-747623fd5f5f.png">

"index.js"
<img width="546" alt="1 index js" src="https://user-images.githubusercontent.com/62497891/92381036-6b46f200-f10a-11ea-910c-6c5ccc4280cf.png">
<img width="546" alt="2 index js" src="https://user-images.githubusercontent.com/62497891/92381048-6f730f80-f10a-11ea-8e42-f0d71bb0a3d5.png">

**Comment by Oleg-Chashko** [comment]
[AdvancedBlocking_2020-09-13-092117_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5214156/AdvancedBlocking_2020-09-13-092117_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-09-13-125048_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5214157/AdvancedBlocking_2020-09-13-125048_MacBook-Pro.crash.zip)
[adg_safari_logs_1600004494637.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5214158/adg_safari_logs_1600004494637.zip)

**Comment by Oleg-Chashko** [comment]
There are formatting errors, parts of your code are a mixture of on the same line, tabs and spaces. Are you interested in this information? And also how much does formatting errors affect your code, depending on the language of the code?
**Example:**
<img width="648" alt="Bildschirmfoto 2020-09-18 um 11 18 29" src="https://user-images.githubusercontent.com/62497891/93581216-1ecca380-f9a1-11ea-9fc3-15a4c1a8bee2.png">
<img width="605" alt="Bildschirmfoto 2020-09-18 um 11 21 18" src="https://user-images.githubusercontent.com/62497891/93581226-22602a80-f9a1-11ea-9d58-91c33e64e648.png">

**Comment by Oleg-Chashko** [comment]
AdGuard for Safari v.1.8.3 Beta
Operating System: macOS Big Sur 11 beta 7

**Frequently freezes.**
Example:
<img width="1027" alt="Bildschirmfoto 2020-09-21 um 20 23 28" src="https://user-images.githubusercontent.com/62497891/93806326-4a71b700-fc49-11ea-8398-9f908c4102ef.png">

**Doesn't remember his place.**
Example:
<img width="309" alt="Bildschirmfoto 2020-09-21 um 20 25 04" src="https://user-images.githubusercontent.com/62497891/93806556-97558d80-fc49-11ea-9c63-274460753bd5.png">
<img width="309" alt="Bildschirmfoto 2020-09-21 um 20 25 34" src="https://user-images.githubusercontent.com/62497891/93806572-9e7c9b80-fc49-11ea-95e2-8ed06e0fe890.png">

**Comment by tvinzz** [comment]
The application freezes because of the problem with `getStateOfSafariExtensionWithIdentifier` method
https://developer.apple.com/forums/thread/662268

**Comment by Oleg-Chashko** [comment]
**Crash log:**
AdGuard for Safari v.1.8.3
Safari v.14.0.1 (16610.2.6.1.6)
macOS Big Sur v.11.0 Beta 9 (20A5384c)

[AdvancedBlocking_2020-10-02-184717_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5323059/AdvancedBlocking_2020-10-02-184717_MacBook-Pro.crash.zip)
[adg_safari_logs_1601809377911.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5323061/adg_safari_logs_1601809377911.zip)

**Comment by Oleg-Chashko** [comment]
**Removed since macOS Big Sur 11 v.11.0.1 (20B29) was released.**
