### ISSUE TITLE
AdGuard for Safari not recognizing EasyPrivacy rule

### ISSUE THREAD

**Issue by tempissue** [AdguardTeam/AdGuardForSafari#382]
This is a followup to a filters issue, which I believe may be an AdGuard for Safari issue rather than a filter issue: https://github.com/AdguardTeam/AdguardFilters/issues/62505.

In EasyPrivacy, there is a rule `/imp?*&li=` which blocks newsletter ads in Gmail. Example URL: `https://ci5.googleusercontent.com/proxy/hh8L6hWd3fPod1bXlegGDpzytaZnRM3XZYW13lJOV67siy0AFQXSbWJGzEahFK1B-IGqj-siMGEfFQtqzFFv2GH6BkIu7iBSwdpKsOGssAyaXWip-M-vPSFuH8RqPLaJlOYWlJ46LITVd3z9bGnU4CsnG_tLIBeapPPlTznQ=s0-d-e1-ft#https://liveintent.newyorktimesinfo.com/imp?s=746643&li=AH&m=79a386bf4889c6cacdd6deba5f2daf9f&p=AH_20200826`

Even when adding it as $important in user filters, AdGuard for Safari doesn't seem to recognize it.

**Comment by zzebrum** [comment]
@tempissue I'll try to repro this issue as well as @Alex-302

**Comment by Alex-302** [comment]
It seems Safari's Content Blocker API can't do anything with proxied element.

**Comment by TheHasagi** [comment]
Seems like nothing we can do with it. Closed.
