### ISSUE TITLE
"Open preferences" splash screen should never get in the way of getting to filter settings.

### ISSUE THREAD

**Issue by dmitriid** [AdguardTeam/AdGuardForSafari#383]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed (similar issue, https://github.com/AdguardTeam/AdGuardForSafari/issues/254 but reinstalling AdGuard didn't work)

### Issue Details

* AdGuard for Safari version: latest (downloaded 2020-09-03)
* Environment name and version: Safari 13.1.2 (15609.3.5.1.3)
* Operating System: macOS Catalina 10.15.6 (19G2021)
* Any other browser extensions you have installed: 1Password

### Expected Behavior

When going into the App I expect to see settings regardless of whether any/all extensions are enabled or not in Safari

### Actual Behavior

The splash screen saying "open preferences" with a non-working button appears and cannot be dismissed.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot 2020-09-03 at 14 03 50](https://user-images.githubusercontent.com/32768/92113335-738fec00-edef-11ea-847a-4f5b3570399c.png)
![Screenshot 2020-09-03 at 14 03 43](https://user-images.githubusercontent.com/32768/92113347-77bc0980-edef-11ea-91e6-414032a74ef0.png)
![Screenshot 2020-09-03 at 14 13 02](https://user-images.githubusercontent.com/32768/92113434-97533200-edef-11ea-9b7e-aa748e7fcded.png)
</details>

### Additional Information

The preferences and about pages should always be available.

**Comment by tvinzz** [comment]
@dmitriid, settings will not work properly until all relevant extensions are enabled

**Comment by dmitriid** [comment]
Which extensions are "relevant" if all extensions are enabled?

One of the comments in #254 said that the app is basically needed to just set and store the rules. So, its dependence on an unspecified number of extensions is strange ;)

**Comment by tvinzz** [comment]
@dmitriid, please update the application to the latest version v1.8.2
https://apps.apple.com/ru/app/adguard-for-safari/id1440147259

**Comment by tvinzz** [comment]
@dmitriid, do you use Safari or Safari Technology Preview browser?

**Comment by dmitriid** [comment]
I'm away from my computer atm, I'll answer as soon as I'm back!

**Comment by dmitriid** [comment]
@tvinzz This worked! Thank you.

For some reason the version from AdGuard's website didn't 🤔
