### ISSUE TITLE
"TypeError: Object has been destroyed" on AdGuard preferences

### ISSUE THREAD

**Issue by brunnopleffken** [AdguardTeam/AdGuardForSafari#386]
### Issue Details

* AdGuard for Safari version: 1.8.2
* Environment name and version: Safari Technology Preview Release 113 (Safari 14.0.1, WebKit 15610.2.3.1)
* Operating System: macOS Mojave 10.15.6
* Filters you use in AdGuard: General and Privacy only
* Any other browser extensions you have installed: IINA

### Actual Behavior
Suddenly I'm unable to open the AdGuard preferences (the gear icon). The main window freezes on the splash screen, when I try to close, it throws the exception below:

### Screenshots
![Screen Shot 2020-09-23 at 11 34 01](https://user-images.githubusercontent.com/3427344/94027289-10abc800-fd91-11ea-84eb-3d17a7378dc8.png)

**Comment by Oleg-Chashko** [comment]
**Crash and Bugs in macOS Big Sur 11 beta * #379**

<img width="299" alt="93808328-1ea40080-fc4c-11ea-81f8-284801531528" src="https://user-images.githubusercontent.com/62497891/94036262-69e11f00-fdc4-11ea-9225-9b75ce590ac1.png">

Uncaught Exception:
Error: Object has been destroyed
at /Applications/Adguard for Safari.app/Contents/Resources/app.asar/node_modules/electron-remote/lib/execute-js-func.js:223:28
at executeJavaScriptMethodObservable (/Applications/Adguard for Safari.app/Contents/Resources/app.asar/node_modules/electron-remote/lib/execute-js-func.js:420:3)
at executeJavaScriptMethod (/Applications/Adguard for Safari.app/Contents/Resources/app.asar/node_modules/electron-remote/lib/execute-js-func.js:452:10)
at /Applications/Adguard for Safari.app/Contents/Resources/app.asar/node_modules/electron-remote/lib/renderer-require.js:51:65
at Generator.next ()
at step (/Applications/Adguard for Safari.app/Contents/Resources/app.asar/node_modules/electron-remote/lib/renderer-require.js:147:191)
at /Applications/Adguard for Safari.app/Contents/Resources/app.asar/node_modules/electron-remote/lib/renderer-require.js:147:361

**Comment by brunnopleffken** [comment]
Same exception message being thrown, but the files and lines are different. I'm not sure if our issues are related or not (I need some more time to investigate the source-code).

**Comment by Oleg-Chashko** [comment]
> Same exception message being thrown, but the files and lines are different. I'm not sure if our issues are related or not (I need some more time to investigate the source-code).
@brunnopleffken 
Perhaps this is due to the fact that we are using "Safari v.14.0.1"
