### ISSUE TITLE
Freezes at spiegel.de

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#387]
@adguard-bot commented on [Sun Sep 20 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64272)

### Issue URL (Incorrect Blocking)
 [https://www.spiegel.de/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.spiegel.de%2F)
### Comment
> Bei aktiviertem AdGuard für Safari ist die Seite sehr langsam und Safari moniert einen zu hohen Speicherverbrauch, trotz 8GB RAM auf einem neuen MacBook Air 2020.
> Seite ist mit AdGuard nicht mehr benutzbar, da sich Safari freezed.
> Tritt nur bei spiegel.de auf. Andere Seiten sind nicht betroffen. Vermutlich zu hoher Speicherverbrauch (laut Infoanzeige ca. 350MB) bei einem offenen Tab.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/aAcCnsO.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/RTeLFKu.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Safari v1.8.2
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard German

---

@Alex-302 commented on [Tue Sep 22 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64272#issuecomment-696699646)

It works fine on old MacBook Air(2016). Could you please check with enabled AdGuard, but disabled filter?

---

@641985 commented on [Thu Sep 24 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64272#issuecomment-698502406)

tested with Adguard and disabled filters. Works fine without freezes. Testet als on my wife's MacBook Pro 13 2015 and with same configuration of AdGuard same freezes at spiegel.de by scrolling the page.

**Comment by tvinzz** [comment]
there are more then 50 rules in the German filter for _spiegel.de_. it can cause some freezes on scrolling.
