### ISSUE TITLE
Error is shown when moving adguard safari to applications folder

### ISSUE THREAD

**Issue by Sam5883** [AdguardTeam/AdGuardForSafari#397]
### Issue Details

* **Version of AdGuard for Safari:**
  *  1.8.4 beta
* **Environment name and version:**
  *  safari 14.0.1 (16610.2.11.51.4)
* **Operating system and version:**
  *  bug sur 11.0.1 beta 1 
* **Filters you use in AdGuard:**
  *  adg base, adg annoyances, easyprivacy
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior

success when drag and drop adg safari to applications folder
### Actual Behavior

shows error, cannot use adg for safari since its not on applications folder

### Additional Information
 cannot test beta version, i could just download via mas but there's only the release channel

**Comment by tvinzz** [comment]
@Sam5883, thank you for your report, we're fixing this problem.
Please, close the error message and check the Application folder. AdGuard for Safari should be there and ready to run.

**Comment by Sam5883** [comment]
> @Sam5883, thank you for your report, we're fixing this problem.
> Please, close the error message and check the Application folder. AdGuard for Safari should be there and ready to run.

lmao didn't even noticed that, it's actually there and it's running fine just tested, thanks.

**Comment by ameshkov** [comment]
This actually seems to be a bug of Electron. 

@tvinzz let's either report it as a new bug or add a comment to the existing issue in the Electron repo.

**Comment by tvinzz** [comment]
https://github.com/electron/electron/issues/26299
