### ISSUE TITLE
A JavaScript error occurred in the main process.

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#398]
* AdGuard for Safari version: v.1.8.4 Beta
* Environment name and version: Safari v.14.0.1 (16610.2.11.51.4)
* Operating System: v.11.0.1 Beta (20B5012d)

### Screenshots:
<img width="301" alt="Bildschirmfoto 2020-11-03 um 15 10 28" src="https://user-images.githubusercontent.com/62497891/97996358-edd8ee80-1de7-11eb-8919-21535bb6922b.png">

### Crash log:
[AdGuardForSafariExtension_2020-11-03-130441_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5481781/AdGuardForSafariExtension_2020-11-03-130441_MacBook-Pro.crash.zip)
[adg_safari_logs_1604412772809.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5481782/adg_safari_logs_1604412772809.zip)

**Comment by tvinzz** [comment]
duplicate: https://github.com/AdguardTeam/AdGuardForSafari/issues/397
