### ISSUE TITLE
Safari crashes immediate after launch on BigSur Beta

### ISSUE THREAD

**Issue by Bleistein** [AdguardTeam/AdGuardForSafari#399]
We are running the latest version 1.8.2 from MAS on 11.0.1 Beta (20B5012d) with Safari Version 14.0.1 (16610.2.11.51.4). After installation in "standard" configuration Safari crashes immediate after starting.

If our internet connection is disabled we are able to start Safari.

If we **disable** the "AdGuard Others" Safari extension we are able to start Safari with active network connection and AdGuard seems to work without problems...

**Comment by Bleistein** [comment]
[AdGuard.for.Safari_2020-09-05-135232_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5487973/AdGuard.for.Safari_2020-09-05-135232_MacBook-Pro.crash.zip)

**Comment by zzebrum** [comment]
@Bleistein sorry for the late reply! The problem should be fixed in the next version. 
The temporary solution is to install [the beta version](https://agrd.io/safari_beta).
