### ISSUE TITLE
Menu Bar Icon Does Not Remember Its Position

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#401]
AdGuard for Safari version: v.1.8.5 Beta
Safari v.14.0.1 (16610.2.11.51.7)
Operating System: v.11.0.1 Beta (20B5022a)

If I move the AdGuard icon in the macOS Menu Bar (⌘-drag), it should stay where I leave it.
After restarting, the icon moves to the left end of the list of icons.

**Example:**
<img width="309" alt="93806556-97558d80-fc49-11ea-9c63-274460753bd5" src="https://user-images.githubusercontent.com/62497891/98727561-61ef3580-2398-11eb-857a-2c97688b5c9c.png">
<img width="309" alt="93806572-9e7c9b80-fc49-11ea-95e2-8ed06e0fe890" src="https://user-images.githubusercontent.com/62497891/98727566-64518f80-2398-11eb-8a5e-0c768e9cbff9.png">

**Comment by tvinzz** [comment]
https://www.electronjs.org/docs/api/tray#new-trayimage-guid
windows only
