### ISSUE TITLE
Rule doesn't work in 1.8.5

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardForSafari#404]
The rule `kitguru.net##a[id^="href-ad-"]` doesn't work here https://www.kitguru.net/reviews/ in 1.8.5, but it works in 1.8.2. (and it worked in 1.8.4 according to reporter)

MacOS 10.15.7 (19H2) Catalina
Safari 14.0 (15610.1.28.1.9, 15610)

The original issue in filters: https://github.com/AdguardTeam/AdguardFilters/issues/67403

P.S. It works from user rules in 1.8.5

**Comment by Sergey-Lyapin** [comment]
Same problem [here](https://www.dailymail.co.uk/news/article-8949423/Fire-kills-ten-Covid-19-ward-Deadly-hospital-blaze-breaks-intensive-care-unit-Romania.html)
for example with this rule:
`dailymail.co.uk##.mol-img > noscript+div[class^="container-"]`

**Comment by zecanard** [comment]
I also had to remove
`||*^$ping`
starting with 1.8.3 beta, if I remember correctly. It causes all webpages to be blocked, both from Custom Filters and User Rules. This also affects AdGuard for iOS in TestFlight.

**Comment by ameshkov** [comment]
Rules with `$ping` need to be ignored, Safari Content blocking API does not support anything like that.

Supported content types: document, image, style-sheet, script, font, raw (Any untyped load), svg-document, media, popup

**Comment by ameshkov** [comment]
Please check it in v1.8.6 beta

**Comment by Oleg-Chashko** [comment]
> Please check it in v1.8.6 beta
Thank you very much, now everything is ok.
