### ISSUE TITLE
Font bug in  "Block element on page"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#405]
AdGuard for Safari version: v.1.8.5 Beta
Safari v.14.0.1 (16610.2.11.51.7)
Operating System: v.11.0.1 Beta (20B5022a)

**The word "Maximum" does not fit on the line.**
**Screenshots:**
<img width="668" alt="Снимок экрана 2020-11-12 в 14 28 53" src="https://user-images.githubusercontent.com/62497891/98946382-1ea9d980-24f4-11eb-8544-7adb1efc7ad2.png">

---------------------------------------------------------------------------------------------------------------------------
These are examples of sites where there is a problem:
opennet.ru, samlab.ws, forum.ru-board.com
**Possibly a problem with other languages!**

**Screenshots:**
_German language MacOS_
<img width="1150" alt="Bildschirmfoto 2020-11-12 um 13 53 12" src="https://user-images.githubusercontent.com/62497891/98944425-4f3c4400-24f1-11eb-81bd-5ba5a38df6cd.png">

_Russian language MacOS_
<img width="1150" alt="Снимок экрана 2020-11-12 в 14 08 30" src="https://user-images.githubusercontent.com/62497891/98944555-81e63c80-24f1-11eb-90b2-8a4b6e238ee0.png">

**Comment by vozersky** [comment]
@tvinzz fix in old Assistant lib please

**Comment by vozersky** [comment]
@tvinzz can we just NOT translate in at all? MIN and MAX fits in perfectly.

**Comment by tvinzz** [comment]
> @tvinzz can we just NOT translate in at all? MIN and MAX fits in perfectly.

yes, done

**Comment by maximtop** [comment]
Issue moved to [AdguardTeam/AdguardAssistant #343](https://github.com/AdguardTeam/AdguardAssistant/issues/343) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Oleg-Chashko** [comment]
**The problem is not solved!**
<img width="666" alt="Bildschirmfoto 2020-11-25 um 20 21 15" src="https://user-images.githubusercontent.com/62497891/100273253-c5629100-2f5c-11eb-824c-3cba579962c6.png">
<img width="701" alt="Bildschirmfoto 2020-11-25 um 20 23 35" src="https://user-images.githubusercontent.com/62497891/100273267-c98eae80-2f5c-11eb-995b-1948b037d56b.png">

**Comment by ameshkov** [comment]
This is a new one.

Question: do you see it on every website or just one some of them?

**Comment by Oleg-Chashko** [comment]
> This is a new one.
> 
> Question: do you see it on every website or just on some of them?

<img width="719" alt="Bildschirmfoto 2020-11-25 um 20 41 18" src="https://user-images.githubusercontent.com/62497891/100274397-a402a480-2f5e-11eb-8d5d-976eb8f681a0.png">

**Comment by ameshkov** [comment]
Got it. The problem is with the webites that use CP1251 encoding.

This should be filed as a new bug.

**Comment by Oleg-Chashko** [comment]
> Got it. The problem is with the webites that use CP1251 encoding.
> 
> This should be filed as a new bug.
@ameshkov 
This topic was opened because of this problem! Look from the beginning of the topic!
