### ISSUE TITLE
Compilation error message on AdGuard for Safari

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#418]
@FaresKi commented on [Sun Nov 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/67634)

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Compilation error message on AdGuard for Safari***:
* **Not blocking everything it's supposed to**: 

Installed AdGuard for Safari, and went to see "content blockers", and noticed that "AdGuard General" was displaying a red error "Compilation error/failure")

<details><summary>Screenshot: <img width="1136" alt="image" src="https://user-images.githubusercontent.com/46092308/99158389-81f16280-26d2-11eb-977f-6858fc9462c3.png"> </summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

I suppose it's expected to be green. 

<details><summary>Screenshot: I don't have a "expected behavior" screenshot</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

1. Install AdGuard for Safari on App Store
2. Enable all features.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | MacOS 
Operating system version (Android/iOS) | Big Sur 11.0
Browser:                               | Safari
AdGuard version:                       | 1.8.5
Filters enabled:                       |  General, Advanced Blocking, Custom, Privacy, Security, Social, Others
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[Settings if helpful](https://gist.github.com/FaresKi/db550ba8810983b04106aa752e5e13cc)

**Comment by Mizzick** [comment]
@FaresKi Please check your user filter rules, there is something wrong probably.
Something there caused the compilation error, we are interested aswell.

**Comment by JakoDel** [comment]
> @FaresKi Please check your user filter rules, there is something wrong probably.
> Something there caused the compilation error, we are interested aswell.
This is also happening to me with Safari 14 on 10.15.7

**Comment by ameshkov** [comment]
@JakoDel what filter lists do you have enabled?

Do you have any rules in the user filter?

**Comment by JakoDel** [comment]
> @JakoDel what filter lists do you have enabled?
> 
> Do you have any rules in the user filter?

![Schermata 2020-11-17 alle 16 04 08](https://user-images.githubusercontent.com/40212961/99406806-a32e9a80-28ee-11eb-88ac-a34dca3363a0.png)

**Comment by ameshkov** [comment]
@JakoDel could you please export settings and attach here?

**Comment by JakoDel** [comment]
> @JakoDel could you please export settings and attach here?


[adguard-settings-20201017_16810.json.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5554306/adguard-settings-20201017_16810.json.zip)

**Comment by Mizzick** [comment]
@JakoDel 
We still cannot reproduce it, might we ask for `.json` files in 
`~/Library⁩/Group\ Containers/TC3Q7MAJXF.com.adguard.safari.AdGuard⁩/`?

**Comment by JakoDel** [comment]
> @JakoDel
> We still cannot reproduce it, might we ask for `.json` files in
> `~/Library⁩/Group\ Containers/TC3Q7MAJXF.com.adguard.safari.AdGuard⁩/`?
[jsonfiles.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5554577/jsonfiles.zip)

**Comment by ameshkov** [comment]
@JakoDel we're close to figuring it out, thank you for the JSON files. Hopefully, tomorrow we'll publish a hotfix, but it may take Apple some time to review it.

@Mizzick once we have a build with a fix, please post it here so that people could try it.

**Comment by TheHasagi** [comment]
@FaresKi @JakoDel 

Dears, probably we fixed the issue with a compilation error. Please, try this build from the [link](https://uploads.adguard.com/myMoonawilz.zip) and left a reply if it helps.

**Comment by FaresKi** [comment]
> @FaresKi @JakoDel
> 
> Dears, probably we fixed the issue with a compilation error. Please, try this build from the [link](https://uploads.adguard.com/myMoonawilz.zip) and left a reply if it helps.

Tried the new version, same error.

**Comment by FaresKi** [comment]
> @JakoDel we're close to figuring it out, thank you for the JSON files. Hopefully, tomorrow we'll publish a hotfix, but it may take Apple some time to review it.
> 
> @Mizzick once we have a build with a fix, please post it here so that people could try it.

I FOUND OUT. I disabled the specific language filter and it seemed to fix the issue.

**Comment by ameshkov** [comment]
@FaresKi 

1. Which one was the issue?
2. Could you please enable it back (temporary) so that the issue was reproduced and get us the JSON files from `~/Library⁩/Group\ Containers/TC3Q7MAJXF.com.adguard.safari.AdGuard⁩/` ?

**Comment by JakoDel** [comment]
I think I found a fix. I unchecked the ads filter and language-specific in the filters tab and checked them again. I now have every filter working

**Comment by JakoDel** [comment]
Oh wow he found it too lol

**Comment by FaresKi** [comment]
> Oh wow he found it too lol

sorry, I was faster

**Comment by ameshkov** [comment]
Ah, the thing is that unchecking/checking a filter triggers re-building the content blocker.

**Comment by JakoDel** [comment]
> > Oh wow he found it too lol
> 
> sorry, I was faster

Actually, I fixed it like 3 hrs ago :)))))
Jokes aside, here are the json files @ameshkov 
[jsonfiles2.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5556685/jsonfiles2.zip)

**Comment by FaresKi** [comment]
> @FaresKi
> 
> 1. Which one was the issue?
> 2. Could you please enable it back (temporary) so that the issue was reproduced and get us the JSON files from `~/Library⁩/Group\ Containers/TC3Q7MAJXF.com.adguard.safari.AdGuard⁩/` ?

1. Seems the language filter is creating compilation errors.
_Edit : never mind - I enabled it again and it seemed to not crash. _

**Comment by ameshkov** [comment]
@Mizzick let's prepare a hotfix
