### ISSUE TITLE
Safari extension doesn't block ads anymore

### ISSUE THREAD

**Issue by cqst** [AdguardTeam/AdGuardForSafari#429]
Hello

I just noticed today that AdGuard Safari extension isn't blocking ads anymore...worked fine until now.

Versions

AdGuard 1.8.6
Safari 14.0.1
MacOS 10.15.7

AdGuard is launched and running, extensions activated in Safari (except AdGuard advanced and AdGuard icon)
I didn't change anything, used to work like a charm

I tried to reboot just in case, nothing change

Tested with :   https://canyoublockit.com/testing/

Did someone else noticed that ?

**Comment by ameshkov** [comment]
`Preferences -> General -> Content Blockers`

1. Do you see any invalid content blockers there?
2. Which ones?
3. What filter lists are you using?
4. Try disabling them one by one to see which one of them is triggering it

**Comment by cqst** [comment]
Thx for answering

You are right, I see a compilation error for "AdGuard General", activated English and French basic AdGuard filters

Desactivating french and reactivating it fixed the issue

**Comment by superlex** [comment]
@ameshkov
Me too!
Desactivating EasyList Italy and reactivating it fixed the issue

**Comment by ameshkov** [comment]
Next time it happens, **before disabling/enabling filters**, could you please export the content blocker JSON file and post it here?

**Comment by ameshkov** [comment]
The JSON files we need are located here: 
`~/Library⁩/Group\ Containers/TC3Q7MAJXF.com.adguard.safari.AdGuard⁩/`

**Comment by Oleg-Chashko** [comment]
@ameshkov
"Compilation failed" #434
Here are the files for you "JSON"

**Comment by ameshkov** [comment]
Merged into #434 since it already contains necessary info and logs.

**Comment by zecanard** [comment]
The French filter is still causing an issue as of AdGuard Safari Extension 1.8.8. I don’t see any compilation error, but the following steps will break AdGuard:

1. Disable AdGuard Safari Extension.
2. Verify that ads are no longer blocked.
3. Reenable AdGuard Safari Extension with AdGuard French Filter v2.0.25.37 (11/27/2020, 5:30:49 AM) enabled.
4. Wait a reasonable amount of time for Safari Extension to reactivate itself.
5. Refresh a page containing ads. Ads will still show on that page.
6. Disable French Filter.
7. Refresh the same page containing ads. Ads are now blocked.
8. Reenable French Filter.
8. Refresh the same page containing ads. Ads are still blocked.

If the AdGuard French Filter is disabled from the start, disabling/reenabling AdGuard behaves as expected.

**Comment by Mizzick** [comment]
@zecanard might you export logs and post it here, please?

**Comment by zecanard** [comment]
Are there specific steps I need to perform before exporting the logs, or can just export them as-is?

**Comment by Mizzick** [comment]
Just as-is, it actually contains all the necessary info

**Comment by zecanard** [comment]
Thanks for looking into it.

[adg_safari_logs_1606517332170.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5609771/adg_safari_logs_1606517332170.zip)
