### ISSUE TITLE
Reduce app UI size and remove scrolling where possible

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#430]
Please Reduce app UI size and optimise vertical space, this application is not for touch screen interface.
I understand that this is a very big rework of the interface, but if you have the opportunity, try to do it.
Example: MacBook Pro 13" - And even at this size, the application does not fit vertically and you have to use scrolling.

<img width="1280" alt="Untitled 2" src="https://user-images.githubusercontent.com/62497891/101346585-0fb30e80-3889-11eb-94f2-021ed58e064e.png">

Is vertical free space not being used but scrolling used.

![Bildschirmaufnahme 2020-11-20 um 23 35 00](https://user-images.githubusercontent.com/62497891/99858620-3fc29800-2b8e-11eb-915e-4da7e8174e5b.gif)

![Bildschirmaufnahme 2020-11-21 um 12 18 53](https://user-images.githubusercontent.com/62497891/99875995-25230a00-2bf4-11eb-84bd-599db775fff4.gif)

![Bildschirmaufnahme 2020-11-20 um 23 35 47](https://user-images.githubusercontent.com/62497891/99858630-48b36980-2b8e-11eb-98f2-ebc99f5f3cc9.gif)

![Bildschirmaufnahme 2020-11-20 um 23 37 13](https://user-images.githubusercontent.com/62497891/99858645-50730e00-2b8e-11eb-94da-e07038253f96.gif)

**Comment by tvinzz** [comment]
we will take note it on the next design update

**Comment by Oleg-Chashko** [comment]
> we will take note it on the next design update

@tvinzz 
Thank you, if it's not a secret in what version can you expect?
