### ISSUE TITLE
Some AdGuard extensions are disabled

### ISSUE THREAD

**Issue by xenofont1** [AdguardTeam/AdGuardForSafari#432]
### Issue Details

* AdGuard for Safari version: 1.8.6
* Environment name and version: 13.1.2 (13609.3.5.1.5)
* Operating System: 10.13.6 (17G14033)
* Filters you use in AdGuard: AdGuard General ONLY (the rest it says are disabled in Safari)
* Any other browser extensions you have installed: None

### Expected Behavior
This error message should not be displayed and filters should not be shown as disabled in Safari. They are not disabled to begin with.
### Actual Behavior
Error message is shown:
Some AdGuard extensions are disabled
You should enable all AdGuard extensions for correct ad blocking in Safari

### Screenshots

![Screen Shot 2020-11-20 at 7 56 06 PM](https://user-images.githubusercontent.com/74800747/99863149-d9784e00-2b6a-11eb-8dc8-ef7d6b2e3a9c.png)
![Screen Shot 2020-11-20 at 7 56 26 PM](https://user-images.githubusercontent.com/74800747/99863150-da10e480-2b6a-11eb-872d-0e7e1f3bdee5.png)
![Screen Shot 2020-11-20 at 7 57 10 PM](https://user-images.githubusercontent.com/74800747/99863152-da10e480-2b6a-11eb-9e10-543f488a93d0.png)
![Screen Shot 2020-11-20 at 7 57 26 PM](https://user-images.githubusercontent.com/74800747/99863153-da10e480-2b6a-11eb-9081-7abb6771e69a.png)

**Comment by xenofont1** [comment]
I would like to try to downgrade to 1.8.2 as it seems this might actually work, but can't see to find the installation file?

**Comment by Oleg-Chashko** [comment]
> I would like to try to downgrade to 1.8.2 as it seems this might actually work, but can't see to find the installation file?

Where are previuos AG for Safari versions? #420
Version 1.8.2:
https://uploads.adguard.com/AdGuard_Safari.app_1.zip

**Comment by crgmrgn** [comment]
Thanks, given exactly the same scenario here (same base OS, Safari release, same issues) …

v1.8.2 resolves all my issues with v1.8.4/5/6 with respect to failing to assemble rulesets and also limited number (3x) extensions showing up in Safari Extensions preference window. Now, is there any convenient way to stop the app auto-updating itself to the latest release until such time as this is all resolved (short of just not restarting the app/system)?

**Comment by DrWhat** [comment]
I can confirm having the exact same issue on the same OS configuration. Here’s an additional piece of info, which might be helpful in addressing the issue. When first launched, v1.8.6 gave me this error:
![Screen Shot 2020-11-22 at 1 30 33 PM](https://user-images.githubusercontent.com/313590/99901478-0726d980-2cc8-11eb-806f-474894a4d11d.png)

Downgrading to 1.8.2 (from the link above) works for a few minutes until the app silently updates itself.

**Comment by TheHasagi** [comment]
Duplicate #419
