### ISSUE TITLE
AdGuard 1.8.6 on macOS Big Sur 11.0.1 with Safari 14.0.1 breaks Gmail

### ISSUE THREAD

**Issue by fareastenders** [AdguardTeam/AdGuardForSafari#433]
AdGuard 1.8.6 on macOS Big Sur 11.0.1 with Safari 14.0.1. With only the default Ad Blocking, Privacy, Social and Annoyances filters enabled, it breaks Gmail.

* AdGuard for Safari version: 1.8.6 
* Environment name and version: Safari 14.0.1 (16610.2.11.51.8)
* Operating System: macOS Big Sur 11.0.1
* Filters you use in AdGuard: default Ad Blocking, Privacy, Social and Annoyances filters enabled
* Any other browser extensions you have installed: Save to Pocket 1.1, LastPass 4.60.0

### Expected Behavior
Gmail (mail.google.com) should display the emails

### Actual Behavior
Gmail (mail.googe.com) does not display the area under the Primary, Promotions etc. tabs which contains the emails.

**Comment by fareastenders** [comment]
<img width="1254" alt="Screenshot 2020-11-21 at 17 18 39" src="https://user-images.githubusercontent.com/16479230/99883265-29641d00-2c1e-11eb-8daf-10988f4ea15c.png">
<img width="1250" alt="Screenshot 2020-11-21 at 17 17 46" src="https://user-images.githubusercontent.com/16479230/99883267-2a954a00-2c1e-11eb-8dba-0a748c113ab0.png">

Furthermore, the issue remains when the 'Enabled on this website' checkbox is unchecked.

Gmail can only be made to work by disabling the extension.

**Comment by whatstevedid** [comment]
For me, this appears when using the 'AdGuard Annoyances filter'. If I disable this and use 'Fanboy's Annoyances' instead, this seems to work around the issue.

Similarly there are issues with the social filters and YouTube.

**Comment by Alex-302** [comment]
@whatstevedid Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window 30-60 seconds.

**Comment by ameshkov** [comment]
@Mizzick also there're some strange errors in the console

![image](https://user-images.githubusercontent.com/5947035/99972375-7dead200-2daf-11eb-8a28-540218f78e37.png)

**Comment by vozersky** [comment]
Hey everyone! Could you please try the latest beta?

It has some important changes that may be related:
https://agrd.io/safari_beta

**Comment by whatstevedid** [comment]
> Hey everyone! Could you please try the latest beta?
> 
> It has some important changes that may be related:
> https://agrd.io/safari_beta

Initial signs are positive - I have the lists enabled and no gmail issues so far, and no YouTube problems either. Will continue to test and report back.

**Comment by kishyr** [comment]
Using the beta, I cannot mark as spam and when I read an email, it leaves it as unread.

**Comment by TheHasagi** [comment]
@kishyr 

Hello!

We've released a new [version](https://agrd.io/safari_beta), can your try with it?
