### ISSUE TITLE
App Icon too big for Big Sur's standard frame

### ISSUE THREAD

**Issue by SamAkc** [AdguardTeam/AdGuardForSafari#435]
### Prerequisites
[x] I am running the latest version

### Problem Description
It is great that the devs updated the app icon to suit Big Sur's new UI design. However, the app icon's size is a little too big compared to the standard app icons in Big Sur. This is especially noticeable when the app remains in the Dock (check attachments)

### Proposed Solution
Simply decreasing the image's size of the app icon should do the trick. There are several templates for Big Sur's icon design on GitHub available as well.

### Additional Information
This issue represents clearly a minor priority and can be deleted if unwanted.

<img width="494" alt="Bildschirmfoto 2020-11-22 um 21 34 02" src="https://user-images.githubusercontent.com/48156679/99916425-73c2c800-2d0a-11eb-825f-092bf165334b.png">

<img width="552" alt="Bildschirmfoto 2020-11-22 um 21 38 37" src="https://user-images.githubusercontent.com/48156679/99916562-15e2b000-2d0b-11eb-96e8-00d36e96d42e.png">

**Comment by superlex** [comment]
Take a look:
https://github.com/AdguardTeam/AdGuardForSafari/issues/425
