### ISSUE TITLE
AdGuard not blocking YouTube ads

### ISSUE THREAD

**Issue by ArchKevin22** [AdguardTeam/AdGuardForSafari#437]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.8.6
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) Safari 14.0.1 (16610.3.6.3)
* Operating System: (e.g macOS High Sierra 10.13.6) macOS Big Sur 11.1
* Filters you use in AdGuard: AdGuard base filter, AdGuard mobile ads filter, EasyList, Peter Lowe's list, Adguard tracking protection filter, EasyPrivacy, Fanboy's enhanced tracking list, AdGuard social media filter, Fanboy's social blocking list, Adguard annoyances filter, Fanboy's annoyances, Adblock warning removal list 
* Any other browser extensions you have installed: n/a

### Expected Behavior
Youtube ads should be blocked, including video and side bar ads
### Actual Behavior
When advanced blocking is disabled, video ads are popping up during a video. When advanced blocking is enabled, I still get ads on the side bar and the home page. Also, YouTube comments aren't loading with an infinite loading wheel instead.
### Screenshots

<details><summary>Screenshot:</summary>

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/19791612/100042243-ea6dcd00-2dbf-11eb-9946-fd1947975b54.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/19791612/100042442-505a5480-2dc0-11eb-9539-d00ea9e159ac.png">

</details>

**Comment by superlex** [comment]
Maybe because of that:
https://github.com/AdguardTeam/AdGuardForSafari/issues/434

**Comment by ameshkov** [comment]
Merged into #434

**Comment by ameshkov** [comment]
Oh, sorry, wrong bug. #419 -- this is the reason.

Please try the beta version: https://agrd.io/safari_beta
