### ISSUE TITLE
Unable to enable parts of AdGuard in Preferences

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdGuardForSafari#438]
### Issue Details

AdGuard for Safari version: 1.8.6
Environment name and version: 13.1.2 (13609.3.5.1.5)
Operating System:macOS High Sierra 10.13.6
 Filters you use in AdGuard: Base, Tracking Protection, Annoyances, Spam 404, 
 Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 1.8.6
* **Environment name and version:**
  * 13.1.2 (13609.3.5.1.5)
* **Operating system and version:**
  * macOS High Sierra 10.13.6
* **Filters you use in AdGuard:**
  * Base, Tracking Protection, Annoyances, Spam 404
* **Any other browser extensions you have installed:**
  * None

### Expected Behavior

Should be able to enable the other parts of AdGuard. 

### Actual Behavior

Cannot enable parts of the AdGuard extension and there is no place for it in Preferences pane. 
### Screenshots

![Screen Shot 2020-11-23 at 9 29 02 PM](https://user-images.githubusercontent.com/69532417/100052553-03cc4480-2dd3-11eb-8a04-157413d84b1b.png)
![Screen Shot 2020-11-23 at 9 29 28 PM](https://user-images.githubusercontent.com/69532417/100052555-05960800-2dd3-11eb-8a44-916e8b8fb40a.png)

<details><summary>Screenshot:</summary>

</details>

### Additional Information

For some reason, I am unable to turn on the additional extensions that are part of Adguard for safari in the latest version. I was able to get it to work in the previous version but it broke in this version of AdGuard when I updated to latest. Already attempted reinstallation and it didn't fix it.

**Comment by TheHasagi** [comment]
Duplicate #419
