### ISSUE TITLE
"Some adguard extensions are disabled" after update to 1.8.6 but all 3 extensions are enabled.

### ISSUE THREAD

**Issue by remcokalf** [AdguardTeam/AdGuardForSafari#442]
I just updated to 1.8.6.
I am on High Sierra.

In Adguard settings I get a big orange notification:

"Some AdGuard extensions are disabled
You should enable all AdGuard extensions for correct ad blocking in Safari"

However, in Safari setting all extensions (3 are visible) are enabled. So there is nothing extra to enable. 
See combined screenshot.

Before this update there were more extensions (6 I believe). 

So, is this a bug? Did my update go wrong, did not all extensions install? Or is there an incompatibility with High Sierra (and if yes, how can I downgrade?)

![Schermafbeelding 2020-11-25 om 16 02 09](https://user-images.githubusercontent.com/4609920/100245731-ac47e900-2f38-11eb-9a6d-733e4ece57f6.png)

**Comment by TheHasagi** [comment]
Hello, we will fix this with the nearest update.

Duplicate #419
