### ISSUE TITLE
The response field of the return button has moved down.

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#446]
* AdGuard for Safari version: 1.8.7 Beta
The field of operation, the return buttons has moved down.

<img width="1023" alt="Bildschirmfoto 2020-11-25 um 22 59 05" src="https://user-images.githubusercontent.com/62497891/100286710-8c81e680-2f73-11eb-96c1-77dc64bbe222.png">

**Sample video:**
[Bildschirmaufnahme 2020-11-25 um 23.06.48.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5599476/Bildschirmaufnahme.2020-11-25.um.23.06.48.zip)

**Comment by tvinzz** [comment]
css bug. fixed.

**Comment by superlex** [comment]
@tvinzz 
Please, take a look at update icon too:

<img width="67" alt="update_icon" src="https://user-images.githubusercontent.com/1375223/100293891-72e99a80-2f85-11eb-9d3e-ad35debd8e77.png">

**Comment by tvinzz** [comment]
@superlex, same, fixed.

**Comment by Oleg-Chashko** [comment]
AdGuard for Safari version: v.1.8.8 Release.
No problem was found in version 1.8.8 Release.
Thanks to the whole team!
The topic is closed.
