### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by Patrickwttm** [AdguardTeam/AdGuardForSafari#447]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
The new icon for macOS Big Sur is very nice but slightly bigger than the other default icons. 

### Proposed Solution
Can you please reduce the icon size so that it aligns with the rest of the icons?

### Alternatives Considered
Do nothing and suffer visual harm?

### Additional Information
I guess that's all you need to know?

**Comment by superlex** [comment]
Fixed in latest beta:
https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.8.7-beta
