### ISSUE TITLE
Add support for more TLDs

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#449]
`.vip`
sample: https://github.com/AdguardTeam/AdguardFilters/issues/67699`

**Comment by ameshkov** [comment]
@Mizzick check the most popular TLDs here:
https://gist.github.com/ameshkov/e02db187d2adf2f068a791f6942f4039

**Comment by ameshkov** [comment]
`.vip` is number 131 there. Let's increase the number of domains to 200 and see how Safari lives with this maybe?

Alternatively, we could even use a larger list and simply split the rule into several rules with the different `if-domain` values (won't work for `~example.*` though).
