### ISSUE TITLE
Extra symbols appers when adding domain to Whitelist

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdGuardForSafari#45]
1. Load a webpage
2. Tap on AG icon in Safari
3. Uncheck "Enable on this website

Actual behavior: Domain will be added to Whitelist  with some alien symbols :)
Domain will be excluded from filtering though.

https://uploads.adguard.com/AdGuard_Settings_2018-10-04_15-27-20.png

**Comment by Stillness-2** [comment]
PR44
