### ISSUE TITLE
Ad blocking does not work in MacOS 10.13.6 and Safari 13.1.2

### ISSUE THREAD

**Issue by GitHubrwkl** [AdguardTeam/AdGuardForSafari#450]
Adguard for Safari can no longer blocks ads like it used to in its previous Mac App Store version before this update to 1.8.6.  The Adguard for Safari application window keeps on saying "Some Adguard extensions are disabled"; and has a "Fix It" button which brings you to the Safari Extension tab, where all the Adguard extensions are already enabled.  I tried disabling/enabling these extensions, reinstalling the Adguard application; they don't work.

Adguard for Safari works fine on my other Mac running MacOS 10.15.7 and Safari 14.0.1.  I notice that there are quite a few more Adguard extensions that show up in this setup than in MacOS 10..13.6 and Safari 13.1.2, which has only:  Adguard Advanced, Adguard General, and Adguard Safari Icon.

[adguard-settings-20201026_9838.json.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5603472/adguard-settings-20201026_9838.json.zip)

**Comment by vozersky** [comment]
@GitHubrwkl Hi! We've already addressed macOS High Sierra compatibility [issue](https://github.com/AdguardTeam/AdGuardForSafari/issues/419) in the latest beta v1.8.7 https://agrd.io/safari_beta . Beta still contains several know issues we're fixing in the momen but I would really appreciate if you could try the beta build on your mac with 10.13.6

**Comment by GitHubrwkl** [comment]
I tried the beta and so far so good.  Thanks!
