### ISSUE TITLE
Adguard Security extension fails to load (intermittently)

### ISSUE THREAD

**Issue by nmt1900** [AdguardTeam/AdGuardForSafari#454]
Adguard For Safari 1.8.8 Beta
Safari 13.1.2 (13609.3.5.1.5)
macOS 10.13.6 (17G14042)

While all other extensions are now loading properly, something is still wrong with Adguard Security.

(AEMainAppServices) AG: Checking enabled extensions...
(AEMainAppServices) AG: Enabled extensions 'com.adguard.safari.AdGuard.AdvancedBlocking': 1, error (null), userInfo: (null)
(AEMainAppServices) AG: Enabled extensions 'com.adguard.safari.AdGuard.BlockerExtension': 1, error (null), userInfo: (null)
(AEMainAppServices) AG: Enabled extensions 'com.adguard.safari.AdGuard.BlockerPrivacy': 1, error (null), userInfo: (null)
**(AEMainAppServices) AG: Enabled extensions 'com.adguard.safari.AdGuard.BlockerSecurity': 0, error Error Domain=SFErrorDomain Code=1 "(null)", userInfo: {
}**
(AESharedResources) AG: responseAllExtensionEnabled
(AEMainAppServices) AG: Checking enabled extensions finished with failure.

**Comment by nmt1900** [comment]
Appearantly 1.8.8 stable release (at least App Store version) has this problem fixed.

**Comment by ameshkov** [comment]
I actually think there is a problem after all, hence reopening the issue.

@Mizzick I think we're facing a situation with Safari intermittently not being able to compile a content blocker. We faced this once on iOS and surprisingly the only working solution was to make a second attempt to load the very same content blocker.

**Comment by nmt1900** [comment]
It looks like standalone release still fails to load Security extension - every time even with multiple reinstalls, but **App Store installation works OK.**

Can there be some relation to installation method? Standalone release gives "unidentified developer" prompt on first run and App Store release obviously not - can there be some possible relation to that?

**Comment by Mizzick** [comment]
@nmt1900 By documentation this error means the following:
```
A Content Blocker or Safari app extension with the specified bundle identifier was not found, or the bundle identifier specified an extension that was not owned by you.
```

Please check you do really have it shown in Safari Preferences - Extensions?

**Comment by Mizzick** [comment]
@ameshkov These logs are from extensions state check, at that point we check is extension enabled etc.
It doesn't affect any compilation questions.

**Comment by nmt1900** [comment]
@Mizzick extension **was** missing when these errors were found in log (on standalone installation). 

All extensions are displayed and working, when install is done from App Store.
