### ISSUE TITLE
`||` prevents custom filter from working

### ISSUE THREAD

**Issue by edzkite** [AdguardTeam/AdGuardForSafari#455]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 1.8.6
* **Environment name and version:**
  * Safari 14.0.1 (16610.2.11.51.8)
* **Operating system and version:**
  * macOS Big Sur 11.0.1
* **Filters you use in AdGuard:**
  * Base, Privacy
* **Any other browser extensions you have installed:**
  * N/A

### Expected Behavior
I have a set of rules 
```
||eater.com##div.c-ad-allowlist
||eater.com##div.adblock-allowlist-messaging__wrapper
||eater.com##div.adblock-allowlist-messaging__article-wrapper
```
that used to block the ad banner for eater.com and its subdomains.

This was working until I upgraded to AdGuard 1.8.6, and is still present in 1.8.8, on both Catalina and Big Sur.
### Actual Behavior
The banner no longer gets blocked. I have to specify the site or the actual subdomain, e.g.` sf.eater.com` for it to work properly.

### Screenshots

<details><summary>Screenshot:</summary>

With `||` rule, e.g. `||eater.com##div.c-ad-allowlist`
<img width="1392" alt="Screen Shot 2020-11-27 at 3 20 49 PM" src="https://user-images.githubusercontent.com/47993402/100488735-e80fb980-30c4-11eb-8a0b-6fb862bf35ad.png">

With subdomain specified instead, e.g. `sf.eater.com##div.c-ad-allowlist`
<img width="1392" alt="Screen Shot 2020-11-27 at 3 21 02 PM" src="https://user-images.githubusercontent.com/47993402/100488753-f8c02f80-30c4-11eb-86d9-47749db64edf.png">

</details>

**Comment by ameshkov** [comment]
Please note, that these rules are invalid.

You can't use `||` in cosmetic rules, the proper syntax is:
```
eater.com##div.c-ad-allowlist
eater.com##div.adblock-allowlist-messaging__wrapper
eater.com##div.adblock-allowlist-messaging__article-wrapper
```

These rules cover subdomains as well.
