### ISSUE TITLE
The French filter is still causing an issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#456]
The French filter is still causing an issue as of AdGuard Safari Extension 1.8.8. I don’t see any compilation error, but the following steps will break AdGuard:

1. Disable AdGuard Safari Extension.
2. Verify that ads are no longer blocked.
3. Reenable AdGuard Safari Extension with AdGuard French Filter v2.0.25.37 (11/27/2020, 5:30:49 AM) enabled.
4. Wait a reasonable amount of time for Safari Extension to reactivate itself.
5. Refresh a page containing ads. Ads will still show on that page.
6. Disable French Filter.
7. Refresh the same page containing ads. Ads are now blocked.
8. Reenable French Filter.
8. Refresh the same page containing ads. Ads are still blocked.

If the AdGuard French Filter is disabled from the start, disabling/reenabling AdGuard behaves as expected.

I believe this issue may also be affecting the beta version of AdGuard for iOS that is on currently TestFlight, because it keeps giving me Filter Update errors. The current release on the App Store (as well as v1.8.2 of AdGuard Safari Extension) works flawlessly.

_Originally posted by @zecanard in https://github.com/AdguardTeam/AdGuardForSafari/issues/429#issuecomment-734965529_

**Comment by ameshkov** [comment]
@Mizzick find the logs in the previous thread:
https://github.com/AdguardTeam/AdGuardForSafari/issues/429#issuecomment-735006383

**Comment by ameshkov** [comment]
> @zecanard

> I believe this issue may also be affecting the beta version of AdGuard for iOS that is on currently TestFlight, because it keeps giving me Filter Update errors. The current release on the App Store (as well as v1.8.2 of AdGuard Safari Extension) works flawlessly.

Could you please export logs from AG for iOS as well?

**Comment by zecanard** [comment]
I went ahead and verified that if I disable the AdGuard French Filter, updating filters works correctly. If I enable it, “Filter update error.”

On a side note, the caption for the Allowlist (“AdGuard doesn’t work on the sites from this list”) is a bit confusing, seemingly suggesting that there is a known problem with AdGuard on those sites. I think “Disable AdGuard on these sites” would be more appropriate.

<img src="https://user-images.githubusercontent.com/25799849/100497644-7ebe9380-3122-11eb-9d0e-6c1da0effacc.PNG" height="640"> <img src="https://user-images.githubusercontent.com/25799849/100497685-bb8a8a80-3122-11eb-859a-1a290d199708.PNG" height="640">

[adguardforios_logs_3331120200211.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5610273/adguardforios_logs_3331120200211.zip)

**Comment by ameshkov** [comment]
@zecanard the issue should go away soon, we fixed the filter list on the server side.

**Comment by zecanard** [comment]
Thank you 🙏🏼

**Comment by zecanard** [comment]
The “Filter update error” appears to be gone in AdGuard for iOS, but AdGuard Safari Extension appears to be working only partially.

If I disable AdGuard Safari Extension, I get an ad banner at the top of my YouTube homepage. That banner remains after I reenable AdGuard Safari Extension with the French Filter. On the other hand, ads on CashbackMonitor disappear. If I disable the French Filter, the banner ad on YouTube disappears. It remains hidden if I then reenable the French Filter.

**Comment by ameshkov** [comment]
Could you please export logs and system info via menu bar?

**Comment by zecanard** [comment]
[adg_safari_logs_1606768996262.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5618624/adg_safari_logs_1606768996262.zip)

**Comment by zecanard** [comment]
The same thing is happening in AdGuard for iOS beta: disabling, then reenabling all content blockers causes ads not to be blocked. Trying to update filters leads to “Filter update error.” Disabling the French Filter allows me to update filters, and leads to ads being blocked in Safari. Ads continue to be blocked after reenabling the French Filter.

[adguardforios_logs_3381220200212.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5634691/adguardforios_logs_3381220200212.zip)

**Comment by ameshkov** [comment]
@zecanard try the build 579 please

**Comment by zecanard** [comment]
Saw it land right after I posted my comment! Looks good so far: disabled all 6 content blockers, ads appeared. Reenabled all 6 content blockers, ads disappeared.

No filter update error, but I had already updated the French Filter. I’ll have to try again next time there is a new French Filter to download. Maybe you could push a dummy update to it?

**Comment by ameshkov** [comment]
> Maybe you could push a dummy update to it?

Well, it's updated rather often, there'll be an update today.

**Comment by ameshkov** [comment]
Can't reproduce it anymore on v1.8.9. We'll publish the updated version today and see how it goes.

**Comment by ameshkov** [comment]
Beta v1.8.9 is finally out

**Comment by zecanard** [comment]
Updating filters is working for the French Filter in AdGuard for iOS beta, and the French Filter no longer appears to be causing issues when disabling/reenabling AdGuard Safari Extension.

Thank you very much 🙏🏼
