### ISSUE TITLE
Scrolling broken on YouTube

### ISSUE THREAD

**Issue by JaJaWa** [AdguardTeam/AdGuardForSafari#457]
### Issue Details

* AdGuard for Safari version: 1.8.8
* Environment name and version: 14.0.1 (16610.2.11.51.8)
* Operating System: 11.0 Big Sur
* Filters you use in AdGuard:
* Any other browser extensions you have installed: Base Filter, Tracking Prevention Filter

### Actual Behavior

YouTube video pages do not scroll normally or at all with AdGuard enabled. Also mentioned here: https://www.reddit.com/r/youtube/comments/ju9jnc/scrolling_broken_on_safari_14/gcoo1l4/?utm_source=reddit&utm_medium=web2x&context=3
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
> Any other browser extensions you have installed: Base Filter, Tracking Prevention Filter

Are you sure these are the only filters enabled?

**Comment by Alex-302** [comment]
I can't reproduce with the same settings. Please try to disable-enable content blockers in Safari settings and restart browser.

**Comment by TheHasagi** [comment]
Closed for now, should be reopened if needed.
