### ISSUE TITLE
AdGuard is not working (not blocking ads), and is not signed either

### ISSUE THREAD

**Issue by einsteinbqat** [AdguardTeam/AdGuardForSafari#459]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.8.8
* Environment name and version: 13.1.2 (13609.3.5.1.5)
* Operating System: macOS High Sierra 10.13.6
* Filters you use in AdGuard:

![Screen Shot 10](https://user-images.githubusercontent.com/48373997/100530471-94829600-31c0-11eb-9817-46a1bdc559e1.png)

![Screen Shot 11](https://user-images.githubusercontent.com/48373997/100530473-98aeb380-31c0-11eb-8d1c-1a7367043c3d.png)

### Expected Behavior

AdGuard should be signed.

AgGuard should be blocking ads.

### Actual Behavior

AdGuard is not signed. It does not matter if I download from AdGuard.com or GitHub.com.
![Screen Shot 14](https://user-images.githubusercontent.com/48373997/100530509-fba04a80-31c0-11eb-8743-42e584d38c4b.png)

AdGuard is not blocking ads.
![Screen Shot 15](https://user-images.githubusercontent.com/48373997/100530513-0529b280-31c1-11eb-8794-d764a354f8cd.png)

![Screen Shot 16](https://user-images.githubusercontent.com/48373997/100530514-0824a300-31c1-11eb-8832-360d90134c19.png)

![Screen Shot 17](https://user-images.githubusercontent.com/48373997/100530516-0bb82a00-31c1-11eb-8ee8-8425274778fa.png)

![Screen Shot 18](https://user-images.githubusercontent.com/48373997/100530517-0eb31a80-31c1-11eb-9a0e-3b33230656fc.png)

![Screen Shot 19](https://user-images.githubusercontent.com/48373997/100530519-11ae0b00-31c1-11eb-9dcb-d858fc0f1910.png)

### Additional Information

AdGuard is enabled.
![Screen Shot 13](https://user-images.githubusercontent.com/48373997/100530522-1e326380-31c1-11eb-86bb-be70518539b2.png)

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdGuardForSafari/issues/453

**Comment by einsteinbqat** [comment]
@ameshkov 
> Dup of #453

Are you saying that the fact that the app is not signed is what is causing AdGuard to not block any ads? Because my post reports 2 issues into one.

**Comment by ameshkov** [comment]
Yes, I suppose Safari can't load extensions if it considers them unsigned.

**Comment by einsteinbqat** [comment]
@ameshkov 
Well that is stupid… considering that I right-clicked and selected open to allow it to run even if it is unsigned. So then where do I download a signed copy in order to downgrade to a version that will work, or are you telling that I will have to wait for some newer version or install another extension like AdBlock or uOrigin?

**Comment by ameshkov** [comment]
> So then where do I download a signed copy in order to downgrade to a version that will work, or are you telling that I will have to wait for some newer version or install another extension like AdBlock or uBlock Origin?

I am not yet sure why it happens (the issue seems to be limited to *some* users with High Sierra, not all of them).

Meanwhile, you can use 1.8.2: https://uploads.adguard.com/AdGuard_Safari.app_1.zip

**Comment by einsteinbqat** [comment]
@ameshkov 

Great! Thanks! 1.8.2 is working.
