### ISSUE TITLE
Launch Screen Icon is blurry

### ISSUE THREAD

**Issue by BranchS** [AdguardTeam/AdGuardForSafari#460]
### Issue Details

* AdGuard for Safari version: 1.8.6
* Environment name and version: 14.0.1
* Operating System: macOS Big Sur 11.0.1

When you open the AdGuard app, the launch screen that shows has the AdGuard icon, but that icon is fuzzy on retina displays. It happens too quick for me to grab a screenshot, but it should be pretty easy to replicate-- just quit AdGuard then open it up.

This could be an opportunity for an overall better launch screen. Best practice is to have the launch screen be similar to the opening screen of the app, minus the actual content... see screenshot from Apple's developer docs. But at the very least, a non-blurry icon would be good! :)

<img width="758" alt="Screen Shot 2020-11-29 at 11 19 19 AM" src="https://user-images.githubusercontent.com/38893932/100547446-cfbeac80-3234-11eb-9d91-e2e13a20398b.png">

**Comment by superlex** [comment]
@BranchS , this?

<img width="1136" alt="dksfm" src="https://user-images.githubusercontent.com/1375223/100555321-eb5c9e00-329a-11eb-997c-efe730c20959.png">

**Comment by TheHasagi** [comment]
@BranchS 

Can you record a short clip then?

**Comment by BranchS** [comment]
@TheHasagi Here you go!
[Screen Recording 2020-12-01 at 11.33.16 PM.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5626977/Screen.Recording.2020-12-01.at.11.33.16.PM.zip)

**Comment by TheHasagi** [comment]
Looks usual for me, but we will think about this, thanks.
