### ISSUE TITLE
AdGuard for Safari V1.8.8 General Release Contains Beta Text

### ISSUE THREAD

**Issue by RobbieTT** [AdguardTeam/AdGuardForSafari#462]
Beta text for V1.8.8 inadvertently released to the Mac App Store:

<img width="1321" alt="Screenshot 2020-11-30 at 13 15 18" src="https://user-images.githubusercontent.com/68080817/100614888-b853f200-330e-11eb-9d95-94f62ea09711.png">

* AdGuard for Safari version: V1.8.8

**Comment by TheHasagi** [comment]
@RobbieTT 

Hello! Thank you for a report, we will fix "What's new" description in the nearest update :)
