### ISSUE TITLE
macOS Big Sur Safari Adguard Advanced Blocker - Gmail won't load

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdGuardForSafari#464]
@th1818 commented on [Tue Dec 01 2020](https://github.com/AdguardTeam/AdguardForMac/issues/796)

### Steps to reproduce

1. Install Adguard Safari extension via the App Store on Mac (I am using Big Sur)
2. Turn on all Adguard extensions in Safari preference
3. Log onto Gmail, and let it run for a while
4. Eventually, Safari will display a message saying that the Gmail page is using significant memory and is automatically refreshed
5. The page will show "Loading Gmail" and then stuck
6. If I disable Adguard in the preference, or go to "Activity Monitor" and force kill the Adguard Advanced Blocker process, and then refresh the page in Safari, Gmail will load successfully

Note: according to the Activity Monitor, the Safari and Adguard processes are *not* actually using a lot of memory (only a few hundred MB from what I can see at the time of the issue).

### Expected behavior

Gmail should load and run correctly.

### Actual behavior

Got a "Loading Gmail" message (Gmail appears to be stuck loading until I kill the Adguard Advance Blocker process).

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):

MacBook Pro M1 16GB RAM
Big Sur 11.0.1
Latest version of Adguard from the App Store

* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

No

---

@th1818 commented on [Tue Dec 01 2020](https://github.com/AdguardTeam/AdguardForMac/issues/796#issuecomment-736208123)

I switched to another adblocker Safari extension after submitting this issue 7 hours ago. Gmail has not run into any issue, and it definitely feels much faster (e.g. changing category, composing new mails, reading new mails, moving mails, etc.). Therefore, I believe that Adguard may not have been optimised for the latest version of Safari (e.g. memory leak). 

Note 1: Adguard works perfectly fine so far on MS Edge on the same MacBook (M1). 
Note 2: I had the same issue with Safari+Adguard on my old MacBook (Intel) running Big Sur.

**Comment by TheHasagi** [comment]
@th1818

Hello, what is the version of AdGuard for Safari is in use and what filters are enabled?

**Comment by th1818** [comment]
Thanks for the question. I just checked and found out I am using version 1.8.6 but the App Store has a new update (version 1.8.8). I will install it and test.

Filters I enabled:
- Ad blocking: AdGuard base filter and AdGuard mobile ads filter
- Privacy: AdGuard tracking protection filter
- Annoyances: AdGuard Annoyances filter 
- Other: Filter unblocking search ads and self-promotion

**Comment by th1818** [comment]
I was using Safari non-stop in the past two hours, with the latest version of AdGuard installed (v1.8.8). The Gmail page refreshed once so far (but did *not* stuck loading). However, I can see this at the top of the Gmail page:

![image](https://user-images.githubusercontent.com/27799412/100805198-5f0ccf80-3482-11eb-89a1-b52b53577bf9.png)

**Comment by th1818** [comment]
Just a quick note: I moved to another adblocker a couple of hours ago, continued my work, and I have not seen the memory message so far.

**Comment by Javert24601** [comment]
Hi, can confirm this was an issue for me too and disabling AdGuard on Gmail fixed it.

**Comment by ameshkov** [comment]
Resolved. The problem was in a new rule in the Annoyances filter list.
