### ISSUE TITLE
1.8.8 appstore download issue?

### ISSUE THREAD

**Issue by remcokalf** [AdguardTeam/AdGuardForSafari#465]
Maybe this is an appstore issue, but to be sure I post it here:

I am trying to update v. 1.8.6 to 1.8.8. But the macos appstore download/update is not working. 

Tried everything, logging in/out of the appstore, reset it, restarts. Then deleted the app and tried a reinstall. 
None of it is working.

When trying to update (from the updates tab, as well as from the app page itself) it just gets me a rotating loading icon and greyed out update button. 
When trying to reinstall I get a 'Adguard for Safari cannot be downloaded), see screenshot.

![Schermafbeelding 2020-12-01 om 16 50 34](https://user-images.githubusercontent.com/4609920/100770006-0e9f5e80-33fd-11eb-922f-0b17317a2aa3.png)

Maybe nothing you can do about it, an appstore issue or glitch? Never seen this before though.

I am on High Sierra if that matters.

**Comment by ameshkov** [comment]
> I am on High Sierra if that matters.

Yeah, this matters a lot.

It seems that Apple broke apps on High Sierra: https://discussions.apple.com/thread/252110775

**Comment by remcokalf** [comment]
FYI I don't have Security Update 2020-006 installed, mentioned in that article. Still have to install Security Update 2020-005 also. The problem is on multiple machines.

**Comment by remcokalf** [comment]
Also, my apps are not crashing. 
And the app store is working: I just updated other apps.
It is just Adguard that is not updating, on 2 machines.
So I doubt the issue is the one in the link.

**Comment by ameshkov** [comment]
Nevertheless, I don't think the problem can be fixed on our side since this is an App Store build.

Anyways, you can try the standalone version.

**Comment by remcokalf** [comment]
FYI. The standalone version is installing and working fine on High Sierra (version 1.8.8). Just installed on 2 machines. 
Appstore build seems broken for me on both machines.
