### ISSUE TITLE
Errors occur: if the application is closed without waiting for a complete download

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#467]
AdGuardForSafari v.1.8.8
If you start the application and close it without waiting for the full download, "A JavaScript error occurred in the main process"
Try in the future to correct these errors if possible.
[Bildschirmaufnahme 2020-12-01 um 22.23.43.mov.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5625645/Bildschirmaufnahme.2020-12-01.um.22.23.43.mov.zip)
[Bildschirmaufnahme 2020-12-01 um 22.25.29.mov.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5625647/Bildschirmaufnahme.2020-12-01.um.22.25.29.mov.zip)

**Comment by superlex** [comment]
AdGuard may alert user if it's updating something.
There could be an option about this.

**Comment by tvinzz** [comment]
@Oleg-Chashko, do you still have this error on the latest beta?

**Comment by Oleg-Chashko** [comment]
@tvinzz 
> @Oleg-Chashko, do you still have this error on the latest beta?

AdGuard for Safari v.1.9.0 beta: I checked it with a test. There are no errors. Thanks for the fix.
Happy New Year to you and all your Team!
