### ISSUE TITLE
YouTube Scroll bugged

### ISSUE THREAD

**Issue by Javert24601** [AdguardTeam/AdGuardForSafari#469]
### Issue Details

* AdGuard for Safari version: 1.8.8
* Environment name and version: Safari 14.0.1
* Operating System: MacOS Big Sur
* Filters you use in AdGuard: AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter,
* Any other browser extensions you have installed: LastPass

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Actual Behavior

Following up on the discussion on Reddit: Hi everyone, has anyone had the same problem with scrolling a YouTube page with a video playing on Safari for Mac. It is impossible to scroll down fluently and I really don’t understand why it is happening. Has anyone found a solution?
Thanks
via https://www.reddit.com/r/mac/comments/k2pu4i/youtube_scroll_bugged_on_safari_for_mac/
### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Disabling AdGuard on Youtube solved the issue with scrolling.

**Comment by Eugene-Savenko** [comment]
This https://github.com/AdguardTeam/AdGuardForSafari/issues/457, and I have this problem, too. Also, user 3059139 is facing a similar one:

> Наблюдаю некоторые задержки/фризы на некоторых сайтах, при использовании расширения AdGuard for Safari. В частности https://vk.com/stopcoronavirusrf. При скролле, есть микрофризы, которые отсутствуют если выключить Adguard в меню extensions Safari.
> ОС MacOS 11.0.1, Safari 14.0.1.

**Comment by ameshkov** [comment]
@Eugene-Savenko regarding YT, could you please add these two rules to the user rules and check again in a few seconds:

```
youtube.com#@$##appbar-guide-menu { margin-top: 50px!important; }
youtube.com#@$##ticker.ytd-masthead { display: none!important; }
```

**Comment by ameshkov** [comment]
@Eugene-Savenko also, check the filters updates, maybe the problematic rule in the Annoyances filter list was causing this.

**Comment by Javert24601** [comment]
That seems to fix it!

**Comment by ameshkov** [comment]
@Javert24601 could you please check what exactly helped -- checking filters updates or those two rules?

**Comment by fristys** [comment]
> @Eugene-Savenko regarding YT, could you please add these two rules to the user rules and check again in a few seconds:
> 
> ```
> youtube.com#@$##appbar-guide-menu { margin-top: 50px!important; }
> youtube.com#@$##ticker.ytd-masthead { display: none!important; }
> ```

These user rules somewhat mitigate the issue, but the scroll is still very intermittent - sometimes it'd just bounce the page and refuse to scroll.

**Comment by ameshkov** [comment]
@fristys what filter lists do you have enabled?

**Comment by Oleg-Chashko** [comment]
@ameshkov 
Did a test, maybe it will help you.
1. AdGuard For Safari and all extensions are completely disabled, video is paused, no scrolling.
<img width="1316" alt="Ohne Adguard" src="https://user-images.githubusercontent.com/62497891/100921362-bcce0580-34dc-11eb-851e-3a3ae135cc56.png">

2. AdGuard For Safari and all extensions are fully enabled, video paused, scrolling.
<img width="1316" alt="Adguard mit peremotka" src="https://user-images.githubusercontent.com/62497891/100921650-23532380-34dd-11eb-852f-d83e9692e923.png">

3. AdGuard For Safari and all extensions are completely disabled, the video is played 1080p60, with scrolling.
<img width="1316" alt="Played video 1080p60, peremotka, ohne Adguard" src="https://user-images.githubusercontent.com/62497891/100922076-b68c5900-34dd-11eb-9ffa-5d580bd1ea95.png">

4. AdGuard For Safari and all extensions are fully enabled, video plays 1080p60, with scrolling.
<img width="1316" alt="Played video 1080p60, peremotka, mit Adguard" src="https://user-images.githubusercontent.com/62497891/100922196-e176ad00-34dd-11eb-84ff-6429c7a7d154.png">

**Comment by ameshkov** [comment]
You can also try this rule and see if it changes anything: `@@||youtube.com^$elemhide`

I suspect that it's caused by the cosmetic CSS rules we apply, and this is what I was trying to test with those two rules: https://github.com/AdguardTeam/AdGuardForSafari/issues/469#issuecomment-737397341

**Comment by fristys** [comment]
> @fristys what filter lists do you have enabled?

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1486500/100922807-9dd07300-34de-11eb-8c71-d44c7bbc1f2a.png">


> You can also try this rule and see if it changes anything: `@@||youtube.com^$elemhide`
> 
> I suspect that it's caused by the cosmetic CSS rules we apply (not just the rules, but the way we use to apply them), and this is what I was trying to test with those two rules: [#469 (comment)](https://github.com/AdguardTeam/AdGuardForSafari/issues/469#issuecomment-737397341)

This causes me to get pre-roll ads (the ones with the Skip ad button)

**Comment by ameshkov** [comment]
> This causes me to get pre-roll ads (the ones with the Skip ad button)

Sure, it disables a lot of rules. I am just trying to narrow the issue down to a specific set of rules.

**Comment by fristys** [comment]
> > This causes me to get pre-roll ads (the ones with the Skip ad button)
> 
> Sure, it disables a lot of rules. I am just trying to narrow the issue down to a specific set of rules.

However, the scroll issue goes away. If I had to guess it has something to do with these stupid pre-roll ads.

**Comment by Oleg-Chashko** [comment]
> You can also try this rule and see if it changes anything: `@@||youtube.com^$elemhide`
> 
> I suspect that it's caused by the cosmetic CSS rules we apply (not just the rules, but the way we use to apply them), and this is what I was trying to test with those two rules: [#469 (comment)](https://github.com/AdguardTeam/AdGuardForSafari/issues/469#issuecomment-737397341)

Which test to run with this filter rule (1. 2. 3. 4.)?

**Comment by ameshkov** [comment]
3 and 4

**Comment by Oleg-Chashko** [comment]
> 3 and 4

3. AdGuard For Safari and all extensions are completely disabled, the video is played 1080p60, with scrolling.
<img width="1314" alt="Test 3" src="https://user-images.githubusercontent.com/62497891/100925225-040ac500-34e2-11eb-9a3d-36d5ff5e7604.png">

4. AdGuard For Safari and all extensions are fully enabled, video plays 1080p60, with scrolling.
<img width="1312" alt="Test 4" src="https://user-images.githubusercontent.com/62497891/100925280-1684fe80-34e2-11eb-9413-cc5fbafa088c.png">

Yes, it got better and there is no banner.
But there are micro-freezes even without extensions in Safari on Youtube.
Youtube on Safari is very resource intensive.

**Comment by Oleg-Chashko** [comment]
4. Test 
Test is correct! Wrongly marked the result. I'm sorry, I was in a hurry.
<img width="1312" alt="4  Test" src="https://user-images.githubusercontent.com/62497891/100928149-24d51980-34e6-11eb-8d01-9cbe85a0f919.png">

**Comment by Oleg-Chashko** [comment]
@ameshkov 
_Be sure to pay attention._
5. Test:
Cleared Safari cache and restarted. Conducted "4. Test" Strong freezes, the load on the processor increased. Until all the comments for the video were loaded into the cache, the load did not drop and there were friezes. After a full download to the cache, everything returned to normal.
<img width="1168" alt="4  Test" src="https://user-images.githubusercontent.com/62497891/100931848-5c929000-34eb-11eb-966f-26b450a010b7.png">

**Comment by Javert24601** [comment]
Hi again, even with the new rules (@@||youtube.com^$elemhide) it still isn't ideal

**Comment by ameshkov** [comment]
The fixes implemented in the upcoming v1.8.9 will solve the most pressing issues with YT scroll.

There's another underlying issue that could be triggering it, we'll investigate here: https://github.com/AdguardTeam/ExtendedCss/issues/120

The fix will probably be included in v1.9.

**Comment by tzm41** [comment]
What about AdGuard for Mac?

**Comment by devburke** [comment]
I'm still seeing this issue. The update fixed scrolling on Duolingo, but YouTube pages are still all kindsa crazy. When I turn off the Advanced Blocking filter, the problem goes away.

**Comment by devburke** [comment]
Actually, disregard. I hadn't picked up the latest 1.8.9 update yet.

**Comment by tate1435** [comment]
Will there be a fix for adGuard for Mac?

**Comment by TheHasagi** [comment]
@tate1435 

Try the latest [Nightly](https://agrd.io/mac_nightly) version.

**Comment by tate1435** [comment]
> @tate1435
> 
> Try the latest [Nightly](https://agrd.io/mac_nightly) version.

So far the nightly seems to fix the issue

**Comment by cloudslash7** [comment]
Disabling "Adguard Extra" in Extension settings fixed it for me. I was still having youtube scrolling problems even on 1.9 nightly on Big Sur.

**Comment by ameshkov** [comment]
Hey all, this task about simple mitigation. The investigation of the root cause is here: https://github.com/AdguardTeam/ExtendedCss/issues/120

The good news is that we have finally figured it out.

It appears that Safari (unlike Chrome/FF) is not doing well with the code like that:
`document.documentElement.addEventListener('wheel', () => { /* doing nothing here */ }), true)`

It is especially bad when this event handler is added from an extension's content script. I reckon this happens due to additional sandboxing applied to extensions' content scripts. Anyways, the fix for this issue will be in the upcoming v1.9.

**Comment by tate1435** [comment]
Thanks reaching out. I replied back earlier saying that the nightly helped
which it did some but I ran into the same problem with the nightly. What I
did notice is that I can scroll the page with the down arrow key

**Comment by tate1435** [comment]
And I found this also

https://forums.macrumors.com/threads/youtube-website-scrolling-issue.2272026/?post=29359909#post-29359909

**Comment by ameshkov** [comment]
@tate1435 interesting, you can achieve the same with AG:

Add these two rules to the User filter:
```
youtube.com#$#ytd-page-manager { overflow-y: unset !important; }
youtube.com#$##page-manager.ytd-app { overflow-x: unset !important; }
```

**Comment by cloudslash7** [comment]
> @tate1435 interesting, you can achieve the same with AG:
> 
> Add these two rules to the User filter:
> 
> ```
> youtube.com#$#ytd-page-manager { overflow-y: unset !important; }
> youtube.com#$##page-manager.ytd-app { overflow-x: unset !important; }
> ```

As far as I can tell, that seems to fix the scrolling behavior, even with Adguard Extra turned on. I'll do some more testing, though! Last time it randomly stopped working again after I was in a different tab haha. Seems good so far, thank you!

**Comment by tate1435** [comment]
I added the rules and it does seem to fix it so far. Thanks for the help

**Comment by ameshkov** [comment]
We added these rules to AdGuard Base filter. Thanks again for the link!
