### ISSUE TITLE
Extension Safari not visible

### ISSUE THREAD

**Issue by docgonzo2015** [AdguardTeam/AdGuardForSafari#470]
Hi!

I installed the plugin via the Appstore, opened it, but it does not appear in Safari under Extensions.
Clicking "Open Preferences" in the plugin does not happen either. I have to press ignore.

**Comment by ameshkov** [comment]
What OS version are you using?

**Comment by docgonzo2015** [comment]
10.13.6 (17G14042)

**Comment by ameshkov** [comment]
I am almost sure the issue is caused by Apple themselves.

There're many issues with App Store apps on High Sierra lately: https://discussions.apple.com/thread/252110775

You can try the standalone build instead.
