### ISSUE TITLE
The cosmetic rule doesn't work

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardForSafari#471]
The cosmetic rule `##a[href*="://go.nordvpn.net/"] > img` from the french filter doesn't work here [extreme-down.video](https://www.extreme-down.video/films-new-sd/dvdrip/77178-mulan-french-webrip.html). It exists in optimised filter and works if added in user rules. 

AdGuard for Safari Version 1.8.8
MacOS Big Sur

https://github.com/AdguardTeam/AdguardFilters/issues/68997

**Comment by ameshkov** [comment]
@Sergey-Lyapin do the following:

1. Menu bar -> Export logs and system info
2. You'll see the content blockers JSON there
3. Find the JSON that's for the "General" content blocker
4. Look for the rule with this selector

Do you see that rule there?

**Comment by Sergey-Lyapin** [comment]
@ameshkov 
I don't see this rule in general content blocker's JSON

**Comment by Mizzick** [comment]
WIth Base and French filters enabled it works fine on my side.
And I can see this selector in .json file.

**Comment by ameshkov** [comment]
@Mizzick easily reproduced on my side

**Comment by ameshkov** [comment]
Base + French - same thing

**Comment by ameshkov** [comment]
Can't reproduce it anymore on 1.8.9

**Comment by Sergey-Lyapin** [comment]
> Can't reproduce it anymore on 1.8.9

same

**Comment by TheHasagi** [comment]
Closed.
