### ISSUE TITLE
Crash on AdGuard for Safari v.1.8.8-1.8.9

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#472]
Perhaps this will help you.

* AdGuard for Safari version: 1.8.8
* Environment name and version: 14.0.1 (16610.2.11.51.8)
* Operating System: 11.0.1 (20B29)

[adg_safari_logs_1606944906020.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5632195/adg_safari_logs_1606944906020.zip)
[AdvancedBlocking_2020-12-02-123358_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5632197/AdvancedBlocking_2020-12-02-123358_MacBook-Pro.crash.zip)
[AdvancedBlocking-2020-12-02-131454.ips.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5632203/AdvancedBlocking-2020-12-02-131454.ips.zip)
[AdvancedBlocking_2020-12-02-130834_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5632209/AdvancedBlocking_2020-12-02-130834_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-02-131453_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5632208/AdvancedBlocking_2020-12-02-131453_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-02-234638_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5635419/AdvancedBlocking_2020-12-02-234638_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-02-234050_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5635421/AdvancedBlocking_2020-12-02-234050_MacBook-Pro.crash.zip)

**Comment by Oleg-Chashko** [comment]
AdGuard for Safari version: 1.8.9
[AdvancedBlocking_2020-12-03-230418_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644482/AdvancedBlocking_2020-12-03-230418_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-03-232441_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644483/AdvancedBlocking_2020-12-03-232441_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-03-233041_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644484/AdvancedBlocking_2020-12-03-233041_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-03-233135_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644485/AdvancedBlocking_2020-12-03-233135_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-04-102159_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644486/AdvancedBlocking_2020-12-04-102159_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-04-112707_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644487/AdvancedBlocking_2020-12-04-112707_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-04-114543_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644488/AdvancedBlocking_2020-12-04-114543_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-04-121725_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644489/AdvancedBlocking_2020-12-04-121725_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-04-121755_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644491/AdvancedBlocking_2020-12-04-121755_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-04-161335_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644492/AdvancedBlocking_2020-12-04-161335_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-04-170106_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644494/AdvancedBlocking_2020-12-04-170106_MacBook-Pro.crash.zip)
[AdvancedBlocking_2020-12-04-180940_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5644495/AdvancedBlocking_2020-12-04-180940_MacBook-Pro.crash.zip)

**Comment by ameshkov** [comment]
Any idea how to reproduce this?

**Comment by Oleg-Chashko** [comment]
> Any idea how to reproduce this?

1. Crashes, as I noticed only on YouTube, but this is not 100%
2. I drive the scroll quickly up and down for 1-2 minutes.
3. A couple of times on YouTube, without scrolling there was a crash.

P.S.: I will write in more detail if I can find it for sure.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
Fast scroll up and down for about 10 seconds.
This is a site page and a crash is 100% scrolling.

https://itc.ua/news/razer-vypustila-tws-naushniki-hammerhead-true-wireless-pro-s-aktivnym-shumopodavleniem-podderzhkoj-thx-i-igrovym-rezhimom-zaderzhka-do-60-ms-za-200/

[AdvancedBlocking_2020-12-04-211113_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5645222/AdvancedBlocking_2020-12-04-211113_MacBook-Pro.crash.zip)

**Comment by ameshkov** [comment]
Could you please try this build?
https://www.dropbox.com/s/02s186re56kys67/AdGuard_Safari.app.zip?dl=0

**Comment by Oleg-Chashko** [comment]
> Any idea how to reproduce this?
https://ru.gecid.com/mmedia/asus_rog_delta_s/
Crash is 100% scrolling.
[AdvancedBlocking_2020-12-04-212000_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5645269/AdvancedBlocking_2020-12-04-212000_MacBook-Pro.crash.zip)

**Comment by Oleg-Chashko** [comment]
> Could you please try this build?
> https://www.dropbox.com/s/02s186re56kys67/AdGuard_Safari.app.zip?dl=0

Already put it. What to check? Scrolling?

**Comment by ameshkov** [comment]
Well, anything what you've been doing to cause the crashes (I couldn't do that on my side)

**Comment by Oleg-Chashko** [comment]
@ameshkov 

Could you please try this build?
https://www.dropbox.com/s/02s186re56kys67/AdGuard_Safari.app.zip?dl=0

Crash - scrolling.

https://itc.ua/news/razer-vypustila-tws-naushniki-hammerhead-true-wireless-pro-s-aktivnym-shumopodavleniem-podderzhkoj-thx-i-igrovym-rezhimom-zaderzhka-do-60-ms-za-200/

[AdvancedBlocking_2020-12-04-212907_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5645306/AdvancedBlocking_2020-12-04-212907_MacBook-Pro.crash.zip)

**Comment by Oleg-Chashko** [comment]
> Well, anything what you've been doing to cause the crashes (I couldn't do that on my side)

I don’t know how to help you.
Any ideas how I can help you?

**Comment by ameshkov** [comment]
I've been able to reproduce the issue after all so no worries:)

**Comment by Oleg-Chashko** [comment]
> I've been able to reproduce the issue after all so no worries:)
I'm happy!

I found the algorithm:
1. You open a new page on the site (itc.ua).
2. Scroll up and down crash.
3. If the page was already in the cache, then there will be no crash, if not, then there will be a crash.
4. Not on every site, it is possible to crash. Perhaps it depends on what the site is written on or from the scripts.

**Comment by ameshkov** [comment]
I think I figured it out, the updated build is coming in a moment

**Comment by Oleg-Chashko** [comment]
> I think I figured it out, the updated build is coming in a moment

If you want I can check it tomorrow and give a report on it.

**Comment by ameshkov** [comment]
@Oleg-Chashko here it is: https://www.dropbox.com/s/5rmlrozk3jffmq6/AdGuard_Safari.app.zip?dl=0

**Comment by ameshkov** [comment]
@Oleg-Chashko I'll probably publish a beta update right away (this is the same build)

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko I'll probably publish a beta update right away (this is the same build)

Already put it. I will check and write tomorrow.

**Comment by Oleg-Chashko** [comment]
Hi @ameshkov 
There are no more crashes. Checked for about 1 hour.

_Please pay attention._ 
Can it be done as I suggested? 
Or, in another way, to improve the information content of the log files and make it easier to send you. 
In order not to have to go to the "Log" folder for a crash file.

Expanding information in the log file by adding crash logs. #475

**Comment by ameshkov** [comment]
In theory, this is not necessary because crash reports are already collected by Apple.

**Comment by Oleg-Chashko** [comment]
I understood you, I will delete the Topic: Expanding information in the log file by adding crash logs. #475
