### ISSUE TITLE
Hide AG browser menu

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdGuardForSafari#48]
1. in Safari tap on AG icon
2. Tap 'Block an element'

Expected behaviour: AG menu hides, Assistant menu opens

Actual behaviour: AG menu stays on the screen

https://uploads.adguard.com/Novosti__Meduza_2018-10-04_17-11-45.png

**Comment by Stillness-2** [comment]
I can't do this. Apol restriction.
