### ISSUE TITLE
Possibly not precision in UI code

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#480]
AdGuardForSafari v.1.8.10
When executing the combination cmd-a.
Please check.
**Example:**
<img width="1092" alt="Untitled" src="https://user-images.githubusercontent.com/62497891/101480170-9b916d00-3953-11eb-9bdf-c771e3887031.png">
<img width="1092" alt="Untitled 2" src="https://user-images.githubusercontent.com/62497891/101480191-a1874e00-3953-11eb-96f4-194607407215.png">

**Comment by tvinzz** [comment]
The active area of the link a bit increased for easy pointing.

**Comment by Oleg-Chashko** [comment]
> The active area of the link a bit increased for easy pointing.
@tvinzz 
Thank you for checking.
