### ISSUE TITLE
Add an option to disable user filter

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#481]
Well, as uBlock Origin, disabling user filter could be very useful to exclude user rules when there's a issue with a site.
An option in Filters tab could be a solution.

<img width="1122" alt="Schermata 2020-12-10 alle 01 24 52" src="https://user-images.githubusercontent.com/1375223/101705551-73a32600-3a87-11eb-8802-1ac64171c4bc.png">

uB0 example:
https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png

Thanks :)

**Comment by zzebrum** [comment]
It's already in the beta version btw

**Comment by tvinzz** [comment]
![image](https://user-images.githubusercontent.com/15062885/117986864-49a5a680-b33a-11eb-8042-bcb40da4d82d.png)
