### ISSUE TITLE
$jsinject doesn't disable JS rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdGuardForSafari#484]
### Issue Details

* **Version of AdGuard for Safari:**
  * v 1.8.10
* **Environment name and version:**
  * Safari 14.0.1 (16610.2.11.51.8)
* **Operating system and version:**
  * MacOS 11.0.1 (20B29)

### Steps to reproduce
1. Add these rules:
```
example.org#%#alert(1);
@@||example.org^$generichide
```
2. Go here - http://example.org

By the way, `$jsinject` doesn't disable JS rules, so I'm not sure if it's a bug or it just works this way in Safari extension.

### Expected Behavior
Alert box message should be displayed.

### Actual Behavior
JS rules are disabled by `$generichide` exception.

**Comment by Mizzick** [comment]
well `$generichide` works this way in Safari.
As about `$jsinject` it's a bug.

**Comment by AdamWr** [comment]
>well $generichide works this way in Safari.

So as I understand, there is no way to fix it unfortunately.

**Comment by Mizzick** [comment]
@AdamWr you are right, nonetheless `$jsinject` will be fixed in the next release.

**Comment by AdamWr** [comment]
Okay, thank you for your answer.
