### ISSUE TITLE
User CSS rules ineffective in 1.8.10 MacOS 10.13.6 Safai 13.1.2

### ISSUE THREAD

**Issue by Richard-Mlynarik** [AdguardTeam/AdGuardForSafari#485]
* **Version of AdGuard for Safari:**
  * 1.8.10
* **Environment name and version:**
  * Safari 13.1.2 (13609.3.5.1.5)
* **Operating system and version:**
  * macOS 10.13.6 (17G14042)
* **Filters you use in AdGuard:**
  * all
* **Any other browser extensions you have installed:**
  * none

### Expected Behavior

"User" CSS rules don't seem to work at all
Simple example:
||ebay.com##a[href*="ebay.com/deals"]

to apply to the first displayed line of https://ebay.com front page

Works in 1.7.2 (the last version of Adguard I can find a binary for that works.)
Does not work in 1.8.10

User site-blocking rules (eg "||googletagmanager.com") do seem to work

### Actual Behavior
User CSS rules not applied.  Unwanted junk is displayed.

### Screenshots

<details><summary>Screenshot:</summary>

![1 7 2 ok](https://user-images.githubusercontent.com/921288/102024241-c0b42000-3d45-11eb-93a8-ede5b25fb882.jpg)
![1 8 10 b0rked](https://user-images.githubusercontent.com/921288/102024243-c14cb680-3d45-11eb-8aa5-32b82833e8ec.jpg)

</details>

### Additional Information

Back to 1.7.2, yet again.

**Comment by ameshkov** [comment]
The rule is invalid, you shouldn't use pipe characters in the cosmetic rules.

Here's the proper rule:
`ebay.com##a[href*="ebay.com/deals"]`
