### ISSUE TITLE
Change the icon in "Filters" to an icon with a new design

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#492]
**Currently:**
<img width="964" alt="Screenshot Filters" src="https://user-images.githubusercontent.com/62497891/103181591-f9560c80-48a2-11eb-8f71-394fd8970563.png">
**For example:**
<img width="246" alt="Screenshot 2020-12-28 at 00 46 06" src="https://user-images.githubusercontent.com/62497891/103181877-7c2c9680-48a6-11eb-99b9-2334f00dc95c.png">

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

No need, the icon is in the correct colour palette according to the overall design guideline.

**Comment by Oleg-Chashko** [comment]
Hi @TheHasagi 
I meant the drawing doesn't match.
The checkmark design is different.
Next time, I will more precisely indicate where to fix it.

<img width="162" alt="Screenshot 2020-12-28 at 11 30 27" src="https://user-images.githubusercontent.com/62497891/103208465-fbe74f00-4900-11eb-950c-d822fff140fb.png">

<img width="109" alt="Screenshot 2020-12-28 at 11 29 24" src="https://user-images.githubusercontent.com/62497891/103208474-00ac0300-4901-11eb-981d-2927ad92ce59.png">

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

As I said before, the icon is matching to design guideline. Maybe in future versions, the icons will change, at the moment this is as it is.
