### ISSUE TITLE
Please fix extension icon blinking in pause mode

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#497]
When the page is refreshed, the extension icon blinks in pause mode.
The application switches from pause to working state, then back to pause, judging by the icon.
This blinking is a little annoying.
![Screen Recording 2020-12-28 at 17 44 11](https://user-images.githubusercontent.com/62497891/103230319-70d47c00-4935-11eb-93ef-d59e567054a7.gif)
[Screen Recording 2020-12-28 at 17.44.11.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5748125/Screen.Recording.2020-12-28.at.17.44.11.zip)

Also when switching between tabs.
![Screen Recording 2020-12-28 at 18 08 40](https://user-images.githubusercontent.com/62497891/103231497-2bfe1480-4938-11eb-91bb-6bfcc2d859d5.gif)
[Screen Recording 2020-12-28 at 18.08.40.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5748199/Screen.Recording.2020-12-28.at.18.08.40.zip)

**Required condition: pause is enabled for this site**
<img width="247" alt="Screenshot 2020-12-28 at 18 22 24" src="https://user-images.githubusercontent.com/62497891/103232137-f2c6a400-4939-11eb-8403-85767087396c.png">

**Comment by tvinzz** [comment]
https://user-images.githubusercontent.com/15062885/104209157-67bdd180-5442-11eb-91b2-95ac304c8035.mov

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Prerequisite: the application in the tray must be running. You do not have it running in the tray.

**Comment by tvinzz** [comment]
https://user-images.githubusercontent.com/15062885/104210700-3a722300-5444-11eb-8344-d43ae9ec2f4f.mov

**Comment by Oleg-Chashko** [comment]
@tvinzz 
The app should be running and the pages paused.

<img width="477" alt="Screenshot 2021-01-11 at 17 38 11" src="https://user-images.githubusercontent.com/62497891/104211005-d5aecc80-5433-11eb-822b-fe3d0637afa7.png">

**Comment by Oleg-Chashko** [comment]
https://user-images.githubusercontent.com/62497891/104213328-72726980-5436-11eb-9246-1db5d9dbf22b.mov

**Comment by Oleg-Chashko** [comment]
At the time of manual update, the icon also blinks. And also when you click on the application icon in the tray.

https://user-images.githubusercontent.com/62497891/104214527-d184ae00-5437-11eb-9b62-1558ef63a4d6.mov

**Comment by Oleg-Chashko** [comment]
Thanks, fixed in v1.9.3 Beta.
