### ISSUE TITLE
Please fix the color of the link (Adguard.com) in "About" on a dark theme

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#498]
Fix the color of the link (Adguard.com) in "About" on a dark theme. As it was done in the light theme of macOS.

<img width="1092" alt="Screenshot 2020-12-28 at 20 25 28" src="https://user-images.githubusercontent.com/62497891/103239214-23fc9f80-494d-11eb-80a9-4b355a174e58.png">

**For Example:**
<img width="1136" alt="Screenshot 2020-12-28 at 20 24 54" src="https://user-images.githubusercontent.com/62497891/103239189-15ae8380-494d-11eb-8071-e1c3f674adc5.png">

**Comment by TheHasagi** [comment]
The issue is solved and the fix will be available in the nearest update.
