### ISSUE TITLE
Please fix the color of the link (filter rules tutorial) in "User rules" on a dark theme

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#499]
Please fix the color of the link (filter rules tutorial) in "User rules" on a dark theme. As it was done in the light theme of macOS.
<img width="1136" alt="filter rules tutorial" src="https://user-images.githubusercontent.com/62497891/103245392-506de700-4960-11eb-9dca-a21b8a513202.png">
**For Example:**
<img width="1136" alt="User rules" src="https://user-images.githubusercontent.com/62497891/103245401-582d8b80-4960-11eb-85ed-ebabbd54f653.png">

**Comment by TheHasagi** [comment]
The issue is solved and the fix will be available in the nearest update.
