### ISSUE TITLE
Please fix the color of the link (our GitHub repo) in "General" on a dark theme

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#500]
Please fix the color of the link (our GitHub repo) in "General" on a dark theme. As it was done in the light theme of macOS.
<img width="1136" alt=" our GitHub repo" src="https://user-images.githubusercontent.com/62497891/103245963-1998d080-4962-11eb-81d0-34731143222e.png">
**For Example:**
<img width="1136" alt="General" src="https://user-images.githubusercontent.com/62497891/103245986-2c130a00-4962-11eb-9e1b-a5d812e60a63.png">

**Comment by TheHasagi** [comment]
The issue is solved and the fix will be available in the nearest update.
