### ISSUE TITLE
Please fix "About" it is desirable that the lines of text are on the same height

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#502]
AdGuard for Safari v1.9 beta
Please fix "About" it is desirable that the lines of text are on the same height.

<img width="1026" alt="Screenshot 2020-12-29 at 15 30 45" src="https://user-images.githubusercontent.com/62497891/103291989-30383980-49ed-11eb-9a32-fc852013e043.png">

**Comment by tvinzz** [comment]
This page was made according to the layout provided by our designer.
