### ISSUE TITLE
Please move the "Export logs" button a little to the left.

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#503]
Please move the "Export logs" button a little to the left.
AdGuard for Safari v1.9 beta

<img width="1232" alt="Screenshot 2020-12-29 at 17 16 39" src="https://user-images.githubusercontent.com/62497891/103298427-9bd4d380-49fa-11eb-8b90-165dd7d0dfc6.png">

**Comment by tvinzz** [comment]
it is exactly on the proper position where it has to be
![image](https://user-images.githubusercontent.com/15062885/104203802-99806980-543d-11eb-8cd6-4132b375dba1.png)

![image](https://user-images.githubusercontent.com/15062885/104204081-ee23e480-543d-11eb-868e-cc567c61312c.png)

**Comment by Oleg-Chashko** [comment]
@tvinzz 

AdGuard for Safari v1.9 beta
It's in beta now. Maybe you forgot you fixed that?

<img width="731" alt="Screenshot 2021-01-11 at 16 56 36" src="https://user-images.githubusercontent.com/62497891/104204979-24596800-542e-11eb-976d-4a17ac319ed4.png">

**Comment by Oleg-Chashko** [comment]
@tvinzz 
You forgot that you fixed it.
https://github.com/AdguardTeam/AdGuardForSafari/commit/c50d584c83418025a637e7682107d120bd9ad4c9

**Comment by tvinzz** [comment]
c50d584 - the button were moved for 10 pixels in this commit.
