### ISSUE TITLE
MacOS V1.9.0 Beta - No Apple Silicon Support

### ISSUE THREAD

**Issue by RobbieTT** [AdguardTeam/AdGuardForSafari#504]
Apple Silicon support moved to V1.9 milestone and issue closed.  However, V1.9.0 Beta has not been compiled as a Universal binary and there is no comment in the changeling regarding the planned inclusion or otherwise of native Apple Silicon support.

Request that macOS changelog is revised to make clear if a version is Intel-only or contains either a Universal or AS specific binary.

**Comment by ameshkov** [comment]
See #493 

For now, it only works with Rosetta. Until there's a clear way for Electron apps to build a Universal binary, it will be that way.

**Comment by RobbieTT** [comment]
Thank-you - it may help if this limitation is added to the V1.9 milestone and the Apple Silicon support is moved to an open issue again.

Good luck with Electron - I didn't know their AS support was lagging behind.
