### ISSUE TITLE
The file “purify.js.map” couldn’t be opened because there is no such file on every site

### ISSUE THREAD

**Issue by qiujiangkun** [AdguardTeam/AdGuardForSafari#510]
### Issue Details

* AdGuard for Safari version: Version 1.8.10
* Environment name and version: Version 14.0.2 (16610.3.7.1.9)
* Operating System: MacOS Big Sur 11.1 MacBook Air (M1, 2020)
* Filters you use in AdGuard: Only Ad Blocking
* Any other browser extensions you have installed:
LastPass, Grammarly

### Actual Behavior
Failed to load resource: The file “purify.js.map” couldn’t be opened because there is no such file.

### Screenshots
<img width="993" alt="image" src="https://user-images.githubusercontent.com/33482468/104877581-1c9d4480-5995-11eb-9944-3fe90b754f0a.png">

**Comment by tvinzz** [comment]
@qiujiangkun, we don't use purify.js in AdGuard for Safari, so it looks like this problem could be caused by LastPass or Grammarly

**Comment by qiujiangkun** [comment]
If I disable these two plugins, the problem remains. I'll double check it later on today











Sincerely,&nbsp;
Jack&nbsp;Quinn

---Original---
