### ISSUE TITLE
The rule doesn't work in AG for Safari and AG for iOS

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardForSafari#511]
The rule below (from annoyances) doesn't work in AG for Safari and AG for iOS.
`@@||adservice.google.*/adsid/integrator.js$~script,domain=muyhistoria.es|marie-claire.es|miarevista.es|muynegociosyeconomia.es|serpadres.es|muyinteresante.es`

But it exists in optimized filters and works from the user rules.

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/71388

Same here https://github.com/AdguardTeam/AdguardFilters/issues/71879 
with rule `@@||pakkotoisto.com/js/siropu/am/ads.min.js$domain=pakkotoisto.com`

And here https://github.com/AdguardTeam/AdguardFilters/issues/71234
`@@||aktuality.sk^$generichide`

[adg_safari_logs_1610993497550.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5831886/adg_safari_logs_1610993497550.zip)

**Comment by tvinzz** [comment]
these exception rules and rules to be excepted are compiled in different extensions, so need to add `affinity` derective
