### ISSUE TITLE
"Save" not translated to German in version 1.8.10 and earlier

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdGuardForSafari#512]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.8.10
* Environment name and version: Safari 14.0.2 (16610.3.7.1.9)
* Operating System: macOS Big Sur 11.1 (20C69)
* Filters you use in AdGuard: not relevant
* Any other browser extensions you have installed: not relevant

* **Version of AdGuard for Safari:**
  * 1.8.10
* **Environment name and version:**
  * Safari 14.0.2 (16610.3.7.1.9)
* **Operating system and version:**
  * macOS Big Sur 11.1 (20C69)
* **Filters you use in AdGuard:**
  * not relevant
* **Any other browser extensions you have installed:**
  * not relevant

### Expected Behavior
The button "Save" under "Positivliste" and "Benutzerregeln" should be called "Speichern"

### Actual Behavior
The button "Save" has not been translated to German.

### Screenshots

<details><summary>Screenshot:</summary>

![2021-01-21_07-58-59](https://user-images.githubusercontent.com/25068100/105315234-4df95880-5bbf-11eb-876a-07eb901431bc.jpg)

</details>

**Comment by el-termikael** [comment]
@sergerosenthaler Hi! Thank you for noticing. The button has already been translated, it's just that a new version hasn't been released yet. The translation will appear as soon as we relese it.
https://uploads.adguard.com/el.termikaeltv03h.png

**Comment by sergerosenthaler** [comment]
@el-termikael Thx Helen for the update.
