### ISSUE TITLE
The "X" button is poorly visible on the dark theme of macOS 

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#513]
### Screenshots
<img width="949" alt="Screen Shot 2021-01-26 at 20 45 37" src="https://user-images.githubusercontent.com/62497891/105897258-3cc5a700-6018-11eb-9d08-2945b5506880.png">

**Comment by tvinzz** [comment]
not actual
new ui is coming
