### ISSUE TITLE
Website: reports.adguard.com (version number AdGuard shifted to the right)

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#514]
https://reports.adguard.com/en/new_issue.html?product_type=Saf&product_version=%20%20%20%20%20%20%20%201.9.0&browser=Safari

### Screenshots
<img width="913" alt="Screen Shot reports adguard com" src="https://user-images.githubusercontent.com/62497891/105900856-e5760580-601c-11eb-8386-48535715bcd5.png">

<img width="885" alt="Screen Shot 2021-01-26 at 21 37 43" src="https://user-images.githubusercontent.com/62497891/105902342-cd9f8100-601e-11eb-934a-de116fba6888.png">

**Comment by tvinzz** [comment]
fixed already
