### ISSUE TITLE
Improvements and fixes (UI)  v.1.9.* beta

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#515]
### Fixed in v.1.9.5 Beta

Please move the "Pause AdGuard" line below as it is done on your sketch.
### Screenshots
- Presently
<img width="249" alt="Screen Shot 2021-02-03 at 18 42 25" src="https://user-images.githubusercontent.com/62497891/106787166-a87ac600-664f-11eb-9a9e-54fd2679b915.png">

- Your sketch 
<img width="428" alt="Screen Shot - (Ext sketch)" src="https://user-images.githubusercontent.com/62497891/105907845-bdd76b00-6025-11eb-85cf-793286e70228.png">

- I would like to
<img width="580" alt="Screen Shot 2021-01-26 at 22 13 11" src="https://user-images.githubusercontent.com/62497891/105907945-e3fd0b00-6025-11eb-94ca-4dced3e10043.png">

**Comment by Oleg-Chashko** [comment]
It is desirable that the extension window closes after clicking the "Report this website" button. In order not to interfere with browsing the website.

https://user-images.githubusercontent.com/62497891/106782917-0658df00-664b-11eb-856b-240741b8bbf5.mov

**Comment by Oleg-Chashko** [comment]
Please remove the extra line. 
<img width="1253" alt="Screen Shot 2021-02-03 at 18 29 05" src="https://user-images.githubusercontent.com/62497891/106786041-6309c900-664e-11eb-9e59-831a9447421d.png">

**Comment by Oleg-Chashko** [comment]
Sometimes it seems to me that this behavior should not be. :)

https://user-images.githubusercontent.com/62497891/106786590-00fd9380-664f-11eb-9f00-663348bb14b9.mov

**Comment by Oleg-Chashko** [comment]
In "Content blockers" please update the font in beta.

<img width="876" alt="Content blockers" src="https://user-images.githubusercontent.com/62497891/106793823-3eb2ea00-6658-11eb-9e16-0a7bb9de046b.png">

**Comment by Oleg-Chashko** [comment]
It is desirable that the user understands that this is his created (User) allowlist.
And it was seen that he allowed or forbade (doesn't). 

**Currently**
<img width="570" alt="Filters" src="https://user-images.githubusercontent.com/62497891/106797004-61470200-665c-11eb-9735-c1683f3188d7.png">

**Desirable** 
- User allowlist
<img width="570" alt="User allowlist" src="https://user-images.githubusercontent.com/62497891/106797136-863b7500-665c-11eb-9dec-f61ec92f5f73.png">

- User allowlist (Inverted)
<img width="570" alt="Filters User allowlist (Inverted)" src="https://user-images.githubusercontent.com/62497891/106797165-8fc4dd00-665c-11eb-9db3-d9dbae81c1b0.png">

**Comment by Oleg-Chashko** [comment]
I apologize for being off topic.
Many thanks to all those who took part in the interface rework. 
Thanks again to everyone.

**Comment by Oleg-Chashko** [comment]
Light theme macOS:
- Arrow not visible 
<img width="902" alt="Screen Shot 2021-02-04 at 14 14 49" src="https://user-images.githubusercontent.com/62497891/106898204-2ee8e380-66f4-11eb-8211-dceda23b01a5.png">

Dark theme macOS:
- Highlight the link in green
<img width="888" alt="Screen Shot 2021-02-04 at 14 17 30" src="https://user-images.githubusercontent.com/62497891/106898215-31e3d400-66f4-11eb-88aa-3a63a6a9c8b0.png">

**Comment by Oleg-Chashko** [comment]
- Arrows must be pressure sensitive 
<img width="925" alt="Screen Shot 2021-02-04 at 15 18 02" src="https://user-images.githubusercontent.com/62497891/106905541-ade21a00-66fc-11eb-970d-6b953bca2610.png">

**Comment by Oleg-Chashko** [comment]
In the "General" and "Filters" sections, the internal content moves upward when starting and switching sections.
And he will not remember his location.

https://user-images.githubusercontent.com/62497891/106930580-0245c380-6716-11eb-9be6-173340a183ba.mov

**Comment by Oleg-Chashko** [comment]
Suddenly again you want "reload-ico-green"

**Your icon** 
<img width="1130" alt="reload-ico-green" src="https://user-images.githubusercontent.com/62497891/106953210-65ddea00-6732-11eb-8c30-bd0245aa5df1.png">

I will try to offer you another icon, but I’m pretty sure you won’t take it into the application. 
![reload-ico-green 2](https://user-images.githubusercontent.com/62497891/106953651-e69ce600-6732-11eb-9d5b-15fdad25e42c.png)

[Sketch - reload-ico-green.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5928424/Sketch.-.reload-ico-green.zip)

[reload-ico-green.svg.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5928422/reload-ico-green.svg.zip)

**Comment by tvinzz** [comment]
> In "Content blockers" please update in beta the font, etc.

fixed

**Comment by Oleg-Chashko** [comment]
@tvinzz 
- Corrected your icon "reload-ico-green".
<img width="550" alt="reload-ico-green" src="https://user-images.githubusercontent.com/62497891/107012826-d10ed700-6799-11eb-91af-e22bad9db883.png">

Sketch and SVG
[reload-ico-green.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5931303/reload-ico-green.zip)
[reload-ico-green.svg.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5931305/reload-ico-green.svg.zip)

**Comment by Oleg-Chashko** [comment]
**Please put the words in bold. As you did in your filters.**

<img width="444" alt="Filters" src="https://user-images.githubusercontent.com/62497891/107115016-04b93200-686a-11eb-8a0b-a7ee64537a69.png">
<img width="420" alt="General" src="https://user-images.githubusercontent.com/62497891/107114877-72b12980-6869-11eb-97d4-a914892a299b.png">
<img width="420" alt="Support" src="https://user-images.githubusercontent.com/62497891/107114881-75ac1a00-6869-11eb-9d6a-f0cf281741cf.png">

**Comment by Oleg-Chashko** [comment]
Please expand the sensitivity zone to the right so that the arrows are also pressure sensitive.
<img width="925" alt="106905541-ade21a00-66fc-11eb-970d-6b953bca2610" src="https://user-images.githubusercontent.com/62497891/109030581-392f4980-76c4-11eb-8032-961482c1c5b3.png">

**Comment by Oleg-Chashko** [comment]
Please remove. In the "Filters" section, when scrolling to the very bottom, an extra horizontal line appears. 
It is clearly seen on the dark theme.

<img width="1253" alt="106786041-6309c900-664e-11eb-9e59-831a9447421d" src="https://user-images.githubusercontent.com/62497891/109032687-333a6800-76c6-11eb-8c98-2b8813719a1d.png">

**Comment by tvinzz** [comment]
@Oleg-Chashko, it's already fixed, will be available in next beta. coming soon
![image](https://user-images.githubusercontent.com/15062885/109033367-a26c8800-76d7-11eb-9412-72825dce4e5f.png)

**Comment by Oleg-Chashko** [comment]
Light theme macOS:

- Arrow not visible
<img width="929" alt="106898204-2ee8e380-66f4-11eb-8211-dceda23b01a5" src="https://user-images.githubusercontent.com/62497891/109033609-1ce0dc00-76c7-11eb-96e2-41244fbd4d12.png">

- Poorly visible rectangle
<img width="916" alt="106899394-981d2680-66f5-11eb-8515-cd9afd43860d" src="https://user-images.githubusercontent.com/62497891/109033627-223e2680-76c7-11eb-997f-73d4b3c35ec8.png">

**Comment by tvinzz** [comment]
@Oleg-Chashko, it has been fixed as well

**Comment by tvinzz** [comment]
> Please expand the sensitivity zone to the right so that the arrows are also pressure sensitive.
@Oleg-Chashko, fixed
![image](https://user-images.githubusercontent.com/15062885/109041833-84efec00-76e0-11eb-9f0e-8f697ac5fe3d.png)

**Comment by Oleg-Chashko** [comment]
In the "About" section, after downloading the update. The "Relaunch" button is moved one line below.
Please fix it, and also if you can highlight the button with some color so that it stands out from the general background.
- Presently
<img width="1367" alt="Presently" src="https://user-images.githubusercontent.com/62497891/109147322-291b7680-7765-11eb-8228-c08bdaefeea5.png">

- For example
<img width="1367" alt="For example" src="https://user-images.githubusercontent.com/62497891/109147360-3173b180-7765-11eb-8fec-ef17544ae80b.png">

**Comment by tvinzz** [comment]
> In the "About" section, after downloading the update. The "Relaunch" button is moved one line below.

already fixed

**Comment by Oleg-Chashko** [comment]
Tooltips are shifted to the left.
<img width="1072" alt="Screen Shot 2021-02-26 at 14 36 48" src="https://user-images.githubusercontent.com/62497891/109315847-43c81b00-784b-11eb-8214-23a52482e9ac.png">

**Comment by tvinzz** [comment]
@Oleg-Chashko, and this is fixed as well)

**Comment by Oleg-Chashko** [comment]
Bug with filters: after deleting a subscription. These filters remain in the "Content blockers" section. Don't tell me you've already fixed it. ;)

https://user-images.githubusercontent.com/62497891/109386213-81837d00-78f9-11eb-9d30-652cf7d25b1e.mov

P.S.: _@Oleg-Chashko, it's already fixed, will be available in next beta. coming soon_
If it's not a secret when the beta is coming soon. Hands itch. :)

**Comment by Oleg-Chashko** [comment]
- German language.
<img width="1091" alt="Bildschirmfoto 2021-02-27 um 20 20 11" src="https://user-images.githubusercontent.com/62497891/109397980-18702980-793a-11eb-93d2-7f3e41927a50.png">

**Comment by tvinzz** [comment]
updated german locales. other locales will be add from crowdin.

**Comment by Oleg-Chashko** [comment]
Sorry @tvinzz Oleg, for distracting you with nonsense. The word "Filters" is lowered slightly. If you can fix it. I just want everything to be beautiful without offense. Thank.

https://user-images.githubusercontent.com/62497891/109552935-b139ad00-7ad2-11eb-86a1-e2c7dd4d8e4e.mov

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Thank you, Oleg!
You fixed everything in the version 1.9.5 Beta.
Closed the topic.
