### ISSUE TITLE
I ask you to redo the animation and redraw the "Reload-ico"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#518]
@ameshkov 
Since you are creating a new app design. I ask you to redo the animation and redraw the "refresh-icon". This is a repeat request to Andrew Meshkov (@ameshkov). Please take "refresh-icon_AdGuard for iOS" as a basis for the example. Please understand me and my request. 

**For the example: Refresh-icon_AdGuard for iOS**
<img width="199" alt="refresh-icon-iOS" src="https://user-images.githubusercontent.com/62497891/106060761-c0ed5c80-60f4-11eb-82cc-8836764fda49.png">

**Reload-ico_AdGuard for Safari**
<img width="211" alt="(reload-ico)" src="https://user-images.githubusercontent.com/62497891/106060850-e4180c00-60f4-11eb-920f-f1e70bac1b7f.png">
<img width="211" alt="(reload-ico-green)" src="https://user-images.githubusercontent.com/62497891/106060857-e5e1cf80-60f4-11eb-97bb-273661d762cf.png">

**Animation - Reload-ico_AdGuard for Safari**

https://user-images.githubusercontent.com/62497891/106061168-4f61de00-60f5-11eb-8d82-309edbe54c7c.mov

**Comment by tvinzz** [comment]
@Oleg-Chashko
Actually it will be not completely new design of app, just UI refreshing. This icon will be replaced by text link.
Also I kindly ask you to don't duplicate similar issues, like "move something one pixel left or right". Please collect all your UI feature requests in a list of one issue to avoid mash.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko
> Actually it will be not completely new design of app, just UI refreshing. This icon will be replaced by text link.
> Also I kindly ask you to don't duplicate similar issues, like "move something one pixel left or right". Please collect all your UI feature requests in a list in one issue to avoid mash.

@tvinzz 
Got it, Thank you, I will do as you asked, so that it is convenient for you to work.

**Comment by tvinzz** [comment]
@Oleg-Chashko, thank you
