### ISSUE TITLE
After the application is closed completely, the extension icon remains visually enabled

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#522]
After the application is closed completely, the extension icon remains visually enabled.
A specific sequence is required for repetition. 
Watch the video: 

https://user-images.githubusercontent.com/62497891/106196377-a3ca9380-61b1-11eb-90d5-3e740b9c9a2a.mov

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

This is not a bug, if you click on the icon again it will show the actual status.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko
> 
> This is not a bug, if you click on the icon again it will show the actual status.

Спасибо, я это знаю :)

**Comment by Oleg-Chashko** [comment]
@TheHasagi 
_This is not a bug, if you click on the icon again it will show the actual status._

Please see the sequel. 

https://user-images.githubusercontent.com/62497891/106528404-017c1a00-64e9-11eb-8a38-7841d25422d0.mov
