### ISSUE TITLE
Disconnect's json lists fail to load as custom filters

### ISSUE THREAD

**Issue by drewthor** [AdguardTeam/AdGuardForSafari#523]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) 
* Operating System: (e.g macOS High Sierra 10.13.6) 
* Filters you use in AdGuard: 
* Any other browser extensions you have installed: 

* **Version of AdGuard for Safari:**
  *  1.8.10
* **Environment name and version:**
  *  Safari 14.0.2 (16610.3.7.1.9)
* **Operating system and version:**
  *  macOS Big Sur 11.1
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior

Adding the 2 Disconnect filter lists or Privacy Badger's list as custom filters I would expect that Adguard for Safari loads them so I can subscribe to them. (Note this does work on the iOS version of Adguard as expected).
- https://raw.githubusercontent.com/disconnectme/disconnect-tracking-protection/master/entities.json
- https://raw.githubusercontent.com/disconnectme/disconnect-tracking-protection/master/services.json
- https://raw.githubusercontent.com/EFForg/badger-sett/master/results.json

### Actual Behavior

Trying to add these two lists as custom filters fails and reports back the following error:
"Error occurred
Unfortunately, your custom filter cannot be added due to an unexpected error."

### Screenshots

<details><summary>Screenshot:</summary>

<img width="1136" alt="Screen Shot 2021-01-31 at 1 35 01 PM" src="https://user-images.githubusercontent.com/9273455/106395705-4577fd80-63c9-11eb-960c-e536c299b98e.png">

</details>

### Additional Information

As mentioned above I do believe this an issue with this version of Adguard specifically as I do not see the issue when adding these custom filters via iOS

**Comment by ameshkov** [comment]
We don't support JSON lists, you should look for plain-text versions of these lists.
