### ISSUE TITLE
Add warning when selecting "Update interval - Do not update"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#527]
Add warning when selecting "Update interval - Do not update"
- For example
<img width="900" alt="Update interval - Do not update" src="https://user-images.githubusercontent.com/62497891/107115901-13a2e300-6870-11eb-9cd4-4b1588f38a32.png">

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Oleg, please pay attention to the behavior of the warning window.

**1. Screen behavior**

https://user-images.githubusercontent.com/62497891/110811005-99a6b500-8286-11eb-962a-0c0a9add3575.mp4

------------------------------------------------------------------------------------------------------------------
**2. Screen behavior**
![Screen 2](https://user-images.githubusercontent.com/62497891/110811153-b9d67400-8286-11eb-8c22-c69721af68b8.gif)


https://user-images.githubusercontent.com/62497891/110811096-acb98500-8286-11eb-82e0-b314d68e6d7b.mp4

**Comment by Oleg-Chashko** [comment]
- Old warnings should not be deleted when new warnings appear.

![ScreenFlow](https://user-images.githubusercontent.com/62497891/111479133-fac00400-8730-11eb-9680-839db7e58e0a.gif)

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Oleg, I'm sorry to distract you. 
Were you able to fix the behavior of the application? 
Do you know when the beta version will be released?

**Comment by tvinzz** [comment]
@Oleg-Chashko, new beta is coming tomorrow,
but unfortunately this issue will be fixed completely only in v1.10

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko, new beta is coming tomorrow,
> but unfortunately this issue will be fixed completely only in v1.10

@tvinzz, 
thank you bro.
