### ISSUE TITLE
AdGuard For Safari (Not Responding) v.1.9.3 beta

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#532]
<img width="1009" alt="Screen Shot 2021-02-08 at 12 11 22" src="https://user-images.githubusercontent.com/62497891/107213609-fce3c400-6a08-11eb-807b-e511f1159178.png">
<img width="965" alt="Screen Shot 2021-02-08 at 12 10 57" src="https://user-images.githubusercontent.com/62497891/107213619-040ad200-6a09-11eb-8156-7ebe9a0de0c9.png">

[AdGuard for Safari_2021-02-08-122309_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5943348/AdGuard.for.Safari_2021-02-08-122309_MacBook-Pro.crash.zip)

[adg_safari_logs_1612783431945.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5943349/adg_safari_logs_1612783431945.zip)

[Sample of AdGuard for Safari.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5943351/Sample.of.AdGuard.for.Safari.zip)

[Spindump.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5943352/Spindump.zip)

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

Hello, can you provide the steps to reproduce?

**Comment by Oleg-Chashko** [comment]
@TheHasagi 
_Can you provide the steps to reproduce?_

Hello, 
Unfortunately, no, since I did not use safari at the wrong time. And I noticed that the application does not work, only when I hovered over it. I took off the logs, I thought it would help you.

 I have one question and one request for you.

1. Give or write an application that will write a log from A to Z. So that you can see everything what is happening with the application. And in case of a problem, I will send it to you.
2. If it's not difficult for you, change the icon, I fixed it.
https://github.com/AdguardTeam/AdGuardForSafari/issues/515#issuecomment-773901142

Thank you for understanding.

**Comment by Oleg-Chashko** [comment]
@TheHasagi 

The memory leak grows to 2GB, then AdGuard For Safari (Not Responding) and, as a result, Crash. Need to spam: 

![Screen Recording 2021-02-09 at 16 58 44](https://user-images.githubusercontent.com/62497891/107392298-d0f43b80-6af9-11eb-9c26-35e5a943ac30.gif)

[AdGuard for Safari_2021-02-09-165617_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5952606/AdGuard.for.Safari_2021-02-09-165617_MacBook-Pro.crash.zip)

**Comment by Oleg-Chashko** [comment]
@TheHasagi, @Mizzick

I compared two logs and I think I found how to reproduce the crash from the topic: 
Possible Memory Leak #505
https://github.com/AdguardTeam/AdGuardForSafari/issues/532#issuecomment-776059371

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

Thank you for the logs, I'll try to figure out with the memory leak regarding your comments.

**Comment by Oleg-Chashko** [comment]
@TheHasagi,  @Mizzick

Here's another way to cause a leak and crash.
Law: "Everything which is not forbidden is allowed"
If you connect a large number of filters, more than 2GB of memory also leaks, followed by a crash. 

[adg_safari_logs_1612961641832.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5958274/adg_safari_logs_1612961641832.zip)
[AdGuard for Safari_2021-02-10-134428_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5958262/AdGuard.for.Safari_2021-02-10-134428_MacBook-Pro.crash.zip)

**Comment by Oleg-Chashko** [comment]
@TheHasagi, @Mizzick

After removing filters, memory consumption does not decrease, but should. Only restarting the application helps.
<img width="1031" alt="Screen Shot 2021-02-10 at 14 25 19" src="https://user-images.githubusercontent.com/62497891/107515968-08bbbb80-6bac-11eb-9f8b-fa3c18d6b77f.png">

**Comment by tvinzz** [comment]
duplicates https://github.com/AdguardTeam/AdGuardForSafari/issues/505

**Comment by Oleg-Chashko** [comment]
> duplicates #505

@tvinzz 
Oleg, this is not a duplicate.
