### ISSUE TITLE
User rules doesn't work

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#534]
@tulik commented on [Sat Feb 13 2021](https://github.com/AdguardTeam/AdguardFilters/issues/74811)

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
When selecting a site element to block the element is visible after reloading the page.

* **Expected behavior**: 
When selecting a site element to block it shouldn't be visible after reloading the page. (The user filter is created but it doesn't apply).

***Steps to reproduce the problem***:

[//]: #

- Go to any Website
- Click Block Element from the Safari AdGuard menu
- Select Site element to block
- Confirm blocking the element
- See the element disappears
- Reload page see element is not blocked
- See the user rule was created, but seems to be ignored

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | MacOS
Operating system version (Android/iOS) | 11.3 Beta (20E5172i)
Browser:                               | Safari Version 14.1 (16611.1.10.1.5)
AdGuard version:                       | 2.5.1.928 release (CL-1.7.150
Filters enabled:                       | Default
AdGuard DNS:                           | Default

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@tulik

**Comment by Chinaski1** [comment]
Hello @tulik!

It looks like you're blocking the element generated by the dynamic link, so the ads reappear after refreshing the page.

Could you please specify on which site you are checking this situation?

**Comment by tulik** [comment]
Please see the recording here:  https://www.icloud.com/iclouddrive/0O-QIaRHpNBZ7G8T7Oh9rbcTg#AdGuardScreenRecord

**Comment by Oleg-Chashko** [comment]
@tulik @Alex-302 

**AdGuardForSafar**i v.1.9.3beta
Blocks "AdGuard for Safari" without problems.

https://user-images.githubusercontent.com/62497891/107961737-99c4d500-6fa6-11eb-9bc2-5a700ed85394.mov

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/AdguardForMac #834](https://github.com/AdguardTeam/AdguardForMac/issues/834) via [**ZenHub**](https://www.zenhub.com/)
