### ISSUE TITLE
Application behavior when clicking on the "About" buttons

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#548]
Hi @TheHasagi, @ameshkov  

Is it possible to improve the behavior of the "About" button. 
To go straight to the "About" tab instead of switching from the "General" tab?

https://user-images.githubusercontent.com/62497891/110921535-f05fcd80-831e-11eb-9008-bc68fe1a53d9.mp4

**Comment by ameshkov** [comment]
Surprisingly, not an easy thing to do at all with the way UI is currently working.

**Comment by Oleg-Chashko** [comment]
> Surprisingly, not an easy thing to do at all with the way UI is currently working.

@ameshkov 
Thanks for the answer, if it is very difficult to do, then delete the topic. Thank you.
