### ISSUE TITLE
The question arose why the sums in the information on the number of rules do not match

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#553]
@ameshkov 
Andrey, sorry to distract you, I am addressing you because you are more talkative than your colleagues. Explain to me, please: why the sums in the information on the number of rules do not match. If they should be the same, please create an "Issue" with this problem. If everything is ok, please delete this topic. Thank you for understanding.
<img width="1350" alt="Bildschirmfoto 2021-03-18 um 13 16 19" src="https://user-images.githubusercontent.com/62497891/111630402-9f564a80-87f2-11eb-84d7-f43bbfaad54d.png">

**Comment by tvinzz** [comment]
They shouldn't match because on Filters tab it is the number of rules in enabled filters, but in Content blockers tab is the number after conversion.

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Oleg, thanks for the answer.
