### ISSUE TITLE
Using "Import settings" causes "Spinning Beach Ball of Death" and freezes

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#556]
Using "Import settings" causes "Spinning Beach Ball of Death" and the application freezes for about 3-5 seconds.

![ScreenFlow](https://user-images.githubusercontent.com/62497891/111784535-ccbafb00-88bb-11eb-8ef7-db711701c63a.gif)

**Comment by zzebrum** [comment]
it should be fixed along with #545
