### ISSUE TITLE
build failure 

### ISSUE THREAD

**Issue by sgulls** [AdguardTeam/AdGuardForSafari#557]
~~build failure using the build.sh script for beta, release, and mas. it seems to be failing at the `xcodebuild -workspace Adguard.xcworkspace -scheme AdGuard archive` step of `build.sh` and within the Xcode step, the `Scripts/build-electron-app.sh` script~~

~~The following build commands failed:~~
	~~ExternalBuildToolExecution BuildElectronApp~~

~~I have a paid dev account and I've edited all the config files to match my team and signing certificates~~

an Xcode reinstall was all I needed for the above.

Now when I run `./build.sh release` it will build fine but the script output says `** ARCHIVE FAILED **`

[log.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/6186979/log.txt)

**Comment by ameshkov** [comment]
Well, the log still states that `Command ExternalBuildToolExecution emitted errors but did not return a nonzero exit code to indicate failure`
