### ISSUE TITLE
The app is infinitely mode check for updates, when internet access is disabled

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#559]
- At the moment, Wi-Fi is off and there is no internet access.

![ScreenFlow](https://user-images.githubusercontent.com/62497891/112210247-be057880-8c1a-11eb-8ab4-fec171b20344.gif)

**Comment by TheHasagi** [comment]
Thank you, good catch.

**Comment by Oleg-Chashko** [comment]
> Thank you, good catch.

I was glad to help you.
