### ISSUE TITLE
Question: why did you make the inscription "You are using the latest version of AdGuard" clickable?

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#560]
Question: why did you make the inscription "You are using the latest version of AdGuard" clickable, if this does not lead to some action of the application?
It seems to me that this should not be so, and is this a mistake?

![ScreenFlow](https://user-images.githubusercontent.com/62497891/112296055-cf8b6680-8c94-11eb-8db4-022b6c764351.gif)

**Comment by tvinzz** [comment]
fixed
