### ISSUE TITLE
Adguard General with xinggsf language-specific blocks loading of YouTube

### ISSUE THREAD

**Issue by HenkPoley** [AdguardTeam/AdGuardForSafari#565]
**Edit**: I've drilled it down to the _xinggsf_ blocklist. I guess I need to contact them (and/or just disable it)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard for Safari:**
  * 1.8.10 macOS
* **Environment name and version:**
  * Safari 14.0.3 (16610.4.3.1.7)
* **Operating system and version:**
  * Big Sur 11.2.3
* **Filters you use in AdGuard:**
  * Check all the boxes in Safari Extensions tab
* **Any other browser extensions you have installed:**
  * There are others, but if I disable them they problem with Adguard General remains

### Expected Behavior

When you load the [Constant Geekery YouTube page](https://www.youtube.com/channel/UCnMf3jl6DDzvPrm5RToktuA) there should be links to the videos, e.g. more than just a top bar. 

### Actual Behavior

When Adguard General is enabled, none of the links to the videos on YouTube load.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by TheHasagi** [comment]
@HenkPoley 

Hello, any updates?

**Comment by HenkPoley** [comment]
Just tried to enable that ruleset again. It seems to have been resolved 🤷‍♂️

But it is not always very clear when the updates are pushed to the Safari side. So it might be that the problem pops up once it finally syncs or something.
