### ISSUE TITLE
"A JavaScript error occurred in the main process" v.1.9.11 Beta

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#567]
I wanted to open "About the application".

[adg_safari_logs_1617220396646.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/6239105/adg_safari_logs_1617220396646.zip)

![ScreenFlow](https://user-images.githubusercontent.com/62497891/113202624-40b9b380-926b-11eb-9593-68705de31a2c.gif)

**Comment by vozersky** [comment]
obsolete issue
