### ISSUE TITLE
"Invert Allowlist" does not work in (v.1.9.11 beta)

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#568]
"Invert Allowlist behavior is the same as that of "Allowlist". At the moment it turns out 2 "Allowlist". And you can switch between them with the toggle switch (Invert Allowlist: Unblock ads everywhere except for the websites from the Allowlist).

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

Did not get you right. Allowlist and its invert option work just fine. Can you explain in more details and steps?

**Comment by Oleg-Chashko** [comment]
Hi @TheHasagi 
Written near the toggle switch.
<img width="492" alt="Bildschirmfoto 2021-04-02 um 10 34 14" src="https://user-images.githubusercontent.com/62497891/113398816-79f34000-939f-11eb-811e-a243cc3a80db.png">

Accordingly, when this function is enabled with an empty white list, the advertisement must be displayed on all sites and the icon must go into pause mode on all sites except the white list.
<img width="624" alt="Bildschirmfoto 2021-04-02 um 10 19 26" src="https://user-images.githubusercontent.com/62497891/113399373-698f9500-93a0-11eb-997e-ee2208d7fd9e.png">

At the moment, the icon is on and ads are removed everywhere.
<img width="1683" alt="Bildschirmfoto 2021-04-02 um 10 17 39" src="https://user-images.githubusercontent.com/62497891/113399528-a3609b80-93a0-11eb-8896-59bbd5537668.png">

**Comment by tvinzz** [comment]
so, it's not a `"Invert Allowlist" does not work` as you wrote, but just a problem with indication (toolbar icon) for inverted allowlist, right?

**Comment by Oleg-Chashko** [comment]
> so, it's not a `"Invert Allowlist" does not work` as you wrote, but just a problem with indication (toolbar icon) for inverted allowlist, right?

I will say this: either the description of the function is incorrect or its behavior is incorrect. Or the word "inverted" doesn't fit here. I don’t know what was the intention of the creator of this function. As I understand it, I have already described.

**Comment by Oleg-Chashko** [comment]
> so, it's not a `"Invert Allowlist" does not work` as you wrote, but just a problem with indication (toolbar icon) for inverted allowlist, right?

In all likelihood, yes. At the same time, ads should not be blocked if the list is empty, and if there are sites in the list, then ads should be blocked for them. (This is the meaning of the word "Inverted" for me).

I will say this: either the description of the function is incorrect or its behavior is incorrect. Or the word "invert" doesn't fit here. I don’t know what was the intention of the creator of this function. As I understand it, I have already described.

**Comment by Oleg-Chashko** [comment]
I checked v.1.9.13 beta and everything is "OK" in the application. But you forgot to do the **inversion** in the app display!
<img width="291" alt="Bildschirmfoto 2021-04-06 um 16 12 13" src="https://user-images.githubusercontent.com/62497891/113725355-8525d300-96f3-11eb-957c-a1831fa39cfa.png">

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

The assistant issue is known and will be fixed with the major update.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko
> 
> The assistant issue is known and will be fixed with a major update.

@TheHasagi 

Create an "issue" so you don't forget to fix it?
If not, in which beta should the fix be expected?
Thanks for the answer.
