### ISSUE TITLE
In Russian localization, the problem with the update sign (v.1.9.11 beta)

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#569]
In Russian localization, when updating filters, the update icon is shifted to the search bar.
It is possible that the same problem occurs in other localizations.

![ScreenFlow](https://user-images.githubusercontent.com/62497891/113412318-38bb5a00-93b8-11eb-9e45-9cabd95f6d55.gif)

--------------------------------------------------------------------------------------------------------------------
I recommend shrinking the search bar.
Example:
<img width="1031" alt="Bildschirmfoto 2021-04-03 um 14 46 53" src="https://user-images.githubusercontent.com/62497891/113479355-eac55580-948e-11eb-8d07-f669965417a2.png">

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

This is a known issue and will be fixed with the nearest update.
