### ISSUE TITLE
Groups enabled by default

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#57]
When the app is started the first time, we should enable the following filters groups by default:

1. Ad Blocking
2. Privacy
3. Language-specific
4. Other

"Allow search ads and the self-promotion of websites" must be **disabled** by default.
"AdGuard Safari filter" must be enabled despite it's not in the "recommended" list.

**Also, fix the language-specific logic, you should use all languages from `navigator.languages`, not just the first one**.

**Comment by ameshkov** [comment]
Default filters logic.

1. If the filter has a `recommended` tag, go to 2.
2. Check all `lang` tags. If the filter does not have `lang` tags, go to 3. If it does, compare them with every language `navigator.languages`. If there's a match, go to 3.
3. Check if the filter has the `mobile` tag. If it does not, go to 4. If it does, check if this is a mobile device.
4. The filter must be enabled by default.

`AdGuard Safari filter` is an exemption of this rule and must be enabled by default anyway.

**Comment by zebrum** [comment]
Language filter (rus in my case) has not been installed. 
Social widget and Annoyances group should not be enabled.
