### ISSUE TITLE
The rule doesn't work

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardForSafari#573]
`mail.yandex.by,mail.yandex.com,mail.yandex.com.tr,mail.yandex.fr,mail.yandex.kz,mail.yandex.ru,mail.yandex.ua##.direct 
` doesn't work in AG for Safari and for iOS (https://github.com/AdguardTeam/AdguardForiOS/issues/1745)

<details>
<summary>Screenshots</summary>
<img src="https://user-images.githubusercontent.com/18536328/113704223-87346580-96e4-11eb-81c3-8efacef97791.png" />
<img src="https://user-images.githubusercontent.com/18536328/113704315-a4693400-96e4-11eb-8542-42e4dd2741c1.png" />
<img src="https://user-images.githubusercontent.com/18536328/113704353-b1862300-96e4-11eb-8881-4c1e6596dcbc.png" />
</details>

**Comment by TheHasagi** [comment]
Fixed in 1.9.17 Beta.
