### ISSUE TITLE
Can't open sites on Safari because of their Manage Cookies requirement

### ISSUE THREAD

**Issue by morrig47** [AdguardTeam/AdGuardForSafari#574]
First of all apologies if this is not the right site to ask this question. 

Increasingly I am unable to open sites on Safari because the site requires me to Manage Cookies. I cannot access the area to click OK. Either the screen goes blank or darkens and the box to tick my acceptance of cookies is unavailable. The only way to counter this is to add the sites to my allow list. The problem is the number of sites which have this issue is growing and I find myself continually adding to the allow list. Is there an alternative?

Many thanks

**Comment by TheHasagi** [comment]
@morrig47 

Hello, it looks like a filters issue, more about annoyances. Can you provide some example of websites so I can investigate further?

**Comment by morrig47** [comment]
Hi Alexander

Many thanks for getting back to me so quickly - very much appreciated.

Here are some examples

https://www.cardiff.gov.uk/ <https://www.cardiff.gov.uk/>

https://www.moonpig.com/uk/ <https://www.moonpig.com/uk/>

https://www.canon.co.uk/support/consumer_products/products/fax__multifunctionals/inkjet/pixma_mg_series/pixma_mg3150.html?type=drivers&driverdetailid=tcm:14-1121819&os=macos%2010.13%20%28high%20sierra%29&language=en <https://www.canon.co.uk/support/consumer_products/products/fax__multifunctionals/inkjet/pixma_mg_series/pixma_mg3150.html?type=drivers&driverdetailid=tcm:14-1121819&os=macos%2010.13%20(high%20sierra)&language=en>

I found a work-around this morning which may bear out your comment. Under Annoyances I deselected the filter and now I have no issue with these websites. Is that my long-term solution do you think? If yes, is there any downside to this option?

Gareth 
Gareth Morris
***@***.***

**Comment by TheHasagi** [comment]
@morrig47 

Seems like it's a filters issue, annoyances are just not yet removed. I'll transfer this issue to the filter devs so they can handle those websites. Disabling filters may cause ads to leak so it's definitely not recommended.

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/AdguardFilters #79683](https://github.com/AdguardTeam/AdguardFilters/issues/79683) via [**ZenHub**](https://www.zenhub.com/)
