### ISSUE TITLE
The extension incorrectly displays the status in the "Invert Allowlist" mode

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#576]
The extension in the browser incorrectly displays the status in the "Invert Allowlist" mode.
<img width="371" alt="113725355-8525d300-96f3-11eb-957c-a1831fa39cfa" src="https://user-images.githubusercontent.com/62497891/114416022-88680580-9bb0-11eb-958f-596b5e65bca4.png">

**P.S.:**
Didn't wait for your answer and created an "issue". In order not to keep this "issue" in my head.
Please don't delete the "issue" until it's fixed.
I always double-check how well my created "issues" have been fixed. 
Thank you for understanding.

**Comment by 10Meisterbaelle** [comment]
Also, if you toggle it off, it will still display ads.
