### ISSUE TITLE
The "Проверить обновления" link-button is cut off in the middle

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#577]
In Russian localization, the "Проверить обновления" link is cut off in the middle.

- Russian localization: Not OK
<img width="612" alt="Rus Not OK" src="https://user-images.githubusercontent.com/62497891/114426087-fd8c0880-9bb9-11eb-8250-83dc7e50dbf5.png">

- Other localizations: OK
<img width="612" alt="De OK" src="https://user-images.githubusercontent.com/62497891/114426104-0250bc80-9bba-11eb-8f82-b62f9858a3bb.png">

- Example:
<img width="1020" alt="OK" src="https://user-images.githubusercontent.com/62497891/114426125-08469d80-9bba-11eb-9b8d-a96e75791a8a.png">

P.S.:
Please guys do it right. In all localizations, it is advisable to adhere to a single style.
Just reduce the size of the search field and this problem will go away in all localizations.
I think it is not difficult for you to do this. 
Moreover, the size of the search field is very large at the moment.

**Comment by vozersky** [comment]
@Oleg-Chashko 

Oleg, hello, I don't know your email, so could you please contact me?  vo@adguard.com

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko
> 
> Oleg, hello, I don't know your email, so could you please contact me? [vo@adguard.com](mailto:vo@adguard.com)

@vozersky 

Vladimir, hello, my e-mail address, I sent you by e-mail.
