### ISSUE TITLE
AdGuard 1.9.13 missing German translations and back button in filter section

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdGuardForSafari#581]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 1.9.13
* **Environment name and version:**
  * Safari 14.0.3 (16610.4.3.1.7)
* **Operating system and version:**
  * macOS BigSur 11.2.3 (20D91)
* **Filters you use in AdGuard:**
  * AdGuard Base Filter, AdGuard Tracking protection, AdGuard German Filter, Show useful Ads
* **Any other browser extensions you have installed:**
  * Dashlane for Safari

### Expected Behavior
Everything should be translated to German and in the filter area a back button should always be visible.
Missing German translations are:
Check for updates
German translation:
"Auf Updates prüfen" or "Auf Aktualisierungen prüfen"

Read more about this product
German translation:
"Mehr über dieses Produkt lesen"

Discuss
Discuss on our forum, in....
German Translation: 
"Diskutieren 
Diskutieren Sie in unserem Forum, in sozialen Netzwerken oder auf GitHub"

### Actual Behavior
Some German translations are missing. In the filter section sometimes when you select a filter a back button is visible, sometimes not.

### Screenshots

<details><summary>Screenshot:</summary>

![2021-04-13_10-39-47](https://user-images.githubusercontent.com/25068100/114524908-eabf1580-9c45-11eb-9a44-2b5a7352dca6.jpg)

![2021-04-13_10-35-31](https://user-images.githubusercontent.com/25068100/114524707-bba8a400-9c45-11eb-9dfb-cfc263b0448d.jpg)

![2021-04-13_10-28-24](https://user-images.githubusercontent.com/25068100/114524775-c8c59300-9c45-11eb-9284-a41719208dc3.jpg)

![2021-04-13_10-28-07](https://user-images.githubusercontent.com/25068100/114524797-cf540a80-9c45-11eb-9445-911f51082eeb.jpg)

![2021-04-13_10-27-50](https://user-images.githubusercontent.com/25068100/114524809-d2e79180-9c45-11eb-86da-89346ca83344.jpg)

</details>

**Comment by el-termikael** [comment]
@sergerosenthaler Hello,
Thank you for noticing. We'll add the missing German translations in the coming v1.10.

**Comment by sergerosenthaler** [comment]
@el-termikael Hello Helen, but don't forget the second bug too (missing back arrow in the filters section).

**Comment by Oleg-Chashko** [comment]
@sergerosenthaler 
_but don't forget the second bug too (missing back arrow in the filters section)._

Hello Serge, everything is in place, scroll down the page and see.
This issue is related, "Issue #562"

![ScreenFlow](https://user-images.githubusercontent.com/62497891/114554369-f40caa00-9c66-11eb-8707-8f576c3ca8f6.gif)

**Comment by sergerosenthaler** [comment]
@el-termikael Not fixed in latest 1.9.19 release and not assigned to the 1.10 milestone. When will this get fixed?

**Comment by el-termikael** [comment]
@sergerosenthaler Hello,
We fixed this task: https://github.com/AdguardTeam/AdGuardForSafari/issues/588. Our testers can't repeat the bug with a missing back arrow that you reported, looks like the issue is already fixed.
As for German translations, we will definitely add them in the coming update (v1.10).
