### ISSUE TITLE
Adguard 1.9.13 doesn't work on YouTube

### ISSUE THREAD

**Issue by JeroenSwets** [AdguardTeam/AdGuardForSafari#583]
### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) 
* Operating System: (e.g macOS High Sierra 10.13.6) 
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 1.9.13
* **Environment name and version:**
  * Safari 14.0.3 (16610.4.3.1.7)
* **Operating system and version:**
  * macOS Big Sur 11.2.3
* **Filters you use in AdGuard:**
  * Base, Allowlist, Privacy
* **Any other browser extensions you have installed:**
  * Reeder

### Expected Behavior
Skip over YouTube ads during playback

### Actual Behavior
Playback stops, YouTube displays an error message "There has been an error. Please try again later."

### Screenshots

<details><summary>Screenshot:</summary>
<img width="1339" alt="Schermafbeelding 2021-04-14 om 17 02 44" src="https://user-images.githubusercontent.com/4659516/114733139-6488f900-9d43-11eb-9c92-46c84ac076ff.png">

</details>

**Comment by TheHasagi** [comment]
@JeroenSwets 

Hello, as I can see you enable Allowlist, can you check once again without it?

**Comment by JeroenSwets** [comment]
Tried disabling the Allowlist, didn't matter. But I noticed that I didn't have any issues when I was connected to the business VPN. So trashed cookies in YouTube and that seems to solve it.

Sorry!
