### ISSUE TITLE
Incorrect behavior underlining a word in the user list [dark theme]

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#585]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.9.13
* Environment name and version: Safari 14.0.3
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: default
* Any other browser extensions you have installed: none

### Expected Behavior
Using dark theme, when you underline a word in the user list, if the same word is already present it becomes highlighted or underlined.

### Actual Behavior
Using dark theme, when you underline a word in the user list, if the same word is already present it becomes unreadable.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="669" alt="hjgj" src="https://user-images.githubusercontent.com/1375223/115019148-1269e400-9eb9-11eb-9b99-9d7b383138a6.png">

</details>

**Comment by Oleg-Chashko** [comment]
And also "Allowlist".

Screenshot:
<img width="533" alt="Bildschirmfoto 2021-04-16 um 13 46 13" src="https://user-images.githubusercontent.com/62497891/115020949-9de47480-9ebb-11eb-9506-db2a5f24d8be.png">
