### ISSUE TITLE
Filters don't update automatically

### ISSUE THREAD

**Issue by odysseus90210** [AdguardTeam/AdGuardForSafari#586]
### Issue Details

* AdGuard for Safari version: 1.9.13
* Environment name and version: 14.1 (16611.1.21.161.3)
* Operating System: Mac OS Big Sur 11.3
* Filters you use in AdGuard: all except custom
* Any other browser extensions you have installed:
DEVONThink, Instapaper, 1Password

### Expected Behavior
I have set the update interval for Adguard to 6 hours. 

### Actual Behavior
However, *every* time I manually check for updates, there are updates. If AG were updating its filters 4 times a day, would this happen every time?

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by vozersky** [comment]
"However, every time I manually check for updates, there are updates. If AG were updating its filters 4 times a day, would this happen every time?"

Yeah, it would, filter rules are constantly being added every day
