### ISSUE TITLE
Errors during Clean install and update app v.1.9.14 Beta

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#596]
It is best to install on a clean system, universal v.1.9.14 Beta.

If possible:
you need a script that deletes unnecessary files when updating the application.

- Clean Install v.1.9.14
<img width="1227" alt="Clean Install v 1 9 14" src="https://user-images.githubusercontent.com/62497891/117547307-3e4b3600-b02f-11eb-8471-cee4ad77178c.png">

- Update from v.1.9.13 to v.1.9.14
<img width="1227" alt="Software-Update from v 1 9 13 to v 1 9 14" src="https://user-images.githubusercontent.com/62497891/117547319-4d31e880-b02f-11eb-8bbc-01e5027fdde4.png">

**Comment by anastenko** [comment]
That would be much easier if you could give us detailed steps on how to reproduce it, since we got same 406,8 MB in both cases.

**Comment by Oleg-Chashko** [comment]
This is a bug of a third-party application, since after updating the application, a lot of garbage remains in the system. And she thought there were two applications installed. Even MacOS will not recognize whether it is for Intel or a universal application.
So everything is OK. Deleted the topic.
<img width="1204" alt="Update from v 13 to v 14" src="https://user-images.githubusercontent.com/62497891/117980796-9e462300-b334-11eb-9158-54b3627a4f05.png">

P.S:
 I forgot to say: "Standalone build, release channel" the application is not installed, you have to Remove app from GateKeeper quarantine.
<img width="409" alt="AdGuard for Safari v 13" src="https://user-images.githubusercontent.com/62497891/117980749-925a6100-b334-11eb-9e7c-f2b88724f492.png">

**Comment by Oleg-Chashko** [comment]
I was glad to help.

**Comment by Oleg-Chashko** [comment]
@anastenko 
Could you explain to me why MacOS recognizes the application as "duplicates" and not "intel" or "universal"?
Thanks for the answer.

**Comment by anastenko** [comment]
Well, that's weird though. I may only assume that it happened 'cause you installed several versions at once. 
We couldn't reproduce it on our end.

**Comment by Oleg-Chashko** [comment]
Somewhere the problem still exists, I hope you find it before the release.

Clean Install v.1.9.14
<img width="642" alt="Screen Shot 2021-05-13 at 12 45 43" src="https://user-images.githubusercontent.com/62497891/118115595-72d14000-b3e9-11eb-8df3-a44d7437048e.png">

Update from v.1.9.13 to v.1.9.14
<img width="642" alt="118015471-95654980-b354-11eb-94cd-6344777376a4" src="https://user-images.githubusercontent.com/62497891/118115496-4fa69080-b3e9-11eb-83ae-1cd2bdbbd076.png">

**Comment by Oleg-Chashko** [comment]
> Well, that's weird though. I may only assume that it happened 'cause you installed several versions at once.
> We couldn't reproduce it on our end.

Here is the sequence of actions, it seems to me that the topic needs to be rediscovered?

https://user-images.githubusercontent.com/62497891/118119965-7667c580-b3ef-11eb-83d8-413e7a4b0036.mp4

**Comment by Oleg-Chashko** [comment]
Here's a clean install with two problems.
Dear girls, it seems it's time to call the "heavy arteleria" by Andrey Meshkov?

Clean Install v.1.9.14

https://user-images.githubusercontent.com/62497891/118123185-2f300380-b3f4-11eb-85b5-ae11d0e1bddd.mp4

**Comment by Oleg-Chashko** [comment]
Sometimes the installation of the application will go well and the app v.1.9.14 Beta will be installed as universal.

https://user-images.githubusercontent.com/62497891/118134403-2cd4a600-b402-11eb-8685-2332d9d023a8.mp4

**Comment by Oleg-Chashko** [comment]
Here's a hint: so that there is no problem when integrating the app v.1.9.14 Beta into the Safari browser. When installing app v.1.9.14 Beta, Safari browser must be running. Only under this condition, the integration into the browser goes without problems for me.

https://user-images.githubusercontent.com/62497891/118136758-bdac8100-b404-11eb-9603-77d0bb0d9144.mp4

**Comment by tvinzz** [comment]
> @anastenko
> Could you explain to me why MacOS recognizes the application as "duplicates" and not "intel" or "universal"?
> Thanks for the answer.
> <img alt="Screen Shot 2021-05-12 at 18 51 19" width="642" src="https://user-images.githubusercontent.com/62497891/118015471-95654980-b354-11eb-94cd-6344777376a4.png">

🤦🤦🤦
take your favourite app, copy it in few places on your comp, check for duplicates

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Oleg, I didn't expect this from you. That you are lazy, I realized this long ago, but that you are a bad programmer, it hung me :)). I will say it again, I am very sorry that you are developing this application.

_take your favourite app, copy it in few places on your comp, check for duplicates_

There is only one "adguard" application on the system.
<img width="938" alt="Screen Shot 2021-05-17 at 13 30 53" src="https://user-images.githubusercontent.com/62497891/118482983-c3140f00-b715-11eb-96a6-ac46624321f5.png">

You think correctly, but your conclusions are not correct.
I will tell you: After upgrading from app v.1.9.13 to app v.1.9.14 Beta manually, without removing the old version (app v.1.9.13). Remains of v.1.9.13 remain and the system sees it as two applications. Which you yourself confirmed with your answer.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
Andrey Meshkov, please help Oleg understand what the problem is. Thank you.

**Comment by ameshkov** [comment]
@Oleg-Chashko I am grateful for your contributions, but this does not give you the right to be outright rude. Please, change the style of your communication.

@tvinzz emojis weren't necessary as well.

Regarding the issue in question, I honestly do not understand what's happening and cannot reproduce it either. I can understand why it may happen with a manual update (for instance, the folder structure inside an intel app may be different from a universal app and thus copy/paste leaves duplicate files). But I have no clue how this could be happening with a clean install.

So here're the questions:
1. Does this happen with the auto-update? That's the most important question tbh.
2. When you reproduced it with a clean install, have you rebooted prior to that? My thinking is that Safari might kept something from the previous installation and this triggered this "duplicates" issue.
3. Are you testing it on an Intel or an M1 Mac?

**Comment by Oleg-Chashko** [comment]
@ameshkov 
_but this does not give you the right to be outright rude. Please, change the style of your communication._
🤦🤦🤦

1. As he treats me, so I will treat a person. Here is the proof of his competence.
2. Can you show me where I have two or more apps? (take your favourite app, copy it in few places on your comp, check for duplicates 🤦🤦🤦)
3. If the programmer does not want to understand the problem and closes the topic, do you mean to say that he is not lazy? And this is not the first time.
-----------------------------------------------------------------------------------------------------------------------

**from v.1.9.13 to v.1.9.14 Beta**
[Name contains adguard_from v.1.9.13 to v.1.9.14 Beta.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/6493839/Name.contains.adguard_from.v.1.9.13.to.v.1.9.14.Beta.zip)

https://user-images.githubusercontent.com/62497891/118491470-530a8680-b71f-11eb-900e-28481b61c858.mp4

-----------------------------------------------------------------------------------------------------------------------

**Clean Install v.1.9.14**
<img width="938" alt="Clean Install v 1 9 14 Beta" src="https://user-images.githubusercontent.com/62497891/118491673-83eabb80-b71f-11eb-8f12-e565f029b716.png">
[Name contains adguard_Clean Install v.1.9.14 Beta.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/6493849/Name.contains.adguard_Clean.Install.v.1.9.14.Beta.zip)

https://user-images.githubusercontent.com/62497891/118491704-89e09c80-b71f-11eb-917e-bcbc7e84300f.mp4

**Comment by Oleg-Chashko** [comment]
@ameshkov 
But I have no clue how this could be happening with a clean install.
I have not rebooted my MAC.

**So that after cleaning it is necessary to reboot the system so that everything is OK.**

**Comment by ameshkov** [comment]
@Oleg-Chashko are you sure everything is okay if you reboot prior to that? If this is so, I am inclined to think this is a Safari bug.

However, the question about auto update still stands. If this issue can happen as a result of an auto-update, this may be a huge problem.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
_However, the question about auto update still stands. If this issue can happen as a result of an auto-update, this may be a huge problem._

And it worries me that's why I opened the topic. I treat this application as if it were my own. And I sincerely wish him prosperity.

P.S:
I forgot to say: "Standalone build, release channel v.1.9.13" the application is not installed, you have to Remove app from GateKeeper quarantine.
This could cause a problem with a manual update?
<img width="409" alt="117980749-925a6100-b334-11eb-9e7c-f2b88724f492" src="https://user-images.githubusercontent.com/62497891/118494832-d7123d80-b722-11eb-8ea1-e1b4007ccfa2.png">

------------------------------------------------------------------------------------------------------------------
_@Oleg-Chashko are you sure everything is okay if you reboot prior to that? If this is so, I am inclined to think this is a Safari bug._ 
I always disable all "AdGuard Safari" extensions before clean uninstallation, if I don't do this sometimes I get problems. And if not cleaned after deletion, the settings remain! I think this is not very good. And that can cause a problem too. Suggest test options, I'm at your disposal.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
3. Are you testing it on an Intel or an M1 Mac?
- Intel

**Comment by ameshkov** [comment]
> I always disable all "AdGuard Safari" extensions before clean uninstallation, if I don't do this sometimes I get problems. And if not cleaned after deletion, the settings remain! I think this is not very good.

Note that some of the leftovers are inside Safari which we don't control directly. Confirms that Safari is to blame here.

Regarding logs folders, on macOS it's a normal thing to keep leftovers. There're no approved way to add a hook on the app folder removal, therefore we cannot get rid of them.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
Understood thanks.

> > I always disable all "AdGuard Safari" extensions before clean uninstallation, if I don't do this sometimes I get problems. And if not cleaned after deletion, the settings remain! I think this is not very good.
> 
> Note that some of the leftovers are inside Safari which we don't control directly. Confirms that Safari is to blame here.
> 
> Regarding logs folders, on macOS it's a normal thing to keep leftovers. There're no approved way to add a hook on the app folder removal, therefore we cannot get rid of them.

And this folder can be deleted in the place with the application.
<img width="1502" alt="118503714-29eff300-b72b-11eb-8271-b137139267f7" src="https://user-images.githubusercontent.com/62497891/118514048-83105480-b734-11eb-8440-5f6221cb1aaa.png">

This is not a log folder and not in Safari. And if I'm not mistaken, the application settings remain in it?

P.S.
Please pay attention, it is possible that this is all interconnected. And it will help in finding the problem.
- If "Quit" is from the application, then it will not launch when login to macOS #600
- With a clean installation of the application: "Safari detected an app or service that interfered with clicking" #594

**Comment by ameshkov** [comment]
> This is not a log folder and not in Safari. And if I'm not mistaken, the application settings remain in it?

Yep, that's it. Well, it's the same problem, there is no way we can react to application removal, no code is being triggered. It's macOS way - no uninstallers.

**Comment by Oleg-Chashko** [comment]
> > This is not a log folder and not in Safari. And if I'm not mistaken, the application settings remain in it?
> 
> Yep, that's it. Well, it's the same problem, there is no way we can react to application removal, no code is being triggered. It's macOS way - no uninstallers.

@ameshkov
Got it, thanks for the clarification.

**Comment by Oleg-Chashko** [comment]
@ameshkov 

These problems, I noticed only in v.1.9.14 Beta. 
In v.1.9.13, these problems were not encountered when installing on clients Mac.
Please pay attention, it is possible that this is all interconnected. And it will help in finding the problem.

If "Quit" is from the application, then it will not launch when login to macOS #600
With a clean installation of the application: "Safari detected an app or service that interfered with clicking" #594

**Comment by Oleg-Chashko** [comment]
@ameshkov 
Or because it is not signed "Standalone build, release channel v.1.9.13"?
<img width="409" alt="118494832-d7123d80-b722-11eb-8ea1-e1b4007ccfa2" src="https://user-images.githubusercontent.com/62497891/118788744-5f642000-b894-11eb-9085-65e535869891.png">

Maybe this is a bug (MacOS Big Sur v.11.3.1 (20E241))? Or is it Electron's problem?
Since the system indicates the same application.

![Screen_1](https://user-images.githubusercontent.com/62497891/118787265-f4661980-b892-11eb-9567-6b1ed66f6c84.gif)

**Comment by Oleg-Chashko** [comment]
_Maybe this is a bug (MacOS Big Sur v.11.3.1 (20E241))? Or is it Electron's problem?_
I myself will answer my own question: there are no compatibility problems. 
Conducted a test on installation and uninstallation "VSCode-darwin-universal".

**Comment by Oleg-Chashko** [comment]
@ameshkov 
With tests in this problem, I'm done. What to do next is up to you.
Maybe ask (@mizzick)?

My report on this issue:

- 1.Test: Script usage, clean (only once)->install v.1.9.13->install v.1.9.13->install v.1.9.13->etc.(Many times) - 100%OK
Files in the system: AdGuard app
[Files in the system - AdGuard app v.1.9.13.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/6508709/Files.in.the.system.-.AdGuard.app.v.1.9.13.txt)

- 2.Test: Update from v.1.9.13 to v.1.9.14.Beta->install v.1.9.14.Beta->install v.1.9.14.Beta->etc.(Many times) - 50%/50% Not OK
Files in the system: AdGuard app
[Files in the system - AdGuard app, from v.1.9.13 to v.1.9.14.Beta.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/6508712/Files.in.the.system.-.AdGuard.app.from.v.1.9.13.to.v.1.9.14.Beta.txt)

https://user-images.githubusercontent.com/62497891/118813688-b0cdd880-b8af-11eb-8d22-76a7d636be89.mp4

- 3.Test: Script usage, clean (only once)->install v.1.9.14.Beta->install v.1.9.14.Beta->etc.(Many times) - 50%/50% Not OK
Files in the system: AdGuard app
[Files in the system - AdGuard app v.1.9.14.Beta.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/6508727/Files.in.the.system.-.AdGuard.app.v.1.9.14.Beta.txt)

https://user-images.githubusercontent.com/62497891/118814110-14f09c80-b8b0-11eb-9b79-5635481d5f0b.mp4

**Comment by ameshkov** [comment]
@Oleg-Chashko I suppose this is just a Safari bug and frankly, I don't see how can we do anything without the risk of making things worse.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko I suppose this is just a Safari bug and frankly, I don't see how can we do anything without the risk of making things worse.

@ameshkov 
Let me put it this way, at first I thought there was a big problem. 
But after observing (many times installed and uninstalled the application, updated it).
 I saw no deterioration in his work! 
It is better to leave it as it is. I wonder how the update will go over the Internet. 
And what will be displayed in MacOS.

P.S.:
I'm dealing with this problem right now:

When opening a large number of tabs in Safari, one of the app's extensions freezes and crash #592

Morally stressing me out, the heavy load when Safari starts up, the interface braking extension and the yellow warning window.
