### ISSUE TITLE
When Safari starts, not all application components start at the same time (v.1.9.14 Beta)

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#598]
When you start Safari, not all components of the v.1.9.14 Beta application are immediately launched.
A warning appears: Some AdGuard for Safari are disabled!

https://user-images.githubusercontent.com/62497891/117680369-62368500-b1b1-11eb-8333-1efa67f346b7.mp4

**Comment by zzebrum** [comment]
@Oleg-Chashko I think it is somehow related to the order (and probably speed) in which Safari loads content blockers. So far we can not repro the issue. But let's wait for @tvinzz comment.

**Comment by Oleg-Chashko** [comment]
@zzebrum 
- This video is slowed down 2 times. And you need to immediately open the browser extension and this is important.

_I think it is somehow related to the order (and probably speed)._
I completely agree with you.

**Comment by TheHasagi** [comment]
@Oleg-Chashko Can't reproduce. Not sure that this depends on us, Safari needs some time to load all extensions properly.

**Comment by Oleg-Chashko** [comment]
@TheHasagi 
Unfortunately, this behavior is also observed when the browser is already running. Of course it's up to you to decide. And I'll wait when you have a developer for this project.
