### ISSUE TITLE
If "Quit" is from the application, then it will not launch when login to macOS

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#600]
If "Quit" is from the application, then it will not launch when login to macOS.

- "Launch AdGuard at Login" is activated.
<img width="280" alt="Screen Shot 2021-05-16 at 12 10 34" src="https://user-images.githubusercontent.com/62497891/118393559-16b42900-b640-11eb-8b9f-3515bfdeaadc.png">

https://user-images.githubusercontent.com/62497891/118393562-1c117380-b640-11eb-924e-9768c4afe382.mp4

**Comment by Oleg-Chashko** [comment]
@ameshkov 
This is beta version v.1.9.14.
After another clean install, this problem went away, but it may reappear. Somewhere there is a problem when installing in v.1.9.14 Beta.

**Comment by ameshkov** [comment]
@Oleg-Chashko could you please run this command next time this issue happens?

`launchctl print-disabled gui/$UID`

I'd like to see the output.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko could you please run this command next time this issue happens?
> 
> `launchctl print-disabled gui/$UID`
> 
> I'd like to see the output.

@ameshkov 
I will try, but unfortunately it does not depend on me.

**Comment by ameshkov** [comment]
The thing is that we're using SMLoginItemSetEnabled to register login helper, this command will show if our helper is on the list.

Depending on that we'll see where to dig.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
To catch this, I have to install and uninstall the application and clean up the MacOS.
To speed up and facilitate the work, I wrote a script.

If you have a desire and free time, you can help me write the script.
 I will be glad and it may be possible to catch this bug earlier and with less time.
Thank you.

P.S: If there is a bug, I will not catch it, we will write it off to chance when installing the application.

AdGuard for Safari uninstaller script:
[AdGuard for Safari uninstaller script.sh.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/6503762/AdGuard.for.Safari.uninstaller.script.sh.zip)


Request if you can:
1. At the moment there is no order in the log.
<img width="1375" alt="Screen Shot 2021-05-18 at 20 39 30" src="https://user-images.githubusercontent.com/62497891/118708649-43249c80-b81c-11eb-8087-7c7198755c8a.png">
Example: The order in the log.
<img width="1450" alt="Screen Shot 2021-05-18 at 20 47 48" src="https://user-images.githubusercontent.com/62497891/118708955-ab737e00-b81c-11eb-8597-6e2edc305c0e.png">

------------------------------------------------------------------------------------------------------------------

2. There is no access to the container, and part of the script does not work yet.
While I don’t know how to get around, I’ll try to disable (System Integrity Protection (SIP) in macOS).
<img width="989" alt="Dont Work" src="https://user-images.githubusercontent.com/62497891/118709771-b37fed80-b81d-11eb-92e1-ad7b25fb261f.png">

**Comment by ameshkov** [comment]
@Oleg-Chashko oh, tbh this looks like overkill for this. If this issue is that rare that the only way is to run it in a loop a hundred times, it is probably simply not worth it.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko oh, tbh this looks like overkill for this. If this issue is that rare that the only way is to run it in a loop a hundred times, it is probably simply not worth it.

But I'll still try for a couple of days, if I don't catch the bug, I'll delete the topic.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
1. The script was slightly corrected. Works OK.
2. Provided Full Disk Access (bach). Works OK.
Now there is no problem with the script.

![Screen_1](https://user-images.githubusercontent.com/62497891/118728353-504d8580-b834-11eb-873c-3ae908f2c830.gif)

Tomorrow after work I will start the test.

Should these files be deleted or do they not affect the operation of the AdGuard application?
<img width="1126" alt="Screen Shot 2021-05-18 at 23 01 25" src="https://user-images.githubusercontent.com/62497891/118728463-7f63f700-b834-11eb-89cb-d2cfffb9f40a.png">

**Comment by ameshkov** [comment]
> Should these files be deleted or do they not affect the operation of the AdGuard application?

Looks like temporary files. Nevertheless, deleting them won't hurt.

**Comment by Oleg-Chashko** [comment]
> > Should these files be deleted or do they not affect the operation of the AdGuard application?
> 
> Looks like temporary files. Nevertheless, deleting them won't hurt.

@ameshkov 
Yes, I will definitely add it to the script.

**Now the question is:** 
I installed and removed the application a lot today. But it is only now the application has created these files and folders. I don't even have these branches to delete in the script yet. Can you comment on this somehow?

<img width="1313" alt="Screen Shot 2021-05-19 at 00 05 34" src="https://user-images.githubusercontent.com/62497891/118729963-1a5dd080-b837-11eb-83d8-e2a105bcc371.png">

**Comment by ameshkov** [comment]
Folders 2 and 3 are created automatically by the system when the sandboxed app is launched.
Tbh, no idea about the first folder.

**Comment by Oleg-Chashko** [comment]
I installed and uninstalled the application about 50 to 60 times, the problem did not appear. 
Hope this was a very rare bug. 
I close the topic.

**Comment by Oleg-Chashko** [comment]
This is the only one that I have seen. 

https://user-images.githubusercontent.com/62497891/118984184-821e3380-b97d-11eb-869c-3705a7a20297.mp4

**Comment by ameshkov** [comment]
> This is the only one that I have seen.

This may mean that the filter rules haven't been compiled. If you see this again, please check "General" -> "Content blockers', what's going on there?

**Comment by Oleg-Chashko** [comment]
This behavior is observed all the time. While launching the application in version 1.9.13 and 14 Beta.

https://user-images.githubusercontent.com/62497891/119264002-a5491d00-bbe1-11eb-94dc-fbbf8f0f4dd8.mp4
