### ISSUE TITLE
When you put AdGuard into pause mode, the content blocker should not completely unload

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#606]
@ameshkov 
When you put AdGuard into pause mode, the content blocker is completely unloaded. 
Why would it do that if it has to go into pause mode? 
And after coming out of pause mode, it now has to convert the rules again, register with the content blocker, and then wait for the content blocker to fully load. 
This loses about 45 seconds to the process.
Maybe there is an option not to unload completely but to pause?

https://user-images.githubusercontent.com/62497891/119575870-f6126e80-bdb7-11eb-887e-faee2e85f483.mp4

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

This is how it works, content blockers cannot be paused as you might think, when you press the pause button from assistant they are just dropping the rules like a machine engine cannot be paused, it is working or turned off. So the meaning of pause should not bother you or cause misunderstanding. We will think about how to speed'em up.

**Comment by Oleg-Chashko** [comment]
> We will think about how to speed'em up.

@TheHasagi
 
Got it, thanks for the clarification. I would be glad if you succeeded.

P.S.:
The machine mechanism does not need to be stopped, you need to build in a clutch system, preferably based on a torque converter. So you don't need to change the friction disc from wear in the future. (Just kidding) ;)

**Comment by ameshkov** [comment]
Calling it a different name would be inconsistent with our other products.

And yeah, unfortunately, there's no way around this:(

**Comment by Oleg-Chashko** [comment]
@ameshkov 
> Calling  it a different name would be inconsistent with our other products.

Sorry, you must have misunderstood, I didn't say anything about renaming your product. I was talking about icons, captions, and what state the application is in. It's a stop or pause state. 

https://user-images.githubusercontent.com/62497891/120114962-ef05aa80-c181-11eb-939d-6f65a09a4392.mp4

**Comment by ameshkov** [comment]
I am talking about the "Pause" feature, we call it like that in other products.

**Comment by Oleg-Chashko** [comment]
If you say it's a pause, then that's what it is. The question was asked because the application indicates this mode as off instead of paused.
<img width="338" alt="Screen Shot 2021-05-30 at 20 11 04" src="https://user-images.githubusercontent.com/62497891/120115718-4c4f2b00-c185-11eb-8be5-77511b5ad154.png">

**Comment by ameshkov** [comment]
True, it should be "AdGuard is enabled" / "AdGuard is paused"
