### ISSUE TITLE
Certficate/Notarization broken

### ISSUE THREAD

**Issue by B-X-M** [AdguardTeam/AdGuardForSafari#607]
On MacOS Catalina (not tested on other MacOS versions) the Adguard for Safari App, standalone build from the stable release channel on github cannot be launched, because the certification chain is broken. The OS rejects the app as being "not from a certified developer". In order to verify and exclude any problems with my system, I uploaded the 1.9.13 release build to virustotal, which also detects the app signature as invalid (report is at https://www.virustotal.com/gui/file/90b39157c503541c895d973ad1493171128e471aacd043943b68ca9c4b1fcfc3/detection).

Thank you for fixing this.

**Comment by TheHasagi** [comment]
@B-X-M 

Hello, thank you for the report. Try out the new 1.9.14 beta version where it's fixed already.

**Comment by TheHasagi** [comment]
@B-X-M 

Any updates?

**Comment by B-X-M** [comment]
Sorry for the late reply.

The issue is **not** fixed. Please see the following report, app _v 1.9.14 beta_ checked with MacOS built-in tools:

`spctl -a -vv Adguard\ for\ Safari.app` 
`Adguard for Safari.app: rejected`
`source=Unnotarized Developer ID`
`origin=Developer ID Application: Adguard Software Limited (TC3Q7MAJXF)`

There's something wrong with the notarization/the developer account.

**Comment by Oleg-Chashko** [comment]
@B-X-M 
app v 1.9.14 beta
<img width="703" alt="Screen Shot 2021-05-29 at 10 37 44" src="https://user-images.githubusercontent.com/62497891/120063996-5a5c5900-c06a-11eb-8e6d-ffa13be078b2.png">

**Comment by B-X-M** [comment]
Now this is interesting, tried again on a fully updated BigSur install on a different machine, same result, app rejected.

@Oleg-Chashko Did you install from the AppStore? This binary seems to work. What is broken (at least over here ;)) is the binary from github releases, see terminal screenshot and screenshot of virustotal scan also flagging the signature as invalid (yellow marker added by me)

<img width="772" alt="adguard1-9-14-VT" src="https://user-images.githubusercontent.com/65444507/120068845-19bd0980-c083-11eb-8180-ce600562c09e.PNG">
.

![adguard1-9-13](https://user-images.githubusercontent.com/65444507/120068679-3efd4800-c082-11eb-8d67-3389577a66dc.jpg)

**Comment by Oleg-Chashko** [comment]
Hi @B-X-M 

> @Oleg-Chashko Did you install from the AppStore? 

No, I installed from "github" (Standalone build, beta channel).
Report virustotal: https://www.virustotal.com/gui/file/c290358460dd43803ba9c4d93f2613871bd1bd6345c77ed8cd0d237d68e74902/detection
P.S.: It feels like we are in different temporal universes. ;)
<img width="1417" alt="Screen Shot 2021-05-29 at 13 51 15" src="https://user-images.githubusercontent.com/62497891/120069405-2abb4a00-c086-11eb-950d-8118ff0acb4a.png">

**Comment by Oleg-Chashko** [comment]
@B-X-M 
Please note: File size and Hash.

**Comment by Oleg-Chashko** [comment]
@B-X-M 
Report virustotal: app **v.1.9.13**
You got it wrong a little bit. You checked with Virustotal v.1.9.13. And it really isn't signed. And we're talking about v.1.9.14 Beta, the v.1.9.14 Beta is okay with the signature.


https://www.virustotal.com/gui/file/90b39157c503541c895d973ad1493171128e471aacd043943b68ca9c4b1fcfc3/detection
<img width="1417" alt="Screen Shot 2021-05-29 at 14 19 55" src="https://user-images.githubusercontent.com/62497891/120070051-61469400-c089-11eb-8ebe-a17126a63971.png">

**Comment by B-X-M** [comment]
Ok, thanks for pointing me into the right direction. If you go to the latest beta release tag, the first standalone build link will still redirect to the broken release version 1.9.13. Only the second "beta" link refers to the actual beta build. My fault, sorry! I was trying to re-check the broken build all over.

**Just a quick recap of the situation:**
There is a signature issue in the release build.
The fix is in 1.9.14beta.

@Oleg-Chashko Is this correct? And thanks again for pointing that out.

Btw, what is the reason for the broken signature in older builds?

**Comment by Oleg-Chashko** [comment]
@B-X-M 

> Just a quick recap of the situation:
There is a signature issue in the release build.
The fix is in 1.9.14beta.

Yes, short and true.
No need to apologize. I was glad to help you. :)

> Btw,` what is the reason for the broken signature in older builds?

As I understand it, now there is a lot of work on v.1.9.14Beta. Transition to Universal build, for Intel CPUs and arm M1 CPUs. Perhaps there is no time for this. A lot of work with SafariConverterLib for Beta. Guys are really busy and trying.

**Comment by B-X-M** [comment]
Sorry to come back to this issue. While 1.9.14Beta camewith a proper signature, the signature/notarization of the 1.19.19 package is broken again. Please fix the signing process as it keeps users from actually installing the github linked files. Screenshot from VT:
<img width="696" alt="VT1 9 19" src="https://user-images.githubusercontent.com/65444507/127096596-3aad0487-2663-4de3-93b5-0067ea466f9b.PNG">
