### ISSUE TITLE
"Ad blocking in Safari is on / off" --> "AdGuard protection is on / paused"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#610]
See the dialog here: https://github.com/AdguardTeam/AdGuardForSafari/issues/606#issuecomment-851033603

To be consistent, we should call it "on / paused".

**Comment by Oleg-Chashko** [comment]
<img width="320" alt="Снимок экрана 2021-06-03 в 21 07 08" src="https://user-images.githubusercontent.com/62497891/120698871-eda0ee80-c4af-11eb-9772-ee351acf1c2f.png">

**Comment by carlylemiii** [comment]
Doesn't seem changed in 1.10.4, despite being in the [release notes](https://github.com/AdguardTeam/AdGuardForSafari/releases) 🤔 

![CleanShot 2021-08-03 at 01 50 38@2x](https://user-images.githubusercontent.com/29067983/127970785-50a4b48f-9c1c-44ab-82a1-c693814ee05e.png)

**Comment by anastenko** [comment]
@carlylemiii Hello.
Just checked and everything seems to be okay: Ad blocking in Safari is on/ Ad blocking in Safari is paused.
Try reinstalling the application (clean install):
- Uncheck all AdGuard for Safari extensions in Safari preferences --> extensions
- Delete:
```
~/Library/Application Support/AdGuardSafariApp
~/Library/Containers/ - all directories started with com.adguard.safari.AdGuard
~/Library/GroupContainers/TC3Q7MAJXF.com.adguard.safari.AdGuard
~/Library/Preferences/com.adgurd.safari.plist
```
- Quit all "AdGuard" and "cfprefsd" processes from Activity monitor
- Delete AG for Safari and install it again ([link for v1.10.4](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.10.4))

**Comment by carlylemiii** [comment]
No such luck. Maybe the App Store build and that ZIP differ? (I've installed — and reinstalled — from the App Store, as that is my preferred location.)

**Comment by anastenko** [comment]
@carlylemiii Should be the same behavior for both.
What os do you use?

**Comment by carlylemiii** [comment]
macOS.

**Comment by carlylemiii** [comment]
Ah, I think I might see the issue — the menu bar text is still the old text, but the text in the extension popover has been updated.

**Comment by anastenko** [comment]
> macOS.

I mean Big Sur, Catalina, etc. 


> Ah, I think I might see the issue — the menu bar text is still the old text, but the text in the extension popover has been updated.

I have the new text on the menu bar. Maybe cached? Could you clear `com.adguard.safari` in `Caches` folder? 
Also make sure there's no trace of AG for Safari once you reinstalling it.
