### ISSUE TITLE
Question: Sometimes I can't turn on one of the extensions in Safari

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#616]
@ameshkov 
I would like to hear your opinion. Thank you for your reply.

https://user-images.githubusercontent.com/62497891/120780578-8e32f500-c528-11eb-9b0a-1f61f52f4ed6.mp4

**Comment by ameshkov** [comment]
Tbh, no idea what's causing this, but this definitely is a Safari issue, not ours.

**Comment by Oleg-Chashko** [comment]
Didn't you try to write to Apple about it?  Or is there no point in writing to them about it?

**Comment by ameshkov** [comment]
Well, we can't write about it because we cannot reproduce this.

If you're able to, you can send a bug report to them as well - it's done through the "Feedback app".

**Comment by Oleg-Chashko** [comment]
Got it, thanks, I'll try to write to them.
