### ISSUE TITLE
Notification status after app update in "About tab" in Russian localization

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#617]
- German is the correct Localization.
<img width="1072" alt="AdGuard für Safari ist aktuell" src="https://user-images.githubusercontent.com/62497891/120917794-7470e980-c6b1-11eb-8802-61161ed20913.png">
<img width="1217" alt="AdGuard für Safari ist aktuell" src="https://user-images.githubusercontent.com/62497891/120820900-3b236700-c555-11eb-9980-a966b6f46bba.png">

---

- English is the correct Localization.
<img width="1072" alt="AdGuard for Safari is up to date" src="https://user-images.githubusercontent.com/62497891/120917805-86eb2300-c6b1-11eb-88cb-a34af2e0fa4d.png">
<img width="1266" alt="AdGuard for Safari is up to date" src="https://user-images.githubusercontent.com/62497891/120821160-82115c80-c555-11eb-8d5d-4edb05548329.png">

---

- Russian is the not quite correct Localization.
<img width="1072" alt="AdGuard для Safari обновлен" src="https://user-images.githubusercontent.com/62497891/120917839-aeda8680-c6b1-11eb-87df-f2a9c09f21d4.png">

- Example: it is advisable to write(в актуальном состоянии).
Или что-то другое, по вашему усмотрению.
<img width="1072" alt="AdGuard для Safari обновлен" src="https://user-images.githubusercontent.com/62497891/120917966-493aca00-c6b2-11eb-8681-27ce4d546a2f.png">

**Comment by el-termikael** [comment]
@Oleg-Chashko
Здравствуйте! Вот четыре строки, переведённые аналогичным образом:
https://crowdin.com/translate/adguard-applications/17594/en-ru#3936974
https://crowdin.com/translate/adguard-applications/17634/en-ru#3867940
https://crowdin.com/translate/adguard-applications/17658/en-ru#3868518
https://crowdin.com/translate/adguard-applications/17658/en-ru#3868644

+ скриншот AdGuard для Mac (если нажать «Проверить обновления»): https://uploads.adguard.com/el.termikaelj6y6q.png 

Кажется, что с нынешним переводом всё в порядке, у нас устоялась такая формулировка.

**Comment by Oleg-Chashko** [comment]
@el-termikael 
Привет! У меня нету акаунта в (https://crowdin.com) так, что я не смогу увидеть перевод.
Английски и Немецкий локализирован правильно. Проблема с русской локализацией.

Мне очень понравился, ваш скриншот 5 из 5 балов: 
<img width="373" alt="el termikaelj6y6q" src="https://user-images.githubusercontent.com/62497891/120833954-af183c00-c562-11eb-8354-a26a44162253.png">

Пожалуйста сделайте, так-как у вас устоялась формулировка.
К такой формулировке, у меня нет вопросов.

По вашему примеру:
<img width="406" alt="120822513-c4876900-c556-11eb-85b3-8dd147333e14" src="https://user-images.githubusercontent.com/62497891/120834119-e71f7f00-c562-11eb-9967-860b8c080a10.png">

**Comment by el-termikael** [comment]
Прошу прощения, в краудине такие строки:
Расширение AdGuard было обновлено до версии %current_version%
Почти обновлено! Перезапустите расширение AdGuard для Safari, чтобы завершить обновление.
Расширение AdGuard для Safari было обновлено до версии $1.

Мы могли бы поменять строку, которую вы предлагаете изменить, на «Расширение AdGuard для Safari обновлено», но тогда это, вероятнее всего, не поместится в одной строке (как и ваш вариант «AdGuard для Safari в актуальном состоянии»).

**Comment by Oleg-Chashko** [comment]
@el-termikael 
Я уверен, что поместится, и место ещё останется. Так как вы сами, мне указываете длину строки:
- Расширение AdGuard было обновлено до версии %current_version%
- Почти обновлено! Перезапустите расширение AdGuard для Safari, чтобы завершить обновление.
- Расширение AdGuard для Safari было обновлено до версии $1.

А вот длина моей строки:
- AdGuard для Safari в актуальном состоянии

<img width="651" alt="Screen Shot 2021-06-04 at 19 05 58" src="https://user-images.githubusercontent.com/62497891/120838410-12f13380-c568-11eb-939a-59712c16a420.png">

**Comment by Oleg-Chashko** [comment]
А почему, вы не хотите сделать вариант, приложенный вами? Он прекрасно написан.
<img width="406" alt="120834119-e71f7f00-c562-11eb-9967-860b8c080a10" src="https://user-images.githubusercontent.com/62497891/120839957-e6d6b200-c569-11eb-9feb-63580ef797fb.png">

**Comment by Oleg-Chashko** [comment]
Длина приложения увеличится на 12 букв. 
При этом понятность предложения для пользователя, увеличится до 100%.
Изменить, только русский вариант локализации.

Вот визуальный пример, Русского варианта: «AdGuard для Safari в актуальном состоянии»
<img width="1072" alt="Meine Variante" src="https://user-images.githubusercontent.com/62497891/120856195-c0237600-c57f-11eb-8b44-aa01e60794e8.png">

**Comment by el-termikael** [comment]
@Oleg-Chashko Добрый день!
Спасибо за ваше предложение, но всё же пока мы оставим нынешний вариант, если не найдется формулировка лучше. Формулировка «AdGuard для Safari в актуальном состоянии», в отличие от немецкого языка, на русском звучит неестественно. А вариант «обновлён» также встречается в переводчиках: https://monosnap.com/file/uAHQolysK4Kf3I0zeaaKUqJ5vY6JZF.

Как кажется, для пользователей понятнее всего было бы «AdGuard для Safari обновлён до последней версии», но это слишком длинная строка для данного интерфейса (не хочется, чтобы её размер в два раза превышал длину двух соседних, с версией и «Узнать больше о продукте»).

**Comment by Oleg-Chashko** [comment]
@el-termikael 

> Как кажется, для пользователей понятнее всего было бы «AdGuard для Safari обновлён до последней версии», но **это слишком длинная строка для данного интерфейса** (не хочется, чтобы её размер в два раза превышал длину двух соседних, с версией и «Узнать больше о продукте»).

Странно, почему вас не смущяет более длинные строки в данном разделе интерфейса?
Был рад, с вами по общаться.

<img width="690" alt="120929179-57a3d880-c6e8-11eb-9c06-8f4608525986" src="https://user-images.githubusercontent.com/62497891/120988574-fbd85e80-c77e-11eb-9838-f72d2c766aec.png">
