### ISSUE TITLE
Cannot open Adguard preferences

### ISSUE THREAD

**Issue by maharjanaman** [AdguardTeam/AdGuardForSafari#619]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.9.17
* Environment name and version: Safari 14.1.1 (16611.2.7.1.4)
* Operating System: macOS Big Sur 11.4
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

### Expected Behavior

When trying to open preferences from menu icon, should open preferences

### Actual Behavior

Open an empty window

### Screenshots

<details><summary>Screenshot:</summary>

<img width="1072" alt="Screen Shot 2021-06-08 at 23 13 26" src="https://user-images.githubusercontent.com/14164484/121231609-4f969500-c8b0-11eb-897c-68f842e87185.png">

</details>

### Additional Information

Running on Intel mac

**Comment by ameshkov** [comment]
The version on App Store is borked on Intel, we're very sorry for this mistake.

Temporary solution is to use the standalone build: https://agrd.io/safari_release

Just unpack and copy it to Applications.

**Comment by kfgstone** [comment]
Exactly the same environment / behavior here on M1 MBP.

**Comment by ameshkov** [comment]
In any case standalone build will work okay, the root cause is the App Store build's signature which is borked.

**Comment by dereksub** [comment]
Same problem. M1 Mac, macOS 11.3.1, Safari 14.1. Do you expect the problem with App Store's version will fixed in days, weeks, months? Thanks.

**Comment by ameshkov** [comment]
Depends on how fast the review goes, a day or two.

**Comment by ameshkov** [comment]
1.9.18 is out, but it may take an hour or two to become available to everyone. This is basically the previous release so all the changes announced for v1.9.17 will come to Mac App Store later (standalone build is still okay, though).

Now we will slow down a bit and take some time to figure out what went wrong and push the update properly this time.

**Comment by n0rt0nthec4t** [comment]
The hot fix update has been released on the Mac app store (1.9.18), however, since this update now causes macOS power usage to report Adguard for safari is using significant energy. Even when doing nothing

<img width="335" alt="Screen Shot 2021-06-09 at 9 48 56 am" src="https://user-images.githubusercontent.com/19759130/121271849-ed697e80-c907-11eb-854b-1a9b82931037.png">

**Comment by ameshkov** [comment]
Please let us know if it still reports anything after some time has passed. Content blockers compilation is indeed a heavy operation and it always used CPU. It only happens on the first run and when filters are updated.

**Comment by maharjanaman** [comment]
As @ameshkov mentioned, macOS reports Adguard is using significant power usage even when safari is closed.

**Comment by maharjanaman** [comment]
Closing this issue as new release from mac app store now open Adguard and its preferences without any issue.
