### ISSUE TITLE
Latest version (1.9.18) still running in Rosetta 2

### ISSUE THREAD

**Issue by BrushXue** [AdguardTeam/AdGuardForSafari#621]
### Issue Details

* AdGuard for Safari version: 1.9.18 (Installed from App Store)
* Environment name and version: Safari 14.1.1
* Operating System: macOS Big Sur 11.4
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

### Expected Behavior
Running in native ARM

### Actual Behavior
Running in Rosetta 2

### Screenshots

<details><summary>Screenshot:</summary>

![Screen Shot 2021-06-08 at 11 52 46 PM](https://user-images.githubusercontent.com/12702149/121290642-fc731100-c8b4-11eb-9110-7ff6264f3236.png)
![Screen Shot 2021-06-08 at 11 53 24 PM](https://user-images.githubusercontent.com/12702149/121290651-fed56b00-c8b4-11eb-95d6-d938b0ab4e74.png)

</details>

### Additional Information
I have tried 1.9.14 beta without any issue. But now the release version is still running in Rosetta.

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdGuardForSafari/issues/619#issuecomment-857216691

**Comment by chungweileong94** [comment]
@ameshkov I don't quite understand, it's been 2 days but the 1.9.18 on App Store still runs on Rosetta. I have to use the standalone version for now.
Does that mean the Apple silicon version still in the progress of releasing to the App Store?

**Comment by TheHasagi** [comment]
@chungweileong94 

For now, version 1.9.18 is a temporary hotfix and it is "intel-based". Please, stand by for the updates.
