### ISSUE TITLE
1.9.18 still using "intel" instance rather than m1 "apple"

### ISSUE THREAD

**Issue by freeman333333** [AdguardTeam/AdGuardForSafari#623]
### Issue Details

* AdGuard for Safari version:  1.9.18
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) Version 14.1.1 (16611.2.7.1.4)
* Operating System: (e.g macOS High Sierra 10.13.6): BigSur 11.4
* Filters you use in AdGuard: Adblock, Language specific (KR)
* Any other browser extensions you have installed: None

### Expected Behavior
 1.9.17 release stated that M1 support has been added however, when I look at running instance, it is still using Intel

### Actual Behavior
 "Intel" instance is running rather than "apple"

 AdGuard for Safari	0.0	13.31	27	1	Intel	0.0	0.00	973	timyoum	0 bytes		0 bytes	0 bytes	0	0	0 bytes	0 bytes	(null)	-	No	No	0 bytes	0 bytes	0 bytes	No	Yes	No	0 bytes	0 bytes	(null)	
 AdGuard for Safari Helper	0.0	0.19	8	1	Intel	0.0	0.00	980	timyoum	0 bytes		0 bytes	0 bytes	0	0	0 bytes	0 bytes	(null)	-	No	No	0 bytes	0 bytes	0 bytes	No	Yes	No	0 bytes	0 bytes	(null)	
 AdGuard for Safari Helper (GPU)	0.2	3.90	10	0	Intel	0.0	0.68	975	timyoum	0 bytes		0 bytes	0 bytes	0	0	0 bytes	0 bytes	(null)	-	No	No	0 bytes	0 bytes	0 bytes	No	Yes	No	0 bytes	0 bytes	(null)	
 AdGuard for Safari Helper (Renderer)	0.0	7.13	16	0	Intel	0.0	0.00	1052	timyoum	0 bytes		0 bytes	0 bytes	0	0	0 bytes	0 bytes	(null)	-	No	No	0 bytes	0 bytes	0 bytes	No	Yes	No	0 bytes	0 bytes	(null)	
 AdGuardForSafariBlockerExtension	0.0	0.07	4	0	Intel	0.0	0.00	1055	timyoum	0 bytes		0 bytes	0 bytes	0	0	0 bytes	0 bytes	(null)	-	No	No	0 bytes	0 bytes	0 bytes	Yes	Yes	No	0 bytes	0 bytes	(null)	
 AdGuardForSafariBlockerExtension	0.0	0.05	4	0	Intel	0.0	0.00	1087	timyoum	0 bytes		0 bytes	0 bytes	0	0	0 bytes	0 bytes	(null)	-	No	No	0 bytes	0 bytes	0 bytes	Yes	Yes	No	0 bytes	0 bytes	(null)	

### Screenshots

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/85729316/121644887-ed6ba900-cad6-11eb-9435-cb46526c9ac2.png">

<details><summary>Screenshot:</summary>

</details>

**Comment by TheHasagi** [comment]
@freeman333333 

Please, read this [comment](https://github.com/AdguardTeam/AdGuardForSafari/issues/619#issuecomment-856965861).

However, you can try to install 1.9.17 [standalone build](https://agrd.io/safari_release).
