### ISSUE TITLE
Safari 15.0 on MacOS Monterey

### ISSUE THREAD

**Issue by Pavo-IM** [AdguardTeam/AdGuardForSafari#625]
* **Version of AdGuard for Safari:**
 Version 1.9.13 
* **Environment name and version:**
 Safari 15.0
* **Operating system and version:**
  MacOS 12 Monterey
* **Filters you use in AdGuard:**
  Ad Blocking, Privacy, Social Widgets, Annoyances
* **Any other browser extensions you have installed:**
  None

### Expected Behavior
Expected Youtube videos to load with Ad Blocking enabled.

### Actual Behavior
When a YouTube ad starts to play, get an error to continue playing the video.

**Comment by n0rt0nthec4t** [comment]
I'm finding with Adblock enabled, that if you watch a YouTube video without fullscreening, will play.. As soon as you go fullscreen, it'll play for a bit, then kinda freeze until go back to "windowed" mode

**Comment by Theredmc** [comment]
Hi Pavo,
I dont have the Problem you mentioned with my M1 Machine.
Are you running Adguard for Safari on an Hackintosh ? Because this could be the Problem

**Comment by anastenko** [comment]
@Pavo-IM Hello. 
Our devs are taking a look at this. We will let you know once we got any information.
