### ISSUE TITLE
Unchecking 'Enabled on this website', ie, Allowlist, doesn't disable content blocker

### ISSUE THREAD

**Issue by nomasprime** [AdguardTeam/AdGuardForSafari#626]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.9.18
* Environment name and version: Version 14.1 (16611.1.21.161.3)
* Operating System: 11.3
* Filters you use in AdGuard: none
* Any other browser extensions you have installed: 1Password

### Expected Behavior

Unchecking 'Enabled on this website' should stop content filtering.

Hubspot live chat should work.

### Actual Behavior

Content filtering continues.

Console outputs `Content blocker prevented frame displaying http://localhost:5000/ from loading a resource from https://js-na1.hs-scripts.com/20268434.js`.

**Comment by nomasprime** [comment]
Works with `{domain}.local`, apparently issue is specific to `localhost`.

**Comment by ralphneeleman** [comment]
Have the same issue, restarting Safari applies the unchecked 'enabled on this site'

**Comment by mykagr** [comment]
Have the same issue but Safari doesn't need to restart. The box is never unchecked.

**Comment by Birbber** [comment]
@nomasprime Hi! Have you tried to check it on 1.10.4 version?

**Comment by mykagr** [comment]
No. I don’t think I have any problems.

With regards,
Mayank Agrawal

**Comment by Birbber** [comment]
Closing this issue as it's not reproducible in v1.10.4. Please re-open if needed.
