### ISSUE TITLE
Missing text in the Swedish translation

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardForSafari#627]
### Prerequisites

A lot of missing text in the UI after switching to Swedish. 

### Issue Details

* AdGuard for Safari version: 1.9.19
* Environment name and version: Safari 14.1.1 (16611.2.7.1.4)
* Operating System: 11.4

### Expected Behavior

No empty boxes

### Actual Behavior

A lot of empty boxes

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/122881467-de40f280-d343-11eb-9392-e4e33e941de3.png)

![image](https://user-images.githubusercontent.com/15856304/122881859-468fd400-d344-11eb-8b0e-34267a2b568f.png)

![image](https://user-images.githubusercontent.com/15856304/122881751-2a8c3280-d344-11eb-928b-c16761643a3e.png)

</details>

**Comment by malmentm** [comment]
Yes, got this error too
