### ISSUE TITLE
AdGuard shows settings every 48 hours upon update

### ISSUE THREAD

**Issue by tonimelisma** [AdguardTeam/AdGuardForSafari#631]
### Issue Details

* AdGuard for Safari version: 1.9.19
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) 14.1.1
* Operating System: (e.g macOS High Sierra 10.13.6) 11.4
* Filters you use in AdGuard: All of them
* Any other browser extensions you have installed: Bitwarden

### Expected Behavior
Every 48 hours, when AdGuard updates, it asks to restart Safari. When I do so, the AdGuard settings window always shows up. When I close it, sometimes it asks if I want to keep running AdGuard in the background. I always click I do, and to never ask me again. However, the settings window keeps popping up each time anyway.

**Comment by zzebrum** [comment]
may be the same as #633 

@tonimelisma AdGuard installed from App Store?

**Comment by tonimelisma** [comment]
@zzebrum yep looks like the same bug, installed from App store

**Comment by zzebrum** [comment]
@tonimelisma can you try the build from standalone channel? Just download and move to Application folder
https://agrd.io/safari_release

I'm not sure if it's our problem.

**Comment by anastenko** [comment]
@tonimelisma Hi, did you try the build from standalone channel? Did it help?

**Comment by anastenko** [comment]
I'm closing this issue due to no response. Please re-open it if the issue still occurs.
