### ISSUE TITLE
AdGuard for Safari will NOT Update

### ISSUE THREAD

**Issue by RayPicard3n** [AdguardTeam/AdGuardForSafari#639]
### Issue Details

* AdGuard for Safari version: 1.9.13
* Environment name and version: Safari Version 14.1 (15611.1.21.161.7, 15611)
* Operating System: macOS 10.15.7
* Any other browser extensions you have installed: NONE

App Store update to any AdGuard 1.10.xx version will NOT update!! 
I quit AdGuard for Safari before updating
App Store download happens to completion, then the AdGuard AppStore button comes back on and says "Update" AGAIN.
Launch AdGuard for Safari to check version--still version 1.9.13
Other App Store updates work properly.
I repeated the AdGuard update, progressed to completion., THEN reverted back to "update" button AGAIN
This happened with AdGuard version 1.10.4 (July 29, 2021). Also happened with version before 1.10.4

What can I do to get beyond version 1.9.13 ?

**Comment by anastenko** [comment]
@RayPicard3n Hello.
It sounds like some local issue. Could you please delete the current version you have and install v1.10.4 from the store?
Let us know the result once tried.

**Comment by RayPicard3n** [comment]
Looks like deleting the old app and the fresh download of 1.10.4 cleared any problem. I had to restart the Mac to clear some security "feature" that prevented AdGuard extensions from being enabled. After the restart, enabling extensions was OK.

We will have to see if this problem recurs with the next App Store update!! Hope NOT.

**Comment by anastenko** [comment]
@RayPicard3n We'll take a deep look into it before the next update.

**Comment by tvinzz** [comment]
@RayPicard3n, please feel free to reopen this issue if the problem is back again.
