### ISSUE TITLE
CPU Spike on Launch after Hardware Repair

### ISSUE THREAD

**Issue by bobodoll131** [AdguardTeam/AdGuardForSafari#647]
[adg_safari_logs_1631812494858.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/7179793/adg_safari_logs_1631812494858.zip)
* **Version of AdGuard for Safari:**
  * v1.10.4
* **Environment name and version:**
  * Safari 14.1.2 (15611.3.10.1.5, 15611)
* **Operating system and version:**
  * MacOS 10.15.7
* **Filters you use in AdGuard:**
  * Base, Ad Blocking, Privacy, Social Widgets, Annoyances, Security
* **Any other browser extensions you have installed:**
  * Downie, Piper, StopTheMadness

### Expected Behavior
For Adguard to run as it always has, silently and in the background.

### Actual Behavior
After a keyboard/topcase replacement, Adguard uses 100% of CPU when launching. Whether starting together with Safari, or after disabling and re-enabling extensions, launching Adguard will spike CPU usage, CPU temp, and fan use. I've verified that disabling the six Safari extensions associated with Adguard prevents this from occurring, but going into preferences to recheck them results in the aforementioned spiking behavior.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@bobodoll131 Hello!
Is it reproducible all the time?

**Comment by bobodoll131** [comment]
Hi,

Yes, as I mentioned this issue occurs every time Adguard is launched, whether manually or automatically. Re other extensions, turning them off and leaving only Adguard on still results in the same behavior. This is also reproducible in Safari Tech Preview (Release 125 (Safari 14.2, WebKit 15612.1.15.1.12)), fyi.

**Comment by Birbber** [comment]
@bobodoll131 That's a weird situation for sure. 
Most likely the problem is not on AdGuard's end. I'm afraid there's nothing we can possibly do about it.

**Comment by bobodoll131** [comment]
Seeing as this is only an issue with Adguard, with nothing of the sort occurring with the launch of any other installed app or extension somehow, I'll have to take your word for it.

**Comment by Birbber** [comment]
@bobodoll131 We will take some time to test it and try to detect the issue.

**Comment by frankroeder** [comment]
I have a similar issue with Safari 15. The ContentBlockerLoader stresses the CPU when AdGuard is activated. Turning all of the extensions off solves the problem.

**Comment by apricot23** [comment]
> I have a similar issue with Safari 15. The ContentBlockerLoader stresses the CPU when AdGuard is activated. Turning all of the extensions off solves the problem.

This is also happening to me.

**Comment by Birbber** [comment]
@bobodoll131 AdGuard definitely loads the processor while loading all the filters after the application start, but when all the filters has been loaded, the CPU load decreases.

**Comment by edzhao8** [comment]
I've also been experiencing this issue after updating to Safari 15, albeit on macOS Big Sur. It's not every time, but especially after a reboot, when I open Safari, my fan starts spinning like crazy. When I try to quit Safari, the app hangs. Like other posters have observed, it seems like temporarily disabling the extensions for Adguard then restarting Safari help side step the initial CPU spike for me.
