### ISSUE TITLE
Microsoft Office Word Online site lag/freeze a lot

### ISSUE THREAD

**Issue by chungweileong94** [AdguardTeam/AdGuardForSafari#650]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard for Safari:**
  * 1.10.4
* **Environment name and version:**
  * Safari 15.0 (16612.1.29.41.4, 16612)
* **Operating system and version:**
  * MacOS Big Sur 11.6
* **Filters you use in AdGuard:**
  * All the filters in "Ad Blocking" section
* **Any other browser extensions you have installed:**
  * Grammarly
  * Userscript

### Expected Behavior
Works smoothly.

### Actual Behavior
Caused the site to freeze a lot.

### Screenshots
None

### Additional Information
It causes the Microsoft Office Word site to freeze consistently if I trying to adjust one of the tables in my document.

**Comment by Birbber** [comment]
@chungweileong94 Hi!
Are you sure AdGuard causes this issue? I've checked both with AG on and off, and I can't see the difference. Seems like it's laggy even without AdGuard for Safari.

**Comment by chungweileong94** [comment]
> @chungweileong94 Hi!
> Are you sure AdGuard causes this issue? I've checked both with AG on and off, and I can't see the difference. Seems like it's laggy even without AdGuard for Safari.

I don't think so, I tried to disable all the extensions exception AdGuard, I even disabled all the filter exceptions "AdGuard Base Filter", but still lag. The only time where it doesn't lag is when I completely turn off the AG.

**Comment by Birbber** [comment]
@chungweileong94 Pretty weird, 'cause we couldn't reproduce it on several devices. And since you've disabled the filters that could interfere with Microsoft Word that should not be anything from AdGuard that could make it laggy.

**Comment by chungweileong94** [comment]
@Birbber Well, that doesn't make too much sense to me, the only time it doesn't lag is when I disabled the AdGuard. The closer thing I can try is to use the Edge browser with ublock, together with the same filters applied, and the result is way better than in safari with AdGuard. Yeah, I understand that could be safari specific issue, but AdGuard is pretty bad in terms of performance in general, specifically the setting app.
