### ISSUE TITLE
High cpu on macOS

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardForSafari#654]
### Issue Details

* **Version of AdGuard for Safari:**
  * 1.10.4
* **Environment name and version:**
  * Safari 15.0 (16612.1.29.41.4, 16612)
* **Operating system and version:**
  * macOS Big Sur 11.6 (20G165)
* **Filters you use in AdGuard:**
  * Base filter
  * Tracking Protection filter
  * Annoyances filter
  * Fanboy's Annoyances
  * I don't care about cookies
  * French filter
  * own ad filters
* **Any other browser extensions you have installed:**
  * no other extension running

### Expected Behavior
Safari running without high cpu

### Actual Behavior
When I start Safari or update filters (with customs rules), the cpu usage is really high during many seconds (15-30s)

### Screenshots
<details><summary>Screenshot:</summary>

<img width="256" alt="Capture d’écran 2021-10-13 à 13 41 18" src="https://user-images.githubusercontent.com/69631254/137126072-da169e96-98d2-4e7c-bbc3-f8f77395e24b.png">
<img width="196" alt="Capture d’écran 2021-10-13 à 13 41 31" src="https://user-images.githubusercontent.com/69631254/137126077-d00ad809-fb23-4004-9c1b-d2862823bbfc.png">

</details>

**Comment by Birbber** [comment]
@ecatomb Hi! Safari loads the processor while loading all the filters after the application start, but when all the filters has been loaded, the CPU load decreases.
