### ISSUE TITLE
Set Startup at  Login but still must Run it when in Safari

### ISSUE THREAD

**Issue by whldorsey** [AdguardTeam/AdGuardForSafari#655]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by Birbber** [comment]
Closing this issue due to no response. Re-open it if needed.
