### ISSUE TITLE
App is not updating on my mac anymore.

### ISSUE THREAD

**Issue by Slate88** [AdguardTeam/AdGuardForSafari#659]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@Slate88 Hi! Please specify AdGuard for Safari version and Operating System you use.
Did you download it from App Store or [our GitHub repo](https://github.com/AdguardTeam/AdGuardForSafari)?

**Comment by Birbber** [comment]
@Slate88 Any news?

**Comment by Birbber** [comment]
I'm closing this issue due to no response. Please re-open it if needed.
