### ISSUE TITLE
Custom rules do not work on applelife.ru

### ISSUE THREAD

**Issue by iclouny** [AdguardTeam/AdGuardForSafari#662]
AdGuard for Safari version: 1.10.4
Environment name and version: Safari 15.1 (17612.3.3.1.2)
Operating System: macOS Monterey 12.1
There are no other browser extensions.

Website - https://applelife.ru. I create a rule using AdGuard. I check the application of the rule - the content is blocked. After reloading the page, the created blocking rule does not work and the content is not blocked. This applies to all rules - after reloading the page, they do not work.

**Comment by Birbber** [comment]
@iclouny Hi! Have you tried clearing the website's data using Web Inspector? After deleting the cached data, the rule is now visually applied.

**Comment by iclouny** [comment]
> @iclouny Hi! Have you tried clearing the website's data using Web Inspector? After deleting the cached data, the rule is now visually applied.

Yes, I deleted the Safari cache - nothing changes, the rules on https://applelife.ru do not work after updating the window ...

**Comment by Birbber** [comment]
@iclouny Strange, I couldn't reproduce the issue on my end.
@tvinzz Could you check it up, please?

**Comment by iclouny** [comment]
The Adguard error was drastically eliminated by reinstalling the system.
