### ISSUE TITLE
AdGuard For Safari Consuming Too Much CPU Resources

### ISSUE THREAD

**Issue by bongoooooo** [AdguardTeam/AdGuardForSafari#663]
# Problem
AdGuard has been using 400+% CPU most times when launching Safari, and it makes my MacBook Pro CPU heat up to 99 degrees Celsius.
It has been a problem since Big Sur, and upgrading to Monterey did not change anything.
And when it uses too much CPU all ad blocking stops to work temporary.
# System
2020 MacBook Pro, 13 inch, Intel Version
Safari Settings: Only AdGuard extension installed, other settings default.
No network extensions, private relay on.

**Comment by Birbber** [comment]
@bongoooooo Hello!
Safari loads the processor while loading all the filters after the application start, but when all the filters has been loaded, the CPU load decreases. It's not the issue on AdGuard's side.
