### ISSUE TITLE
Adguard IOS taking a long time to refresh filter lists

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdGuardForSafari#666]
I'm not sure what the problem is but for some reason on all my devices it is taking a really long time to refresh or add filters in AdGuard for IOS. I am on the latest IOS version and the latest AdGuard version but I still have this issue. Adguard seems to refresh filters a lot faster in the extension or on my Mac but takes like about 10 minutes on my iPhone.

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardForiOS #1844](https://github.com/AdguardTeam/AdguardForiOS/issues/1844) via [**ZenHub**](https://www.zenhub.com/)
