### ISSUE TITLE
When a filter rule is selected, artifacts appear around the brackets

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#668]
- AdGuard for Safari v.1.10.4
- Safari v.15.1 (17612.2.9.1.20)
- macOS v.12.0.1 (21A559)

When a filter rule is selected, artifacts appear around the brackets.
<img width="908" alt="144661369-5bf996fb-053b-406f-a14a-ecde161e7b2e" src="https://user-images.githubusercontent.com/62497891/144662004-1296dc09-9ae5-4244-824a-d1ba6ce83067.png">

**Comment by Birbber** [comment]
@Oleg-Chashko It works as expected. These paired brackets should be highlighted.
