### ISSUE TITLE
Google popup not being blocked

### ISSUE THREAD

**Issue by tecumsa** [AdguardTeam/AdGuardForSafari#677]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior
The Google popup login should be blocked

### Actual Behavior
It appears on every site that allows google login

### Screenshots
![Screen Shot 2022-01-11 at 9 19 56 PM](https://user-images.githubusercontent.com/58710687/149052518-10c91f44-b002-4d2c-b415-92788517720b.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@tecumsa Please tell what filters are enabled in AdGuard for safari?
What os do you use?

**Comment by tecumsa** [comment]
OS 12.1



Mike

"Americans understand that government is not a force for good, but a great big unintended consequence generator.” — Jay Maynard

**Comment by Birbber** [comment]
@tecumsa Please send us the application logs. Here's what we need you to do:

- Make sure all Safari content blockers are enabled;
- Reproduce the issue and remember the exact time when it happened;
- Open the extension settings --> **Export logs and system info**;
- Send the archive to apple@adguard.com and mention this issue number in the subject.

**Comment by Birbber** [comment]
Thanks, the logs has been received.

**Comment by tecumsa** [comment]
Not fixed.

![Screen Shot 2022-01-20 at 8 54 42 AM](https://user-images.githubusercontent.com/58710687/150352088-054a652d-5b6f-474d-b963-e29ef37613aa.png)

**Comment by Birbber** [comment]
It was mistakenly closed. Already re-opened it.

**Comment by tecumsa** [comment]
👍

Mike

"Quiet the mind, and the soul will speak.” ~ Ma Jaya Sati Bhagavati

**Comment by tecumsa** [comment]
Ok, worked for that site, but not for Pinterest:




Mike

To regret one’s own experience is to arrest one’s own development. — Oscar Wild

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #108129](https://github.com/AdguardTeam/AdguardFilters/issues/108129) via [**ZenHub**](https://www.zenhub.com/)
