### ISSUE TITLE
Ad's appear even if use AdGuard and even if you block elements

### ISSUE THREAD

**Issue by stamatgeorge** [AdguardTeam/AdGuardForSafari#678]

**Comment by Birbber** [comment]
@stamatgeorge Have you tried clearing a webpage's cache or re-installing the application?

**Comment by Birbber** [comment]
@stamatgeorge Any news?

**Comment by Birbber** [comment]
Will close it as a duplicate of [#672](https://github.com/AdguardTeam/AdGuardForSafari/issues/672).

**Comment by stamatgeorge** [comment]
@Birbber  I have tried it with no success 😢 Still the same issue. As soon I restart Safari ads reappear.

Tried it yourself: https://www.tvanouvelles.ca

**Comment by Birbber** [comment]
@stamatgeorge I couldn't reproduce the issue on my end. We'll investigate it within [#672](https://github.com/AdguardTeam/AdGuardForSafari/issues/672), looks like the same issue.

**Comment by stamatgeorge** [comment]
You must have a powerful computer :) 

I tried it on 2 mac laptops and have the same results.

**Comment by stamatgeorge** [comment]
@Birbber If you block the element and then scroll down the page, refresh the page, the element will reapear even though it was blocked. Check screen video I did for you so you can see the issue: https://youtu.be/bQyHhenmO6M

**Comment by Birbber** [comment]
@stamatgeorge Hi, sorry for the late reply. 
It looks like you don't block the entire element. As it can be seen on the video there's a grey area around the block you select. Try to expand the area of selection by moving the slider to max until the entire element is highlighted.
