### ISSUE TITLE
AdGuard keeps launching at login even after I unchecked the "Launch at Login"

### ISSUE THREAD

**Issue by albas99** [AdguardTeam/AdGuardForSafari#683]
- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

* **Operating system and version:**
 MacOS 12.1 Monterey

**Comment by Birbber** [comment]
@albas99 Hi, we already have the issue for this matter [#519](https://github.com/AdguardTeam/AdGuardForSafari/issues/519). I'll close this one.
