### ISSUE TITLE
AdGuard not quitting properly when shutting down MacBook Pro 

### ISSUE THREAD

**Issue by ddt8889** [AdguardTeam/AdGuardForSafari#689]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [* ] I am running the latest version
- [* ] I checked the documentation and found no answer
- [* ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version:  1.10.4

* Environment name and version:  15.3 (17612.4.9.1.8)

* Operating System: macOS Monterey 12.2.1 (21D62)

When shutting down my MacBook Pro and then restarting, I was getting a "your computer shut down because of a problem", I did a look at log files, when I finally manually quit AdGuard before shutting down, the problem went away, when I just shut down without quitting AdGuard that problem returned, maybe AdGuard has a bug under Monterey?

**Comment by Birbber** [comment]
@ddt8889 Hi! Would you mind sharing a crash report with us?

**Comment by Birbber** [comment]
@ddt8889 Any news?

**Comment by Birbber** [comment]
I'm closing this issue due to no response. Feel free to re-open it if needed.
