### ISSUE TITLE
'Launch at login' could not be disabled

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdGuardForSafari#69]
Once enabled, it could not be unchecked.

Related issue:
https://github.com/electron/electron/issues/10880

**Comment by tobiasmuecksch** [comment]
This issue doesn't seem to be present on windows. So it might be a macOS only problem.

**Comment by timirila1** [comment]
Didn't find exact version, but for 2.0.12 this issue have been resolved.

**Comment by timirila1** [comment]
@tobiasmuecksch I suppose it also was fixed for Electron 3.0.x in the last updates.

**Comment by tobiasmuecksch** [comment]
@timirila1 It's present in Electron 3.0.2

**Comment by timirila1** [comment]
@tobiasmuecksch Did you try to update to 3.0.5?
https://github.com/electron/electron/releases/tag/v3.0.5

**Comment by tobiasmuecksch** [comment]
Not yet. Didn't realize that there is an update. Will do tomorrow. Thanks!

**Comment by tobiasmuecksch** [comment]
@timirila1 Yes you are right. Seems to be fixed in 3.0.5

**Comment by tobiasmuecksch** [comment]
@Mizzick Please update electron to 3.0.5 and try again.

**Comment by pronebird** [comment]
@timirila1 which item from changelist claims that it's fixed? It's still broken on 3.0.5.

**Comment by pronebird** [comment]
Works on 3.0.6, presumably should be fixed since 3.0.5. 👍
