### ISSUE TITLE
did I pay?

### ISSUE THREAD

**Issue by Yui-Him** [AdguardTeam/AdGuardForSafari#693]
so Im a kid and i don't have a credit card so whatever things that need money is link to my parents credit card so today i reinstalled adguard and i'm on the latest version and i have acess to all the premium feature i didn't buy the premium plan i use the free one is this a bug ot trail or it auto pay

**Comment by Birbber** [comment]
@Yui-Him Hi! AdGuard for Safari (desktop application) is a free app to use.

**Comment by vozersky** [comment]
@Yui-Him If you by any chance meant https://github.com/AdguardTeam/AdguardForMac you might be on trial version, yeah. Anyway, we don't have in-app purchase in desktop applications, it's done on the website.
