### ISSUE TITLE
Too many filters enabled. Safari cannot use more than 50,000 rules in one group.

### ISSUE THREAD

**Issue by Edwardmunn** [AdguardTeam/AdGuardForSafari#694]
Too many filters enabled. Safari cannot use more than 50,000 rules in one group.

AdGuard Privacy says the following: 'The limit of 50,000 rules has been exceeded. Please disable unnecessary rules for the app to work correctly. Enabled rules at the moment: 55990 (disabled rules: 5990)'

I only have 'AdGuard Tracking Protection filter' enabled.

![Screenshot 2022-03-22 at 19 19 01](https://user-images.githubusercontent.com/40793125/159558778-65df6d42-7849-4431-be5b-4e10b24d1272.png)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)

* **Version of AdGuard for Safari:**
  * 1.10.4
* **Environment name and version:**
  * Safari 15.4
* **Operating system and version:**
  * MacOS 12.3

**Comment by planet0** [comment]
Can confirm I have the same issue as well.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/65204836/159571756-38ba10e6-011e-426e-852d-ac238b764cde.png">

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/65204836/159571798-23a5a988-e7ee-4ede-a814-f5debc54b2aa.png">

**Comment by richardparker** [comment]
I am seeing a very similar error. With just the "AdGuard Tracking Protection filter" enabled I get the following error:
```
The limit of 50,000 rules has been exceeded. Please disable unnecessary rules for the app to work correctly.
Enabled rules at the moment: 55995 (disabled rules: 5995)
```

**Comment by ameshkov** [comment]
We're looking into it, thank you!

**Comment by ameshkov** [comment]
Found the reason. Of the CNAME-trackers generated a list of almost 30k domains which were automatically included into the list. The thing is all those domains can be blocked by only a couple of rules, we don't need to have all 30k there. We removed this tracker temporarily, will replace it later.
