### ISSUE TITLE
Kernel panic: com.apple.Safari.ContentBlockerLoader

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#704]
Version 1.11.3: 
Heavy load on the processor in: "com.apple.Safari.ContentBlockerLoader". 
It ends up rebooting due to "Kernel panic".

_If you have any questions, ask._

---

<img width="1324" alt="Screen Shot 2022-04-17 at 21 49 49" src="https://user-images.githubusercontent.com/62497891/163730506-13e3cf86-b814-4966-9448-ba34e6b21414.png">

---

[adg_safari_logs_1650225976620.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/8502343/adg_safari_logs_1650225976620.zip)
[Kernel panic.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/8502338/Kernel.panic.zip)
[com.apple.Safari.ContentBlockerLoader-2022-04-17-213701.ips.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/8502341/com.apple.Safari.ContentBlockerLoader-2022-04-17-213701.ips.zip)

---

* AdGuard for Safari version: v.1.11.3
* Environment name and version: Safari v.15.4 (17613.1.17.1.13)
* Operating System: macOS v.12.3.1 (21E258)
* Filters you use in AdGuard:
<img width="960" alt="Screen Shot 2022-04-17 at 21 58 46" src="https://user-images.githubusercontent.com/62497891/163730286-b316f070-3e2b-4bab-8222-1cdf5753be61.png">

**Comment by Birbber** [comment]
@Oleg-Chashko Hi! Quite an unpleasant situation for sure. I've tried to reproduce the issue on my end with no luck.
It's better to report to Apple on this matter, since the issue seems to be on their side.
Will transfer the logs to our devs though. Maybe there's something they might find.

**Comment by Oleg-Chashko** [comment]
@Birbber Hi! 
1. Unfortunately this started in v.1.11.3.
2. I have found how to reproduce the issue. This is the action which leads to "Kernel panic". But it's not the action that leads to a real "Kernel panic". But the issue is absent if the add-in is disabled in Safari.

https://user-images.githubusercontent.com/62497891/163837090-c5ff14b6-49ec-4f84-a2cb-f44326cd46c5.mp4

**Comment by Birbber** [comment]
@Oleg-Chashko You should definitely report this issue to Apple. There’s nothing we can do on our end.

**Comment by Oleg-Chashko** [comment]
@Birbber 
Ok.

**Comment by gedw99** [comment]
@Birbber 

quick question, as this is really a PITA on mac.

Presuming that i can uninstall Aguard for Chrome and Adguard for Safari, and let Adguard for Mac do it all ?
