### ISSUE TITLE
Malaysian Ads continue on while using Adguard on safari in Malaysia

### ISSUE THREAD

**Issue by 240360** [AdguardTeam/AdGuardForSafari#706]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I'm using the latest version of Adguard for Safari but after initially getting no ads on Dailymotion now I'm getting Malaysian Ads (as I'm based in Malaysia). All filters are on. Please help me to get rid of them! Thanks

**Comment by 240360** [comment]
I'm using the latest version of Adguard for Safari but after initially getting no ads on Dailymotion now I'm getting Malaysian Ads (as I'm based in Malaysia). All filters are on. Please help me to get rid of them! Thanks

**Comment by Birbber** [comment]
@240360 Hi! There's no need in turning all filters on. You should enable only those you need. (Like AdGuard Base filter, AdGuard Annoyances filter, etc. )
Try to update the filters and see if anything's changed, and also check `content blockers`section (General --> Content blockers). Make sure there are no errors.

**Comment by Birbber** [comment]
@240360 Any news?

**Comment by Birbber** [comment]
I'm closing this issue due to no response. Please re-open if needed.
