### ISSUE TITLE
Unchecking "Enabled on this site" does not disable the annoyances filters for the site

### ISSUE THREAD

**Issue by piejanssens** [AdguardTeam/AdGuardForSafari#718]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.11.4
* Environment name and version: Safari 15.5 (17613.2.7.1.8)
* Operating System: macOS 12.4.0
* Filters you use in AdGuard: ads, privacy, annoyances (EasyList Cookie List, I don't care about cookies, AdBlock warning removal list), language-specific (NL)

### Expected Behavior

If I uncheck "Enabled on this site", I expect any AdGuard to no longer affect the site in any way.

### Actual Behavior

Some filters are still being applied. I am certain that this is a bug in AdGuard as I can get the wanted effect by disabling the AdGuard all-together via the "Pause AdGuard for Safari" option.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@piejanssens Hi! Could you give an example of the webpage so I could check it on my end?

**Comment by piejanssens** [comment]
Hi @Birbber,

1. Enable the "I don't care about cookies" annoyance filter.
2. Visit https://www.era.be/nl/te-koop
3. Notice you can't scroll
4. Disable AdGuard on the site
5. Notice you still can't scroll...
7. "Pause AdGuard for Safari"
8. Accept the cookies
9. Notice you can scroll

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #121425](https://github.com/AdguardTeam/AdguardFilters/issues/121425) via [**ZenHub**](https://www.zenhub.com/)

**Comment by piejanssens** [comment]
I donˋt get it. It's clearly a bug and both this and the new issue you created are closed...
