### ISSUE TITLE
Unexpected "filters update error" notification

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#73]
## Steps to reproduce

1. Go to "Filters" settings and enable all filters groups there
2. Go to "General" settings and uncheck "use optimized filters"
3. Wait a bit till the "Too many filters enabled." warning message appears (that's expected)
4. Check the notifications -- you'll see a "Failed to get updates" notification -- **which is wrong**;
5. Check the "use optimized filters" again a couple of times -- the filters update will never finish and eventually, you'll get the "failed" notification again

## Expected

1. Updates go smoothly
2. Switching "use optimized filters" helps get rid of "too many filters enabled" warning

**Comment by zebrum** [comment]
can not reproduce
