### ISSUE TITLE
AdGuard for Safari app intercepts Cmd+R shortcut globally when backgrounded

### ISSUE THREAD

**Issue by klanchman** [AdguardTeam/AdGuardForSafari#730]
### Issue Details

When in the background, the AdGuard for Safari app is preventing other apps (e.g. Safari, Xcode) from responding to the Cmd+R shortcut.

* AdGuard for Safari version: 1.11.5
* Environment name and version: Safari 15.5 (17613.2.7.1.8)
* Operating System: macOS Monterey 12.4 (21F79)
* Filters you use in AdGuard: N/A
* Any other browser extensions you have installed: N/A

### Expected Behavior

1. Open AdGuard app
2. Close it (Cmd+W)
3. Go to Safari
4. Try to reload a page with Cmd+R
    - Expected: the page reloads
5. Try to run an app in Xcode with Cmd+R
    - Expected: the app runs

### Actual Behavior

Safari: the page does not reload.
Xcode: the app does not run.

### Additional Information

**Workaround:** If I leave the AdGuard app running, the Cmd+R shortcut works as expected in other apps. Even hiding it with Cmd+H allows the shortcut to continue working.

I assume this is related to 6c3bc44490ed3f57cc10de4391faa9a873ef5559 / #728.

**Comment by ameshkov** [comment]
This is super annoying, we'll roll out a hotfix soon.

**Comment by sweetppro** [comment]
Ah that’s what it is!
It’s super annoying trying to refresh the page in Safari

**Comment by klanchman** [comment]
Latest update on the Mac App Store seems to fix the issue, thank you! 🎉
