### ISSUE TITLE
AdGuard for Safari crashing using macOS Monterey

### ISSUE THREAD

**Issue by brkmgrcn** [AdguardTeam/AdGuardForSafari#733]
Steps To Reproduce:

1. Use MacBook Air (M1, 2020) on macOS Monterey 12.4 (21F79) 
2. Install AdGuard for Safari (1.11.6)
3. The app launches and crashes after a few seconds.

Here is the crash log:
[crash.log](https://github.com/AdguardTeam/AdGuardForSafari/files/9056224/crash.log)

**Comment by Versty** [comment]
@brkmgrcn Hi! 
We took this issue to work. 
Crashes may be caused by wrong application location. 
Are you launching AdGuard for Safari from the Applications folder?

**Comment by Versty** [comment]
@brkmgrcn Is the issue still actual?

**Comment by Versty** [comment]
@brkmgrcn Closed due to inactivity. Please reopen if needed.
