### ISSUE TITLE
hope add HalfLife  rule

### ISSUE THREAD

**Issue by Mircc** [AdguardTeam/AdGuardForSafari#735]
This rule contains most of the rules in the Chinese Internet，eg：Tencent, Youku, iqiyi, watermelon video and other video websites to advertise and merge EasylistChina、EasylistLite、CJX'sAnnoyance rule

rule address：https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt

**Comment by Versty** [comment]
@Mircc Hi! 

You can use this list of the rules in the Custom rules option. 
Click on the AdGuard icon in the Safari browser -> Gear -> Filters -> Scroll down to the bottom -> Custom -> Add custom filer -> Upload this filter list as txt file.
