### ISSUE TITLE
Bug - single page app url blocking

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardForSafari#736]
If I block for example the homepage of a single page app, use my browser history to navigate to a non-homepage part of the site that is not blocked, then navigate to the homepage, Adguard does not block the page.

AdGuard for Safari
Version 1.11.6 (216)

User filter:
`/.*facebook.com/?$/`

1. Go to http://facebook.com/notifications
2. then click F logo in top left which goes to https://www.facebook.com/
3. Then the page loads

Reported by: helpdesk ID 618038.

**Comment by tvinzz** [comment]
That's safari problem:
SPA navigation works through `window.history` and when you go back there is no page reload and safari can't handle it.
