### ISSUE TITLE
Filtering is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#741]
@adguard-bot commented on [Wed Aug 03 2022](https://github.com/AdguardTeam/AdguardFilters/issues/126112)

### Issue URL (Ads)
 [https://www.packagetrackr.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.packagetrackr.com%2F)
### Comment
Username: @twopir
> AdGuard isn't working at all. It reports 7 filters, 123651 rules, 20642 advanced rules, and a last update of August 3, 2022 at 1:03 AM (UTC), but every web page I visit is drenched in ads. Turning it on and off has not worked. Updating filters has not worked. Uninstalling and reinstalling has not worked. Please advise.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/dK3bG0t.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Safari v1.11.6
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>I don't care about cookies, <br/>Dandelion Sprout's Annoyances List<br/><br/><b>Security:</b><br/>NoCoin Filter List

---

@Alex-302 commented on [Wed Aug 03 2022](https://github.com/AdguardTeam/AdguardFilters/issues/126112#issuecomment-1203876127)

@twopir Hi.
Cannot reproduce with your settings. 
Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window 30-60 seconds, because iOS will breaks configuration process.

---

@twopir commented on [Wed Aug 03 2022](https://github.com/AdguardTeam/AdguardFilters/issues/126112#issuecomment-1204092484)

@Alex-302 I have already done this, several times, to no effect. Also I am not using Safari on iOS, this is on macOS.

Is there a way to remove all settings and start fresh, to rule that out? I have asked this several times and have not gotten an answer.

---

@Alex-302 commented on [Wed Aug 03 2022](https://github.com/AdguardTeam/AdguardFilters/issues/126112#issuecomment-1204404247)

> Also I am not using Safari on iOS, this is on macOS.

the steps are the same, just content-blockers in browser's settings)

---

@twopir commented on [Wed Aug 03 2022](https://github.com/AdguardTeam/AdguardFilters/issues/126112#issuecomment-1204438242)

again, as stated in this, and previous issues, **i have tried those steps already, to no effect**

for the third time this week:

Is there a way to remove all settings and start fresh, to rule that out? I have asked this several times and have not gotten an answer.

---

@VladisLoveZh commented on [Thu Aug 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/126112#issuecomment-1205146476)

> again, as stated in this, and previous issues, **i have tried those steps already, to no effect**
> 
> for the third time this week:
> 
> Is there a way to remove all settings and start fresh, to rule that out? I have asked this several times and have not gotten an answer.

Hello, please [reinstall](https://kb.adguard.com/en/safari/installation#how-to-uninstall-adguard-for-safari) the app. 

---

@twopir commented on [Thu Aug 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/126112#issuecomment-1205398716)

@VladisLoveZh I performed this action. The extension retains its settings after reinstall. How do I actually remove all settings and start over?

**Comment by Versty** [comment]
@Alex-302 @twopir @VladisLoveZh
Follow steps below to fully uninstall AdGuard for Safari: 
1. Uncheck all AdGuard for Safari extensions in **Safari -> Preferences -> Extensions** (if available)
2. Open **Finder** and press Shift+Command+G
    - Remove AdGuardSafariApp folder from **~/Library/Application Support** directory
    - Remove from **~/Library/Containers** - all directories started with AdGuard-
    - Remove TC3Q7MAJXF.com.adguard.safari.AdGuard folder from **~/Library/GroupContainers** directory
    - Remove com.adguard.safari.AdGuard.plist from **~/Library/Preferences** 
3. Open **Activity Monitor** and force quit all "cfprefsd" processes 
4. Remove AdGuard for Safari from **Applications**

**Comment by twopir** [comment]
Thank you! After doing this action and reinstalling AdGuard, it has begun to function again.

**Comment by twopir** [comment]
@Versty can i suggest that this procedure be documented on the [how to reinstall](https://kb.adguard.com/en/safari/installation#how-to-uninstall-adguard-for-safari) page?

**Comment by Versty** [comment]
@twopir I'm glad it helped. 
Perhaps we'll add information about advanced uninstallation to the knowledge base later.
