### ISSUE TITLE
Can't rate AdGuard from the popup, Submit button is greyed out

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardForSafari#747]
It doesn't matter whether 1 or 5 stars is selected, the Submit button remains greyed out.

<img width="532" alt="Screenshot 2022-09-08 at 22 20 45" src="https://user-images.githubusercontent.com/95468948/189120658-d92e1113-e166-42b9-bc5f-b03ac18bef9d.png">

macOS Version 13.0 Beta (22A5331f)

**Comment by Versty** [comment]
@jslawler Hi! This window is a part of the functionality provided by Apple. The appearance of the bug is probably related to Ventura beta version and hopefully will be fixed with the macOS 13.0 release.
