### ISSUE TITLE
Web error 104

### ISSUE THREAD

**Issue by tecumsa** [AdguardTeam/AdGuardForSafari#748]
When I go to the link below I get a Web Error Domain 104 error, when I pause AdGuard it opens with no problems. This has happened on different sites, but this is the first time I had the time to find out where the error was coming from.

[The link](https://duckduckgo.com/y.js?ad_domain=fast%2Dgrowing%2Dtrees.com&ad_provider=bingv7aa&ad_type=txad&eddgt=UGQMSR7OLvTyMETf2HRtQQ%3D%3D&rut=ca2e32aa1943c032d0c6ba87da53a21c04f6a9eb9b017dda5badac83173b3750&u3=https%3A%2F%2Fwww.bing.com%2Faclick%3Fld%3De8A9x_azESPk36Rum005LE%2DTVUCUz1o6Qn7YQe1ay4KuWa2lr20QdHIZc5_XghzTBfN_y7NJgqPWeNprZlf5r%2DDypDYFfEDpCTUjtQjtpdjMIpXEoWz49L_hcCK5j6vatkunETpf9nv7EiAGE9y%2DduEjTiWAgp91sqdnPBXmQ5VzuKQw7ZG4VVaADirrpMA9dWyey5xA0Iiegt2lJiQVTnGryyV3OxoNinz5aB0WlIczDliwia6Lql8jaOWGgWA4Y4qJl99_HBUX5eD2e8FHFv376OtaEuDuflX8E0SSUnHxJCWZe%2D4hmRd4AcF%2D7MbBIw%2D7DMdrrTbOgegZdUXbLFbTX2UQJ0l9X6G82l_uxqVDsl2euj1GR5%2DJ%2DmB3bon9pjKqelLmZCPZuB7TAuVWVfTO46HgFx5CBvaZ8%2Dcl7MxgDv7vbbfv1QhZcI9dcUtVMd75d%2D05iC48vcAgK1Ph04HmFuFut14teeJCmsBs_mhX8pVbJaGD_VZAUbCFdYPx2nclCqLZQ%2DsDe_qaYqa7w2DpdB69Ohnwfet8OJFwbPDwTYMrFTnD74Ss7gyCi9uMRTqwL9A9npy8mhLNnPsqj847N2lnQH3Sh89iFjGiRpTKokbMamic4GNTN2putj07_nZwcHFliWu%2DmeqQ_eYuQ4iU73miI_0I2xlf8eXFf7FU%2DIByDjKU8u%2Dyn381pSnqw5VhI4QDUhb17zg7LN5M2rb0Z4RP9AbtJJwLcnlEAA9UEkN4MJ80J2lW8JIRGxKIXW2Jqekw%26u%3DaHR0cHMlM2ElMmYlMmZhZC5hdGRtdC5jb20lMmZzJTJmZ28lM2JhZHYlM2QxMTA1MjIwNDEyNDkxNCUzYmVjJTNkMTEwNTIyMDQxNTI3NDUlM2JjLmElM2QzNzY1MTA0MTQlM2JzLmElM2RiaW5nJTNicC5hJTNkMzc2NTEwNDE0JTNiYXMuYSUzZDEyMzM2NTIyNzgxODMzNjglM2JjLm4lM2QoTVQpJTI1MjAoRkdUKSUyNTIwU2VhcmNoJTI1MjAtJTI1MjBOQiUyNTIwLSUyNTIwRnJ1aXQlMjUyMC0lMjUyME90aGVyJTNicC5uJTNkKE1UKSUyNTIwKEZHVCklMjUyMFNlYXJjaCUyNTIwLSUyNTIwTkIlMjUyMC0lMjUyMEZydWl0JTI1MjAtJTI1MjBPdGhlciUzYmFzLm4lM2Rsb3didXNoJTI1MjBibHVlYmVycnklM2JxcGIlM2QxJTNiJTNmYmlka3clM2RkZWZhdWx0a2V5d29yZCUyNmR2YyUzZGMlMjZoJTNkaHR0cHMlMjUzQSUyNTJGJTI1MkZ3d3cuZmFzdC1ncm93aW5nLXRyZWVzLmNvbSUyNTJGcHJvZHVjdHMlMjUyRmxvd2J1c2gtYmx1ZWJlcnJ5JTI2bXNjbGtpZCUzZGUxNjhlNDYxYTY4ODExZTA0N2MwODc3Yzc2ZWRkYjlhJTI2dXRtX3NvdXJjZSUzZGJpbmclMjZ1dG1fbWVkaXVtJTNkY3BjJTI2dXRtX2NhbXBhaWduJTNkKE1UKSUyNTIwKEZHVCklMjUyMFNlYXJjaCUyNTIwLSUyNTIwTkIlMjUyMC0lMjUyMEZydWl0JTI1MjAtJTI1MjBPdGhlciUyNnV0bV90ZXJtJTNkbG93YnVzaCUyNTIwYmx1ZWJlcnJ5JTI2dXRtX2NvbnRlbnQlM2Rsb3didXNoJTI1MjBibHVlYmVycnk%26rlid%3De168e461a68811e047c0877c76eddb9a&vqd=3-242349138561409058395860605329734079630-197703259417691598906245034783282000224&iurl=%7B1%7DIG%3DD0DCFAC65212415E8EEB204984F4445C%26CID%3D2E947FDEE0E1674832146DC2E1076609%26ID%3DDevEx%2C5048.1)

**Comment by Versty** [comment]
@tecumsa Hi! 
This error probably related to one of the filters. Please, tap on the AdGuard icon in the Safari browser, select the `Report an issue` option and fill in the web form. Here is a [detailed guide](https://kb.adguard.com/en/technical-support/reporting-tool#form).
