### ISSUE TITLE
Adguard for Safari - Too many filters enabled...but which group!?

### ISSUE THREAD

**Issue by bonerpope** [AdguardTeam/AdGuardForSafari#749]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [] I checked to make sure that this issue has not already been filed

### Problem Description

Too many filters enabled in one group...but which group? I have no idea which group is over the limit. How do I fix this if I can't figure out which one?

**Comment by Versty** [comment]
@bonerpope Hi! 
Please open **Settings** -> **General** -> **Content blockers**, the problematic group should be shown.
