### ISSUE TITLE
Anti-adblock banner on https://rus.delfi.lv 

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdGuardForSafari#754]
@innervisionteam commented on [Thu Oct 27 2022](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2217)

        Не повторяется. Попробуйте обновить фильтры, а затем перезапустить контент блокеры в настройках Сафари - сперва нужно подождать примерно минуту на их применение, а затем открыть сайт.

_Originally posted by @zloyden in https://github.com/AdguardTeam/AdguardFilters/issues/133295#issuecomment-1293099468_
      

---

@innervisionteam commented on [Thu Oct 27 2022](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2217#issuecomment-1293378410)

Не помогло. Фильтры обновлены и контент блокеры перезапущены. Ждал около 5 минут и затем перезапустил сайт. Проблема не пропала.

---

@maximtop commented on [Fri Oct 28 2022](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2217#issuecomment-1294912722)

сафари расширение в другом репозитории https://github.com/AdguardTeam/AdGuardForSafari

**Comment by innervisionteam** [comment]
делал все по инструкции. не работает. даже переустановил заново. по прежнему определяется сайтом.

**Comment by Versty** [comment]
@innervisionteam 
Мы пробовали повторить проблему, но на наших устройствах этот баннер блокируется успешно. 
Поэтому для диагностики потребуются логи с вашего устройства. 

1. Убедитесь, что все **Блокировщики контента** включены в настройках Safari;
2. Проверьте, что в настройках расширения **Общее -> Блокировщики контента** напротив каждой категории блокировщиков стоит зеленая галочка;
2. Воспроизведите проблему и запомните точное время воспроизведения;
3. Откройте настройки приложения --> Выберите **Экспортировать логи и информацию о системе**;
4. Отправьте полученный архив по адресу `apple@adguard.com`. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by innervisionteam** [comment]
Сделал все по инструкции и отправил вам на почту

**Comment by innervisionteam** [comment]
Спасибо. надеюсь получится решить проблему. Перепробовал уже все варианты, ничего не помогло.

**Comment by Versty** [comment]
@innervisionteam Пожалуйста, пришлите ваши настройки. Вполне вероятно что именно они могли вызвать проблему. 

В настройках откройте вкладку **Общее**, выберите опцию **Экспортировать настройки** и отправьте этот файл нам на почту `apple@adguard.com`. 

Также, нам необходимо понимать какую версию Сафари вы используете. 
Чтобы узнать свою версию, откройте Safari -> O приложении Safari.

**Comment by innervisionteam** [comment]
Выслал все что вы просили на указанную почту

**Comment by Versty** [comment]
@innervisionteam Пытались воспроизвести проблему с вашими настройками на такой же версии Сафари, но безуспешно. Баннер, по-прежнему, не показывается. 

Давайте попробуем сделать полное удаление, а потом чистую установку. 

1. Снимате галочки расширения AdGuard for Safari в настройках Сафари **Safari -> Preferences -> Extensions** 
2. Удалите приложение AdGuard for Safari из **Applications**
3. Откройте **Finder** и используйте Shift+Command+G
    - Удалите AdGuardSafariApp директорию из **~/Library/Application Support** 
    - Удалите из **~/Library/Application Scripts** - все директории начинабщиеся с com.adguard.safari
    - Удалите из **~/Library/Containers** - все директории начинающиеся с AdGuard-
    - Удалите TC3Q7MAJXF.com.adguard.safari.AdGuard из **~/Library/GroupContainers** 
    - Удалите com.adguard.safari.AdGuard.plist из **~/Library/Preferences** 
4. Откройте **Activity Monitor** и завершите все "cfprefsd" процессы

Затем скачайте AdGuard for Safari из AppStore и установите.

**Comment by innervisionteam** [comment]
К сожалению данный способ тоже не помог. все сделал по инструкции. Поставил все с нуля и проблема по прежнему присутствует.
