### ISSUE TITLE
Filter update error - ongoing

### ISSUE THREAD

**Issue by fazer1k143** [AdguardTeam/AdGuardForSafari#756]
On a manually requested update of filters earlier this week I encountered an error notification which has appeared regularly ever since as follows:

"AdGuard Other
The limit of 150000 rules has been exceeded. Please disable unnecessary rules for the app to work correctly.
Enabled rules at the moment: 50711 (disabled rules: -99289)
Enabled: AdGuard DNS filter and User rules"

I have never encountered this issue before and only my Macbook Pro is affected (my iPad is NOT affected), and is updating as normal. Seems to be a Mac issue only (at least for me).

Safari: Version 16.1 (17614.2.9.1.13, 17614)
Mac: Monterey version 12.6.1
Adguard: Version 1.11.7 (220)

**Comment by tvinzz** [comment]
@fazer1k143, please provide AdGuard for Safari logs.

**Comment by fazer1k143** [comment]
Logs attached. I also attempted to attach the settings files but this site system would not allow that. Thanks.

[adg_safari_logs_1667818273104.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/9950722/adg_safari_logs_1667818273104.zip)

**Comment by fazer1k143** [comment]
@tvinzz (Forgot to tag you when I sent the logs, above.)

**Comment by fazer1k143** [comment]
@tvinzz @maximtop @ameshkov No change here - still not fixed
<img width="1072" alt="Screenshot 2022-11-10 at 22 31 09" src="https://user-images.githubusercontent.com/109391397/201220983-48432122-f6de-4ce2-8ae6-1d2438cb3277.png">

**Comment by maximtop** [comment]
@fazer1k143 fix will be released next week

**Comment by fazer1k143** [comment]
Still not fixed yet, here.

**Comment by maximtop** [comment]
> Still not fixed yet, here.

The update is on the way. Sorry, it took more time than I was expecting.

**Comment by fazer1k143** [comment]
@tvinzz @maximtop @ameshkov Not sure why this has been closed as there is no change here.
<img width="1072" alt="Screenshot 2022-11-25 at 08 13 34" src="https://user-images.githubusercontent.com/109391397/203933945-077a4852-ce5d-468e-adb8-c18b81136ecc.png">

**Comment by Versty** [comment]
@fazer1k143 Hi! 
Have you updated to the last version of the app? 
AdGuard for Safari 1.11.8 is already out in the AppStore. 
If so, please, check for the filters update in the Filters tab.

**Comment by fazer1k143** [comment]
No I hadn’t because updates are normally suggested by the app store automatically unless there is some disadvantage to the user through updating. Fixed now though. Thanks.
