### ISSUE TITLE
Too many filters enabled

### ISSUE THREAD

**Issue by klausness** [AdguardTeam/AdGuardForSafari#758]
* AdGuard for Safari version: 1.11.7
* Environment name and version: Safari 14.1.2 (14611.3.10.1.7)
* Operating System: MacOS Mojave 10.14.6
* Filters you use in AdGuard: AdGuard Base Filters, Annoyances, Tracking
* Any other browser extensions you have installed:

### Expected Behavior
Filters are loaded

### Actual Behavior
Get message stating that there are too many filters in the filter group.  Disabling AdGuard Base Filters clears the message but makes AdGuard useless.  AdGuard Base Filters is the only enabled list in its group, and disabling other groups does not clear the message, so the issue appears to be with AdGuard Base Filters. 

### Additional Information
My guess is that a recent update to the AdGuard base filters increased the number of filters above the maximum allowed in Safari 14.  I believe later versions of Safari allow more filters, but Mojave does not support Safari 15 or later.

**Comment by Versty** [comment]
@klausness got it, already fixed. 
Please check for filters update, then restart Safari.

**Comment by klausness** [comment]
@Versty, thanks, working again after a filter update.

**Comment by klausness** [comment]
@Versty, it's back....
