### ISSUE TITLE
How to determine which filter group is too large?

### ISSUE THREAD

**Issue by maciboy** [AdguardTeam/AdGuardForSafari#759]
Hi,
I get the warning that a filter group is too large for Safari.
But how to find out which one it is?

Thanks!
![Bildschirmfoto 2022-11-11 um 09 44 59](https://user-images.githubusercontent.com/19333006/201301908-bd30e6c0-e032-443c-8961-dcc517a6ba06.png)

**Comment by Versty** [comment]
@maciboy Go to General -> Content blockers. 
Seems like you are using Safari 16, this issue is known and will be fixed soon!

**Comment by maciboy** [comment]
Wow, thanks for the quick reply!
Correct, Safari 16 on macOS 12.6.

So, does this mean, that there is no too large filter group but only a bug indicating this?
![Bildschirmfoto 2022-11-11 um 10 09 41](https://user-images.githubusercontent.com/19333006/201306248-f2313a86-91c2-458c-8ebf-639052e9e6df.png)

Btw: I'm using the TestFlight betas, so a fix should arrive faster for me :P

**Comment by Versty** [comment]
@maciboy This bug is functional, not visual. 
As a temporary solution, I would recommend you to disable unnecessary filter lists, for example AdGuard DNS filter.

**Comment by Versty** [comment]
@maciboy Disabling `Dandelion Sprout's Annoyances List` might also help, it contains lots of rules.
