### ISSUE TITLE
Misspelling/typo in German translation for "App rating"

### ISSUE THREAD

**Issue by maciboy** [AdguardTeam/AdGuardForSafari#760]
Hi,
I found a minor misspelling/typo for German in the current version 1.11.7 (220).

"Rate the app" is "App **bewerten**" in German
![Bildschirmfoto 2022-11-11 um 10 15 10](https://user-images.githubusercontent.com/19333006/201307999-2914a310-c6d4-40a5-8c55-79cda728b32d.png)

**Comment by maximtop** [comment]
Already been fixed in v1.11.8
