### ISSUE TITLE
Add filters update interval setting

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#77]
First of all, filters auto-update seem to not fully work. Filters are updated in background, but "Last update" does not change in UI.

Second, just like in the browser extension, we should add "filter interval" setting (with the same options).

**Comment by tiiiecherle** [comment]
That's a good idea. Corresponding with [this](https://github.com/AdguardTeam/AdGuardForSafari/issues/78#issuecomment-438184496) comment please make sure the auto-filter-update is working if "only" the safari adguard extension is enabled and the app itself and the safari icon extension are not enabled. Thanks a lot.

**Comment by ameshkov** [comment]
> please make sure the auto-filter-update is working if "only" the safari adguard extension is enabled 

We should only check for filters updates automatically if "content blocker" extension is enabled in Safari.

> and the app itself and the safari icon extension are not enabled. 

The updates are handled by the Mac AppStore, we don't control it.
