### ISSUE TITLE
Suppress AdGuard pop-up / splash on load

### ISSUE THREAD

**Issue by neutralrhomboid** [AdguardTeam/AdGuardForSafari#775]
Hello! Whenever I load up Safari I get the very annoying pop-up about AdGuard to simply indicate that it's loaded and running fine. I would like to be able to suppress this pop-up as it's just another window that needs to closed, and doesn't serve me any function.

Is there some way to stop that from happening, or a checkbox I've missed somewhere in the configuration?

Sincerely,

Saif

**Comment by Versty** [comment]
@neutralrhomboid Hi! 
If you launch AdGuard for Safari from the extension icon in the Safari browser, there won't be any annoying pop-ups. 
Click the AdGuard for Safari icon -> Run AdGuard.
