### ISSUE TITLE
Too Many Filters Enabled (again)

### ISSUE THREAD

**Issue by klausness** [AdguardTeam/AdGuardForSafari#776]
* AdGuard for Safari version: 1.11.8
* Environment name and version: Safari 14.1.2 (14611.3.10.1.7)
* Operating System: MacOS Mojave 10.14.6
* Filters you use in AdGuard: AdGuard Base Filters, Annoyances, Tracking
* Any other browser extensions you have installed:

### Expected Behavior

Filters are loaded

### Actual Behavior

Get message stating that there are too many filters in the filter group. Disabling AdGuard Base Filters clears the message but makes AdGuard useless. AdGuard Base Filters is the only enabled list in its group, and disabling other groups does not clear the message, so the issue appears to be with AdGuard Base Filters.

### Additional Information

This appears to be a recurrence of issue #758 

My guess is that a recent update to the AdGuard base filters increased the number of filters above the maximum allowed in Safari 14. I believe later versions of Safari allow more filters, but Mojave does not support Safari 15 or later.

**Comment by crgmrgn** [comment]
Same behaviour here (v1.11.8) running on MacOS 10.13.6, looks like an update in the last 24hrs of the base filters has caused ADG to add ~20k+ (guess, I wasn't monitoring the numbers too carefully before the fault showed up) to the filter list, popping the 50k limit.

**Comment by ameshkov** [comment]
Yeah, you're right, the base filter is too large. Please check the filters updates, it should be okay now.

**Comment by klausness** [comment]
Confirmed as fixed after filter update.
