### ISSUE TITLE
Do not force the use of Safari Icon

### ISSUE THREAD

**Issue by FJdeKermadec** [AdguardTeam/AdGuardForSafari#78]
As far as I can tell, the AdGuard menu application refuses to display app preferences when the Safari Button is not enabled in Safari → Preferences → Extensions. I believe this is an issue, and possibly a security issue that will hinder AdGuard’s adoption.

### Steps to reproduce

1. Install AdGuard for Safari from the App Store
2. Enable the AdGuard extension in Safari
3. Keep the AdGuard Button disabled
4. Use the AdGuard Menu Bar item → Preferences

### Expected behavior

The Preferences window should open, listing all the available filtering options in the usual format.

### Actual behavior

A blocking tutorial replaces the window, explaining how the user can (and should, and must) enable the AdGuard for Safari Button. There seems to be no way of bypassing this.

The AdGuard for Safari content blocking extension requires no access to webpages and can therefore be safely enabled by all users in all environments. The Button requires access to the full web page and the user’s complete history, making it more of a security risk in case of a supply chain attack (see CCleaner and others).

Users might legitimately want to use AdGuard for Safari and to edit the Whitelist (and toggle other filter lists) without wanting to use (or needing to use) the Button itself.

Furthermore, the Button is an extra extension to enable in Safari. When memory is constrained or multiple extensions are already running (for whatever reason), users may legitimately want to use AdGuard for Safari all the while keeping its memory footprint as small as possible.

### Your environment

* AdGuard for Safari version: 1.0.1
* Environment name and version: Safari 12.0.1 (14606.2.104.1.1)
* Operating System: macOS Mojave 10.14.1 (18B75)

**Comment by ameshkov** [comment]
Makes sense, thank you!

**Comment by superlex** [comment]
Also, if Safari Icon is not enabled and AdGuard is launched on login, the full app is opened as well and it asks for enable Safari Icon.

**Comment by tiiiecherle** [comment]
In addition to my question [here](https://github.com/AdguardTeam/AdGuardForSafari/issues/84#issuecomment-438182108) in my point of view it should be enough to enable "only" one (the adguard) safari extension for full functionality and updating filter lists. I don't know how it is right now.

Opening the app itself (manually or on autostart) and the safari icon button should be optional and for customizing / changing settings only.

Thanks for all the hard work. Really appreciated.

**Comment by Shnub** [comment]
I agree with @tiiiecherle, it would be nicer and also much clearer for the user if only one instance of AdGuard (namely, the basic browser extension) were required; all else should be for configuration only and on a when-needed basis.

**Comment by ameshkov** [comment]
@timirila1 one note about implementation. If we detect that Safari icon extension is disabled, we should show a small message in the UI (@AlikhanAliev will assist you)
