### ISSUE TITLE
I still see ads... How can I completely remove them...

### ISSUE THREAD

**Issue by AsafElbaz** [AdguardTeam/AdGuardForSafari#782]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@AsafElbaz Hi! 
Please describe in detail what is not working as expected. 
Also provide additional information about: 

- AdGuard for Safari version:
- Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
- Operating System: (e.g macOS High Sierra 10.13.6)
- Filters you use in AdGuard:
- Any other browser extensions you have installed:

**Comment by AsafElbaz** [comment]
When I surf I still see ads… 
using
Mac OS monterey version 12.6
Safari Version 16.0
Filters are activated once I see an ad (I choose block an element)- I’d rather have it done automatically
No other browsers

**Comment by Versty** [comment]
@AsafElbaz Please make sure you have enabled in the filters tab: 

- AdGuard Base Filter 
- AdGuard Annoyances filter 
- AdGuard Popups filter
- Language-specific filter related to your language

**Comment by Versty** [comment]
@AsafElbaz Was my advice useful?

**Comment by AsafElbaz** [comment]
Yes thank you 🙏 On 12 Jan 2023, at 10:29, Diana ***@***.***> wrote:﻿
@AsafElbaz Was my advice useful?
