### ISSUE TITLE
AdGuard for Safari

### ISSUE THREAD

**Issue by Mulder-X1** [AdguardTeam/AdGuardForSafari#789]
### Prerequisites

- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Whenever there's an update, we get notified via the Mac App Store, and unless we update, the reminder keeps coming back every day (the longest you can delay it).

### Proposed solution

Send notices that AdGuard for Safari has been updated via email instead. That way we can ignore updating if we don't want or need the update. Or, figure out how we can decline any update on the Mac App Store if we don't want or need it.

Turning off any update notifications in the application itself doesn't help; then you never find out about any update or what it's supposed to fix, so you can't decide if you want it.

### Additional information

You should have thought about this before putting it on the App Store.

**Comment by Versty** [comment]
@Mulder-X1 Hi! 
We have discussed your suggestion and decided to extend reminder period to one week, so it will be less annoying in the future. 
Some updates contain important improvements and necessary support for new syntax used in the filters lists. Therefore, we have no plans to provide decline update option. We are working hard to deliver the best adblocking experience to our users with every update. 

You can follow and discuss related improvement in this thread #790.

**Comment by Versty** [comment]
@Mulder-X1 We are currently working on changes related to notifications. 
Could you please provide the screenshot of the reminder you were talking about?
