### ISSUE TITLE
AdGuard social is blocking LinkedIn to start a new post

### ISSUE THREAD

**Issue by joshpadua** [AdguardTeam/AdGuardForSafari#793]
### Issue Details

* AdGuard for Safari version: 
* Environment name and version: 
AdGuard for Safari
Version 1.11.10 (build 266, CT 2.0.34)

* Operating System: macOS Ventura 13.1
* Filters you use in AdGuard: uol.com.br###app > div > div:nth-child(6) > section.orderSections__section.orderSections__section__publisher.section:first-child > div.container > div.row > div.col-24 > div.section__grid__highlight > div.cardAd.cardAd--1190x70.cardAd--showLabel--true.section__grid__highlight__item
macmagazine.com.br###bannerVitrine
macmagazine.com.br##div.up-floating:nth-child(65)
noticiasautomotivas.com.br###masthead
macmagazine.com.br##div.up-floating:nth-child(72)
##.up-floating
##.up-floating
###bannerVitrine
###bannerVitrine
##.cs-custom-content, .cs-custom-content-header-after
##div.up-floating:nth-child(65) > div
macmagazine.com.br##div.up-floating:nth-child(71) > div
##.cs-custom-content, .cs-custom-content-header-after
###__next > section.fixed.bottom-0.z-20.w-full.rounded-lg.bg-gray-100.py-0.lg\:py-8:nth-child(7)
##div.tw-contents:nth-child(36) > section.tw.tw-w-full.tw-z-30.tw-fixed.tw-bottom-0.tw-bg-gray-100.tw-shadow-lg.tw-rounded-tw-lg.tw-py-0.lg\:tw-py-8
uol.com.br###l2hl78s486 > div.section__grid__highlight > div.section__grid__highlight__item.cardAd.cardAd--970x250.cardAd--showLabel--true
uol.com.br###app > div > div:nth-child(6) > section.orderSections__section.section:nth-child(6) > div.container:last-child > div.row > div.col-24 > div.row.section__grid__main > div.col-24.col-lg-15:first-child > div.section__grid__main__rows:last-child > div.sectionGrid > div.sectionGrid__rows:last-child > div.row > div.col-24.col-lg-16:first-child > div.sectionGrid__grid__highlight > div.sectionGrid__grid__highlight__item.cardAd.cardAd--300x250-sport-section.cardAd--showLabel--true
uol.com.br###l2hl78yz > div.section__grid__highlight > div.section__grid__highlight__item.cardAd.cardAd--1190x330-sport-section.cardAd--showLabel--true
uol.com.br###app > div > div:nth-child(6) > section.orderSections__section.section:nth-child(6) > div.container:last-child > div.row > div.col-24 > div.row.section__grid__main > div.col-24.col-lg-15:first-child > div.section__grid__main__rows:last-child > div.sectionGrid > div.sectionGrid__rows:last-child > div.row > div.col-24.col-lg-16:first-child
Ad blocking, Privacy, Annoyances and security as well
* Any other browser extensions you have installed: DuckDuckGo, Folx, Fakespot, Grammarly, Notion, Onesec, Paypal Honey

### Screenshots

<details><summary>Screenshot:</summary>
<img width="739" alt="Screenshot 2023-01-31 at 12 33 25 p m" src="https://user-images.githubusercontent.com/85679258/215761119-1b32f54a-2c12-405b-a27d-fb35a108ed21.png">
<img width="739" alt="Screenshot 2023-01-31 at 12 33 43 p m" src="https://user-images.githubusercontent.com/85679258/215761126-d54a74a0-2ba6-467b-a4a4-ebf87e687346.png">

</details>

**Comment by Versty** [comment]
@joshpadua Hi!
Unfortunately we can not reproduce this issue. 

Please enable every content blocker in the Safari preferences, update filters, wait for the content blockers to be compiled (approximately 30 sec), and then open LinkedIn page in the private tab and check whether the post creation part is blocked.

If so, please export settings (General -> Export settings option) and send it to `apple@adguard.com`.  
Mention `#793` number in the subject line.

**Comment by Versty** [comment]
@joshpadua Closed due to inactivity.
Please reopen if needed.
