### ISSUE TITLE
Adguard is not blocking any ads

### ISSUE THREAD

**Issue by Monke-af** [AdguardTeam/AdGuardForSafari#799]
Just blocks some basic ads gif ads popups still do remain and my browser is extremely slowed down

**Comment by Versty** [comment]
@Monke-af Hi! Please make sure you've configured AdGuard for Safari according to your needs. 
We recommend enabling AdGuard filters from the "Annoyances" category which will help to get rid of popups.

**Comment by Monke-af** [comment]
i have enabled all annoyances filters still getting gif images.

**Comment by Versty** [comment]
@Monke-af Please fill in incorrect blocking report via in-app option Support -> **Report incorrect blocking**.
