### ISSUE TITLE
Filters are not being updated since 1 December 2022

### ISSUE THREAD

**Issue by Wieroo** [AdguardTeam/AdGuardForSafari#800]
Не обновляются фильтры с 1 декабря 2022 года для adguard safari

**Comment by Versty** [comment]
@Wieroo Добрый день! 
Пожалуйста, проверьте обновления фильтров, затем воспользуйтесь опцией "Экспортировать логи" и отправьте  файл нам на почту `apple@adguard.com`. В теме письма укажите номер `#800`. Мы постараемся разобраться и решить проблему с обновлениями.

**Comment by Versty** [comment]
@Wieroo Похоже, вы используете устаревшую версию приложения. Обновление до последний версии (1.11.10) должно исправить проблему. 

Скачать актуальную версию AdGuard for Safari можно по этой [ссылке](https://agrd.io/safari_release).

**Comment by Versty** [comment]
@Wieroo Помогло ли вам обновление?

**Comment by Wieroo** [comment]
Забыл ответить, да обновление помогло, спасибо

Стефан Александрович
Руководитель межрегионального направления | Этажи

• Website: http://stefan.realtor.tilda.ws
• Vk/Inst: stefan.realtor
• Mobile: ‭8 (905) 687-51-37‬
• ***@***.***
• Address: Первомайская 117, Липецк
•
•


20 февр. 2023 г., 14:19 +0300, Diana ***@***.***>, писал:
