### ISSUE TITLE
Youtube adverts incorrectly filtered

### ISSUE THREAD

**Issue by HensTeeth** [AdguardTeam/AdGuardForSafari#801]
Example: https://www.youtube.com/watch?v=3yR8HQGtSTU

URL: https://play.google.com/log?format=json&hasfast=true&authuser=0
Status: 401 Unauthorized
Source: Network
Address: 17.248.255.6:443 (Proxy)
Initiator: 
base.js:7233:83

Blocks content with some of adverts.

**Comment by HensTeeth** [comment]
Hi,

Apologies for the delay, but it seems that the error is very much dependent on the served advert. i.e. it depends on which video I'm looking at whether the video 'sticks' like this:
https://user-images.githubusercontent.com/34035851/219112745-f9eb77a6-2195-481e-b596-158406ddd5a6.mp4

It can be temporarily unjammed for a given video by turning off, then turning on again, the base filter.

But as you can see from the video, refreshing the page doesn't seem to solve the problem - you get a different stuck advert. However if I then view a different video, it can just work. So it seems to be a combination of the video I want to watch, and the advert which is being served. Possibly there are 'sets' of adverts for a video - but I'm guessing...

Just to mention, in case it's relevant, this is the latest patch of macOS, 13.2.1 .

Many thanks for your assistance.

**Comment by Versty** [comment]
@HensTeeth Unfortunately, your video is not loading. Could you download it on the YouTube and share a link?

**Comment by HensTeeth** [comment]
YouTube link here: https://youtu.be/Z2qHPcqrGmI. Let me know if that doesn't work.

**Comment by sinamombeiny** [comment]
hello!
Yes, that's right ad blockers is not well for YouTube! is not just about Adguard all ad blockers like (1Blocker, Ghostery and...) not blocking ads in YouTube

in search : **[LINK](https://send.hrzn.cool/download/9ded524b-b147-4261-a176-b266d2b7d1c3#HtgIvPD03CNcbUvYC8wGK2JhcjXRQKW-JBdiOfijybo)**
in video page : **[LINK](https://send.hrzn.cool/download/57f1ec7b-76c5-4715-bc96-43cba939dd72#qVIuy7VLNDxHw2pePFd50jcBMF5DcOTkFwFBqot2vY4)**
and sometimes at all like there is no ad blocker **[LINK](https://send.hrzn.cool/download/0b118f42-7668-4bb2-8516-ac035299e015#J8LgJ8-oAYM5JLmeuLplNvgNLNE4zgMJqiNP8rGZtAQ)**

adguard for safari 1.11.11
safari 16.3
macbook apple silicon

**Comment by Versty** [comment]
@HensTeeth It works, thank you. 
We would like you to export settings via in-app option (Preferences -> General -> Export settings) and send it to our email `apple@adguard.com`. Please mention `#801` number in the subject line. 
The settings file from your device is needed for the further investigation.

**Comment by Versty** [comment]
@HensTeeth Any updates?

**Comment by HensTeeth** [comment]
Email with settings file attached sent mentioning #801 number in the subject, as requested.

**Comment by sinamombeiny** [comment]
any news about this?

**Comment by Versty** [comment]
@sinamombeiny Hi, we are working on this issue. 
You can also monitor progress on the similar issue #771.

**Comment by Versty** [comment]
@HensTeeth If the issue still persists on your device, let's continue to discuss it further in #771.
