### ISSUE TITLE
Improve response time new Electron releases

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardForSafari#803]
### Issue Details

The current version of Electron running in AG for Safari is v18, prior to that it was v11.

V18 has been EOL since the released of v21. V23 is now the latest.

Updating Electron can improve performance of the app, and going so long between versions can leave the app exposed to unnecessary security risks, especially when using EOL versions.

### Proposed solution

In line with the [Electron best practices](https://www.electronjs.org/docs/latest/tutorial/security#), it would be good to see a more regular update of Electron when a new version is released, preferably before it goes EOL.

This could be initiated with dependabot.

**Comment by Versty** [comment]
@jslawler Hi! 

We plan to improve the application drastically and are currently reconsidering the usage of Electron in AdGuard for Safari. Possibly we will switch to Sciter in the near future.

**Comment by jslawler** [comment]
@Versty Just out of curiosity more than anything, is there a reason why Electron (or a substitute) is being used at all?
