### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by ibrahim1023** [AdguardTeam/AdGuardForSafari#817]
### Issue Details

In the earlier version, the adguard would start running when I would open safari for the first time. Now with this current version, it opens a window at startup which is pretty annoying. Why can't we have an option to not run at startup and instead start working when safari would open for the first time?

**Comment by Versty** [comment]
@ibrahim1023, hi! 
This is a known issue, will be fixed soon. 

Closed as a duplicate of #805.
