### ISSUE TITLE
Won't start minimized / hidden

### ISSUE THREAD

**Issue by ChrisTheCat** [AdguardTeam/AdGuardForSafari#819]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11

### Environment

```markdown
- OS: Ventura 13.1
- Safari version: 16.2
```

### Issue Details

Steps to reproduce:
1. Reboot Mac
2. Log in

### Expected Behavior

AdGuard for Safari starts minimized / hidden

### Actual Behavior

AdGuard for Safari opens with the settings window visible.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1280" alt="Screenshot 2023-03-01 at 08 05 26" src="https://user-images.githubusercontent.com/8732435/222195511-873320b5-87f9-4bdf-b2ee-20797c1c373f.png">

</details>

**Comment by vozersky** [comment]
We are working on the fix: https://github.com/AdguardTeam/AdGuardForSafari/issues/805
