### ISSUE TITLE
Installing AdGuard for Safari corrupt the toolbar's flexible spaces.

### ISSUE THREAD

**Issue by csabigabi** [AdguardTeam/AdGuardForSafari#821]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11

### Environment

```markdown
- OS: 13.2.1 (22D68)
- Safari version: 16.3 (18614.4.6.1.6)
- Base 14" MBP

Fresh install of the machine, first and only safari extension.
```

### Issue Details

Steps to reproduce:
1. Install AdGuard
2. Flexible spaces in Safari's toolbar goes wrong. Existing and new also.
3. End

### Expected Behavior

Flexible spaces are working correctly.

### Actual Behavior

Flexible spaces are not flexible anymore, just a one pixel separator.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="386" alt="Screenshot 2023-03-02 at 14 52 04" src="https://user-images.githubusercontent.com/95917410/222447465-0a67b08b-9d59-4b1e-aa95-f982e739e6a0.png">

</details>

**Comment by Versty** [comment]
@csabigabi A flexible space turns into a separator if there is not much space available on the toolbar. 
You can easily delete the separator by clicking RMB on the toolbar -> `Customise Toolbar`, then drag the separator from the toolbar.

**Comment by csabigabi** [comment]
> @csabigabi A flexible space turns into a separator if there is not much space available on the toolbar.
> You can easily delete the separator by clicking RMB on the toolbar -> `Customise Toolbar`, then drag the separator from the toolbar.

**Comment by csabigabi** [comment]
oops.

yeah I know but it's not the case now.

**Comment by csabigabi** [comment]
nope. uninstalled AdGuard with AppCleaner and the flexible spaces still doesn't work properly.

**Comment by Versty** [comment]
@csabigabi Could you explain in detail what do you mean by `doesn't work properly`?

**Comment by csabigabi** [comment]
I attached a screenshot to my original issue where the flexible spaces are visible as thin lines. I can arrange them but they are just always that thin.

I just reinstalled my machine, arranged my safari toolbar (with flexible spaces) when I discovered Adguard hasn't been installed so I installed it. As soon as I enabled it the flexible spaces went crap.

**Comment by Versty** [comment]
@csabigabi Can you provide a screenshot of the full toolbar from editing mode? This will help us investigate the issue.

**Comment by csabigabi** [comment]
https://user-images.githubusercontent.com/95917410/222542428-28947150-83b3-4ef7-9fcd-01512e79ba18.mov

**Comment by Versty** [comment]
@csabigabi Thanks. Have you figured out how to restore the functionality of flexible spaces after removal? 

We have tried to reproduce issue on the same environment, but with no luck. Flexible spaces remain flexible after AdGuard has been installed. 

Did you install AdGuard from App Store or via the direct link when the issue occurred?

**Comment by csabigabi** [comment]
@Versty No I can't solve it. Shortly after I commented here I reinstalled my machine one more time, did the same things and happened the same things. I'm installing the App Store version.

**Comment by csabigabi** [comment]
@Versty One thing I discovered: if I remove the address bar from the toolbar the flexible spaces are working again.


https://user-images.githubusercontent.com/95917410/224303802-01f24d0a-cc9a-4d03-8b6a-fca27d09cf9c.mov

**Comment by Versty** [comment]
@csabigabi Looks like you use "Compact" tab layout in the Safari, which does not support flexible spaces. 
Switch it to "Separate" (*Safari -> Settings ->Tabs*) and the flexible spaces will be back to normal.

**Comment by Versty** [comment]
@csabigabi Could you open some tabs and send one more video like this?
