### ISSUE TITLE
"Move to the applications folder" dialog 

### ISSUE THREAD

**Issue by JamesKayten** [AdguardTeam/AdGuardForSafari#823]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

 AdGuard for Safari Version 1.11.11

### Environment

```markdown
- OS:13
- Safari version: 16.3 (18614.4.6.1.6)

AdGuard for Safari
Version 1.11.11
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

I keep getting this offer to move the app to the applications folder but its already in the applications folder

<img width="312" alt="Screenshot 2023-03-03 at 1 39 59 PM" src="https://user-images.githubusercontent.com/7013619/222834866-bd10f83b-4d48-4759-8cd8-b64a52382912.png">
<img width="312" alt="Screenshot 2023-03-03 at 1 39 59 PM" src="https://user-images.githubusercontent.com/7013619/222834902-38f2794d-a550-41fb-a84c-c26c84190c70.png">

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="312" alt="Screenshot 2023-03-03 at 1 39 59 PM" src="https://user-images.githubusercontent.com/7013619/222834934-6bfbc378-3f74-4921-9dda-d0282bad4ad1.png">

**Comment by Versty** [comment]
@JamesKayten Hi! Seems like something went wrong locally on your device. 
Please remove the application, then download and move it manually to the applications folder again.

**Comment by Versty** [comment]
@JamesKayten Did my advice resolve the issue?

**Comment by JamesKayten** [comment]
I think the issue is resolved
