### ISSUE TITLE
Add "Pause AdGuard" / "Enable AdGuard" to menu

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#83]
Hi,
it could be an idea adding "Pause AdGuard" / "Enable AdGuard" to menu (the one with launch adguard at login etc.), in this way AdGuard can be stopped/enabled directly from there without use AdGuard Safari Icon.
See #78 .

### Your environment

* AdGuard for Safari version: 12.0.1
* Environment name and version: Safari 12.0.1 
* Operating System: macOS High Sierra 10.13.6
* Filters you use in AdGuard: default
* Any other browser extensions you have installed: none

**Comment by Shnub** [comment]
Yes, and please also restore this functionality to the browser icon!

**Comment by ameshkov** [comment]
@Mizzick one more thing about this. If AdGuard is paused, we should show a warning in the preferences UI. Something like this: `AdGuard protection is paused. Enable AdGuard.`
