### ISSUE TITLE
Don't automatically open settings pane on app start

### ISSUE THREAD

**Issue by ghostlyman101** [AdguardTeam/AdGuardForSafari#833]
### Issue Details

The settings pane opens automatically on app start. It's a minor annoyance but I don't like closing it every time. MacOS Ventura 13.2.1

### Proposed solution

The app will start "quietly". The settings pane will only open when the user clicks on the Settings icon.

### Alternative solution

A checkbox for whether it opens automatically on start or fully manually

**Comment by Versty** [comment]
@ghostlyman101 This issue has already been fixed. Please update to 1.11.12.
