### ISSUE TITLE
Auto minimised at startup

### ISSUE THREAD

**Issue by Frederic-Modine** [AdguardTeam/AdGuardForSafari#835]
### Issue Details

When launching the MAC, the AdGuard window appears when you want the application to launch automatically at start-up.

My config : MacBook / OS Ventura 13.2.1

### Proposed solution

It will be great if you app could be reduced automatically (In the top taskbar) when starting the session on MAC.

**Comment by Versty** [comment]
@Frederic-Modine Hi! Please update to the latest version (1.11.12). 
This issue has already been fixed.
