### ISSUE TITLE
CPU spikes www.notion.so

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardForSafari#836]
@adguard-bot commented on [Wed Mar 29 2023](https://github.com/AdguardTeam/AdguardFilters/issues/146822)

### Issue URL (Incorrect Blocking)
 [https://www.notion.so/personal](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.notion.so%2Fpersonal)
### Comment
Username: @FluffCycle
> Clicking between the tabs on the highlighted section with AdGuard enabled causes a significant lag in the browser and the content switching. Scrolling down in the page seems to be worse as well when the extension is enabled. Other pages on the Notion website seemed to be affected too but I noticed it the most here.
> 
> Through enabling and disabling extensions I was able to narrow it down to AdGuard appearing to cause it. Once I disable all AdGuard extensions in Safari settings and refresh the page, I'm able to interact with it quickly/smoothly as expected.
> 
> I noticed in activity monitor that the 'https://www.notion.so' process appears to use more CPU with AdGuard enabled vs not (~30% more from what I can tell on my Mac)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/vlshyRp.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/keFgnSe.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Safari v1.11.12
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List
Other extensions used: | 1Password (enabled), neeva (disabled for testing), Honey (disabled for testing)

---

@zloyden commented on [Wed Mar 29 2023](https://github.com/AdguardTeam/AdguardFilters/issues/146822#issuecomment-1488491737)

I don't see that with AdGuard filters on my end.

> I noticed in activity monitor that the '[notion.so](https://www.notion.so/)' process appears to use more CPU with AdGuard enabled vs not (~30% more from what I can tell on my Mac)

Strange, but I'll move it to another repo. Please be ready to answer developers' questions.

**Comment by Versty** [comment]
@FluffCycle Closed due to lack of activity. Please reopen if needed.
