### ISSUE TITLE
Silent Start

### ISSUE THREAD

**Issue by vexir** [AdguardTeam/AdGuardForSafari#838]
### Issue Details

  When AdGuard starts up at login, it shows the window. 

### Proposed solution

Start silently - in other words, do not show the window at login.

**Comment by CrazySky2121** [comment]
+

**Comment by interpretor** [comment]
It behaved like that before, for some reason that behavior has changed a few releases ago.
I would also like to get the old silent startup, so we don't have the window popping up at login or update.

**Comment by Marcus-Kivra** [comment]
+1

**Comment by Versty** [comment]
@vexir @CrazySky2121 @interpretor @Marcus-Kivra 
We have already improved this behaviour, please update to the latest version (1.11.12).

**Comment by Marcus-Kivra** [comment]
@Versty I still have the same issue in 1.11.12.
