### ISSUE TITLE
when the app is closed ( command + q) the extension doesn't work anymore ( a week ago It did)

### ISSUE THREAD

**Issue by applepineapple1** [AdguardTeam/AdGuardForSafari#840]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.12

### Environment

```markdown
- OS:Ventura 13.2.1
- Safari version:16.3
```

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

when I close the app I expect for the program to keep running on the backround on safari

### Actual Behavior

when I close the app th extortion doesn't continue to work as it did

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@applepineapple1 Hi! 
Please use `Command+H` shortcut to hide the settings window and `Command+Q` to quit. 

Lean more about useful [Mac keyboard shortcuts](https://support.apple.com/en-us/HT201236).
