### ISSUE TITLE
onlinedizi.cc are fully unresponsive with AdGuard

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardForSafari#841]
@adguard-bot commented on [Tue Apr 04 2023](https://github.com/AdguardTeam/AdguardFilters/issues/147397)

### Issue URL (Incorrect Blocking)
 [https://onlinedizi.cc/call-it-love-1-bolum/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fonlinedizi.cc%2Fcall-it-love-1-bolum%2F)
### Comment
Username: @telepati
> I am using DNS protection. The page crashes and part of the video always stay white. The video never shows. If I stop AdGuard, the page usually works. If I disable it only for this page, it still doesn't work.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Rz3h1gc.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/91tCFIC.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Safari v1.11.12
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Turkish

---

@zloyden commented on [Wed Apr 05 2023](https://github.com/AdguardTeam/AdguardFilters/issues/147397#issuecomment-1497044628)

Not reproduced it on my end even with our DNS.
Try to clear browser data, update the filters (wait almost one minute there), open the site.
If that doesn't work, you should re-enable the content blockers in Safari settings (wait about the same time as when you update the filters).

---

@telepati commented on [Wed Apr 05 2023](https://github.com/AdguardTeam/AdguardFilters/issues/147397#issuecomment-1497370353)

With AdGuard the pages are fully unresponsive.
<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/3812286/230074003-729d9dec-bf7d-47f6-ad74-317265aad8ec.png">
</details>

If I choose to reload without content blocker pages opening with ads and videos work.

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/3812286/230074111-96ed02e2-b59c-4a80-89c2-9514ff6e2af3.png">
</details> 
<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/3812286/230074186-8380721e-d5e7-4e7f-b32a-7d195b50a418.png">
</details> 

---

@zloyden commented on [Wed Apr 05 2023](https://github.com/AdguardTeam/AdguardFilters/issues/147397#issuecomment-1497428697)

Please hide the images above under the spoiler.
Have you done what I said [here](https://github.com/AdguardTeam/AdguardFilters/issues/147397#issuecomment-1497044628)?
I've also checked the site with a Turkish IP, but it works fine on my end.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/230083054-a2e37bb6-3391-4c14-94c9-e7c7a545895f.png)

</details><br/>

---

@zloyden commented on [Wed Apr 05 2023](https://github.com/AdguardTeam/AdguardFilters/issues/147397#issuecomment-1497433083)

> With AdGuard the pages are fully unresponsive.

If you still have this even after reloading AdGuard for Safari, please let me know. It can be a bug, but the devs will say for sure.

---

@telepati commented on [Wed Apr 05 2023](https://github.com/AdguardTeam/AdguardFilters/issues/147397#issuecomment-1497785910)

Off course, I did what you said. Clear browser data, update filters, and wait for open. But the problem is site is fully unresponsive when the AdGuards is active. When I get a Force Reloading error and click the Visit page did not fix anything.

**Comment by Versty** [comment]
@telepati Hi! We have tried to reproduce the issue, but the video loads and plays properly on our side. 
Could you specify your Safari version? Have you installed AdGuard for Safari from App Store?

**Comment by telepati** [comment]
@Versty Hi! Unfortunately for this site, the problem still persists on my end. It is not possible for me to use this site without disabling AdGuard.

Safari Version 16.4 (18615.1.26.110.1)

I tried both AdGuard (Website and App Store)
I also used a DNS profile from your website.

**Comment by Versty** [comment]
@telepati Hi! 
Please update the application to the latest version (1.11.13). We have made some adjustments in the libs, which may resolve this issue.

**Comment by telepati** [comment]
Hi @Versty I've already been using this version for a week, but nothing has changed. But I found what was affecting this issue. AdGuard is not blocking the Vidmoly ads and crashes the page. I tried on 2 different websites, same result on all of them. One of them even warns you to turn off your ad blocker.

[https://dizilla2.org/darkness-those-who-kill-3-sezon-4-bolum/?source=Vidmoly](url)
<details>
  <summary>Screenshot-1</summary>
<img width="2189" alt="Screenshot 2023-05-29 at 05 08 37" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/3812286/a60523a2-ae47-4e96-9e72-860465a78d26">
</details>

[https://720pizle5.com/izle/altyazi/the-amazing-maurice.html?player=vid](url)
<details>
  <summary>Screenshot-2</summary>
<img width="2189" alt="Screenshot 2023-05-29 at 05 09 14" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/3812286/3ef516ef-7d8a-441d-8cc8-1923d436aeb6">

</details>

**Comment by alexx7311** [comment]
Hello! Please go to AdGuard for Safari > Preferences > General > Export settings. Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by alexx7311** [comment]
@telepati We haven't gotten an email from you. We will wait a few more days, if there is no reply we will have to close the ticket. But you will be able to reopen it if the problem recurs.

**Comment by telepati** [comment]
> @telepati We haven't gotten an email from you. We will wait a few more days, if there is no reply we will have to close the issue. But you will be able to reopen it if the problem recurs.

It's done.

**Comment by telepati** [comment]
The updated to v1.11.14 didn't change anything. Problem still persists.

**Comment by alexx7311** [comment]
@telepati Hello! We couldn't reproduce the problem even with your settings.  It may be a conflict with other extensions. Please try uninstalling all other extensions in Safari except AdGuard for Safari, and then check if the problem recurs in browser incognito mode. If you have other programs installed that work with the network, such as antivirus, VPN and proxy applications, firewalls, try disabling them temporarily.

**Comment by alexx7311** [comment]
@telepati Is the problem still persists?

**Comment by alexx7311** [comment]
@telepati You originally mentioned a problem with pages not responding. Does this problem still occur?

**Comment by telepati** [comment]
@alexx7311 Yes, video not showing, page not responding.

**Comment by telepati** [comment]
It didn't help. Tried on many sites. Actually, I tried this suggestion before with every filter.

**Comment by alexx7311** [comment]
Did you test with AdGuard DNS enabled or disabled? Have you tried disabling AdGuard DNS?

**Comment by telepati** [comment]
Yes, DNS is among the things I tried first. Regardless, AdGuard does not block ads related to Vidmoly player and causes the page to lose its functionality.

**Comment by alexx7311** [comment]
@telepati To definitely rule out that the problem is not with the filters, please try disabling all filters and see if the problem persists.

**Comment by telepati** [comment]
I tried disabling/enabling the filters I use one by one. Whichever I activate, the problem comes back. I think I will use another Ad Blocker app cos I use such sites a lot and almost all of them use Vidmoly.
