### ISSUE TITLE
energy consumpion

### ISSUE THREAD

**Issue by onetigerr** [AdguardTeam/AdGuardForSafari#842]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

latest on date

### Environment

```markdown
- OS: 13.2.1 
- Safari version: 16.3 (18614.4.6.1.6)
```

### Issue Details

Steps to reproduce:
1. have adguard
2. close lid
3. enjoy

### Actual Behavior

Steps to reproduce:
1. have adguard
2. close lid
3. enjoy

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="558" alt="image" src="https://user-images.githubusercontent.com/61534552/230718061-c148772d-f2cd-46d7-868e-cb1a2d6a910d.png">

</details>

**Comment by Versty** [comment]
@onetigerr Hi! 
We have tried to reproduce this issue but to no avail. 
Therefore, we would like to know more details about:
- your Mac device (model, chip) 
- how many attempts out of 5 the issue occurs 
- application download source (App Store or direct link)

**Comment by Versty** [comment]
@onetigerr Any updates?

**Comment by onetigerr** [comment]
I removed your plug-in, it’s kind of annoying
