### ISSUE TITLE
AdGuard does not get disabled when accessing 127.0.0.1 even when I add it to allowlist

### ISSUE THREAD

**Issue by OIRNOIR** [AdguardTeam/AdGuardForSafari#843]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.12

### Environment

```markdown
- OS: Ventura 13.3.1
- Safari version: 16.4 (18615.1.26.11.23)
```

### Issue Details

Steps to reproduce:
1. Host a local server on your computer with the purpose of testing a website you're building. Can be a simple flask or express app, but make sure your local server sends a Content-Security-Policy header that disallows 'unsafe-inline'. `Content-Security-Policy: default-src 'self';` should work fine.
2. Visit your local server via the IP address `127.0.0.1`. Example: http://127.0.0.1:8080. Visiting it via `localhost` is not affected by this bug.
3. Open the console. Ensure you can see AdGuard's logs and that AdGuard is enabled on the page. If the `Content-Security-Policy` header is set correctly, you will be able to verify whether AdGuard is enabled by checking if there are any Content Security Policy errors due to scripts and stylesheets AdGuard attempts to apply.
4. Click the AdGuard extension icon in your browser
5. Uncheck the "Enabled on this website" box
6. Verify that 127.0.0.1 is present in the Allowlist
7. Restart Safari, visit the same page, open the console, and reload (normal reload, force reload, Reload Without Content Blockers) a couple times, ending with a normal reload, to make sure the changes were applied.

### Expected Behavior

The Content-Security-Policy errors should stop occurring, like they do for `localhost`. It should be obvious that AdGuard was disabled.

### Actual Behavior

The Content-Security-Policy errors continue, indicating that AdGuard was not disabled. If you put any content on the page that would be filtered by AdGuard, it is blocked despite AdGuard being disabled on 127.0.0.1.

### Screenshots

<details><summary>Screenshot 1: The page with the affected bug, accessed via https://127.0.0.1:44433 (with self-signed certificate.) It is clear that AdGuard is disabled on the page, but it is not actually disabled in effect.</summary>

<img width="1680" alt="Screenshot 2023-04-15 at 2 10 33 PM" src="https://user-images.githubusercontent.com/70721372/232253441-eaa5db4d-81be-468d-b711-8c01aee4f144.png">

</details>

<details><summary>Screenshot 2: The same page, accessed via https://localhost:44433. AdGuard is properly disabled.</summary>

<img width="1680" alt="Screenshot 2023-04-15 at 2 11 17 PM" src="https://user-images.githubusercontent.com/70721372/232253543-a9d5ef1d-76a4-4d23-9f96-5fc89b6dfa53.png">

</details>

<details><summary>Screenshot 3: My allowlist. The censored domains have nothing to do with this report and are censored for privacy.</summary>

<img width="604" alt="Screenshot 2023-04-15 at 2 19 59 PM" src="https://user-images.githubusercontent.com/70721372/232253630-b8bcdc95-3974-438f-aa3a-54e5982cad9a.png">

</details>

### Additional Information

(NOTE: This report is NOT about the Content-Security-Policy errors, it's about AdGuard refusing to be disabled on 127.0.0.1. Content-Security-Policy errors are merely a definitive indicator as to whether AdGuard is enabled or not. You can try the same thing on Github, which has a similar Content-Security-Policy, and see that these errors stop when AdGuard is disabled.)

**Comment by VladisLoveZh** [comment]
Hi @OIRNOIR , 
What if you disable content blockers specifically for your websita via Safari>Settings for "website name">uncheck "Enable content blocker" to see if that helps? 

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/103937301/f4bab55c-8ca5-43a8-9aba-d85de0502e86)

**Comment by OIRNOIR** [comment]
Hi @VladisLoveZh,

I attempted this on 127.0.0.1 and localhost multiple times. My findings were that the enable content blockers checkbox had no effect on whether the errors were being shown.

In addition, I know that whatever is throwing these errors *is* affected by the allowlist, because it works for localhost when localhost is added to the allowlist. I suspect it might have something to do with parsing URLs. It might count anything before the second-to-last dot in the domain as a subdomain, which is not valid for an IP which needs all four digits.

**Comment by VladisLoveZh** [comment]
> 

Hi,

 **AdGuard Advanced Blocking** extension causes CSP errors, which can't be disabled for a particular website but completely disabled in Safari. Hence, that's why nor allowlist, nor rules, nor even disabling content blockers from Safari helps in this case, as AdGuard Advanced Blocking extension works every time. 

Allowlist as well as any other allow-rules that are based on content-blockers executes correctly. Both: localhost and 127.0.0.1 can be excluded from filtering and so on (I wasn't able to reproduce the issue you're experiencing).
