### ISSUE TITLE
Where are the "user rules" on Safari in Mac?

### ISSUE THREAD

**Issue by emadeldinaldafrawy** [AdguardTeam/AdGuardForSafari#844]

**Comment by jslawler** [comment]
AdGuard for Safari - Settings > Filters > User rules

<img width="1072" alt="Screenshot 2023-04-19 at 10 49 30" src="https://user-images.githubusercontent.com/95468948/232937848-391dcdea-c398-445f-8edc-d5207dc10771.png">

**Comment by emadeldinaldafrawy** [comment]
Oh! So, that one is clickable! I got confused from the toggle switch! The look on the Android version is intuitive. The option at the "general" to hide the icon from the computer's "menu bar" is worded to feel that it removes the icon from the Safari browser.
