### ISSUE TITLE
Horizontal scroll bar showing for AdGuard for Safari - Settings window

### ISSUE THREAD

**Issue by e2196099** [AdguardTeam/AdGuardForSafari#845]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.12 (build 289, CT 2.0.34)

### Environment

```markdown
OS: Ventura 13.3.1
Safari: Version 16.4 (18615.1.26.11.23)
```

### What filters do you have enabled?

Others

### Issue Details

Steps to reproduce:
1. Show about
2. observe shitty scroll bar on the horizontal and vertical
3. call or request specific information from the bug reporter

### Expected Behavior

no shitty horizontal scrollbar
![image](https://user-images.githubusercontent.com/123342150/234455114-9a8bad7c-3bbb-4e71-bce2-00d715f8a47b.png)

### Actual Behavior

an horizontal scroll bar showed up

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/123342150/234454760-0315b9ea-3090-4e6c-8864-e6e4bdbc2d2b.png)

</details>

### Additional Information

I'll share screen and do video call.

**Comment by Versty** [comment]
@e2196099 Hi! Has the horizontal scroll bar been displayed in the previous version of the AdGuard for Safari (1.11.11) or on the previous version of MacOS?

**Comment by Versty** [comment]
@e2196099 any updates on this issue? 
If the issue persists, we would recommend a clean install. 

Follow the steps below to fully uninstall AdGuard for Safari: 
1. Uncheck all AdGuard for Safari extensions in **Safari -> Preferences -> Extensions** (if available)
2. Open **Finder** and press Shift+Command+G
    - Remove AdGuardSafariApp folder from **~/Library/Application Support** directory
    - Remove from **~/Library/Application Scripts** - all directories started with com.adguard.safari
    - Remove from **~/Library/Containers** - all directories started with AdGuard-
    - Remove TC3Q7MAJXF.com.adguard.safari.AdGuard folder from **~/Library/GroupContainers** directory
    - Remove com.adguard.safari.AdGuard.plist from **~/Library/Preferences** 
3. Open **Activity Monitor** and force quit all "cfprefsd" processes 
4. Remove AdGuard for Safari from **Applications**

Then download and install the latest version again.
