### ISSUE TITLE
Settings windows automatically opens daily requiring you to close it

### ISSUE THREAD

**Issue by Extravagangsta** [AdguardTeam/AdGuardForSafari#846]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.11 (build 275, CT 2.0.34)

### Environment

```markdown
- OS: 13.3.1 (22E261)
- Safari version: Version 16.4
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Nothing is required for the Settings window to open. It just pops open from day to day, it seems. 

### Expected Behavior

In the past, this Settings window rarely opened on its own. 

### Actual Behavior

When working on your MacBook, the Adguard settings window appears. You click the red button in the top left of the window for it to close, then the next day, it does the same thing. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maximtop** [comment]
@Extravagangsta looks like your issue was already fixed in v1.1.12, please update to v1.1.12
check this issue https://github.com/AdguardTeam/AdGuardForSafari/issues/805

**Comment by Extravagangsta** [comment]
My apologies. My App Store didn't notify me of the available update (or some other updates that were waiting) and I thought I was on the latest version. Thanks for the quick response.
