### ISSUE TITLE
AdGuard does not work properly on YouTube if multiple YouTube tabs are open in Safari

### ISSUE THREAD

**Issue by wilburpan** [AdguardTeam/AdGuardForSafari#848]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.12 (build 289, CT 2.0.34)

### Environment

```markdown
- OS: Ventura 13.3.1(a)
- Safari version: 16.4 (18615.1.26.110.1)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, EasyPrivacy, Adblock Warning Removal List, Fanboy's Enhanced Tracking List

### Issue Details

Steps to reproduce:
1. Open YouTube.com
2. Use command-click to open a Youtube video in a second tab
3. Switch to the second tab and try to play the video.
4.
5.

### Expected Behavior

Expect the video to play.

### Actual Behavior

A screenshot presumably from an ad appears in the YouTube video area in the second tab. Pressing "play" starts the progress wheel on the YouTube video spinning, but the video won't start.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="809" alt="Screenshot 2023-05-03 at 2 29 58 PM" src="https://user-images.githubusercontent.com/103464445/236010692-a23a9d8f-f6ba-48bc-ab19-22d8726ac256.png">

</details>

**Comment by RJKflyer** [comment]
I have precisely this same issue.

It is not 100% repeatable, and so not sure if it is just the AdGuard not working full stop issue.

**Comment by jslawler** [comment]
I am currently experiencing this issue when running multiple versions of Safari at the same time.

Steps to reproduce:
1. Open Safari stable
2. Browse to a [YouTube video](https://www.youtube.com/watch?v=l3uW7OngOuQ) (video will load without ads)
3. Open Safari Preview
4. Browse to the [same video](https://www.youtube.com/watch?v=l3uW7OngOuQ) as in step 2 (video will load with ads)
5. Disable AdGuard for Safari for that webpage on both browser windows (page will reload with a video ad)
6. Enable AdGuard for Safari for that webpage on both browser windows (page will reload with a video ad, when it shouldn't)

These steps don't reproduce it every time, but I have noticed it does occur often enough to identify the issue as it's happened quite a few times over the last half hour whilst browsing videos.

**Comment by RevENGE-code** [comment]
**Environment**
```
OS: MacOS 13.4 (22F66)
Safari Version 16.5 (18615.2.9.11.4)
Adguard Version 1.11.13 (build 297, CT 2.0.39)
```

I am experiencing this issue as well. It's very much intermittent.

**Comment by Versty** [comment]
@wilburpan @RJKflyer @jslawler @RevENGE-code 
Thank you for reporting this issue. We are investigating.

**Comment by Versty** [comment]
@wilburpan We have managed to reproduce this issue. 
The same case as #771. Please continue in the linked bug report.
