### ISSUE TITLE
DNS protection on AdGuard for Safari

### ISSUE THREAD

**Issue by leebanj** [AdguardTeam/AdGuardForSafari#849]
### Issue Details

in the mobile application the VPN feature is available as part of paid version. Would like the paid version extended to the desktop as well.

### Proposed solution

Implement the same feature available for ios to MacOs.

**Comment by Versty** [comment]
@leebanj Hi! 
Do you mean the DNS protection option? 
This feature is already available in the AdGuard for Mac application. 

Learn more about AdGuard for Mac on our [website](https://adguard.com/en/adguard-mac/overview.html).
