### ISSUE TITLE
Problem with NY Times Page Rendering

### ISSUE THREAD

**Issue by solusla** [AdguardTeam/AdGuardForSafari#85]
### Steps to reproduce

1. Install AdGuard for Safari and enable it and the Icon.
2. Load the nytimes.com main page (https://www.nytimes.com).
3.
4.

### Expected behavior
The page should load as it does with the old-styler Safari extension, which means hiding the blank space left by removing the large banner ad.

### Actual behavior
The space remains.

<details><summary>Screenshots:</summary>

The old-style extension hides this blank space, but the new AdGuard for Safari app extension does not. I have the same filters enabled and updated on both the old and new extensions. Only one extension was ever enabled at a time.

Below is a screenshot of the page loaded with the new extension enabled.

<img width="1589" alt="screen shot 2018-11-10 at 13 37 17" src="https://user-images.githubusercontent.com/35608295/48306470-32c63500-e4ee-11e8-9d2c-99664e8a0b8a.png">

</details>

### Your environment

* AdGuard for Safari version: 1.0.1
* Environment name and version: 12.0.1 (14606.2.104.1.1)
* Operating System: macOS Mojave 10.14.1
* Filters you use in AdGuard: AdGuard Base filter, AdGuard Spyware filter, AdGuard Social Media filter, AdGuard Annoyances filter, Adblock Warning Removal List, NoCoin Filter List, and AdGuard Safari filter.
* Any other browser extensions you have installed: 1Password (new app extension).

**Comment by ameshkov** [comment]
@Alex-302 could you please take a look and see what's wrong?

@solusla it'd be better to report this kind of issues to agrd.io/report next time. You can easily do it via the Safari toolbar icon menu.
