### ISSUE TITLE
fenêtres de superposition du RGPD

### ISSUE THREAD

**Issue by Tonton6217** [AdguardTeam/AdGuardForSafari#850]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS:
- Safari version: Version 16.5 (17615.2.9.11.6, 17615)
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.
2.
3.
Cookie
Afin d'améliorer votre expérience utilisateur et de vous proposer un contenu adapté à vos besoins notre site utilise des cookies.

En cliquant sur "Accepter et continuer" vous acceptez l'utilisation des cookies par DIGIT-PHOTO ainsi que par ses partenaires, et par conséquent leur dépôt sur votre périphérique afin de stocker et accéder à des informations comme les pages consultées, votre identifiant client...

Vous autorisez donc DIGIT-PHOTO à utiliser ces dernières, tout comme ses partenaires, à des fins d'optimisation de contenu.

Vous pouvez également refuser en cliquant sur "Paraméter" puis "Désélectionner tout", dès lors vous perdez toute personnalisation et optimisation de la consultation, vous pouvez aussi personnaliser la totalité des cookies sur cette même page.

Ce choix sera conservé durant 6 mois, vous pourrez le modifier à tout moment depuis la section "Paramètres cookies" en bas de notre site internet.

[Consulter notre politique de confidentialité](https://www.digit-photo.com/politique-confidentialite.html#part5)

ACCEPTER ET CONTINUER
PARAMÉTRER

### Expected Behavior

Bonjour, 
Depuis plusieurs jours, le blocage des RGPD ne fonctionne plus. 
Tous les sites que je consulte me demande d'accepter ou non les cookies.
Merci pour votre réponse. 
Cordialement.

### Actual Behavior

Cookie
Afin d'améliorer votre expérience utilisateur et de vous proposer un contenu adapté à vos besoins notre site utilise des cookies.

En cliquant sur "Accepter et continuer" vous acceptez l'utilisation des cookies par DIGIT-PHOTO ainsi que par ses partenaires, et par conséquent leur dépôt sur votre périphérique afin de stocker et accéder à des informations comme les pages consultées, votre identifiant client...

Vous autorisez donc DIGIT-PHOTO à utiliser ces dernières, tout comme ses partenaires, à des fins d'optimisation de contenu.

Vous pouvez également refuser en cliquant sur "Paraméter" puis "Désélectionner tout", dès lors vous perdez toute personnalisation et optimisation de la consultation, vous pouvez aussi personnaliser la totalité des cookies sur cette même page.

Ce choix sera conservé durant 6 mois, vous pourrez le modifier à tout moment depuis la section "Paramètres cookies" en bas de notre site internet.

[Consulter notre politique de confidentialité](https://www.digit-photo.com/politique-confidentialite.html#part5)

ACCEPTER ET CONTINUER
PARAMÉTRER

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Tonton6217** [comment]
Bonjour,
Depuis plusieurs jours, le blocage des RGPD ne fonctionne plus.
Tous les sites que je consulte me demande d'accepter ou non les cookies.
Merci pour votre réponse.
Cordialement.

**Comment by Tonton6217** [comment]
Bonjour,Merci pour votre réponse.Suite à votre message, j'ai effectué les recommandations et cela ne fonctionne toujours pas.Merci pour votre aide.Cordialement.envoyé : 23 mai 2023 à 14:34de : enakr ***@***.***>à : AdguardTeam/AdGuardForSafari ***@***.***>cc : Tonton6217 ***@***.***>, State change ***@***.***>objet : Re: [AdguardTeam/AdGuardForSafari] fenêtres de superposition du RGPD (Issue #850) Bonjour ! Pourriez-vous vérifier les mises à jour des filtres et que le filtre AdGuard Cookie Notices est activée, s'il vous plait ? Ensuite, désactivez et réactivez les extensions de AdGuard et redémarrez l'ordinateur. Cordialement.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by Tonton6217** [comment]
> Bonjour,Merci pour votre réponse.Suite à votre message, j'ai effectué les recommandations et cela ne fonctionne toujours pas.Merci pour votre aide.Cordialement.envoyé : 23 mai 2023 à 14:34de : enakr ***@***.***>à : AdguardTeam/AdGuardForSafari ***@***.***>cc : Tonton6217 *** Pourriez-vous vérifier les mises à jour des filtres et que le filtre AdGuard Cookie Notices est activée, s'il vous plait ? Ensuite, désactivez et réactivez les extensions de AdGuard et redémarrez l'ordinateur. Cordialement.-Répondez directement à cet e-mail, consultez-le sur GitHub ou désabonnez-vous. Vous le recevez parce que vous avez modifié l'état d'ouverture/fermeture.ID du message : ***@***. ***>

**Comment by enakr** [comment]
Bonjour, Merci de votre réponse ! Pourriez-vous préciser si des fenêtres pour accepter des cookies apparaissent sur un seul site ou sur tous les sites, s'il vous plait ? Avez-vous d'autres filtres activés dans l'extension, par exemple, ceux contre publicités ? Lesquels ?
Cordialement.

**Comment by Tonton6217** [comment]
Bonjour,Merci pour votre aide.Après avoir procédé à un grand nettoyage de l'ordinateur, il semblerait que tout soit devenu normal.Je n'ai plus d'affichage de demandes de cookies.Toutes mes excuses pour le dérangement.Cordialement.envoyé : 24 mai 2023 à 10:23de : enakr ***@***.***>à : AdguardTeam/AdGuardForSafari ***@***.***>cc : Tonton6217 ***@***.***>, State change ***@***.***>objet : Re: [AdguardTeam/AdGuardForSafari] fenêtres de superposition du RGPD (Issue #850) Bonjour, Merci de votre réponse ! Pourriez-vous préciser si des fenêtres pour accepter des cookies apparaissent sur un seul site ou sur tous les sites, s'il vous plait ? Avez-vous d'autres filtres activés dans l'extension, par exemple, ceux contre publicités ? Lesquels ? Cordialement.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by enakr** [comment]
Bonjour ! Merci de votre réponse ! Pas de souci, nous sommes heureux que le problème soit résolu et que l'extension fonctionne comme dû. Nous clôturons le dossier. Si le problème réapparait, ne vous prions de rouvrir ce dossier. Nous vous souhaitons une excellente journée ! Bien cordialement.
