### ISSUE TITLE
Filtering is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#851]
@adguard-bot commented on [Sat May 20 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151375)

### Issue URL (Ads)
 [https://mezha.media/2023/05/15/100gb-games/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmezha.media%2F2023%2F05%2F15%2F100gb-games%2F)
### Comment
Username: @kuchkovsky
> Ad leftover

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/OZMUeyx.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Safari v1.11.13
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Ukrainian

---

@kuchkovsky commented on [Sat May 20 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151375#issuecomment-1555912495)

UPD: seems there's a bug in the Safari extension. The extension completely stopped working until I checked for the filter updates _twice_. So it's not a filtering issue, you can close this.

---

@Alex-302 commented on [Tue May 23 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151375#issuecomment-1559025975)

Probably a bug. Not sure - of Safari of or AdGuard. Usually this happens on iOS (but it is a rare problem).

**Comment by VladisLoveZh** [comment]
@kuchkovsky 
Hi, 

Would you please elaborate on this bug in detail? Please share a screenshot of your Console tab results in Safari via Inspect elements menu
