### ISSUE TITLE
AdGuard for Safari not working on macOS Sonoma Beta

### ISSUE THREAD

**Issue by BlaT2512** [AdguardTeam/AdGuardForSafari#854]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.12

### Environment

```markdown
- OS: Sonoma 14.0 Developer Beta 1 (23A5757q)
- Safari version: 17.0 (19616.1.14.11.11)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter

### Issue Details

On the first developer beta of macOS Sonoma (Safari version 17.0) AdGuard blocking does not appear to be doing anything despite the extension being installed and all filters turned on as before the upgrade. Upon opening the AdGuard for Safari control settings, and clicking Content Blockers all 6 have an exclamation mark and message "Compilation failed".

### Expected Behavior

Filters work correctly and block ads.

### Actual Behavior

Cannot see any ads being blocked on any websites

**Comment by jslawler** [comment]
@BlaT2512 I don't imagine it will make a difference given the changes, but does AdGuard for Safari 1.11.13 also not work?

**Comment by BlaT2512** [comment]
Actually installing a 1.11.3 from the AdGuard website rather than app store does appear to work, thankyou!

**Comment by vozersky** [comment]
@BlaT2512 are you saying v1.11.3 from the app store doesn't work?

**Comment by BlaT2512** [comment]
@vozersky No I haven’t tried 1.11.3 from the app store but the app store wasn’t updating it so I uninstalled and downloaded it from AdGuard website. I think it’s the same as the app store version my app store was just being slow.

**Comment by vozersky** [comment]
@BlaT2512 ok, thanks!

**Comment by 0xCUB3** [comment]
it is crashing for me on beta 2 on launch. Both the App Store and GitHub latest versions don't work.
