### ISSUE TITLE
Please block ads (thumbnails ads) on YouTube (search, and viewing video)

### ISSUE THREAD

**Issue by AlexRVillalobos** [AdguardTeam/AdGuardForSafari#855]
### Issue Details

A lot of  thumbnails ads on YouTube (search, and viewing video)

**Comment by Versty** [comment]
@AlexRVillalobos Hi! 

If you are talking about any specific cases, please fill in a report form using the in-app option located in *Settings -> Support tab -> Report incorrect blocking*.

However, if you are talking about thumbnails ads in general, we would like you to use the `Bug report` form to get a more detailed understanding of the problem.
