### ISSUE TITLE
Some adGuard extensions are disabled

### ISSUE THREAD

**Issue by randall2020** [AdguardTeam/AdGuardForSafari#857]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS: Ventura 13.4
- Safari version:Version 16.5 (18615.2.9.11.4)
```

### Issue Details

Steps to reproduce:
1.Log out and back into macOS 
2.Reboot macOS

3.

### Expected Behavior

No error messages

### Actual Behavior

Always get warning "Some AdGuard extensions are disabled". Even though none are disabled.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="933" alt="Screenshot 2023-06-10 at 8 24 46 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/65458561/ad0612e6-6f3f-4cc0-99db-de545f734566">

### Additional Information

Even though I have all extensions enabled, I always get this error when I log out and back in or reboot. I can click on the "FIX IT" button, but then nothing happens. If I click Ignore.....the windows closes and everything seems to work as it should.

**Comment by Versty** [comment]
@randall2020 Hi!

This issue appears very rarely and is usually caused by an incorrect application launch or installation.  
Restarting the application fixes the problem in 10 out of 10 cases. 

If the problem occurs every time you reboot masOS, the application reinstall should help.
Before removing the application, disable all content blockers related to AdGuard for Safari in the Safari settings (*Safari -> Settings -> Extensions*).

**Comment by Versty** [comment]
@randall2020 Did the above solution help?

**Comment by randall2020** [comment]
Cancel my previous message that it did not work. I accidentally went to the adguard website instead of going to GitHub and from there to the App Store where I re-installed it from there (after completely removing it first, per your instructions above) and now it is working again without errors. Thank you for your assistance. This ticket can be closed.
