### ISSUE TITLE
Adguard window keeps popping up

### ISSUE THREAD

**Issue by tecumsa** [AdguardTeam/AdGuardForSafari#859]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.12

### Environment

```markdown
- OS: Ventura 13.4
- Safari version: 16.5 (18615.2.9.11.4)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Just wait a few hours
2. or close the top (laptop) and open again after a few hours
3.

### Expected Behavior

AdGuard window should stay closed

### Actual Behavior

I close the AdGuard window by clicking on the red dot, after a few hours it will reopen itself. 

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1072" alt="Screenshot 2023-06-17 at 7 49 59 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/58710687/c91151da-5b6e-4d52-a2f1-ffa6fe63e1c1">

</details>

**Comment by Versty** [comment]
@tecumsa Hi! 
Please update to the latest version (1.11.13). 

If the issue will persist, follow the steps below to collect and send us the logs:

1. Wait for the issue to be reproduced and remember the exact time when it happened;
2. Open the extension settings --> **Export logs and system info**;
3. Send the archive to `apple@adguard.com`, mention in the subject the issue number `853` and the reproduction time.

This issue duplicates #853, so let's continue there.

**Comment by tecumsa** [comment]
Seems to be working now, thanks.

Mike

The greatest thing about a man is his ability to transcend himself, his environment, and to be what he dreams of being. -- Tully C. Knoles
