### ISSUE TITLE
Close browser icon popup when clicking "Select"

### ISSUE THREAD

**Issue by Shnub** [AdguardTeam/AdGuardForSafari#86]
When aiming to block a website element via the browser icon, the icon's popup stays open after clicking "Select" and obstructs the selection interface. It only disappears after something outside the popup is actually clicked. It should rather close immediately.

![screen shot 2018-11-15 at 20 09 45](https://user-images.githubusercontent.com/29605254/48575585-a9aa6600-e912-11e8-9d63-45f4f456db66.png)

### Your environment

* AdGuard for Safari version: 1.0.1
* Environment name and version: Safari 11.1.2
* Operating System: macOS High Sierra 10.13.6

**Comment by zzebrum** [comment]
related #48
