### ISSUE TITLE
Too Many Security Filters After Latest Filter Update

### ISSUE THREAD

**Issue by ljmac** [AdguardTeam/AdGuardForSafari#861]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS: 10.14.16
- Safari version: 14.1.2
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter

### Issue Details

Upon updating to the latest filters, there are too many Security filters (>50,000), so I have to disable them.

### Actual Behavior

See above

**Comment by ljmac** [comment]
Oops, my apologies - I meant the AdGuard Privacy filters

**Comment by ljmac** [comment]
On a side note, I had this problem once before after a filter update, but I was able to fix it by deleting all of AdGuard's data (everything in ~/Library) and rebuilding it, but this didn't work this time. My suspicion is that it isn't properly deleting the old filter set before adding the new one, hence the overload.

**Comment by ljmac** [comment]
Yep, I did follow all of these steps, with the exception of the staged extension, which doesn't appear to exist on my system (not necessary on Mojave perhaps?).

I think it may have worked last time as it coincided with an update to the app itself. Now when I do this, it is initially fine, but a few minutes later when it updates to the current filters, the problem returns.

**Comment by crgmrgn** [comment]
Same issue, here began 2 days ago when the filters were updated … its the AdGuard Privacy filters which seem to overrun the bounds.

**Comment by phantasm** [comment]
In my case, issue appeared after updating to v1.11.13 (Mac OS High Sierra 10.13.6, Safari 13.1.2)

**Comment by crgmrgn** [comment]
I've been running v1.11.13 (MacOS 10.13.6, Safari 13.1.2 also) since its release (approx 1 month ago) and it didn't exhibit this problem until approx 2-3 days ago when I updated the filters, so I'm pretty sure its just a revision of the filter set that has induced this problem.

**Comment by Versty** [comment]
@ljmac Enable AdGuard Tracking Protection filter, then check for the updates. This issue should be fixed.

**Comment by ljmac** [comment]
Yep, all good now. Thank you!
