### ISSUE TITLE
"Too many filters enabled" message even though I have fewer than 150k rules enabled

### ISSUE THREAD

**Issue by afontenot** [AdguardTeam/AdGuardForSafari#862]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS: 11.7.2
- Safari version: 16.2
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, Fanboy's Annoyances

### Issue Details

Steps to reproduce:
1. Enable some basic filters (see above). 

### Expected Behavior

No warning message about too many filters.

### Actual Behavior

Many warning messages about too many filters - in fact, I see one every few minutes and it's spamming my notifications.

On the settings screen, I see the following: "4 filters, 131801 rules, 14612 advanced rules." At the top of the screen it says "Safari cannot use more than 150000 rules in one group."

I'm not sure what a group is, but even if every single rule + filter is in the same group, that's 4 + 131801 + 14612 = 146417.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

There are a variety of related issues, but all of them are closed. At a glance I didn't see any issues where AdGuard was reporting too many filters despite the number of filters being below the Safari maximum.

**Comment by afontenot** [comment]
> #861

Fairly sure that's not relevant to this.

> Upon updating to the latest filters, there are too many Security filters (>50,000), so I have to disable them.

That user has a lot more filters enabled than me, so I assume their issue is that the enabled filters actually do have more than 50k in Security. My error is the more generic "Too many filters enabled. Safari cannot use more than 150000 rules in one group."

**Comment by ljmac** [comment]
I'm quite sure it is the same problem. It is specifically the AdGuard Privacy set since the latest filter update - if you disable this set it will no longer have too many filters.

**Comment by afontenot** [comment]
> I'm quite sure it is the same problem. It is specifically the AdGuard Privacy set since the latest filter update - if you disable this set it will no longer have too many filters.

Thanks, this does indeed work around my issue, although this could just be because it appears to drop the total number of filters by about 80k. The other issue specifically mentions the "Security" list, not the privacy list, as being a problem. Looks like that was a mistake. I'll close this issue as a dupe since it's clear enough now in the other issue what the source of the problem is.

**Comment by ljmac** [comment]
Yes, that was my mistake - it was a bit late when I reported the issue initially. :) But it is indeed the Privacy filters.
