### ISSUE TITLE
Rule to block Facebook Plugin

### ISSUE THREAD

**Issue by victorchor2868** [AdguardTeam/AdGuardForSafari#865]
### Issue Details

I want to block plugin of Facebook, and I have enabled filter of AdGuard Social Media Blocking, but it still appears, may I know how can it blocked? Is it possible to block?
<img width="912" alt="CleanShot 2023-07-03 at 01 19 28@2x" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/87065622/6f3c9753-9eb8-48d1-994a-b2edaa043cc6">
<img width="922" alt="CleanShot 2023-07-03 at 01 20 48@2x" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/87065622/4c574286-203b-4a18-b809-0dd65e573b62">

**Comment by alexx7311** [comment]
Hello! Please send us a link to the website where this plugin can be found and we will send you a rule that can be pasted into user rules to remove it.

**Comment by victorchor2868** [comment]
[https://prn2023.sinchew.com.my/20230705/斗士党希望与国盟合作-慕克力：避免多角战/](url)

Thanks

**Comment by victorchor2868** [comment]
Thanks a lot, it's missing!!!
