### ISSUE TITLE
Typo in General Settings screen

### ISSUE THREAD

**Issue by azehnwirth** [AdguardTeam/AdGuardForSafari#87]
### Typo in General Settings screen
"Light-_**weigth**_ filter lists optimized for Safari Content Blocking API."

![screen shot 2018-11-20 at 21 22 27](https://user-images.githubusercontent.com/4419090/48767484-f45d2100-ed0a-11e8-9458-d1d9a95e661f.png)

### Your environment

* AdGuard for Safari version: 1.01
* Environment name and version: Safari 12.0 (14606.1.36.1.9)
* Operating System: MacOS Mojave 10.14 (18A391)
* Filters you use in AdGuard: Defaults

**Comment by ameshkov** [comment]
ops

**Comment by ameshkov** [comment]
thank you:)

**Comment by floam** [comment]
"AdGuard for Safari is a free and ..." should be "AdGuard for Safari is free and ..."
