### ISSUE TITLE
Daily Telegraph bypassing rules

### ISSUE THREAD

**Issue by IanMetz** [AdguardTeam/AdGuardForSafari#871]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS:Ventura 13.4.1 c
- Safari version:16.5.2
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Annoyances filter

### Issue Details

These user rules:

telegraph.co.uk###main-content > div.grid:nth-child(2) > div.grid-col.grid-col-12:first-child
telegraph.co.uk###advert_tmg_ban
telegraph.co.uk###main-content > div.grid:nth-child(2) > div.grid-col.grid-col-12:first-child
telegraph.co.uk###main-content > div.commercial-unit.u-full-bleed:nth-child(3)
telegraph.co.uk###main-content > div.commercial-unit.u-full-bleed:nth-child(24)
telegraph.co.uk###main-content > div.commercial-unit.u-full-bleed:nth-child(27)
telegraph.co.uk###main-content > article.grid:last-child > aside.grid-col.grid-col-12.tpl-article__layout.tpl-article__layout--sidebar:nth-child(6) > div.tpl-article__sidebar > div.commercial-unit.commercial-unit--sidebar:first-child
telegraph.co.uk###advert_tmg_dyn_0_container
telegraph.co.uk###advert_tmg_dyn_1_container

### Expected Behavior

That the adverts would stay blocked.

### Actual Behavior

On setting the rules, the adverts disappeared.

On reboot, the adverts reappeared, with the rules still in place.

<img width="960" alt="Screenshot 2023-07-22 at 10 39 01" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/31656439/564c4c65-914e-4b92-b387-2828289a4ab2">

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="960" alt="Telegraph" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/31656439/aa05691f-02fc-4cbc-8ea5-851d80889f33">

### Additional Information

The website is not in Allowlist.

And... I am not technical, just an average user!

**Comment by IanMetz** [comment]
The user rules are now working again - I have done nothing.  Odd.

**Comment by Versty** [comment]
@IanMetz Hi! 
The described behavior can be some technical glitch related to content blockers. 
Please reopen this issue, if the problem occurs again.
