### ISSUE TITLE
News & Stock App under macOS platform

### ISSUE THREAD

**Issue by EricRivera88** [AdguardTeam/AdGuardForSafari#874]
### Issue Details

I see there are some advertisement in these stock and news apps and I am recommending you should and/or can certainly suggest how toggles for new options can be added as new features. Here's a guide on adding toggles to enable/disable new options: 

Implement Actions: Assign actions or behaviors to each option when toggled. This may involve enabling/disabling specific functionalities, displaying/hiding certain information, or altering the behavior of existing features. However, these ads should be blocked while customers are able to refocus the newsfeed. 

### Proposed solution

I think some suggest that you may add these features to block advertisement in this programs of Stock and News app that way customers will enrich the lives for your extraordinary service  

### Alternative solution

In future of the new updates for the AdGuard enhancements on the version, It may be better experience toward customers like me to satisfying these new options for Stock and News app under macOS platform alternatively.

**Comment by alexx7311** [comment]
@EricRivera88 Hello! What is the name of this app in the App Store? Could you send us a link to the app and some screenshots with examples of ads?

**Comment by alexx7311** [comment]
@EricRivera88 AdGuard For Safari only blocks ads in the Safari browser. To block ads in applications, you can use the full-fledged AdGuard for Mac application https://adguard.info/en/download.html?os=mac

If you're using AdGuard for Mac please try adding the **News & Stock app** to the list of filtered apps in AdGuard → gear → Preferences... → Network → Applications. If the ads are not hardcoded and the News & Stoc app supports HTTPS filtering, there's a high chance AdGuard will be able to block the ads there.

If you use AdGuard for Safari and use News & Stock in Safari, you can use the Browser Assistant to block specific ad units https://adguard.app/kb/adguard-for-mac/browser-assistant/
