### ISSUE TITLE
Can the adguard settings panel not pop up everytime I start my macbook?

### ISSUE THREAD

**Issue by benfischer1** [AdguardTeam/AdGuardForSafari#875]
### Issue Details

Everytime I restart my mac, and also at seemingly random times (perhaps when Adguard updates something) The settings window pops up, which is annoying clutter on my desktop.  There's no reason for it to be there. I don't need to change Adguard settings very often.

### Proposed solution

Don't pop up that window.

**Comment by Versty** [comment]
@benfischer1 Hi! Sounds like a bug. 
Please specify your macOS version, Safari version, and AdGuard for Safari version.

**Comment by benfischer1** [comment]
Mac OS 13.5Safari 16.6 (18615.3.12.11.2)AdGuard 1.11.13ThanksOn Aug 2, 2023, at 9:06 AM, Diana ***@***.***> wrote:﻿
@benfischer1 Hi! Sounds like a bug.
Please specify your macOS version, Safari version, and AdGuard for Safari version.

**Comment by Drakon74** [comment]
+1 I have the exact same issue.

MacOS Ventura 13.5.
ADguard 1.11.14 (build 301, CT 2.0.41)

I also turned off the option to notify about updates, but that didn't helped.

**Comment by audiocommander** [comment]
same here, AdGuard Panel showing up and making itself the frontmost window since I got AdGuard installed. It's super annoying, as it also terminates fullscreen apps when popping up. Not related to login.
Adguard V 1.11.13

**Comment by audiocommander** [comment]
Here's something I noticed: My Provider just had a short disconnect, so my WiFi wasn't connected to the internet. Immediately after the internet connection became available again, AdGuard was showing its Pop-Up window. Maybe this helps to narrow it further down.
MacBook Air M2, 2022 on MacOS Ventura 13.4.1 (c), AdGuard 1.11.13

**Comment by enakr** [comment]
+1
crm 789086
MacOS: Ventura 13.4.1
Safari: 16.5.2 (18615.2.9.11.10)
AdGuard for Safari : 1.11.14

**Comment by Versty** [comment]
@Aeron @audiocommander @benfischer1 
Could you check the "Login Items" in the system settings?
Is there AdGuard for Safari among the "Open at login" applications? 
Is there any app in the "Allow in the background" list that is named with numbers and has an AdGuard icon?

**Comment by Aeron** [comment]
@Versty, there are no items in “Open as Login” and nothing suspicious in “Allow in the Background” list (only usual AdGuard for Safari, among other services).

**Comment by tylerregas** [comment]
This started happening to me a couple weeks ago. 
Ver: 1.11.13
OS: 13.5
h/w: M1 Mini

**Comment by audiocommander** [comment]
> Could you check the "Login Items" in the system settings?
> Is there AdGuard for Safari among the "Open at login" applications? 

Yes

> Is there any app in the "Allow in the background" list that is named with numbers and has an AdGuard icon? 

No

**Comment by vozersky** [comment]
Guys, let's please keep it in https://github.com/AdguardTeam/AdGuardForSafari/issues/853
