### ISSUE TITLE
Disable macOS safari popup

### ISSUE THREAD

**Issue by prophoto** [AdguardTeam/AdGuardForSafari#880]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13 

### Environment

```markdown
- OS:13.4
- Safari version:16.5
```

### Issue Details

Every other day your app shows a popup when I unlock my computer or reboot. Nag screens are not good UX. 

### Actual Behavior

Turn off nag screen in code or allow me to do it in prefs.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by prophoto** [comment]
bump?

**Comment by onesadlittleboy** [comment]
This bug has been reported multiple times and hasn't been fixed. At that point the best solution is to remove Adguard and look for a different blocker.

https://github.com/AdguardTeam/AdGuardForSafari/issues/875
https://github.com/AdguardTeam/AdGuardForSafari/issues/876
https://github.com/AdguardTeam/AdGuardForSafari/issues/853

**Comment by prophoto** [comment]
Well thats pretty sad is the project dead?

**Comment by vozersky** [comment]
duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/875

**Comment by prophoto** [comment]
Closed, ok since its duplicate. Completed? No.
