### ISSUE TITLE
Blocking YouTube ads in Firefox, Brave and Vivaldi

### ISSUE THREAD

**Issue by LarrytheLaffer** [AdguardTeam/AdGuardForSafari#883]
### Issue Details

Hi Gang:

Just wondering if it is possible to avoid all the advertisements that have become rampant on YouTube?  I am sure you have gotten many requests for this as well as I am sure that YouTube has a lot of systems built in to prevent ad blocking. 

Also, you seem to have singled out Safari as your main Web Browser. I, for one, don't care for that particular browser nor do I use it unless it is a requirement of whatever site I am on. Is AdGuard not effective with Firefox, Brave or Vivaldi?  These browsers are the ones that I have found work best for me.

Thank you for producing such a great product!
Jon

**Comment by alexx7311** [comment]
Hello! To block YouTube ads in Firefox, Brave or Vivaldi, you can use either the full-fledged AdGuard app or our browser extension. Links:
AdGuard For Mac: https://adguard.app/en/adguard-mac/overview.html
AdGuard For Windows: https://adguard.app/en/adguard-windows/overview.html
AdGuard Browser extension: https://adguard.app/en/adguard-browser-extension/overview.html

If you would like to learn more about the functionality of each AdGuard product, you can visit our knowledge base at https://adguard.app/kb/
