### ISSUE TITLE
Youtube information panel removal

### ISSUE THREAD

**Issue by usernamemaxcache** [AdguardTeam/AdGuardForSafari#892]
### Issue Details

I'm tired of YouTubes thought police telling me how to think. I would like to see an end to this. Please make a filter that removes the youtube information panel that loads state funded propaganda. 

### Proposed solution

Filter

**Comment by alexx7311** [comment]
@usernamemaxcache Hello! Please report about this panel via the extension popup.

<details>
  <summary>Screenshot</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/1c6404a2-a6a7-428f-9fea-18eebb79e47d)

</details>

 You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
