### ISSUE TITLE
In `README`, logo is hard to see when using dark theme in GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardForSafari#893]
### Issue Details

In the [README](https://github.com/AdguardTeam/AdGuardForSafari#readme), the logo is hard to see when using the dark theme on GitHub. Also, the app's screenshots look too bright with a light background.

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/19418601/b9f97cd0-d195-46a8-9c40-307326975ae2)

</details>

### Proposed solution

You need to add logo and screenshot options for the dark theme.

Useful link: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by Versty** [comment]
@rakleed done!
