### ISSUE TITLE
AdGuard seems to be using Electron 18.3.15, vulnerable to libwebp zero-click attack

### ISSUE THREAD

**Issue by lpar** [AdguardTeam/AdGuardForSafari#895]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
macOS Ventura 13.6
Safari 16.6
```

### Issue Details

Running a script to report Electron versions [found here](https://infosec.exchange/@TomSellers/111126339492371432):

```
find /Applications -type f -name "*Electron Framework*" -exec \
sh -c "echo  \"{}\" && strings \"{}\" | grep '^Chrome/[0-9.]* Electron/[0-9]' | head -n1 && echo " \;
```

I get

`/Applications/AdGuard for Safari.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
Chrome/100.0.4896.160 Electron/18.3.15`

Electron 18.3.15 is [not supported](https://endoflife.date/electron) and is no longer getting security fixes; and there's a [massive security hole](https://arstechnica.com/security/2023/09/incomplete-disclosures-by-apple-and-google-create-huge-blindspot-for-0-day-hunters/) that affects Electron and is leading to 0-click malware installs as a result.

While the actual blocking extension presumably isn't affected, I can imagine malware being injected by replacing a configured third party blocklist that the preference editor would then download as part of applying filter updates.

### Actual Behavior

AdGuard for Safari in the app store appears to ship with an obsolete and likely extremely insecure version of Electron.

**Comment by crgmrgn** [comment]
A response/clarification on this issue would be much appreciated ASAP.

**Comment by mafredri** [comment]
Does the team have a timeline to update Electron? If not, can it be made a priority? This CVE has been public for some time now, meanwhile the team seems to be [actively rejecting Electron updates](https://github.com/AdguardTeam/AdGuardForSafari/pull/902) and also [making new releases based on the vulnerable Electron version](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.15.309-release).

**Comment by mafredri** [comment]
@alexx7311 I appreciate the response and I understand your motivation for not upgrading because of the aforementioned security issue. However, I can't say I support the decision of staying with an Electron version that reached EOL more than a year ago, and thus, will receive no more security updates. Considering AdGuard for Safari does make outbound network connections and downloads, this is a deal-breaker for me (granted, N=1). I really hope you can reconsider.

**Comment by ameshkov** [comment]
@mafredri I wouldn't say we made a decision to stay with an old Electron version. On the contrary, we're working on completely ditching Electron, it's just this is a big rewrite and we only expect it to happen in 2024 Q1.

**Comment by mafredri** [comment]
@ameshkov that's fair, thanks for sharing that bit of information. 👍🏻

**Comment by MineGene** [comment]
Hi @ameshkov, are there any updates to share on the progress of this?

**Comment by ameshkov** [comment]
Well, takes longer than we expected, but we're close
