### ISSUE TITLE
Shows Ad on Safari

### ISSUE THREAD

**Issue by Opinari2** [AdguardTeam/AdGuardForSafari#899]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: Ventura
- Safari version: 17
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

No ad on my email pages

### Actual Behavior

Ad on my email page

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="416" alt="Screenshot 2023-09-28 at 1 03 24 PM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/146383541/907eeef9-e4a8-463a-beb4-55a3a417f434">

### Additional Information

Tried to remove by restarting browser etc

**Comment by alexx7311** [comment]
@Opinari2 Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
