### ISSUE TITLE
Total rules counter is zero after update

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdGuardForSafari#90]
https://uploads.adguard.com/Nastroiki_AdGuard_dlya_Safari_2018-12-04_7_PP-28-25.png

Restart the program and filters update doesn't help.

**Comment by ameshkov** [comment]
Cannot reproduce this one as well

**Comment by superlex** [comment]
I confirm, sometimes it happens, but it disappears after filters update.

**Comment by Mizzick** [comment]
cannot reproduce

**Comment by superlex** [comment]
@Mizzick 
I'm still able to reproduce it.
Steps:
1) close AdGuard (cmd+quit);
2) open AdGuard;
3) go to menu -> preferences;
4) go to filters tab: total rules counter is 0 for me.
