### ISSUE TITLE
Update the README logo for dark mode

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardForSafari#906]
Logo on the README hasn't been updated for dark mode displays.

Similar to [this commit](https://github.com/AdguardTeam/AdguardForMac/commit/9ff130ccc36c825eb8a25ff01d0d27a3016219f2), so the same for this repo.

**Comment by Versty** [comment]
@jslawler Hi! 
Duplicate of #893. Will be implemented soon.
