### ISSUE TITLE
APP STORE not actually updating, just a spinning cursor

### ISSUE THREAD

**Issue by avincent98144** [AdguardTeam/AdGuardForSafari#907]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: 14.0
- Safari version: STP 180
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter, EasyList, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Peter Lowe's Blocklist, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, I don't care about cookies, EasyList Cookie List

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

APP STORE update actually happens

### Actual Behavior

App sits in the APP STORE/UPDATES and has been spinning for over 24 hours with no UPDATE happening. Reboots do not resolve.

### Screenshots

<details><summary>Screenshot 1:</summary>

![SCR-20231007-fbhw](https://github.com/AdguardTeam/AdGuardForSafari/assets/65172111/8800e9ff-bc36-4a2a-ba7d-8347d147ad56)

</details>

**Comment by alexx7311** [comment]
@avincent98144 Please click on AdGuard icon in the menu bar  > 'About' and click 'Update'.
If it didn't help please reinstall the app.

**Comment by alexx7311** [comment]
@avincent98144 The issue will be closed in a few days if we do not hear back from you.
