### ISSUE TITLE
AdGuard Safari icon getting disabled after update

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdGuardForSafari#91]
### Steps to reproduce

1. setup AG for Safari v1.0.1 from AppStore
2. run it, enable both checkboxes in Safari settings
3. exit the app, then set up a new version 1.1
4. run the app again

### Expected behavior
AdGuard Safari icon is enabled

### Actual behavior
AdGuard Safari icon getting disabled

**Comment by ameshkov** [comment]
Confirmed that it's okay with the normal app store update
