### ISSUE TITLE
Youtube's anti-ad is getting in the way

### ISSUE THREAD

**Issue by ovvldc** [AdguardTeam/AdGuardForSafari#910]
### Issue Details

If I go to youtube.com with Ad guard for Safari on MacOS enabled, that website refuses to show me any videos unless I disable ad blocking for YouTube. And I do not want to.

If I understand correctly, the German courts at least suggest that ad blocking is not illegal (https://adguard.com/en/blog/eyeo-axel-springer-lawsuit-copyright-win.html), so I should be allowed to do this.

### Proposed solution

Ad another rule (scriptlet?) that intercepts youtube's checking for ad blockers, or the script that blocks the videos.

### Alternative solution

Disable Adguard, but that kind of deafest the whole purpose of an ad blocker.

**Comment by ovvldc** [comment]
I saw this one? https://github.com/AdguardTeam/Scriptlets/issues/333

**Comment by ovvldc** [comment]
Never mind, I got it to work with a couple of additional filters...

Perhaps you could write a blog post on which filters to turn on to avoid this kind of ad enforcement?

**Comment by ovvldc** [comment]
As suggested, the problem was not in Ad guard necessarily but in setting it up properly.

**Comment by st12141997** [comment]
May I ask which additional filters you use to make it work?

**Comment by ovvldc** [comment]
I currently have a lot of them running: Peter Lowe's Blocklist,  Fanboy's Enhanced Tracking, EasyPrivacy, and Spyware Filter in the Privacy section, then Fanboy's Annoyances, Adblock Warning Removal List, and then a Filter against Annoying Elements that contains AdGuard Widgets, AdGuard Other Annoyances, AdGuard Mobile Apps Banner, AdGuard Popups, and AdGuard for Cookies. Also the NoCoin Filter and the Online Malicious URL Blocklist.

Mind you, the ad blocking breaks regularly. I feel like I have a window when the filters catch up with Youtube's newest blocking, and then they stop working overnight when Youtube comes up with something new.

**Comment by alexx7311** [comment]
Dup. of #913

**Comment by bschollnick** [comment]
This still seems to be an issue, deactivating or reactivating rules does not seem to change anything.
While I can block the "ad detected" screen.  The video player is then unusable.  The controls don't seem to do anything. 
It seems like youtube is detecting the presence of the ad blocker, and not any one specific rule?

**Comment by ovvldc** [comment]
I expect that Adguard and the other adblockers on one hand and Google on the other hand are constantly trying to tighten and evade the adblockers.

**Comment by ovvldc** [comment]
YouTube was fine last week, but blocked again today. And I assume Adguard and  allied people are hard at work to work around the block again.
