### ISSUE TITLE
Allow option to disable settings window pop-up

### ISSUE THREAD

**Issue by lukeredmore** [AdguardTeam/AdGuardForSafari#918]
### Issue Details

Frequently (I'm assuming after updating), AdGuard will automatically launch its settings window. I'm not sure what permissions this window has, but it immediately foregrounds itself and does not respect the currently foregrounded/full screen app, Do Not Disturb, etc. It can make Safari "risky" (so to speak) to have open during a game, movie, etc.

### Proposed solution

Add option to disable this behavior, or just present it as a push notification.

### Alternative solution

Temporary fix (I believe) would be to disable automatic updates, but that's obviously not an ideal solution

**Comment by craftey** [comment]
I use Adguard for some years now and it seems, something has changed. Either a macOS upgrade or an update of Adguard introduced the issue, that the app window and dock icon become visible after a while of operating nicely in the background. I think, it typically pops up when I open the lid of my MacBook. But I still need to figure out what the exact pattern is. But it happens quite often, daily I guess.

I have the following relevant settings enabled:
- Launch at Login
- Show in the menu bar

I will test if disabling automatic update is related to this behaviour on my machine as well. I ll disable it for a while and report here.

**Comment by illixion** [comment]
I've been experiencing this issue for almost a year now, first reported it to AdGuard on January 5th of this year with no resolution, and I've found that this is indeed caused by some internal auto-update mechanism (as this happens even while I have an AdGuard update pending in the App Store.)

**Comment by illixion** [comment]
Here's an info-level log file that might help: https://gist.github.com/illixion/0e07bc34fc0189523b7b5f0b12af7d9b

I've unlocked the screen at 11:19:05.308 and the window seems to have been instantly activated. Perhaps this is because the dock icon isn't being hidden properly while the screen is off, and so macOS automatically activates the app when you log in? One possible solution is to follow macOS conventions and only create a window when the user presses Cmd+N instead of whenever the app becomes active.

**Comment by Versty** [comment]
@lukeredmore Hi! 
Updating to the latest version (1.11.15) should resolve this issue. 
Please try to update and let us know the result.

**Comment by Versty** [comment]
@illixion @lukeredmore @craftey 
How is it going?

**Comment by illixion** [comment]
@Versty haven't seen this happen on 1.11.15 so far, will add another comment if it does, thanks for the update!

**Comment by lukeredmore** [comment]
@Versty Same here, working great so far! Thanks!

**Comment by craftey** [comment]
Tested with hourly updates before and after the upgrade. The new version seems to have fixed it. Good work. Thank you.
