### ISSUE TITLE
YouTube videos become black after running AdGuard.

### ISSUE THREAD

**Issue by sleepylegs** [AdguardTeam/AdGuardForSafari#919]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.15

### Environment

```markdown
- OS:
- Safari version:
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

Ad blocking and normal video palyback

### Actual Behavior

Video becomes black. its just a black video with audio but no visuals.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot 2023-10-21 at 2 16 15 PM](https://github.com/AdguardTeam/AdGuardForSafari/assets/63106330/03fc7314-e88b-4397-bb15-b57bf5d8ec85)
![Screenshot 2023-10-21 at 2 16 21 PM](https://github.com/AdguardTeam/AdGuardForSafari/assets/63106330/b94817c7-f9f5-4cba-9b5a-2173a3ca835a)

</details>

**Comment by alexx7311** [comment]
@sleepylegs Please install the latest beta build at https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.16.323-beta and check if the problem persists.

**Comment by alexx7311** [comment]
@sleepylegs Has the issue been resolved?

**Comment by sleepylegs** [comment]
yes it works. thank you!
