### ISSUE TITLE
Problem with Youtube. I have already sent and email and I was asked to write through the app.

### ISSUE THREAD

**Issue by ujujujju** [AdguardTeam/AdGuardForSafari#920]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: 12.4
- Safari version: 15.5 (17613.2.7.1.8)
```

### Issue Details

Steps to reproduce:
1. Youtube isn't working
2. I can't delete the app (i used the method from your website, but nothing changed)
3.

### Actual Behavior

Problem is continuing with Youtube and deleting

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Добрый вечер! Вынуждена обратиться за помощью в решении проблемы, которую сама не могу понять. 
Изначально проблема возникала в том, что Ютуб был недоволен с использованием AdGuard и по началу я могла нажать на кнопку "Показывать рекламу". Сейчас же у меня просто висит это окно и я не могу пользоваться платформой. 
Дальше при попытке удалить программу, компьютер (Мак) не дает этого сделать: всплывает окно "Вы не можете объект перенести в корзину, потому что приложение работает"
Как через само приложение удалить его или остановить его работу, я не поняла и не нашла на Вашем сайте ничего, кроме способа "Перетащить в корзину", поэтому и прошу помощи в решении этой проблемы. Заранее спасибо.
С уважением, 
Виолетта Василовская

**Comment by alexx7311** [comment]
@ujujujju Здравствуйте! 
1. Скоро мы выпустим обновление, которое решит проблему с ютубом. Пока вы можете попробовать отключить защиту AdGuard на сайте YouTube. Для этого перейдите на youtube.com, шелкните по значку AdGuard рядом с поисковой строкой Safari и уберите галку с соответствующего чекбокса (см. скриншот). Следить за ходом решения проблемы можно в задаче #913
<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/9481b2e8-513a-4a33-a2d3-815adebc1de2)

</details>

2. Чтобы полностью отключить AdGuard for Safari, кликните по иконке AdGuard на верхней панеле вашего устройства и уберите галку с "Блокировка в Safari включена".
Инструкции по удалению AdGuard for Safari вы можете найти в нашей базе знаний по ссылке https://adguard.info/kb/ru/adguard-for-safari/installation/#uninstall
