### ISSUE TITLE
Twitter Ads

### ISSUE THREAD

**Issue by G7TOK** [AdguardTeam/AdGuardForSafari#923]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.15

### Environment

```markdown
- OS:Sonoma
- Safari version:17.0 (19616.1.27.211.1)

Stopped blocking Twitter ads
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Social Blocking List, Fanboy's Enhanced Tracking List, Fanboy's Anti-Facebook List

### Issue Details

Steps to reproduce:
1.I go to twitter
2.there are ads
3.

### Expected Behavior

No ads in twitter

### Actual Behavior

Ads in twitter

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@G7TOK Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
