### ISSUE TITLE
Mcafee

### ISSUE THREAD

**Issue by Maeu2023** [AdguardTeam/AdGuardForSafari#927]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.15

### Environment

```markdown
-MacOS Ventura 13.4.1 
- Safari version:16.5.1
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, ---Third-party filters---, EasyList, ABPindo, Bulgarian list, EasyList China, EasyList Czech and Slovak, EasyList Dutch, EasyList Germany, EasyList Hebrew, EasyList Italy, EasyList Lithuania, Latvian List, Liste AR, Liste FR, ROList, EasyPrivacy, Icelandic ABP List, AdBlockID, Greek AdBlock Filter, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Thai Ads Filters, Hungarian filter, Peter Lowe's Blocklist, Xfiles, Adblock Warning Removal List, Online Malicious URL Blocklist, RU AdList - Counters, ABPVN List, Fanboy's Enhanced Tracking List, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish GDPR-Cookies Filters, Estonian List, CJX's Annoyances List, Polish Social Filters, Fanboy's Anti-Facebook List, List-KR, xinggsf, I don't care about cookies, EasyList Spanish, KAD - Anti-Scam, Adblock List for Finland, ROLIST2, Iranian filter, road-block, Polish Annoyances Filters, Polish Anti Adblock Filters, Fanboy's Anti-thirdparty Fonts, EasyList Cookie List, NoCoin Filter List, Frellwit's Swedish Filter, YousList, AlleBlock, EasyList Polish, Polish Anti-Annoying Special Supplement, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List, Legitimate URL Shortener, Dandelion Sprout's Serbo-Croatian List, IndianList

### Issue Details

Steps to reproduce:
1. KEEP PUP IT UP ON THE SCREEN
2.
3.

### Expected Behavior

IT KEEP POPPING UP ON THE SCREEN WITH THE GENERAL MANU LOGO.

### Actual Behavior

IT KEEP POPPING UP ON THE SCREEN WITH THE GENERAL MANU LOGO.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

IT KEEP POPPING UP ON MY RIGHT UPPER CORNER AND IS  ANNOYING!!

**Comment by alexx7311** [comment]
@Maeu2023 Hello! Please describe the problem in as much detail as possible, reproduce the problem and take a screenshot.

**Comment by alexx7311** [comment]
@Maeu2023 The issue will be closed in a few days if we won't get a response from you.
