### ISSUE TITLE
Licence issue

### ISSUE THREAD

**Issue by G7TOK** [AdguardTeam/AdGuardForSafari#928]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.15

### Environment

```markdown
- OS:
- Safari version:

Hi,

I have an apple sub, but the version I download from the App Store appears to show as a free version when I log into my account.
Apple do not provide a licence key so I can’t add it in my account and download the correct version.
How do I rectify?

Note: the Apple mail app will not let me mail your support address from the registered email I use for my Adguard account, so in order to preserve my privacy I CANNOT use email.
Not unless Apple fix the mail app or Adguard provide a different method.

Best,
Gary
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Fanboy's Anti-Facebook List

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

My account does not show my subscription and Apple do not provide a key to add it.

### Actual Behavior

Unable to link my account to my sub

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@G7TOK Hello! For license-related questions, please contact our support team at `support@adguard.com`. You can use any email address to write an email to our support, just include your order number in the message or attach your purchase receipt and our support team will be able to help you.

AdGuard for Safari is a free application. The application that can be activated with a license is called AdGuard for Mac, and you can get it from our website at https://adguard.info/en/adguard-mac/overview.html

Step by step guide on activating your license on Mac: https://adguard.app/kb/general/license/activation/#activating-adguard-for-mac
