### ISSUE TITLE
Ad blocker settings window keeps opening on Mac

### ISSUE THREAD

**Issue by fKing** [AdguardTeam/AdGuardForSafari#929]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14 (build 301, CT 2.0.41)

### Environment

```markdown
- OS: sonoma 14.2 beta2
- Safari version:  17.2 (19617.1.13.11.1)
```

### Issue Details

Steps to reproduce:
1. window sometimes pops up on startup
2. window sometimes pops up on wake
3. window sometimes pops up during mac use

### Expected Behavior

window shouldn't open unless app is selected to open

### Actual Behavior

window simply pops up randomly; has been happening on sonoma for some time...

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@fKing Hello! The issue has already been fixed. Please update to [1.11.15](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.15.309-release) or [1.11.16 beta](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.16.323-beta).
