### ISSUE TITLE
Adguard Privacy filters overruns 50k limit

### ISSUE THREAD

**Issue by crgmrgn** [AdguardTeam/AdGuardForSafari#932]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16beta

### Environment

```markdown
- OS: macOS 10.13.6
- Safari version: 13.1.2
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

Running v.1.11.16beta, with "Adguard Privacy Protection filter" and "Peter Lowe's Blocklist" enabled, everything was fine, no errors regarding filtering.

### Actual Behavior

"Adguard Privacy Protection filter" update was pushed and now receiving errors regarding "Too many filters enabled. Safari cannot use more than 50000 rules in one group".

Disabled the "Peter Lowe's Blocklist", as a process of elimination, so now only one set of filters is being loaded, still generates errors. "Adguard Privacy" ruleset alone, breaks over the 50k limit, no user rules in place.

"Adguard Privacy Protection filter" is id'ed as v2.0.63.40, as at 15/11/2023

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ljmac** [comment]
I can confirm this as well

**Comment by maximtop** [comment]
Thank you all, this will be fixed on the filters part.

**Comment by maximtop** [comment]
Yep, update your filters to solve this problem. Closing this issue.
