### ISSUE TITLE
Block Advertising on twitch.tv - Possible?

### ISSUE THREAD

**Issue by herry23xet** [AdguardTeam/AdGuardForSafari#941]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16

### Environment

```markdown
- OS: 14.2.1
- Safari version: 17.2.1
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, EasyList, EasyList Germany, EasyPrivacy, Peter Lowe's Blocklist, Online Malicious URL Blocklist

### Issue Details

Steps to reproduce:
1. When I want to watch streams on twitch.tv, adverts appear before and during the broadcast.
Is there a way to block this advertising?

### Actual Behavior

Advertising on twitch.tv. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@herry23xet Hello! The problem could be solved with [AdGuard Extra](https://github.com/AdguardTeam/AdGuardExtra) userscript.

Unfortunately, you can't enable userscripts in AdGuard For Safari, but if you use the full-fledged AdGuard app for Mac, Windows or Android, there is an option in the app's settings with AdGuard Extra enabled by default. 

You can also use third-party userscript managers with which you can install AdGuard Extra.
