### ISSUE TITLE
Ability to remove class from an element.

### ISSUE THREAD

**Issue by oleg-andreyev** [AdguardTeam/AdGuardForSafari#942]
### Issue Details

Some website are blocking overflow-y until you doing something in annoying popup.

### Proposed solution

I'd like to have an ability to alter attitudes: like remove class or add higher priority style attribute

**Comment by Alex-302** [comment]
It can be done using scriptlet:
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-remove-class

or by css rule like `#$#body { overflow: auto !important; }` (sometimes also must be applied to `html` element)
