### ISSUE TITLE
Youtube blocking adguard

### ISSUE THREAD

**Issue by AGnepp** [AdguardTeam/AdGuardForSafari#943]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16

### Environment

```markdown
- OS: Sonoma 14.2.1
- Safari version: 17.2.1 (19617.1.17.11.12)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1. go to any monetized video like: https://www.youtube.com/watch?v=w6t2Q2F2NGY
2. see the attached image instead of video
<img width="993" alt="Screenshot 2024-01-11 at 1 54 19 PM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/18485077/d0f0dc62-15f1-41d9-bcc5-988de01da927">
3. Can't watch YouTube videos unless I disable AdGuard

### Expected Behavior

To watch YouTube videos add-free.

### Actual Behavior

Youtube blocks video

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="993" alt="Screenshot 2024-01-11 at 1 54 19 PM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/18485077/d0f0dc62-15f1-41d9-bcc5-988de01da927">

</details>

**Comment by BigTimeStats** [comment]
+1, I am facing the same issue. Seemed like it happened shortly after updating to Sonoma 14.2.1.

Sonoma 14.2.1
Safari 17.2.1
Adguard 1.11.16

In the past when this happened I used to be able to update adguard and restart mac / safari and it would work again. This doesn't seem to resolve the issue this time

**Comment by BigTimeStats** [comment]
At least for me this randomly started working again on safari.

**Comment by AGnepp** [comment]
Me too today. So strange I will mark this issue as resolved I guess?

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdGuardForSafari/issues/913

**Comment by BigTimeStats** [comment]
This is not a dupe. This continues to plague this ad blocker from time to time. Just because it eventually resolves itself doesn't mean that it worked as intended and this issue has been fixed for good. I would hazard to guess that this will continue to happen again and it would be in the best interest of this community to have a framework to handle these flare ups and not ignore them as "dupes".
