### ISSUE TITLE
youtube slow to load with Adguard enabled

### ISSUE THREAD

**Issue by derekschrock** [AdguardTeam/AdGuardForSafari#947]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16

### Environment

```markdown
- OS:14.2.1 (23C71)
- Safari version:17.2.1 (19617.1.17.11.12)

```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Goto https://www.youtube.com see it slowly load, scroll down a couple pages and see infinite scrolling updates stop or are slow to load.

As described here https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2688 youtube.com is slow to load and slow to update with Adguard for Safari enabled.

Like the comment https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2688#issuecomment-1900687685 filter updating and cookie clearing doesn't help.

Assuming that 4.3.4 beta fixes this and it's not part of the updatable filters can this same change be made to the Safari extension?

### Expected Behavior

Not be slow to load

### Actual Behavior

It's slow to load and update.  With the extension off everything is fine.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by swarupbc** [comment]
same here

**Comment by TechnicalLee** [comment]
Also experiencing extremely slow performance on YouTube in the past few days, disabling all AdGuard plugins restored speedy performance.

**Comment by Emahhh** [comment]
The Adblock Plus team had the same issue, and they fixed it in a recent update. I hope AdGuard can also fix this quickly.

https://www.neowin.net/news/adblock-google-did-not-slow-down-and-lag-youtube-performance-with-ad-blocker-on/

**Comment by BigTimeStats** [comment]
I am still experiencing this issue and have moved to using firefox instead

**Comment by derekschrock** [comment]
YMMV, but I disabled content blockers (Safari, Settings for youtube.com, uncheck Enable Content Blockers) and while I'm getting more of the youtube promo content and banners, I've yet to see youtube play any ads.  Disabling it for youtube for the time being could be a valid workaround for now.

**Comment by alexx7311** [comment]
@derekschrock @TechnicalLee @Emahhh @BigTimeStats @cattyhouse Hello! It looks like the problem was with the EasyList filter. Please try updating the filters, clearing Safari browser cookies and see if the problem persists.

**Comment by derekschrock** [comment]
Looks good from here as well.

**Comment by Hildebrand** [comment]
Page loading itself seems ok, but video loading still takes ages. Seems this is still an issue here.
