### ISSUE TITLE
SECURITY: AdGuard for Safari is logging all URLs you visit

### ISSUE THREAD

**Issue by dj-documentation** [AdguardTeam/AdGuardForSafari#952]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16

### Environment

```markdown
- OS: Sonoma 14.3
- Safari version: 17.3
```

### Issue Details

Steps to reproduce:
1. Install AdGuard for Safari
2.
3.

### Actual Behavior

AdGuard for Safari is logging URLs to ~/Library/Group Containers/TC3Q7MAJXF.com.adguard.safari.AdGuard/Logs/

**Comment by dj-documentation** [comment]
@Mizzick @tvinzz @maximtop AdGuard for Safari is logging URLs to disk

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdGuardForSafari/issues/940
