### ISSUE TITLE
Getting 'splash page' of ads instead of just getting to video on YouTube.

### ISSUE THREAD

**Issue by swoondrones** [AdguardTeam/AdGuardForSafari#957]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard for Safari

### Environment

```markdown
- OS:Sonoma 14.3.1
- Safari version: 17.3.1

I have all filters going except social media, but have always had social media filter off for years.
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

If the specific AdGuard for Safari extension is off, I get the splash page, but turn it on and it always goes straight to the video.  The dilemma is the splash pages are coming back. I turn the extension off and on again ad it seems to go back to the usual behaviour of going straight to video, but then the splash pages come back again. This is really unusual, and really frustrating. I do mot know how to fix it. 

I uninstalled and reinstalled, but it ia doing the same thing.

### Expected Behavior

It should go straight to video without splash pages of blocked ads.

### Actual Behavior

I get these splash pages of the ads, for the duration of the blocked ad. As best as I cna figure.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1111" alt="Screenshot 2024-02-18 at 02 29 05" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/76269339/16a4aeba-5ac9-4a27-a4aa-7da6b46a29e9">

</details>

### Additional Information

The full blown AdGuard app was doing this,  but AdGuard for Safari did not, but now it is. It is really really really frustrating. I can't fix it. does AFS need an update? Please update it. Please.

**Comment by alexx7311** [comment]
@swoondrones Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
