### ISSUE TITLE
facebook rules won't save

### ISSUE THREAD

**Issue by cesarre13** [AdguardTeam/AdGuardForSafari#962]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

latest

### Environment

```markdown
- OS:sonoma 4.1.1 (23B81)
- Safari version:Version 17.1
```

### Issue Details

Steps to reproduce:
1.spected results
<img width="1512" alt="Screenshot 2024-03-01 at 3 53 09 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/161818847/266bb3ed-5c60-4f56-918e-4b90f1627170">

2.i use a normal blocking process
<img width="1512" alt="Screenshot 2024-03-01 at 3 58 35 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/161818847/4d65b65f-b4b4-4cc8-8ada-96f93713e2ec">

3.
<img width="1512" alt="Screenshot 2024-03-01 at 3 58 40 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/161818847/1cd2eead-2180-4e71-ab91-7fce7f8ff3e9">

### Expected Behavior

i want to block stories feed and  some elements of facebook main page

### Actual Behavior

it blocks  when i press block but when i restart or reload the page it won't keep the settings

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@cesarre13 Hello! You need to clean your browser cookies or check the blocking of elements in the browser's incognito mode. The browser saves page elements in cache, and if you don't clear cookies, what you described will happen.

**Comment by alexx7311** [comment]
@cesarre13 Note that some elements can't be blocked by the assistant, so you may need to create the rules yourself.
To learn how to do it, you can refer to our knowledge base at https://adguard.info/kb/general/ad-filtering/create-own-filters/
