### ISSUE TITLE
The website does not work only on the Adguard Safari.

### ISSUE THREAD

**Issue by alxxjd** [AdguardTeam/AdGuardForSafari#967]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.17

### Environment

```markdown
- OS: Mac os
- Safari version: Version 17.2.1
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. I'm trying to download the app from apkmirror, but suddenly it doesn't load.
2. I stayed on the web page for about 3 seconds and suddenly an error appears.
3. If you use a different filter without using an Adguard base filter, it works fine.
4. It seems necessary to check if there is a filter in the base filter that blocks the loading of the website.

### Expected Behavior

Both mac and ios have the same problem.
<img width="1512" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/160719549/2a539bbe-6f93-4533-a4ff-d3b84715c089">

### Actual Behavior

<img width="1512" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/160719549/74de93c7-bb9a-43d6-8fda-8772149f82dc">

### Screenshots

<details><summary>Screenshot 1: apkmirror.com screenshot</summary>
<img width="1512" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/160719549/0f6ff9ab-c7c8-415d-a136-009a6b591f5c">

</details>
<details><summary>Screenshot 2: Adguard Filter</summary>
<img width="948" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/160719549/c5717a8b-42a6-4143-bfb9-84c480f95013">

</details>

### Additional Information

Is there a way to solve it in a way that the user doesn't control?

**Comment by alexx7311** [comment]
@alxxjd Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
