### ISSUE TITLE
loawa.com website is not displaying correctly

### ISSUE THREAD

**Issue by liam2589** [AdguardTeam/AdGuardForSafari#968]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.17

### Environment

```markdown
- OS:IOS & Mac os
- Safari version:17.3
```

### Issue Details

Steps to reproduce:
1. When I turn on the Adguard base filter, I can't use web pages. And this issue only occurs in Safari.
2. The problem occurs as if all CSS hasn't been loaded.

### Expected Behavior

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163834442/1ca0b223-eb57-4224-844f-2d19112d4c54)

### Actual Behavior

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163834442/bdd9f929-7a2b-49a7-ae2d-ed0765d8b0ec)

### Screenshots

<details><summary>Screenshot 1: chrome Adgaurd setting</summary>

<b>Only use basefilter</b>
![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163834442/74f9ce89-a8b5-450c-80ac-d67688b58994)

</details>
<details><summary>Screenshot 2: safari Adgaurd setting</summary>

<b>Only use basefilter</b>
![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163834442/33c0969c-a339-4c06-b09b-fd0078b354f0)

</details>

### Additional Information

**Please respond to the question.**
1. Why does the issue only occur in Safari?
2. Can you provide a solution?

**Comment by alexx7311** [comment]
@liam2589 Hello! Please update the filters and check if the problem persists.
If it does you can report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form

**Comment by piquark6046** [comment]
@liam2589 
Also, please install [microShield userscript](https://github.com/List-KR/microShield) that resolves the Ad-Shield issue.
If you want to read its installation instruction written in Korean language, please refer https://community.list-kr.com/docs/AdGuard/Userscripts/microShield.
