### ISSUE TITLE
Page CSS rendering issue

### ISSUE THREAD

**Issue by owen7298** [AdguardTeam/AdGuardForSafari#970]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.2

### Environment

```markdown
- OS: IOS
- Safari version: version 17.3
```

### Issue Details

Even after resetting Adguard filter, the error still occurs.
The issue only occurs on the Safari browser when accessing loawa.com.
Disabling Adguard base filter resolves the issue.
Doesn't occur immediately; it takes about 3 seconds to manifest.

### Expected Behavior

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163830611/868f13da-306e-4d26-9e62-fc83fba18569)

### Actual Behavior

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163830611/4f050f04-2fca-4755-82ad-bdfb52c5352b)

### Screenshots

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163830611/981a3ae9-259c-40f0-b441-0f79d6c0eebe)

### Additional Information

Considering it occurs only on Safari, and browsers can behave differently, it seems necessary to check if the base filter is functioning properly on Safari.

**Comment by alexx7311** [comment]
@owen7298 Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
