### ISSUE TITLE
Unable to reload when AdGuard for Safari is enabled and Web Inspector is displayed

### ISSUE THREAD

**Issue by shungo27** [AdguardTeam/AdGuardForSafari#972]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.17

### Environment

```markdown
- OS: macOS Sonoma 14.4.1
- Safari version: 17.4.1
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter

### Issue Details

Steps to reproduce:
1. Enable AdGuard for Safari.
2. Open Web Inspector in Safari (Command + Option + I).
3. Reload Safari (Command + R).

### Actual Behavior

The progress bar is stuck and the reload does not finish. At this, AdGuard Scriptlets Version 1.10.1 is displayed in Web Inspector.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

There are two ways to reload:
a. Close Web Inspector
b. Disable AdGuarod for Safari from Safari preferences.

**Comment by alexx7311** [comment]
@shungo27 Hello! We couldn't reproduce the problem. Is reload not working on any particular page or all pages? Have you tried reinstalling AdGuard for Safari?

**Comment by shungo27** [comment]
@alexx7311 hi. Almost all pages cannot be reloaded. I have reinstalled and updated the filters about 3 times.

google.com
apple.com
amazon.com

**Comment by dawwe** [comment]
I have almost the same issue, once in a while pages cant load, the tab is "frozen" and just showing a blank page / activity is ongoing but the page dont load. 

Can't right click to bring webinspector up, pause on adguard and the pageloading works

AdGuard can then be enabled again and It works for a while, this happens a couple of times a day. 
Can I try to activate some kind of logging to maybe get a log to send?

Sonoma 14.4.1 , newest Safari

**Comment by alexx7311** [comment]
@shungo27 @dawwe Are there any other extensions installed in Safari besides AdGuard for Safari? If installed, try disabling them.
Please collect the logs according to these instructions:

1. Make sure all Safari content blockers are enabled;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the extension settings --> Export logs and system info;
4. Send the archive to [apple@adguard.com](mailto:apple@adguard.com) and mention this issue number (972) in the subject.

**Comment by dawwe** [comment]
No other extensions installed 

All Safari content blockers are enabled, I tried exporting logs in my own faultfinding but did not se anything out of the ordinary, but will record time and send logs when it happens again.

When the fault happens the blur "loading" bar is present, has moved about 1/4 of the way and it just sits there until the tab / safari is closed or pause AdGuard. The tab is unresponsive , cant open webinspector or right klick anywhere on the blank page beeing displayed

**Comment by dawwe** [comment]
Can also note that I did a clean install with the guide from AdGuards homepage deleting all data yesterday but the error occured again this morning

**Comment by dawwe** [comment]
@alexx7311  - Sent a logfile to the above emailaddress.

**Comment by dawwe** [comment]
Is there a way to activate more logging to catch the deadlock that seems to happen?
When this happens and i kill "AdGuardForSafariBlockerExtension" process the page continues to load correctly, so it seems like a loop or a regexp that can't  finish somewhere in the rules

**Comment by shungo27** [comment]
@dawwe Your issue seems different than mine. My macOS process does not have "AdGuardForSafariBlockerExtension".
<img width="907" alt="process" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/7065076/89aeb22f-b370-4d10-8fd4-3f4c2bfa8237">

**Comment by dawwe** [comment]
@shungo27  - Im sorry if I hijacked your issue, I assumed that the issue was the same, maybe I should create a related issue instead if they are not the same

**Comment by dawwe** [comment]
My problem seems to be related to "DisplayLink" for an external screen, when "Display Link Manager" was not active Safari would not hang,  and now on Sonoma 14.5 the error seems to have been rectified.

@shungo27  - also using a dock and display link?

**Comment by shungo27** [comment]
@dawwe no, I only use a macbook air.

**Comment by shungo27** [comment]
I was able to solve the problem by unchecking "All Requests" as shown in the attached screenshot.
![allrequests](https://github.com/AdguardTeam/AdGuardForSafari/assets/7065076/ce8dd586-a32f-4ccf-931e-d5a3f512f0e5)

**Comment by shungo27** [comment]
I was able to solve the problem by unchecking "All Requests" as shown in the attached screenshot.
![allrequests](https://github.com/AdguardTeam/AdGuardForSafari/assets/7065076/b59e03b8-84f7-4767-b350-0edee0fa8ef7)
