### ISSUE TITLE
Web apps support

### ISSUE THREAD

**Issue by Royalzzzzzz** [AdguardTeam/AdGuardForSafari#974]
### Issue Details

At first glance the application looks amazing but I wanna request for a feature i.e. is it possible to enable ad guard for my web apps as well? Like I have created few web apps through safari but pop up appears on them so is it possible for ad guard to block the pop ups in those web apps too????

### Proposed solution

n/a

### Alternative solution

n/a

**Comment by Versty** [comment]
@Royalzzzzzz Thank you for suggestion! 
We recently found out that this is a Safari-related bug and reported it to Apple. 

Stay tuned in #872
