### ISSUE TITLE
A banner (about cookies) is masked, so we see only a greyed content

### ISSUE THREAD

**Issue by quark67** [AdguardTeam/AdGuardForSafari#979]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.17

### Environment

```markdown
- OS: Sonoma 14.4
- Safari version: 17.4
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard French filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. I don't be sure if the list of filter is complete, as it is written in English, and some are note listed (eg privacy).
2. Here is a screenshot of the list:
3. 
<img width="917" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/9338576/79d8d67f-3a4d-455f-a878-46474e1af1d3">

4. Go to https://videos.univ-grenoble-alpes.fr/la-formation/864-cours-d-introduction-la-relativit-g-n-rale/
5. Content is greyed:
6. 
<img width="1718" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/9338576/09111456-0f2f-4384-90e4-05306a877055">
7. If I disable Adguard on this site, I see this (a banner about cookies, which block access when it is hide by Adguard)
8. 
<img width="2193" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/9338576/890d7697-7c96-47d9-b811-d4cd981a7b6c">

### Expected Behavior

No greyed content, but the content as if there is no banner.

I expect to see this:

<img width="1949" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/9338576/206bc9a4-54cd-4203-868b-0ee3e16e8da4">

(Either the content after I click on the banner with Adguard enabled, but for this, I need to see the banner with Adguard enabled, or the content not greyed out, without seeing the banner and have to click on the accept button)

### Actual Behavior

I only see a greyed content, with no interaction possible (unable to click on a video).

<img width="1513" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/9338576/4e314b29-231c-4fc5-9811-ea3a9ba9bdca">

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@quark67 Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
