### ISSUE TITLE
Whitelisted site still gets stuff blocked

### ISSUE THREAD

**Issue by fgimenezm** [AdguardTeam/AdGuardForSafari#98]
### Steps to reproduce
1. install AdGuard and configure your filters
2. go to www.clarin.com
3. verify ads are blocked (compare with other browser if needed)
4. click AdGuard icon and and un-check the "Enabled for this site" checkbox (site gets reloaded)

### Expected behavior
Ads should show up (trust me, this site has many)

### Actual behavior
Ads are not displayed. Some palceholder space shows up where some of the ads should be but no ads are there.

<details><summary>Screenshots:</summary>
With AdGuard enabled ads are beautifully removed and the page looks clean as expected:
<br>
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/8161434/49770996-d2314000-fcc5-11e8-9774-7327ae18fac7.png">
<br><br><br>
After un-checking the "Enabled for this site" checkbox to whitelist the site, notice the white space on the right in the screenshot and no ads at the bottom:
<br>
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/8161434/49770244-5da8d200-fcc2-11e8-83c6-f6e17f1ab87c.png">
<br><br><br>
If I disable ad blockers for this site in Safari's settings this is how it looks (ads below the page header, in the right column and at the bottom):
<br>
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/8161434/49770316-b4aea700-fcc2-11e8-8e18-58c0a9c91a89.png">

</details>

### Your environment
* AdGuard for Safari version: 1.1.0
* Environment name and version: Safari 12.0.2 (14606.3.4)
* Operating System: macOS Mojave 10.14.2 (18C54)
* Filters you use in AdGuard:
 AdGuard Base Filter
 AdGuard Mobile Ads filter
 Easylist
 AdGuard Spyware filter
 Adblock Warning Removal List
 Malware Domains
 NoCoin Filter List
 AdGuard Safari filter
 AdGuard Spanish/Portuguese filter
* Any other browser extensions you have installed:
 LastPass
 Webex Meetings
 Box Tools

**Comment by ameshkov** [comment]
@Mizzick we might need to use `if-top-url` for this case

**Comment by Mizzick** [comment]
Waiting for #103

**Comment by ameshkov** [comment]
@Mizzick I guess the only viable solution would be to change the way `$document` rules are applied.

We should use `if-top-url` for them **without** mixing them with `if-domain`. This approach must be used for `$document` rules **only**.

**Comment by ameshkov** [comment]
Ah, I see, we cannot mix them inside a content blocker list... 

What about converting `$document` to `if-domain` type of rules?

**Comment by Mizzick** [comment]
`$document` rules are actually converting now to `if-domain` exceptions.
