### ISSUE TITLE
AdGuard For Safari: Too Many Filters

### ISSUE THREAD

**Issue by oushima** [AdguardTeam/AdGuardForSafari#982]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.17

### Environment

```markdown
- OS: 14.4.1
- Safari version: 17.4.1
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion, ---Third-party filters---, EasyList, ABPindo, Bulgarian list, EasyList China, EasyList Czech and Slovak, EasyList Dutch, EasyList Germany, EasyList Hebrew, EasyList Italy, EasyList Lithuania, Latvian List, Liste AR, Liste FR, ROList, EasyPrivacy, Icelandic ABP List, AdBlockID, Greek AdBlock Filter, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Thai Ads Filters, Hungarian filter, Peter Lowe's Blocklist, Xfiles, Adblock Warning Removal List, Online Malicious URL Blocklist, RU AdList - Counters, ABPVN List, Fanboy's Enhanced Tracking List, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish GDPR-Cookies Filters, Estonian List, CJX's Annoyances List, Polish Social Filters, Fanboy's Anti-Facebook List, List-KR, xinggsf, I don't care about cookies, EasyList Spanish, KAD - Anti-Scam, Adblock List for Finland, ROLIST2, Iranian filter, road-block, Polish Annoyances Filters, Polish Anti Adblock Filters, Fanboy's Anti-thirdparty Fonts, EasyList Cookie List, NoCoin Filter List, Frellwit's Swedish Filter, YousList, AlleBlock, EasyList Polish, Polish Anti-Annoying Special Supplement, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List, Legitimate URL Shortener, Dandelion Sprout's Serbo-Croatian List, IndianList

### Issue Details

Steps to reproduce:
Try to toggle on all options in AdGuard settings.

The warning will show eventually. Also, those toggles are laggy. I would wish it had a "toggle all and save" button instead.
It seems to happen when you select all Filters minus 4. That seems to be the limit. Also, it requires the app to be fully restarted. The warning is often delayed.

### Expected Behavior

No error.

### Actual Behavior

Error.

### Screenshots

<img width="992" alt="Screenshot 2024-05-12 at 17 49 45" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/27223330/4576c014-c48c-4ae6-812d-7fe93ac56609">

**Comment by oushima** [comment]
The warning disappear if you select all Filters minus 4.

**Comment by alexx7311** [comment]
@oushima Hello! For each content-blocking extension you're allowed to use a [maximum of 150,000 rules](https://adguard.com/kb/adguard-for-safari/solving-problems/rule-limit/#safari-content-blocker-rule-limit) and this is a limitation of the Safari browser itself.

Even if there was no limit to the number of rules in Safari, we wouldn't recommend enabling all filters at once because they may conflict with each other.

The list of filters that covers the main part of ads is following: Base filter, Tracking Protection filter, Mobile Ads filter, Social Media filter, Annoyances filter.
