### ISSUE TITLE
Adguard for Safari.app process exits unexpectedly when trying to launch (Electron related?)

### ISSUE THREAD

**Issue by tangestani** [AdguardTeam/AdGuardForSafari#985]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS: 14.4.1 (23E224)
- Safari version: 17.4.1 (19618.1.15.11.14)
```

### Issue Details

Steps to reproduce:
1. Open "Adguard for Safari.app"

### Expected Behavior

Adguard for Safari should start and a window should open.

### Actual Behavior

The Adguard for Safari icon will bounce a couple of times in the dock indicating that it's in the process of starting, then it will just stop.

The app never actually starts completely and a window never appears on screen.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I've attached a file containing the logs outputed to stdout and sterr when launching the app from the cli.
[adguard_crash.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/15333421/adguard_crash.txt)

**Comment by alexx7311** [comment]
@tangestani Hello! Is the problem still relevant? Please try the following:
1. Uncheck all AdGuard for Safari extensions in `Safari - Preferences - Extensions`
2. Remove AdGuard for Safari application from Applications folder
3. In Finder press Shift+Command+G and remove following files:
- Remove **AdGuardSafariApp** folder from `~/Library/Application` Support directory
- Remove from `~/Library/Application Scripts` - all directories started with **com.adguard.safari** and **TC3Q7MAJXF.com.adguard.safari.AdGuard** folder
- Remove from `~/Library/Containers` - all directories started with **AdGuard-**
- Remove **TC3Q7MAJXF.com.adguard.safari.AdGuard** folder from `~/Library/GroupContainers` directory
- Remove **com.adguard.safari.AdGuard.plist** from `~/Library/Preferences`
4. Quit all `AdGuard` and `cfprefsd` processes from Activity monitor
5. Reinstall AdGuard for Safari

**Comment by alexx7311** [comment]
@tangestani Please leave a comment if the problem still relevant.
