### ISSUE TITLE
Slowing down my computer

### ISSUE THREAD

**Issue by sadiekc** [AdguardTeam/AdGuardForSafari#986]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS: Big Sur 11.7.5
- Safari version:15.0 (16612.1.29.41.4, 16612)
```

### What filters do you have enabled?

No filters, AdGuard Base filter, AdGuard Mobile App Banners filter

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

Slowing down my computer and websites

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by PavelParkhomenko** [comment]
Hello! Could you please provide more details about the issue you're experiencing? Specifically, what exactly is slowing down on your computer? Are we correct in understanding that disabling the AdGuard protection resolves the issue?

**Comment by zzebrum** [comment]
Reopen if necessary
