### ISSUE TITLE
YouTube Ads are Back

### ISSUE THREAD

**Issue by AlexMorello** [AdguardTeam/AdGuardForSafari#987]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.17

### Environment

```markdown
- OS: Ventura
- Safari version: 17.3.1
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Russian filter, EasyList Hebrew

### Issue Details

Steps to reproduce:
1. Go to YouTube
2.
3.

### Expected Behavior

No ads.

### Actual Behavior

Ads play in full.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@AlexMorello Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
