### ISSUE TITLE
Adguard for Safari won't download/install from App Store.

### ISSUE THREAD

**Issue by bigplayer-ai** [AdguardTeam/AdGuardForSafari#990]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment
- **Operating System:** Version 14.5 (23F79)
- **Safari Version:** 17.5 (19618.2.12.11.6)

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1. Initiate AdGuard for Safari download/installation from the App Store.
2. Encounter error during installation phase (approximately at 90% circle completion).

**Error Message:**
```
Unable to Download App
"AdGuard for Safari" could not be installed.
Please try again later.
```
![Unable to Download App Error](https://github.com/AdguardTeam/AdGuardForSafari/assets/119108387/b1fd319d-2b70-44ca-a1a4-34db21285fc0)

### Expected Behavior

Seamless download and installation of AdGuard for Safari.

### Actual Behavior

 Installation fails with an error message indicating the app could not be downloaded.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Unable to Download App Error](https://github.com/AdguardTeam/AdGuardForSafari/assets/119108387/419d9c9e-616c-4b4c-918b-a1417ae82848)
</details>

<details><summary>Screenshot 2:</summary>

![Download Speed Capped](https://github.com/AdguardTeam/AdGuardForSafari/assets/119108387/3ffc1fdd-7bb6-4e88-96ce-100b8ebb6d11)
</details>

### Additional Information

Device: MacBook Pro 16" M1 Pro with 1TB storage.

I am trying to install Adguard for Safari after uninstalling Adguard for Mac.

Download is super slow, I have Fibre optic at home and it is capped to 200 KBps

**Comment by alexx7311** [comment]
@bigplayer-ai Hello! Does the problem reproduce on a different network?

**Comment by alexx7311** [comment]
@bigplayer-ai Any updates?

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai Any updates?

installing the .dmg package from the adguard website solved the issue for me.
