### ISSUE TITLE
Photo non apparente sur Orange

### ISSUE THREAD

**Issue by Tonton6217** [AdguardTeam/AdGuardForSafari#991]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS:
- Safari version:17.5
```

### What filters do you have enabled?

AdGuard French filter

### Issue Details

Problème affichage photo

### Expected Behavior

Visualisation des photos sur la page d’accueil "Portail Orange"

### Actual Behavior

Bonjour, 
Depuis quelques temps, la photo de la page du "Portail Orange" ne s'affiche plus. 
Il est possible d'accéder à une éventuelle vidéo en cliquant sur le lien en dessous de la photo non apparente. 
Lien qui se connecte directement sur "dailymotion.com"et possibilité de visualiser la vidéo. 
Je ne sais comment paramétrer correctement les filtres pour obtenir les photos. 
Merci pour votre réponse. 
Cordialement.

### Screenshots

<img width="1045" alt="Capture d'écran 3" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/134369413/ed31de16-5ad2-4ca3-921b-43d37b8fc7bf">    
<img width="1016" alt="Capture d’écran 4" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/134369413/166de8cc-f615-4a2e-bdde-3ea71c0cfc5b">

**Comment by Tonton6217** [comment]
Il n'y a que les liens "Dailymotion" qui fonctionnent.

**Comment by alexx7311** [comment]
Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
