### ISSUE TITLE
Adguard doesn't block ads in Safari MacOS 

### ISSUE THREAD

**Issue by saidiarad** [AdguardTeam/AdGuardForSafari#998]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS: Sonoma 14.5
- Safari version: 17.5
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, I don't care about cookies

### Issue Details

Steps to reproduce:
1. Ads are still visible in all websites.

### Expected Behavior

Ads should not be visible.

### Actual Behavior

Ads are still visible in all websites.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1500" alt="Screenshot 2024-06-30 at 12 56 32" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/21284840/aefd86db-0971-44d7-b831-9bd17b7e9e92"

</details>

**Comment by saidiarad** [comment]
FIXED: I uninstalled Adguard for Safari app from apps store and installed natively from adguard website. I seems like the problem was with app store

**Comment by alexx7311** [comment]
Looks like a dup. of https://github.com/AdguardTeam/AdGuardForSafari/issues/995
